export default {
  hero: {
    description: "Browser automation extension with advanced macros, built for MMORPG players such as Flyff Universe enthusiasts and their Ringmaster support class. Automate your repetitive actions, shortcuts and sequences to optimize your gameplay.",
    ctaPrimary: "Get started now",
    ctaSecondary: "Learn more",
    trust1: "Free version available",
    trust2: "No commitment",
    trust3: "100% secure payment",
    trust4: "Automatic updates",
  },
  features: {
    tag: "Skills & Abilities",
    titleBefore: "Everything you ",
    titleEm: "need",
    subtitle: "Discover the exceptional capabilities of Reborn Assistant.",
    card1: { badge: "Active",  title: "Full Automation",        description: "Key macros, automatic sequences and configurable actions for complete automation." },
    card2: { badge: "Passive", title: "Maximum Security",       description: "Your data stays local. No tracking, no telemetry." },
    card3: { badge: "Active",  title: "Customizable Macros",   description: "3 configurable macros with automatic triggers and keyboard shortcuts." },
    card4: { badge: "Passive", title: "Customizable Interface", description: "Choose from 6 themes and adapt the interface to your needs." },
    card5: { badge: "Passive", title: "Multi-Language",         description: "Available in 15 languages. Worldwide support with localized interfaces." },
    card6: { badge: "Free",    title: "Free Version",           description: "Try for free with the included basic features." },
  },
  security: {
    tag: "Security",
    titleBefore: "Professional-grade ",
    titleEm: "security",
    titleAfter: "",
    description: "Reborn Assistant uses the same security standards as global streaming platforms. Your credentials are protected by <strong style='color:var(--gold);'>JWT encryption</strong>, your payments secured via <strong style='color:var(--gold);'>Stripe</strong>, and your data stays <strong style='color:var(--gold);'>100% local</strong>. No tracking, no data resale.",
    card1Title: "JWT Encryption",
    card1Text:  "Bank-level secure authentication",
    card2Title: "Stripe Payment",
    card2Text:  "Processor used by Amazon & Google",
    card3Title: "Zero Tracking",
    card3Text:  "Your data never leaves your device",
    card4Text:  "Secure Google Cloud infrastructure",
  },
  pricing: {
    tag:         "Choose your Class",
    titleBefore: "Choose your ",
    titleEm:     "rank",
    subtitle:    "Choose the plan that suits you. No commitment.",
    voyageur: {
      rank: "Rank I · Voyager", plan: "Free", period: "forever",
      feat1: "Heal macro", feat2: "6 visual themes", feat3: "15 languages available", feat4: "Floating interface",
      btn: "Get started", download: "Add to Chrome", guarantee: "🔒 Free forever",
    },
    aventurier: {
      rank: "Rank II · Adventurer", plan: "Monthly", period: "per month",
      feat1: "All Premium features", feat2: "Priority support", feat3: "Free updates",
      btn: "Try for Free", guarantee: "🎁 7 days free · No credit card",
      download: "Add to Chrome",
    },
    champion: {
      badge: "⭐ Popular -17%",
      rank: "Rank III · Champion", plan: "Annual", period: "per year · €2.50/month",
      feat1: "All Premium features", feat2: "Priority support", feat3: "Free updates",
      btn: "Try for Free", guarantee: "🎁 7 days free · No credit card",
      download: "Add to Chrome",
    },
    legende: {
      badge: "⚡ Limited Offer",
      rank: "Rank IV · Legend", plan: "Lifetime", period: "one-time payment · never pay again",
      feat1: "Lifetime access", feat2: "All future updates", feat3: "Dedicated premium support", feat4: "Best value for money",
      btn: "Buy", guarantee: "🔒 One-time payment · Lifetime access guaranteed",
      download: "Add to Chrome",
    },
  },
  stats: {
    label1: "Languages available", label2: "Visual themes", label3: "Local data", label4: "Active extension",
  },
  trust: {
    badge1: "SSL secure payment", badge2: "Instant access", badge3: "100% private data", badge4: "Responsive support",
  },
  store: {
    status: "Official extension",
    title:  "Available on the Chrome Web Store",
    install: "Install",
    available: "Free to install · Official extension verified by Google",
  },
  faq: {
    titleBefore: "Frequently asked ",
    titleEm:     "questions",
    subtitle:    "Everything you need to know before getting started.",
    q1: "Does the free trial require a credit card?",
    a1: "No, no credit card is required. The first 7 days are completely free, with no commitment. Just create your account to get started immediately.",
    q2: "Can I change plans at any time?",
    a2: "Yes, you can upgrade or downgrade at any time from your account. No switching fees.",
    q3: "Does the Lifetime plan really include all future updates?",
    a3: "Absolutely. The Lifetime plan guarantees you access to all future updates and new features, without ever paying anything extra.",
    q4: "Is my data safe?",
    a4: "All your data is stored locally on your device. We collect no personal data and use no tracking or telemetry.",
    q5: "How do I contact support?",
    a5: "Contact us by email at seymoon@constellation-89.fr or on Discord (Seymoon). Premium subscribers get priority responses.",
    q6: "Is Reborn Assistant a bot?",
    a6: "No, Reborn Assistant is not a bot. It's an extension of configurable macros that automates key sequences you define yourself. No artificial intelligence, no interaction with the game server, no memory reading. The extension neither reads nor modifies game data — it only simulates the keys you would type manually. You must stay at your computer to play: Reborn Assistant does not solve captchas, does not resurrect your character, and does not bring you back to the spot after death. It's a tool to make your gameplay easier, not to replace you.",
  },
  footer: {
    privacy:   "Privacy",
    terms:     "Terms of Use",
    copyright: "© 2026 Reborn Assistant. All rights reserved.<br>Developed by Seymoon",
  },

  // ── Shared docs navigation ────────────────────────────────────────
  docsNav: {
    backToDocs:      "← Back to docs",
    mainSite:        "⌂ Main site",
    backToMainSite:  "← Back to main site",
    footer:          "© 2026 Reborn Assistant — Developed by Seymoon · All rights reserved",
  },

  // ── docs/index.html ───────────────────────────────────────────────
  docsHome: {
    version:              "VERSION 1.3.3 · COMPLETE DOCUMENTATION",
    userGuide:            "User Guide",
    support:              "Support",
    legal:                "Legal information",
    quickstartTitle:      "Quick Start",
    quickstartDesc:       "Installation, initial setup and first steps with Reborn Assistant.",
    featuresTitle:        "Features",
    featuresDesc:         "Full detail of free and Premium features with comparison table.",
    premiumTitle:         "Premium Guide",
    premiumDesc:          "Automatic sequences, customizable macros and periodic macro.",
    interfaceTitle:       "Interface & Customization",
    interfaceDesc:        "Visual themes, languages and customization options.",
    troubleshootingTitle: "Troubleshooting",
    troubleshootingDesc:  "Solutions to common issues, FAQ and performance optimization.",
    legalTitle:           "Legal & Privacy",
    legalDesc:            "Disclaimer, legal notices, license terms, privacy policy and changelog.",
    articles:             "Flyff Universe Articles & Guides",
    articleAutomateTitle: "Automate your Ringmaster",
    articleAutomateDesc:  "Step-by-step tutorial to automate your Ringmaster on Flyff Universe with Reborn Assistant.",
    articleToolsTitle:    "Best Flyff Universe tools 2026",
    articleToolsDesc:     "Comparison of extensions, translators and calculators tested for Flyff Universe.",
    articleGuideTitle:    "Complete Ringmaster guide",
    articleGuideDesc:     "Role, buffs, STA/INT builds, gear: everything about the Flyff Universe support class.",
    articleShortcutsTitle: "Flyff Universe Keyboard Shortcuts",
    articleShortcutsDesc:  "Complete list of Flyff Universe shortcuts and recommended configuration per class.",
    footer:               "© 2026 Reborn Assistant — Developed by Seymoon · All rights reserved",
  },

  // ── docs/features.html ────────────────────────────────────────────
  docFeatures: {
    h1:        "⚡ Features",
    subtitle:  "Discover everything Reborn Assistant can do for you",
    h2Free:    "FREE Features",
    freeBadge: "FREE",
    c1Title: "Automatic action type 1",
    c1Desc:  "Automatically trigger your type 1 action (HP) on a configurable timer.",
    c1li1:   "Configurable action timer",
    c1li2:   "Works in the background",
    c2Title: "Visual themes",
    c2Desc:  "Customize the interface appearance with 6 different themes.",
    c2li1:   "MMO Gold (default)",
    c2li2:   "Dark Mode & White Mode",
    c3Title: "Multi-language",
    c3Desc:  "Interface available in 15 languages for an international experience.",
    c3li3:   "Instant switch",
    h2Premium: "PREMIUM Features 💎",
    p1Title: "Automatic trigger macro 1",
    p1Desc:  "Automatic triggering of your type 1 action (HP) on a configurable timer.",
    p1li1:   "Configurable trigger 1 timer",
    p1li2:   "Configurable shortcut key",
    p1li3:   "Works in the background",
    p2Title: "Automatic trigger macro 2",
    p2Desc:  "Automatic use of your type 2 actions on a configurable timer.",
    p2li1:   "Configurable trigger 2 timer",
    p2li2:   "Configurable shortcut key",
    p2li3:   "Works in the background",
    p3Title: "Keyboard shortcuts",
    p3Desc:  "Control Reborn Assistant on the fly with customizable global shortcuts.",
    p3li1:   "CTRL+A: Start the automation",
    p3li2:   "CTRL+O: Stop the automation",
    p4Title: "Sequence rotation",
    p4Desc:  "Automatic sequence maintenance system with a predefined sequence.",
    p4li1:   "Sequence: F2 → 1-9 → 0 → F1",
    p4li2:   "Configurable interval (minutes)",
    p4li3:   "Adjustable delay between keys",
    p5Title: "Customizable Macros",
    p5Desc:  "Create up to 3 macros with your own key sequences.",
    p5li1:   "3 independent macros",
    p5li2:   "Custom sequences",
    p5li3:   "Adjustable repeat intervals",
    p6Title: "Periodic macro",
    p6Desc:  "Automatic call and storage of your periodic macro every 15 seconds.",
    p6li1:   "Automatic periodic macro call",
    p6li2:   "Auto-stored after call",
    p6li3:   "Fixed 15-second interval",
    tableH2:      "Comparison table",
    tableFeature: "Feature",
    tableFree:    "Free",
    row1:  "Automatic type 1 action (HP)",
    row2:  "Visual themes (6)",
    row3:  "Multi-language (15)",
    row4:  "Automatic trigger macro 1",
    row5:  "Automatic trigger macro 2",
    row6:  "Keyboard shortcuts (CTRL+A / CTRL+O)",
    row7:  "Automatic sequence rotation",
    row8:  "Customizable macros (3x)",
    row9:  "Auto periodic macro",
    learnMore: "→ Learn more about Premium features",
  },

  // ── docs/quickstart.html ──────────────────────────────────────────
  docQuickstart: {
    h1:       "🚀 Quick Start",
    subtitle: "Install and configure Reborn Assistant in a few minutes",
    reqH2:    "Requirements",
    req1:     "<strong>Compatible browser:</strong> Google Chrome, Microsoft Edge, Brave or any Chromium-based browser",
    req2:     "<strong>Google account:</strong> Required only for Premium authentication (optional for free version)",
    req3:     "<strong>Compatible site:</strong> Works with standard websites",
    installH2:  "Installation",
    step1Title: "Visit the Chrome Web Store",
    step1p:     "Go to the Reborn Assistant page in the <a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome Web Store</a> and click <strong>«Add to Chrome»</strong>.",
    step1tip:   "💡 Compatible with Google Chrome, Microsoft Edge, Brave and any Chromium-based browser.",
    step2Title: "Confirm installation",
    step2p:     "Click <strong>«Add extension»</strong> in the confirmation window. The extension installs automatically.",
    step3Title: "Pin the extension",
    step3p:     "Click the puzzle icon 🧩 in your browser toolbar, then pin Reborn Assistant for quick access.",
    step4Title: "Login (optional for Premium)",
    step4p:     "• Click the Reborn icon in the toolbar<br>• For Premium: Log in with your Google account<br>• For Free: Use directly without login",
    alertTitle: "✅ Installation successful!",
    alertText:  "The Reborn icon turns green when the extension is active. You can now configure your features.",
    configH2:   "Initial configuration",
    freeH3:     "FREE Version",
    freeTitle:  "<strong>Features available without login:</strong>",
    freeText:   "• Automatic action type 1 (HP only)<br>• 6 visual themes<br>• Support for 15 languages",
    freeStepTitle: "Type 1 automatic action setup",
    freeStepText:  "1. Open the Reborn panel (click the icon)<br>2. Set the HP action timer (default: 2s)<br>3. The action triggers automatically<br>4. No login required",
    premiumH3:       "PREMIUM Version 💎",
    premiumFeatTitle:"<strong>Additional features (requires Google login):</strong>",
    premiumFeatText: "• Automatic trigger macro 1 (configurable timer + shortcut)<br>• Automatic trigger macro 2 (configurable timer + shortcut)<br>• Keyboard shortcuts (CTRL+A / CTRL+O)<br>• Automatic sequence rotation (F2 → 1-9 → 0 → F1)<br>• 3 customizable macros with key sequences<br>• Automatic periodic macro system (call + store every 15s)",
    premConfigTitle: "Premium configuration",
    premConfigSeq:   "<strong>Automatic sequences:</strong><br>• Enable «Sequence Rotation» in the panel<br>• Configure the interval between cycles (default: 5 min)<br>• Adjust the delay between each key (default: 1s)",
    premConfigMacro: "<strong>Macros:</strong><br>• Enable Macro 1, 2 or 3<br>• Define the key sequence (e.g. <code>1,2,3,4</code>)<br>• Configure the repeat interval",
    premConfigPer:   "<strong>Periodic macro:</strong><br>• Enable the «Periodic macro» toggle<br>• The system automatically calls your periodic macro every 15s<br>• Auto-stored after the call",
    warnTitle: "⚠️ Important note",
    warnText:  "Premium features (Trigger macros 1 and 2, Automatic sequences, Automatic periodic macro, 3 configurable macros) require a valid Premium license and a Google login. Without a license, only the basic macro is accessible.",
    shortcutsH2:   "Keyboard shortcuts",
    shortcutsText: "<code>CTRL + A</code>: Start the automation<br><code>CTRL + O</code>: Stop the automation",
    nextH2: "Next steps",
    link1:  "Discover all features",
    link2:  "Complete Premium guide",
    link3:  "Solutions to common issues",
  },

  // ── docs/interface.html ───────────────────────────────────────────
  docInterface: {
    h1:       "🎨 Interface & Customization",
    subtitle: "Customize Reborn Assistant to your preferences",
    themesH2:    "Visual themes",
    themesDesc:  "Reborn Assistant offers 6 themes to customize the interface appearance:",
    changeThemeH3:   "Change theme",
    changeThemeText: "1. Open the Reborn panel<br>2. Click the \"⚙️ CONFIGURATION\" tab<br>3. Select your theme from the dropdown<br>4. The change is instant",
    langsH2:    "Available languages",
    langsDesc:  "Interface available in 15 languages:",
    changeLangH3:   "Change language",
    changeLangText: "1. Open the Reborn panel<br>2. Click \"⚙️ CONFIGURATION\"<br>3. Select your language from the dropdown<br>4. The entire interface translates instantly",
    shortcutsH2:   "Keyboard shortcuts",
    shortcutsDesc: "Reborn Assistant includes global shortcuts for quick control:",
    systemH3: "System shortcuts",
    sysSC1:   "<code>CTRL + A</code>: Start the automation",
    sysSC2:   "<code>CTRL + O</code>: Stop the automation",
    customH3:   "Customizable shortcuts",
    customDesc: "You can configure keys for:",
    customLi1:  "Type 1 and 2 actions",
    customLi2:  "Macros (key sequences)",
    customLi3:  "Periodic macro",
    displayH2:    "Display options",
    panelPosH3:   "Panel position",
    panelPosDesc: "The Reborn panel is draggable:",
    panelLi1: "Click on the panel header",
    panelLi2: "Hold the button and drag",
    panelLi3: "Release at the desired location",
    panelLi4: "Position is saved automatically",
    opacityH3:   "Panel opacity",
    opacityDesc: "Adjust transparency so it doesn't interfere with your navigation while keeping an eye on your stats.",
    logH3:   "Activity log",
    logDesc: "The log displays all actions performed in real time:",
    logLi1:  "System activation/deactivation",
    logLi2:  "Potion usage",
    logLi3:  "Macro and sequence execution",
    logLi4:  "Periodic macro calls",
    logLi5:  "Any errors",
    saveH2:    "Settings backup",
    saveDesc:  "All your configurations are automatically saved locally:",
    saveLi1:   "Selected theme",
    saveLi2:   "Interface language",
    saveLi3:   "Trigger thresholds",
    saveLi4:   "Assigned keys",
    saveLi5:   "Macro configuration",
    saveLi6:   "Panel position",
    savePersist: "They persist between sessions, even after closing the browser.",
  },

  // ── docs/premium.html ─────────────────────────────────────────────
  docPremium: {
    h1:       "💎 Premium Guide",
    subtitle: "Master all the advanced features of Reborn Assistant",
    rotH2:    "🛡️ Automatic sequence rotation",
    rotDesc:  "The rotation system automatically keeps all your sequences active by pressing a predefined key sequence at regular intervals.",
    rotSeqH3:   "Key sequence",
    rotSeqText: "The rotation always follows this fixed order:",
    rotConfigH3:   "Configuration",
    rotIntName:    "Interval between cycles",
    rotIntDesc:    "Wait time before restarting the full sequence. Default: 5 minutes. Adjust based on the duration of your shortest sequences.",
    rotDelName:    "Delay between keys",
    rotDelDesc:    "Wait time between each key in the sequence. Default: 1 second. Adjust based on the speed of the target service (animations, cooldowns...).",
    rotExTitle:    "💡 Example usage",
    rotExScenario: "<strong>Scenario:</strong> Your sequences last 5 minutes and you have 8 sequences on keys 1-8.",
    rotExConfig:   "<strong>Configuration:</strong>",
    rotExLi1:      "Interval: 5 minutes",
    rotExLi2:      "Delay: 1 second",
    rotExLi3:      "The extension will press F2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1 every 5 minutes",
    rotExLi4:      "13 keys total with 1 second between each = ~13 seconds per cycle",
    macH2:    "⚙️ Customizable Macros",
    macDesc:  "Create up to 3 independent macros with your own key sequences. Perfect for automating repetitive tasks, recurring combos or skill rotations.",
    macHowH3:   "How it works",
    macHowText: "Each macro executes a key sequence at a regular interval, independently of other systems.",
    macConfigH3:  "Configuration",
    macSeqName:   "Key sequence",
    macSeqDesc:   "Define the keys to press in order, separated by commas. Example: 1,2,3,4 or q,w,e,r,f",
    macRepName:   "Repeat interval",
    macRepDesc:   "Wait time before repeating the sequence. Configure based on your needs (seconds or minutes).",
    macDelName:   "Delay between keys",
    macDelDesc:   "Wait time between each key in the sequence (usually 0.5 to 2 seconds).",
    macExTitle:   "💡 Usage examples",
    mac1Title:    "<strong>Macro 1 – Repetitive automation:</strong>",
    mac1Li1:      "Sequence: 1,2,3,space",
    mac1Li2:      "Interval: 10 seconds",
    mac1Li3:      "Use: Looping basic attack rotation",
    mac2Title:    "<strong>Macro 2 – Skill combo:</strong>",
    mac2Li1:      "Sequence: q,w,e,r",
    mac2Li2:      "Interval: 30 seconds",
    mac2Li3:      "Use: Optimal DPS rotation",
    mac3Title:    "<strong>Macro 3 – Automatic support:</strong>",
    mac3Li1:      "Sequence: f,g,h",
    mac3Li2:      "Interval: 15 seconds",
    mac3Li3:      "Use: Group sequences or periodic actions",
    perH2:    "🐉 Periodic macro",
    perDesc:  "This system automatically executes a periodic action every 15 seconds. Ideal for repetitive tasks that need to be triggered regularly.",
    perHowH3:   "How it works",
    perHowText: "The system automatically executes this sequence every 15 seconds:",
    perLi1:     "Calls the periodic macro (configurable key, default §)",
    perLi2:     "Waits 500ms",
    perLi3:     "Automatically stores the periodic macro",
    perConfigH3:  "Configuration",
    perCallName:  "Call key",
    perCallDesc:  "The key that triggers your periodic macro. Default: §. Change it to match your configuration.",
    perIntName:   "Interval (fixed)",
    perIntDesc:   "The system always uses a fixed interval of 15 seconds. Not configurable.",
    perExTitle:   "💡 Use case",
    perExText:    "In some services, the periodic macro needs to be called regularly to collect items, provide temporary sequences or gain experience. This system fully automates this process.",
    perImpH3:     "⚠️ Important",
    perImpLi1:    "Make sure the configured key matches your invocation key",
    perImpLi2:    "The periodic macro is automatically stored after each call",
    perImpLi3:    "Works in parallel with other systems (sequences, macros, actions)",
    optH2:   "Optimization tips",
    combH3:  "🎯 Combining systems",
    combDesc:"All Premium features work simultaneously. You can:",
    combLi1: "Enable automatic sequences + 3 macros + periodic macro at the same time",
    combLi2: "Trigger actions 1 &amp; 2 always work in parallel",
    combLi3: "Each system has its own independent timer",
    perfH3:  "⚡ Performance",
    perfLi1: "The more systems you enable, the more resources the extension uses",
    perfLi2: "Adjust intervals to avoid too-frequent actions",
    perfLi3: "Monitor the activity log to verify everything is working correctly",
    secH3:   "🔑 Security",
    secLi1:  "Your Premium license is verified in real time",
    secLi2:  "If the connection is lost, Premium features are disabled",
    secLi3:  "Log back in to re-enable all features",
  },

  // ── docs/troubleshooting.html ─────────────────────────────────────
  docTroubleshooting: {
    h1:       "🔧 Troubleshooting",
    subtitle: "Solutions to common issues and FAQ",
    installH2: "Installation issues",
    faq1Q: "❌ The extension doesn't appear in the toolbar",
    faq1A: "<strong>Solutions:</strong><br>1. Make sure the extension is installed from the <strong>Chrome Web Store</strong><br>2. Pin the extension: click the puzzle icon 🧩 in the toolbar and pin Reborn Assistant<br>3. Restart your browser<br>4. If the issue persists, uninstall then reinstall the extension from the Chrome Web Store",
    connH2: "Connection issues",
    faq2Q: "❌ \"Connection failed\" or \"Invalid license\"",
    faq2A: "<strong>Possible causes:</strong><br>• Poor internet connection<br>• Google Cloud servers temporarily unavailable<br>• Expired or revoked license<br><br><strong>Solutions:</strong><br>1. Check your internet connection<br>2. Log out and log back in with Google<br>3. Check your license status in your Stripe portal<br>4. Contact support if the issue persists",
    faq3Q: "❌ The panel shows \"FREE\" but I have Premium",
    faq3A: "1. Log out of your Google account<br>2. Fully close the browser<br>3. Reopen and log back in<br>4. If the issue persists, make sure you're logged in with the correct Google account (the one used for the purchase)",
    funcH2: "Functionality issues",
    faq4Q:     "❌ Type 1/2 actions are not triggering",
    faq4Alert: "<strong>⚠️ IMPORTANT</strong><br>Type 1 and 2 actions are <strong>PREMIUM ONLY</strong> features. Only the automatic type 1 action (HP) is available in the free version.",
    faq4Prem:  "<strong>If you have Premium:</strong><br>1. Is the automation running? <code>CTRL+A</code><br>2. Are the trigger toggles enabled? (green indicator «ON»)<br>3. Are the configured keys correct?",
    faq5Q:     "❌ Sequences / macros / periodic macro / shortcuts are not working",
    faq5Alert: "<strong>⚠️ IMPORTANT</strong><br>Keyboard shortcuts, sequences, macros and periodic macro are <strong>PREMIUM ONLY</strong> features. In the free version, only the automatic type 1 action (HP) is available.",
    faq5Prem:  "<strong>If you have Premium:</strong><br>1. Verify that your Premium license is active (💎 icon in the panel)<br>2. Are the corresponding toggles enabled?<br>3. Check the configured intervals and delays",
    faq6Q: "❌ The automation stops on its own",
    faq6A: "<strong>Possible causes:</strong><br>• Lost Google Cloud connection<br>• DevTools detection<br>• Page URL changed<br><br><strong>Solutions:</strong><br>1. Restart the automation with <code>CTRL+A</code> (Premium) or via the panel<br>2. Reload the relevant page<br>3. Check your internet connection<br>4. Do not open DevTools if you are on Premium",
    optH2: "Optimization & Performance",
    faq7Q: "💡 The extension uses too many resources",
    faq7A: "<strong>Recommendations:</strong><br>• Increase macro and sequence intervals (fewer actions = less CPU)<br>• Disable systems you don't need<br>• Close unnecessary tabs<br>• Use an optimized browser (Brave, Edge are lighter than Chrome)",
    faq8Q: "💡 How do I optimize the settings?",
    faq8A: "<strong>Recommended configuration:</strong><br>• <strong>Sequence interval:</strong> 5-25 minutes (depending on sequence duration)<br>• <strong>Delay between keys:</strong> 1-2 seconds (avoids errors)<br>• <strong>Macros:</strong> 10-30s intervals depending on use",
    genH2:  "General FAQ",
    faq9Q:  "❓ Can I use Reborn on multiple browsers?",
    faq9A:  "Yes, but you must install the extension on each browser. Your Premium license works on all your devices as long as you log in with the same Google account (max 1 simultaneous connection).",
    faq10Q: "❓ Is my data saved?",
    faq10A: "All your configurations (keys, macros, theme, language) are saved <strong>locally</strong> in the browser. They persist between sessions. However, if you uninstall the extension, you will lose this data.",
    faq11Q: "❓ Can Reborn cause a ban?",
    faq11A: "Using automation tools may violate the Terms of Service of some platforms. <strong>You are solely responsible</strong> for how you use Reborn. Check the terms of use of the target service before using this tool.",
    faq12Q: "❓ How do I cancel my Premium subscription?",
    faq12A: "You can cancel at any time from your Stripe management portal (link received by email after payment). Cancellation takes effect at the end of your current period. No cancellation fees.",
    faq13Q: "❓ What happens to the Lifetime plan if the service closes?",
    faq13A: "The Lifetime plan guarantees access as long as the service is active. Once installed, the extension works locally; only license verification requires an internet connection.",
    supportH2:    "Need more help?",
    supportTitle: "📧 Support",
    supportText:  "If your issue persists, contact support directly by email. Include in your message:<br><br>• A detailed description of the problem<br>• The steps you have already tried<br>• Screenshots if relevant<br>• Your browser and operating system",
  },

  // ── docs/privacy.html ─────────────────────────────────────────────
  docPrivacy: {
    h1:       "⚖️ Legal & Privacy",
    subtitle: "Disclaimer, legal notices, license terms and privacy policy",
    navLegal:  "⚖️ Legal Information",
    navLicence:"© License",
    navPrivacy:"🔒 Privacy",
    disclaimerH2:  "⚠️ Disclaimer",
    disclaimerBox: "<strong>⚠️ Important warning:</strong> Reborn Assistant is an automation tool. Its use may violate the Terms of Service of certain online services. Use of this tool is entirely at your own risk.",
    respH3:    "User responsibility",
    respIntro: "By using Reborn Assistant, you acknowledge and agree that:",
    respLi1:   "You are solely responsible for your use of this software",
    respLi2:   "You will check the terms of service of each platform before using this tool",
    respLi3:   "The author cannot be held responsible for any ban, account restriction, or legal action resulting from the use of Reborn",
    respLi4:   "You use this software knowingly and at your own risk",
    respLi5:   "This tool must not be used in a way that harms the experience of other users",
    warrantH3:   "No warranty",
    warrantText: "The software is provided \"AS IS\" without warranty of any kind. The author does not guarantee that the software will operate uninterrupted or error-free, nor that it will be compatible with all services or browsers.",
    legalH2:    "📄 Legal notices",
    copyrightH3:   "Copyright & Intellectual property",
    copyrightText: "<strong>© 2026 Reborn Assistant – All rights reserved</strong><br>Developed by <strong>Seymoon</strong>",
    copyrightText2:"This software and all associated materials are the exclusive intellectual property of their author. Any reproduction, modification, distribution or reverse engineering without written permission is strictly prohibited.",
    liabilityH3:   "Limitation of liability",
    liabilityIntro:"In no event shall the author be liable for any claim or damage arising from the use or inability to use this software, including but not limited to:",
    liabilityLi1:  "Loss of data or user account",
    liabilityLi2:  "Bans or restrictions imposed by service publishers",
    liabilityLi3:  "Damage to computer systems",
    liabilityLi4:  "Any legal consequences arising from use that violates the terms of service of platforms",
    dataH3:    "Personal data",
    dataText:  "Reborn Assistant uses Firebase (Google Cloud) for account and license management. The data collected is limited to your email address and account identifier, solely for authentication and license verification purposes.",
    dataText2: "<strong>No activity data is collected or transmitted.</strong> Your configurations remain stored locally on your device.",
    jurisH3:   "Jurisdiction",
    jurisText: "This agreement is governed by the law applicable in the jurisdiction of the copyright holder's residence. By installing and using this software, you acknowledge that you have read, understood and accepted all of these terms.",
    licenceH2:     "© License terms",
    licenceH3:     "Usage license",
    licenceIntro:  "Purchasing a Reborn Assistant plan grants you a personal, non-exclusive and non-transferable license to use the software.",
    licenceAllows: "<strong>This license allows you to:</strong>",
    licenceLi1:    "Use the software for personal purposes on your own devices",
    licenceLi2:    "Benefit from updates included in your plan",
    licenceForbids:"<strong>This license does not allow you to:</strong>",
    licenceLi3:    "Redistribute, resell or share your access",
    licenceLi4:    "Modify, decompile or reverse engineer the software",
    licenceLi5:    "Use the software for commercial purposes without prior written agreement",
    licenceLi6:    "Transfer your license to a third party",
    terminationH3:   "Termination",
    terminationText: "The license may be terminated immediately in case of violation of these terms. For subscription plans, you can cancel at any time from your Stripe portal.",
    refundBox: "<strong>✅ Refund policy:</strong> If you are not satisfied within 7 days of your purchase, contact our support for a full refund. Beyond this period, no refund will be granted except in exceptional cases.",
    privacyH1:      "🔒 Privacy Policy",
    privacySubtitle:"How we protect your personal data",
    privacyBox:     "<strong>✅ Your privacy is our priority</strong><br>Free version: no personal data collected. Premium version: only data strictly necessary for license verification is processed.",
    collectH2:        "Data collection",
    collectFreeH3:    "Free Version",
    collectFreeText:  "No personal data is collected or transmitted. All your preferences are stored only on your device.",
    collectPremH3:    "Premium Version",
    collectPremIntro: "To verify your license and secure your account, the following data is processed:",
    collectPremLi1:   "Your Google email address (via Google authentication)",
    collectPremLi2:   "A unique device identifier (generated locally)",
    collectPremLi3:   "Your subscription status and session timestamps",
    collectPremLi4:   "Up to 2 registered devices per account",
    collectPremBasis: "<strong>Legal basis:</strong> performance of contract (Art. 6.1.b GDPR).",
    collectNotH3:     "Data never collected",
    collectNotLi1:    "❌ No gameplay or activity data",
    collectNotLi2:    "❌ No browsing history",
    collectNotLi3:    "❌ No advertising or tracking cookies",
    localH2:    "Locally stored data",
    localIntro: "The following information is saved <strong>only on your device</strong>:",
    localLi1:   "<strong>Language preferences</strong>: Your interface language choice",
    localLi2:   "<strong>Visual theme selection</strong>: The chosen theme from the 6 available",
    localLi3:   "<strong>Configured keyboard shortcuts</strong>: The keys assigned to your actions",
    localLi4:   "<strong>Custom timer intervals</strong>: The timers configured for your macros",
    localLi5:   "<strong>Interface position</strong>: The location of the Reborn panel on your screen",
    localLi6:   "<strong>License cache (Premium)</strong>: device identifier and subscription status, to avoid verification on every startup",
    thirdH2:       "Third-party services",
    thirdH3:       "Services used (Premium version)",
    thirdDesc:     "For authentication and payments, Reborn Assistant uses:",
    thirdLi1:      "🔐 <strong>Google</strong> — Authentication and secure storage of license data",
    thirdLi2:      "💳 <strong>Stripe</strong> — Premium payment processing (your banking details never pass through our servers)",
    thirdTransfer: "These providers comply with GDPR and have appropriate safeguards for international data transfers.",
    thirdNoH3:     "No tracking, no advertising",
    thirdLi3:      "❌ No analytics or statistics services",
    thirdLi4:      "❌ No advertising or targeted marketing",
    thirdLi5:      "❌ No third-party cookies or behavioral tracking",
    authH2:    "Authentication and device management",
    authH3:    "Google sign-in (Premium version)",
    authText:  "Your Google account is used solely to authenticate your identity and verify your license. Your device is registered in our secure system (up to 2 devices per account).",
    authText2: "You receive a notification if your account is used on an unrecognized device. You can manage your registered devices directly from the extension.",
    payH2:    "Secure Payments",
    payText:  "Premium payments are processed by <strong>Stripe</strong>. Your banking information <strong>never</strong> passes through our servers. We store <strong>no</strong> card data.",
    retentionH2:   "Data retention",
    retentionText: "Your data is kept only for as long as necessary:",
    retentionLi1:  "<strong>Active account:</strong> data retained for the duration of the subscription",
    retentionLi2:  "<strong>After cancellation:</strong> deletion within 30 days",
    retentionLi3:  "<strong>Local data:</strong> deleted immediately upon uninstalling the extension",
    rightsH2:      "Your rights (GDPR)",
    rightsText:    "Under GDPR, you have the following rights regarding your data:",
    rightsLi1:     "✅ <strong>Access</strong> — Obtain a copy of your personal data",
    rightsLi2:     "✅ <strong>Rectification</strong> — Correct inaccurate data",
    rightsLi3:     "✅ <strong>Erasure</strong> — Request deletion of your account and data",
    rightsLi4:     "✅ <strong>Portability</strong> — Receive your data in a readable format",
    rightsLi5:     "✅ <strong>Complaint</strong> — Lodge a complaint with your national data authority",
    rightsExercise:"To exercise these rights, contact us at: seymoon@constellation-89.fr or on Discord (Seymoon)",
    deleteH2:    "Deleting your data",
    deleteText1: "<strong>1. Uninstall the extension</strong><br>By uninstalling Reborn Assistant, all local data is automatically deleted.",
    deleteText2: "<strong>2. Manual reset</strong><br>You can reset settings from the Reborn interface at any time.",
    deleteText3: "<strong>3. Account deletion (Premium)</strong><br>To delete your Premium account and all associated data, contact us by email.",
    contactH2:   "Contact",
    contactText: "For any questions regarding legal information or the privacy policy:",
    changelogH2: "📋 Changelog",
    v130H3:          "Version 1.3.0 (March 2026) · Current",
    v130newLabel:    "✨ What's New",
    v130improvLabel: "🔧 Improvements",
    v130fixLabel:    "🐛 Bug Fixes",
    v130Li1:  "⏱ Draggable floating mini-timer — small floating window displaying buff timers and timers over 1 minute, automatically reopens on next launch and follows the active skin.",
    v130Li2:  "⚡ Priority macros — macros execute before heals/HP/mana, with a 0.5s heal freeze before and after each execution to avoid conflicts.",
    v130Li3:  "🧠 Smart buff management — buff executes first, silenced macros are queued and automatically restarted after it ends (delay reduced to 2s).",
    v130Li4:  "💾 Position memory — floating windows retain their position between sessions.",
    v130Li5:  "🇸🇦 Arabic support — 15th language available in the extension.",
    v130Li6:  "💳 Stripe payment in popup — opens in a dedicated window with auto-close, without leaving the extension.",
    v130Li7:  "🐾 Pet: fixed bug where pet didn't come out on first buff + better F1/F2 mode tracking for storage on stop.",
    v130Li8:  "⏱ Timer: premium design visual rework + opacity 55% at rest → 95% on hover for better readability.",
    v130Li9:  "💳 Billing portal: single active window in memory with automatic closing.",
    v130Li10:  "Fixed several memory leaks in the content and popup.",
    v130Li16:  "UI alignment on the 2 device max limit (consistency with the backend).",
    v120H3:  "Version 1.2.0 (March 2026)",
    v120Li1: "✨ The 6 skins have been reworked with a subtle transparency effect.",
    v120Li2: "🔐 View and manage your registered device directly from the extension.",
    v120Li3: "💳 Access your subscription in one click from the extension.",
    v120Li4: "🔔 Instant notification if your account is used on another device.",
    v12H3:   "Version 1.2 (February 2026)",
    v12Li1:  "Support for 15 languages (added Turkish 🇹🇷)",
    v12Li2:  "Visual redesign of the website",
    v12Li3:  "Merged legal pages into a single unified page",
    v12Li4:  "Full FR/EN translation of the site",
    v11H3:   "Version 1.1.1 (February 2026)",
    v11Li1:  "Added automatic periodic macro (15s + auto-store)",
    v11Li2:  "Keyboard shortcuts CTRL+A / CTRL+O",
    v11Li3:  "Support for 15 languages (added Filipino + Turkish)",
    v11Li4:  "Improved Premium license stability",
    v11Li5:  "Bug fixes on sequence rotation",
    v10H3:   "Version 1.0 (2025) · Initial",
    v10Li1:  "Launch of Reborn Assistant",
    v10Li2:  "Automatic type 1 and 2 actions",
    v10Li3:  "Automatic sequence rotation (F2 → 1-9 → 0 → F1)",
    v10Li4:  "3 customizable macros",
    v10Li5:  "6 visual themes and 12 languages",
    v10Li6:  "Premium license system via Firebase",
    pageFooter:"© 2026 Reborn Assistant — Developed by Seymoon · All rights reserved",
  },
  nav: {
    docsFull:    "📚 Docs",
    docsShort:   "📚 Docs",
    manageFull:  "Manage subscription",
    manageShort: "Manage",
  },
};