export default {
  hero: {
    description: "Extension d'automatisation pour navigateur avec macros avancées, pensée pour les joueurs de MMORPG comme Flyff Universe et leur classe support Ringmaster. Automatisez vos actions répétitives, raccourcis et séquences pour optimiser votre gameplay.",
    ctaPrimary: "Commencer maintenant",
    ctaSecondary: "En savoir plus",
    trust1: "Version gratuite disponible",
    trust2: "Sans engagement",
    trust3: "Paiement 100% sécurisé",
    trust4: "Mises à jour automatiques",
  },
  features: {
    tag: "Compétences & Aptitudes",
    titleBefore: "Tout ce dont vous ",
    titleEm: "avez besoin",
    subtitle: "Découvrez les capacités exceptionnelles de Reborn Assistant.",
    card1: { badge: "Actif",  title: "Automatisation Complète",    description: "Macros de touches, séquences automatiques et actions configurables pour une automatisation complète." },
    card2: { badge: "Passif", title: "Sécurité Maximale",          description: "Vos données restent locales. Aucun tracking, aucune télémétrie." },
    card3: { badge: "Actif",  title: "Macros Personnalisables",    description: "3 macros configurables avec déclencheurs automatiques et raccourcis clavier." },
    card4: { badge: "Passif", title: "Interface Personnalisable",  description: "Choisissez parmi 6 thèmes et adaptez l'interface à vos besoins." },
    card5: { badge: "Passif", title: "Multi-Langues",              description: "Disponible en 15 langues. Support mondial avec interfaces localisées." },
    card6: { badge: "Gratuit",title: "Version Gratuite",           description: "Testez gratuitement avec les fonctionnalités de base incluses." },
  },
  security: {
    tag: "Sécurité",
    titleBefore: "Niveau de sécurité ",
    titleEm: "professionnel",
    titleAfter: "",
    description: "Reborn Assistant utilise les mêmes standards de sécurité que les plateformes de streaming mondiales. Vos identifiants sont protégés par <strong style='color:var(--gold);'>chiffrement JWT</strong>, vos paiements sécurisés via <strong style='color:var(--gold);'>Stripe</strong>, et vos données restent <strong style='color:var(--gold);'>100% locales</strong>. Aucun tracking, aucune revente de données.",
    card1Title: "Chiffrement JWT",
    card1Text:  "Authentification sécurisée de niveau bancaire",
    card2Title: "Paiement Stripe",
    card2Text:  "Processeur utilisé par Amazon & Google",
    card3Title: "Zéro Tracking",
    card3Text:  "Vos données ne quittent jamais votre appareil",
    card4Text:  "Infrastructure Google Cloud sécurisée",
  },
  pricing: {
    tag:         "Choisissez votre Classe",
    titleBefore: "Choisissez votre ",
    titleEm:     "rang",
    subtitle:    "Choisissez la formule qui vous convient. Sans engagement.",
    voyageur: {
      rank: "Rang I · Voyageur", plan: "Gratuit", period: "à jamais",
      feat1: "Macro soin", feat2: "6 thèmes visuels", feat3: "15 langues disponibles", feat4: "Interface flottante",
      btn: "Commencer", download: "Ajouter à Chrome", guarantee: "🔒 Gratuit pour toujours",
    },
    aventurier: {
      rank: "Rang II · Aventurier", plan: "Mensuel", period: "par mois",
      feat1: "Toutes les fonctionnalités Premium", feat2: "Support prioritaire", feat3: "Mises à jour gratuites",
      btn: "Essayer Gratuitement", guarantee: "🎁 7 jours gratuits · Sans carte bancaire",
      download: "Ajouter à Chrome",
    },
    champion: {
      badge: "⭐ Populaire -17%",
      rank: "Rang III · Champion", plan: "Annuel", period: "par an · soit 2,50€/mois",
      feat1: "Toutes les fonctionnalités Premium", feat2: "Support prioritaire", feat3: "Mises à jour gratuites",
      btn: "Essayer Gratuitement", guarantee: "🎁 7 jours gratuits · Sans carte bancaire",
      download: "Ajouter à Chrome",
    },
    legende: {
      badge: "⚡ Offre Limitée",
      rank: "Rang IV · Légende", plan: "À Vie", period: "paiement unique · plus jamais rien",
      feat1: "Accès à vie", feat2: "Toutes les mises à jour futures", feat3: "Support premium dédié", feat4: "Meilleur rapport qualité-prix",
      btn: "Acheter", guarantee: "🔒 Paiement unique · Accès garanti à vie",
      download: "Ajouter à Chrome",
    },
  },
  stats: {
    label1: "Langues disponibles", label2: "Thèmes visuels", label3: "Données locales", label4: "Extension active",
  },
  trust: {
    badge1: "Paiement sécurisé SSL", badge2: "Accès instantané", badge3: "Données 100% privées", badge4: "Support réactif",
  },
  store: {
    status: "   Extension officielle",
    title:  "Disponible sur le Chrome Web Store",
    install: "Installer",
    available: "Disponible gratuitement · Extension officielle vérifiée par Google",
  },
  faq: {
    titleBefore: "Questions ",
    titleEm:     "fréquentes",
    subtitle:    "Tout ce que vous devez savoir avant de commencer.",
    q1: "L'essai gratuit nécessite-t-il une carte bancaire ?",
    a1: "Non, aucune carte bancaire n'est requise. Les 7 premiers jours sont entièrement gratuits, sans engagement. Vous n'avez qu'à créer votre compte pour commencer immédiatement.",
    q2: "Puis-je changer de plan à tout moment ?",
    a2: "Oui, vous pouvez passer à un plan supérieur ou inférieur à tout moment depuis votre espace client. Aucun frais de changement.",
    q3: "Le plan À Vie inclut-il vraiment toutes les futures mises à jour ?",
    a3: "Absolument. Le plan À Vie vous garantit l'accès à toutes les mises à jour et nouvelles fonctionnalités futures, sans jamais débourser quoi que ce soit de plus.",
    q4: "Mes données sont-elles en sécurité ?",
    a4: "Toutes vos données restent stockées localement sur votre appareil. Nous ne collectons aucune donnée personnelle et n'utilisons aucun tracking ou télémétrie.",
    q5: "Comment contacter le support ?",
    a5: "Contactez-nous par email à seymoon.cell@gmail.com ou sur Discord (Seymoon). Les abonnés premium bénéficient d'une réponse prioritaire.",
    q6: "Reborn Assistant est-il un bot ?",
    a6: "Au sens strict, Reborn Assistant n'est pas un bot conventionnel. C'est une extension de macros configurables qui automatise des séquences de touches que vous définissez vous-même. Aucune intelligence artificielle, aucune interaction avec le serveur du jeu, aucune lecture de la mémoire. L'extension ne lit ni ne modifie les données du jeu : elle simule seulement les touches que vous taperiez manuellement. À vous de respecter les conditions d'utilisation des services que vous utilisez.",
  },
  footer: {
    privacy:   "Confidentialité",
    terms:     "Conditions d'Utilisation",
    copyright: "© 2026 Reborn Assistant. Tous droits réservés.<br>Développé par Seymoon",
  },

  // ── Navigation partagée docs ──────────────────────────────────────
  docsNav: {
    backToDocs:      "← Retour aux docs",
    mainSite:        "⌂ Site principal",
    backToMainSite:  "← Retour au site principal",
    footer:          "© 2026 Reborn Assistant — Développé par Seymoon · Tous droits réservés",
  },

  // ── docs/index.html ───────────────────────────────────────────────
  docsHome: {
    version:              "VERSION 1.3 · DOCUMENTATION COMPLÈTE",
    userGuide:            "Guide d'utilisation",
    support:              "Support",
    legal:                "Informations légales",
    quickstartTitle:      "Démarrage Rapide",
    quickstartDesc:       "Installation, configuration initiale et premiers pas avec Reborn Assistant.",
    featuresTitle:        "Fonctionnalités",
    featuresDesc:         "Détail complet des fonctionnalités gratuites et Premium avec tableau comparatif.",
    premiumTitle:         "Guide Premium",
    premiumDesc:          "Séquences automatiques, macros personnalisables et macro périodique.",
    interfaceTitle:       "Interface & Personnalisation",
    interfaceDesc:        "Thèmes visuels, langues et options de personnalisation.",
    troubleshootingTitle: "Dépannage",
    troubleshootingDesc:  "Solutions aux problèmes courants, FAQ et optimisation des performances.",
    legalTitle:           "Légal & Confidentialité",
    legalDesc:            "Disclaimer, mentions légales, termes de licence, politique de confidentialité et changelog.",
    articles:             "Articles & Guides Flyff Universe",
    articleAutomateTitle: "Automatiser son Ringmaster",
    articleAutomateDesc:  "Tutoriel pas à pas pour automatiser votre Ringmaster sur Flyff Universe avec Reborn Assistant.",
    articleToolsTitle:    "Meilleurs outils Flyff Universe 2026",
    articleToolsDesc:     "Comparatif des extensions, traducteurs et calculateurs testés pour Flyff Universe.",
    articleGuideTitle:    "Guide complet du Ringmaster",
    articleGuideDesc:     "Rôle, buffs, builds STA/INT, équipement : tout sur la classe support Flyff Universe.",
    footer:               "© 2026 Reborn Assistant — Développé par Seymoon · Tous droits réservés",
  },

  // ── docs/features.html ────────────────────────────────────────────
  docFeatures: {
    h1:        "⚡ Fonctionnalités",
    subtitle:  "Découvrez tout ce que Reborn Assistant peut faire pour vous",
    h2Free:    "Fonctionnalités GRATUITES",
    freeBadge: "GRATUIT",
    c1Title: "Action automatique de type 1",
    c1Desc:  "Déclenchez automatiquement votre action de type 1 (HP) selon un timer configurable.",
    c1li1:   "Timer d'action configurable",
    c1li2:   "Fonctionne en arrière-plan",
    c2Title: "Thèmes visuels",
    c2Desc:  "Personnalisez l'apparence de l'interface avec 6 thèmes différents.",
    c2li1:   "MMO Gold (par défaut)",
    c2li2:   "Dark Mode & White Mode",
    c3Title: "Multi-langues",
    c3Desc:  "Interface disponible en 15 langues pour une expérience internationale.",
    c3li3:   "Changement instantané",
    h2Premium: "Fonctionnalités PREMIUM 💎",
    p1Title: "Macro déclencheur 1 automatique",
    p1Desc:  "Déclenchement automatique de votre action de type 1 (HP) selon un timer configurable.",
    p1li1:   "Timer déclencheur 1 configurable",
    p1li2:   "Touche de raccourci configurable",
    p1li3:   "Fonctionne en arrière-plan",
    p2Title: "Macro déclencheur 2 automatique",
    p2Desc:  "Utilisation automatique de vos actions de type 2 selon un timer configurable.",
    p2li1:   "Timer déclencheur 2 configurable",
    p2li2:   "Touche de raccourci configurable",
    p2li3:   "Fonctionne en arrière-plan",
    p3Title: "Raccourcis clavier",
    p3Desc:  "Contrôlez Reborn Assistant à la volée avec des raccourcis globaux personnalisables.",
    p3li1:   "CTRL+A : Démarrer le bot",
    p3li2:   "CTRL+O : Arrêter le bot",
    p4Title: "Rotation de séquences",
    p4Desc:  "Système automatique de maintien des séquences avec une séquence prédéfinie.",
    p4li1:   "Séquence : F2 → 1-9 → 0 → F1",
    p4li2:   "Intervalle configurable (minutes)",
    p4li3:   "Délai entre touches réglable",
    p5Title: "Macros Personnalisables",
    p5Desc:  "Créez jusqu'à 3 macros avec vos propres séquences de touches.",
    p5li1:   "3 macros indépendantes",
    p5li2:   "Séquences personnalisées",
    p5li3:   "Intervalles de répétition réglables",
    p6Title: "Macro périodique",
    p6Desc:  "Appel et stockage automatique de votre macro périodique toutes les 15 secondes.",
    p6li1:   "Appel automatique de la macro périodique",
    p6li2:   "Auto-stockage après appel",
    p6li3:   "Intervalle fixe de 15 secondes",
    tableH2:      "Tableau comparatif",
    tableFeature: "Fonctionnalité",
    tableFree:    "Gratuit",
    row1:  "Action automatique de type 1 (HP)",
    row2:  "Thèmes visuels (6)",
    row3:  "Multi-langues (15)",
    row4:  "Macro déclencheur 1 automatique",
    row5:  "Macro déclencheur 2 automatique",
    row6:  "Raccourcis clavier (CTRL+A / CTRL+O)",
    row7:  "Rotation de séquences automatique",
    row8:  "Macros personnalisables (3x)",
    row9:  "Macro périodique auto",
    learnMore: "→ En savoir plus sur les fonctionnalités Premium",
  },

  // ── docs/quickstart.html ──────────────────────────────────────────
  docQuickstart: {
    h1:       "🚀 Démarrage Rapide",
    subtitle: "Installez et configurez Reborn Assistant en quelques minutes",
    reqH2:    "Prérequis",
    req1:     "<strong>Navigateur compatible :</strong> Google Chrome, Microsoft Edge, Brave ou tout navigateur basé sur Chromium",
    req2:     "<strong>Compte Google :</strong> Requis uniquement pour l'authentification Premium (optionnel pour version gratuite)",
    req3:     "<strong>Site compatible :</strong> Compatible avec les sites web standards",
    installH2:  "Installation",
    step1Title: "Visiter le Chrome Web Store",
    step1p:     "Rendez-vous sur la page Reborn Assistant dans le <a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome Web Store</a> et cliquez sur <strong>« Ajouter à Chrome »</strong>.",
    step1tip:   "💡 Compatible avec Google Chrome, Microsoft Edge, Brave et tout navigateur basé sur Chromium.",
    step2Title: "Confirmer l'installation",
    step2p:     "Cliquez sur <strong>« Ajouter l'extension »</strong> dans la fenêtre de confirmation. L'extension s'installe automatiquement.",
    step3Title: "Épingler l'extension",
    step3p:     "Cliquez sur l'icône puzzle 🧩 dans la barre d'outils de votre navigateur, puis épinglez Reborn Assistant pour un accès rapide.",
    step4Title: "Connexion (optionnelle pour Premium)",
    step4p:     "• Cliquez sur l'icône Reborn dans la barre d'outils<br>• Pour Premium : Connectez-vous avec votre compte Google<br>• Pour Gratuit : Utilisez directement sans connexion",
    alertTitle: "✅ Installation réussie !",
    alertText:  "L'icône Reborn devient verte lorsque l'extension est active. Vous pouvez maintenant configurer vos fonctionnalités.",
    configH2:   "Configuration initiale",
    freeH3:     "Version GRATUITE",
    freeTitle:  "<strong>Fonctionnalités disponibles sans connexion :</strong>",
    freeText:   "• Action automatique de type 1 (HP uniquement)<br>• 6 thèmes visuels<br>• Support de 15 langues",
    freeStepTitle: "Configuration de l'action automatique de type 1",
    freeStepText:  "1. Ouvrez le panneau Reborn (clic sur l'icône)<br>2. Réglez le timer de l'action HP (par défaut : 2s)<br>3. L'action se déclenche automatiquement<br>4. Aucune connexion requise",
    premiumH3:       "Version PREMIUM 💎",
    premiumFeatTitle:"<strong>Fonctionnalités additionnelles (nécessite connexion Google) :</strong>",
    premiumFeatText: "• Macro déclencheur 1 automatique (timer configurable + raccourci)<br>• Macro déclencheur 2 automatique (timer configurable + raccourci)<br>• Raccourcis clavier (CTRL+A / CTRL+O)<br>• Rotation automatique de séquences (F2 → 1-9 → 0 → F1)<br>• 3 macros personnalisables avec séquences de touches<br>• Système de familier périodique automatique (appel + stockage toutes les 15s)",
    premConfigTitle: "Configuration Premium",
    premConfigSeq:   "<strong>Séquences automatiques :</strong><br>• Activez « Séquence Rotation » dans le panneau<br>• Configurez l'intervalle entre les cycles (défaut : 5 min)<br>• Ajustez le délai entre chaque touche (défaut : 1s)",
    premConfigMacro: "<strong>Macros :</strong><br>• Activez Macro 1, 2 ou 3<br>• Définissez la séquence de touches (ex: <code>1,2,3,4</code>)<br>• Configurez l'intervalle de répétition",
    premConfigPer:   "<strong>Macro périodique :</strong><br>• Activez le toggle « Macro périodique »<br>• Le système appelle automatiquement votre macro périodique toutes les 15s<br>• Stockage automatique après l'appel",
    warnTitle: "⚠️ Note importante",
    warnText:  "Les fonctionnalités Premium (Macros déclencheur 1 et 2, Séquences automatiques, Macro périodique automatique, 3 macros configurables) nécessitent une licence Premium valide et une connexion Google. Sans licence, seule la macro de base est accessible.",
    shortcutsH2:   "Raccourcis clavier",
    shortcutsText: "<code>CTRL + A</code> : Démarrer le bot<br><code>CTRL + O</code> : Arrêter le bot",
    nextH2: "Prochaines étapes",
    link1:  "Découvrez toutes les fonctionnalités",
    link2:  "Guide complet Premium",
    link3:  "Solutions aux problèmes courants",
  },

  // ── docs/interface.html ───────────────────────────────────────────
  docInterface: {
    h1:       "🎨 Interface & Personnalisation",
    subtitle: "Personnalisez Reborn Assistant selon vos préférences",
    themesH2:    "Thèmes visuels",
    themesDesc:  "Reborn Assistant propose 6 thèmes pour personnaliser l'apparence de l'interface :",
    changeThemeH3:   "Changer de thème",
    changeThemeText: "1. Ouvrez le panneau Reborn<br>2. Cliquez sur l'onglet \"⚙️ CONFIGURATION\"<br>3. Sélectionnez votre thème dans le menu déroulant<br>4. Le changement est instantané",
    langsH2:   "Langues disponibles",
    langsDesc:  "Interface disponible en 15 langues :",
    changeLangH3:   "Changer de langue",
    changeLangText: "1. Ouvrez le panneau Reborn<br>2. Cliquez sur \"⚙️ CONFIGURATION\"<br>3. Sélectionnez votre langue dans le menu déroulant<br>4. Toute l'interface se traduit instantanément",
    shortcutsH2:   "Raccourcis clavier",
    shortcutsDesc: "Reborn Assistant inclut des raccourcis globaux pour un contrôle rapide :",
    systemH3: "Raccourcis système",
    sysSC1:   "<code>CTRL + A</code> : Démarrer le bot",
    sysSC2:   "<code>CTRL + O</code> : Arrêter le bot",
    customH3:   "Raccourcis personnalisables",
    customDesc: "Vous pouvez configurer les touches pour :",
    customLi1:  "Actions de type 1 et 2",
    customLi2:  "Macros (séquences de touches)",
    customLi3:  "Macro périodique",
    displayH2:    "Options d'affichage",
    panelPosH3:   "Position du panneau",
    panelPosDesc: "Le panneau Reborn est déplaçable :",
    panelLi1: "Cliquez sur l'en-tête du panneau",
    panelLi2: "Maintenez le bouton enfoncé et déplacez",
    panelLi3: "Relâchez à l'endroit souhaité",
    panelLi4: "La position est sauvegardée automatiquement",
    opacityH3:   "Opacité du panneau",
    opacityDesc: "Ajustez la transparence pour ne pas gêner votre navigation tout en gardant un œil sur vos statistiques.",
    logH3:   "Log d'activité",
    logDesc: "Le log affiche en temps réel toutes les actions effectuées :",
    logLi1:  "Activation/désactivation des systèmes",
    logLi2:  "Utilisation de potions",
    logLi3:  "Exécution des macros et séquences",
    logLi4:  "Appels de la macro périodique",
    logLi5:  "Erreurs éventuelles",
    saveH2:    "Sauvegarde des paramètres",
    saveDesc:  "Toutes vos configurations sont automatiquement sauvegardées localement :",
    saveLi1:   "Thème sélectionné",
    saveLi2:   "Langue de l'interface",
    saveLi3:   "Seuils déclencheurs",
    saveLi4:   "Touches assignées",
    saveLi5:   "Configuration des macros",
    saveLi6:   "Position du panneau",
    savePersist: "Elles persistent entre les sessions, même après fermeture du navigateur.",
  },

  // ── docs/premium.html ─────────────────────────────────────────────
  docPremium: {
    h1:       "💎 Guide Premium",
    subtitle: "Maîtrisez toutes les fonctionnalités avancées de Reborn Assistant",
    rotH2:    "🛡️ Rotation de séquences automatique",
    rotDesc:  "Le système de rotation maintient automatiquement toutes vos séquences actives en appuyant sur une séquence prédéfinie de touches à intervalles réguliers.",
    rotSeqH3:   "Séquence de touches",
    rotSeqText: "La rotation suit toujours cet ordre fixe :",
    rotConfigH3:   "Configuration",
    rotIntName:    "Intervalle entre cycles",
    rotIntDesc:    "Temps d'attente avant de recommencer toute la séquence. Par défaut : 5 minutes. Réglez selon la durée de vos séquences les plus courtes.",
    rotDelName:    "Délai entre touches",
    rotDelDesc:    "Temps d'attente entre chaque touche de la séquence. Par défaut : 1 seconde. Ajustez selon la vitesse du service concerné (animations, cooldowns...).",
    rotExTitle:    "💡 Exemple d'utilisation",
    rotExScenario: "<strong>Scénario :</strong> Vos séquences durent 5 minutes et vous avez 8 séquences sur les touches 1-8.",
    rotExConfig:   "<strong>Configuration :</strong>",
    rotExLi1:      "Intervalle : 5 minutes",
    rotExLi2:      "Délai : 1 seconde",
    rotExLi3:      "Le bot appuiera sur F2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1 toutes les 5 minutes",
    rotExLi4:      "Total de 13 touches avec 1 seconde entre chaque = ~13 secondes par cycle",
    macH2:    "⚙️ Macros Personnalisables",
    macDesc:  "Créez jusqu'à 3 macros indépendantes avec vos propres séquences de touches. Parfait pour l'automatisation des tâches répétitives, combos récurrents ou rotations de compétences.",
    macHowH3:   "Fonctionnement",
    macHowText: "Chaque macro exécute une séquence de touches à intervalle régulier, indépendamment des autres systèmes.",
    macConfigH3:  "Configuration",
    macSeqName:   "Séquence de touches",
    macSeqDesc:   "Définissez les touches à appuyer dans l'ordre, séparées par des virgules. Exemple : 1,2,3,4 ou q,w,e,r,f",
    macRepName:   "Intervalle de répétition",
    macRepDesc:   "Temps d'attente avant de recommencer la séquence. Configurez selon vos besoins (secondes ou minutes).",
    macDelName:   "Délai entre touches",
    macDelDesc:   "Temps d'attente entre chaque touche de la séquence (généralement 0.5 à 2 secondes).",
    macExTitle:   "💡 Exemples d'utilisation",
    mac1Title:    "<strong>Macro 1 – Automatisation répétitive :</strong>",
    mac1Li1:      "Séquence : 1,2,3,space",
    mac1Li2:      "Intervalle : 10 secondes",
    mac1Li3:      "Utilisation : Rotation d'attaques de base en boucle",
    mac2Title:    "<strong>Macro 2 – Combo de compétences :</strong>",
    mac2Li1:      "Séquence : q,w,e,r",
    mac2Li2:      "Intervalle : 30 secondes",
    mac2Li3:      "Utilisation : Rotation DPS optimale",
    mac3Title:    "<strong>Macro 3 – Support automatique :</strong>",
    mac3Li1:      "Séquence : f,g,h",
    mac3Li2:      "Intervalle : 15 secondes",
    mac3Li3:      "Utilisation : Séquences de groupe ou actions périodiques",
    perH2:    "🐉 Macro périodique",
    perDesc:  "Ce système exécute automatiquement une action périodique toutes les 15 secondes. Idéal pour les tâches répétitives qui doivent être relancées régulièrement.",
    perHowH3:   "Fonctionnement",
    perHowText: "Le système exécute automatiquement cette séquence toutes les 15 secondes :",
    perLi1:     "Appelle la macro périodique (touche configurable, par défaut §)",
    perLi2:     "Attend 500ms",
    perLi3:     "Stocke la macro périodique automatiquement",
    perConfigH3:  "Configuration",
    perCallName:  "Touche d'appel",
    perCallDesc:  "La touche qui déclenche votre macro périodique. Par défaut : §. Modifiez selon votre configuration.",
    perIntName:   "Intervalle (fixe)",
    perIntDesc:   "Le système fonctionne toujours avec un intervalle fixe de 15 secondes. Non configurable.",
    perExTitle:   "💡 Cas d'usage",
    perExText:    "Dans certains services, la macro périodique doit être appelée régulièrement pour collecter des objets, fournir des séquences temporaires ou gagner de l'expérience. Ce système automatise complètement ce processus.",
    perImpH3:     "⚠️ Important",
    perImpLi1:    "Vérifiez que la touche configurée correspond bien à votre touche d'invocation",
    perImpLi2:    "La macro périodique est automatiquement stockée après chaque appel",
    perImpLi3:    "Fonctionne en parallèle des autres systèmes (séquences, macros, actions)",
    optH2:   "Conseils d'optimisation",
    combH3:  "🎯 Combinaison des systèmes",
    combDesc:"Toutes les fonctionnalités Premium fonctionnent simultanément. Vous pouvez :",
    combLi1: "Activer les séquences automatiques + 3 macros + macro périodique en même temps",
    combLi2: "Les actions déclencheur 1 &amp; 2 fonctionnent toujours en parallèle",
    combLi3: "Chaque système a son propre timer indépendant",
    perfH3:  "⚡ Performance",
    perfLi1: "Plus vous activez de systèmes, plus l'extension consomme de ressources",
    perfLi2: "Ajustez les intervalles pour éviter des actions trop fréquentes",
    perfLi3: "Surveillez le log d'activité pour vérifier le bon fonctionnement",
    secH3:   "🔑 Sécurité",
    secLi1:  "Votre licence Premium est vérifiée en temps réel",
    secLi2:  "Si la connexion est perdue, les fonctionnalités Premium se désactivent",
    secLi3:  "Reconnectez-vous pour réactiver toutes les fonctionnalités",
  },

  // ── docs/troubleshooting.html ─────────────────────────────────────
  docTroubleshooting: {
    h1:       "🔧 Dépannage",
    subtitle: "Solutions aux problèmes courants et FAQ",
    installH2: "Problèmes d'installation",
    faq1Q: "❌ L'extension n'apparaît pas dans la barre d'outils",
    faq1A: "<strong>Solutions :</strong><br>1. Vérifiez que l'extension est bien installée depuis le <strong>Chrome Web Store</strong><br>2. Épinglez l'extension : cliquez sur l'icône puzzle 🧩 dans la barre d'outils et épinglez Reborn Assistant<br>3. Redémarrez votre navigateur<br>4. Si le problème persiste, désinstallez puis réinstallez l'extension depuis le Chrome Web Store",
    connH2: "Problèmes de connexion",
    faq2Q: "❌ \"Connexion échouée\" ou \"Licence invalide\"",
    faq2A: "<strong>Causes possibles :</strong><br>• Mauvaise connexion internet<br>• Serveurs Google Cloud temporairement indisponibles<br>• Licence expirée ou révoquée<br><br><strong>Solutions :</strong><br>1. Vérifiez votre connexion internet<br>2. Déconnectez-vous et reconnectez-vous avec Google<br>3. Vérifiez votre statut de licence dans votre espace Stripe<br>4. Contactez le support si le problème persiste",
    faq3Q: "❌ Le panneau indique \"FREE\" alors que j'ai Premium",
    faq3A: "1. Déconnectez-vous du compte Google<br>2. Fermez complètement le navigateur<br>3. Rouvrez et reconnectez-vous<br>4. Si le problème persiste, vérifiez que vous êtes connecté avec le bon compte Google (celui utilisé pour l'achat)",
    funcH2: "Problèmes de fonctionnement",
    faq4Q:     "❌ Les actions de type 1/2 ne se déclenchent pas",
    faq4Alert: "<strong>⚠️ IMPORTANT</strong><br>Les actions de type 1 et 2 sont des fonctionnalités <strong>PREMIUM UNIQUEMENT</strong>. Seule l'action automatique de type 1 (HP) est disponible en version gratuite.",
    faq4Prem:  "<strong>Si vous avez Premium :</strong><br>1. Le bot est-il démarré ? <code>CTRL+A</code><br>2. Les toggles déclencheurs sont-ils activés ? (indicateur vert « ON »)<br>3. Les touches configurées sont-elles correctes ?",
    faq5Q:     "❌ Les séquences / macros / macro périodique / raccourcis ne fonctionnent pas",
    faq5Alert: "<strong>⚠️ IMPORTANT</strong><br>Les raccourcis clavier, séquences, macros et macro périodique sont des fonctionnalités <strong>PREMIUM UNIQUEMENT</strong>. En version gratuite, seule l'action automatique de type 1 (HP) est disponible.",
    faq5Prem:  "<strong>Si vous avez Premium :</strong><br>1. Vérifiez que votre licence Premium est active (icône 💎 dans le panneau)<br>2. Les toggles correspondants sont-ils activés ?<br>3. Vérifiez les intervalles et délais configurés",
    faq6Q: "❌ Le bot s'arrête tout seul",
    faq6A: "<strong>Causes possibles :</strong><br>• Perte de connexion à Google Cloud<br>• Détection DevTools<br>• La page a changé d'URL<br><br><strong>Solutions :</strong><br>1. Redémarrez le bot avec <code>CTRL+A</code> (Premium) ou via le panneau<br>2. Rechargez la page concernée<br>3. Vérifiez votre connexion internet<br>4. Ne pas ouvrir les DevTools si vous êtes en Premium",
    optH2: "Optimisation & Performance",
    faq7Q: "💡 Le bot consomme trop de ressources",
    faq7A: "<strong>Recommandations :</strong><br>• Augmentez les intervalles des macros et séquences (moins d'actions = moins de CPU)<br>• Désactivez les systèmes dont vous n'avez pas besoin<br>• Fermez les autres onglets inutiles<br>• Utilisez un navigateur optimisé (Brave, Edge sont plus légers que Chrome)",
    faq8Q: "💡 Comment optimiser les paramètres ?",
    faq8A: "<strong>Configuration recommandée :</strong><br>• <strong>Intervalle séquences :</strong> 5-25 minutes (selon durée de vos séquences)<br>• <strong>Délai entre touches :</strong> 1-2 secondes (évite les erreurs)<br>• <strong>Macros :</strong> Intervalles de 10-30s selon l'usage",
    genH2:  "FAQ Générale",
    faq9Q:  "❓ Puis-je utiliser Reborn sur plusieurs navigateurs ?",
    faq9A:  "Oui, mais vous devez installer l'extension sur chaque navigateur. Votre licence Premium fonctionne sur tous vos appareils tant que vous vous connectez avec le même compte Google (1 connexion simultanée max).",
    faq10Q: "❓ Mes données sont-elles sauvegardées ?",
    faq10A: "Toutes vos configurations (touches, macros, thème, langue) sont sauvegardées <strong>localement</strong> dans le navigateur. Elles persistent entre les sessions. En revanche, si vous désinstallez l'extension, vous perdez ces données.",
    faq11Q: "❓ Reborn peut-il provoquer un bannissement ?",
    faq11A: "L'utilisation d'outils d'automatisation peut violer les CGU de certains services. <strong>Vous êtes seul responsable</strong> de l'utilisation que vous faites de Reborn. Consultez les conditions d'utilisation du service concerné avant d'utiliser cet outil.",
    faq12Q: "❓ Comment annuler mon abonnement Premium ?",
    faq12A: "Vous pouvez annuler à tout moment depuis votre portail de gestion Stripe (lien reçu par email après le paiement). L'annulation prend effet à la fin de votre période en cours. Aucun frais d'annulation.",
    faq13Q: "❓ Quid du plan À Vie si le service ferme ?",
    faq13A: "Le plan À Vie garantit l'accès tant que le service est actif. L'extension une fois installée fonctionne localement ; seule la vérification de licence nécessite une connexion internet.",
    supportH2:    "Besoin d'aide supplémentaire ?",
    supportTitle: "📧 Support",
    supportText:  "Si votre problème persiste, contactez le support directement par email. Incluez dans votre message :<br><br>• Une description détaillée du problème<br>• Les étapes que vous avez déjà tentées<br>• Des captures d'écran si pertinent<br>• Votre navigateur et système d'exploitation",
  },

  // ── docs/privacy.html ─────────────────────────────────────────────
  docPrivacy: {
    h1:       "⚖️ Légal & Confidentialité",
    subtitle: "Disclaimer, mentions légales, termes de licence et politique de confidentialité",
    navLegal:  "⚖️ Informations Légales",
    navLicence:"© Licence",
    navPrivacy:"🔒 Confidentialité",
    disclaimerH2:  "⚠️ Disclaimer",
    disclaimerBox: "<strong>⚠️ Avertissement important :</strong> Reborn Assistant est un outil d'automatisation. Son utilisation peut violer les Conditions Générales d'Utilisation de certains services en ligne. L'utilisation de cet outil est entièrement à vos risques et périls.",
    respH3:    "Responsabilité de l'utilisateur",
    respIntro: "En utilisant Reborn Assistant, vous reconnaissez et acceptez que :",
    respLi1:   "Vous êtes seul responsable de votre utilisation de ce logiciel",
    respLi2:   "Vous vérifierez les conditions d'utilisation de chaque service avant d'utiliser cet outil",
    respLi3:   "L'auteur ne peut être tenu responsable de tout bannissement, restriction de compte, ou action légale résultant de l'utilisation de Reborn",
    respLi4:   "Vous utilisez ce logiciel en connaissance de cause et à vos propres risques",
    respLi5:   "Cet outil ne doit pas être utilisé de manière à nuire à l'expérience d'autres utilisateurs",
    warrantH3:   "Absence de garantie",
    warrantText: "Le logiciel est fourni \"TEL QUEL\" sans garantie d'aucune sorte. L'auteur ne garantit pas que le logiciel fonctionnera de manière ininterrompue ou sans erreur, ni qu'il sera compatible avec tous les services ou navigateurs.",
    legalH2:    "📄 Mentions légales",
    copyrightH3:   "Droits d'auteur & Propriété intellectuelle",
    copyrightText: "<strong>© 2026 Reborn Assistant – Tous droits réservés</strong><br>Développé par <strong>Seymoon</strong>",
    copyrightText2:"Ce logiciel et tous les matériaux associés sont la propriété intellectuelle exclusive de leur auteur. Toute reproduction, modification, distribution ou rétro-ingénierie sans autorisation écrite est strictement interdite.",
    liabilityH3:   "Limitation de responsabilité",
    liabilityIntro:"En aucun cas l'auteur ne sera responsable de toute réclamation ou dommage découlant de l'utilisation ou de l'impossibilité d'utiliser ce logiciel, incluant mais sans s'y limiter :",
    liabilityLi1:  "Perte de données ou de compte utilisateur",
    liabilityLi2:  "Bannissements ou restrictions imposés par des éditeurs de services",
    liabilityLi3:  "Dommages aux systèmes informatiques",
    liabilityLi4:  "Toute conséquence juridique découlant d'une utilisation non conforme aux CGU des services",
    dataH3:    "Données personnelles",
    dataText:  "Reborn Assistant utilise Firebase (Google Cloud) pour la gestion des comptes et licences. Les données collectées se limitent à votre adresse email et identifiant de compte, uniquement à des fins d'authentification et de vérification de licence.",
    dataText2: "<strong>Aucune donnée d'activité n'est collectée ou transmise.</strong> Vos configurations restent stockées localement sur votre appareil.",
    jurisH3:   "Juridiction",
    jurisText: "Cet accord est régi par le droit applicable dans la juridiction de résidence du détenteur des droits d'auteur. En installant et utilisant ce logiciel, vous reconnaissez avoir lu, compris et accepté l'intégralité de ces conditions.",
    licenceH2:     "© Termes de licence",
    licenceH3:     "Licence d'utilisation",
    licenceIntro:  "L'achat d'un plan Reborn Assistant vous accorde une licence personnelle, non exclusive et non transférable d'utilisation du logiciel.",
    licenceAllows: "<strong>Cette licence vous autorise à :</strong>",
    licenceLi1:    "Utiliser le logiciel à des fins personnelles sur vos propres appareils",
    licenceLi2:    "Bénéficier des mises à jour incluses dans votre plan",
    licenceForbids:"<strong>Cette licence ne vous autorise pas à :</strong>",
    licenceLi3:    "Redistribuer, revendre ou partager votre accès",
    licenceLi4:    "Modifier, décompiler ou procéder à une rétro-ingénierie du logiciel",
    licenceLi5:    "Utiliser le logiciel à des fins commerciales sans accord écrit préalable",
    licenceLi6:    "Transférer votre licence à un tiers",
    terminationH3:   "Résiliation",
    terminationText: "La licence peut être résiliée immédiatement en cas de violation de ces termes. Pour les plans avec abonnement, vous pouvez résilier à tout moment depuis votre portail Stripe.",
    refundBox: "<strong>✅ Politique de remboursement :</strong> Si vous n'êtes pas satisfait dans les 7 jours suivant votre achat, contactez notre support pour un remboursement intégral. Au-delà de cette période, aucun remboursement ne sera accordé sauf cas exceptionnel.",
    privacyH1:      "🔒 Politique de Confidentialité",
    privacySubtitle:"Comment nous protégeons vos données personnelles",
    privacyBox:     "<strong>✅ Votre vie privée est notre priorité</strong><br>Version gratuite : aucune donnée personnelle collectée. Version Premium : seules les données strictement nécessaires à la vérification de votre licence sont traitées.",
    collectH2:        "Collecte de données",
    collectFreeH3:    "Version Gratuite",
    collectFreeText:  "Aucune donnée personnelle n'est collectée ni transmise. Toutes vos préférences sont stockées uniquement sur votre appareil.",
    collectPremH3:    "Version Premium",
    collectPremIntro: "Pour vérifier votre licence et sécuriser votre compte, les données suivantes sont traitées :",
    collectPremLi1:   "Votre adresse email Google (via authentification Google)",
    collectPremLi2:   "Un identifiant d'appareil unique (généré localement)",
    collectPremLi3:   "Votre statut d'abonnement et horodatages de session",
    collectPremLi4:   "Maximum 2 appareils enregistrés par compte",
    collectPremBasis: "<strong>Base légale :</strong> exécution du contrat (art. 6.1.b RGPD).",
    collectNotH3:     "Données jamais collectées",
    collectNotLi1:    "❌ Aucune donnée de gameplay ou d'activité",
    collectNotLi2:    "❌ Aucun historique de navigation",
    collectNotLi3:    "❌ Aucun cookie publicitaire ou de tracking",
    localH2:    "Données stockées localement",
    localIntro: "Les informations suivantes sont sauvegardées <strong>uniquement sur votre appareil</strong> :",
    localLi1:   "<strong>Préférences de langue</strong> : Votre choix de langue d'interface",
    localLi2:   "<strong>Sélection du thème visuel</strong> : Le thème choisi parmi les 6 disponibles",
    localLi3:   "<strong>Raccourcis clavier configurés</strong> : Les touches assignées pour vos actions",
    localLi4:   "<strong>Intervalles de timer personnalisés</strong> : Les timers configurés pour vos macros",
    localLi5:   "<strong>Position de l'interface</strong> : L'emplacement du panneau Reborn sur votre écran",
    localLi6:   "<strong>Cache de licence (Premium)</strong> : identifiant d'appareil et statut d'abonnement, pour éviter une vérification à chaque démarrage",
    thirdH2:       "Services tiers",
    thirdH3:       "Services utilisés (version Premium)",
    thirdDesc:     "Pour l'authentification et les paiements, Reborn Assistant utilise :",
    thirdLi1:      "🔐 <strong>Google</strong> — Authentification et stockage sécurisé des données de licence",
    thirdLi2:      "💳 <strong>Stripe</strong> — Traitement des paiements Premium (vos données bancaires ne transitent jamais par nos serveurs)",
    thirdTransfer: "Ces prestataires sont conformes au RGPD et disposent des garanties appropriées pour les transferts internationaux de données.",
    thirdNoH3:     "Aucun tracking, aucune publicité",
    thirdLi3:      "❌ Aucun service d'analyse ou de statistiques",
    thirdLi4:      "❌ Aucune publicité ni marketing ciblé",
    thirdLi5:      "❌ Aucun cookie tiers ou suivi comportemental",
    authH2:    "Authentification et gestion des appareils",
    authH3:    "Connexion Google (version Premium)",
    authText:  "Votre compte Google est utilisé uniquement pour authentifier votre identité et vérifier votre licence. Votre appareil est enregistré dans notre système sécurisé (maximum 2 appareils par compte).",
    authText2: "Vous recevez une notification si votre compte est utilisé sur un appareil non reconnu. Vous pouvez gérer vos appareils enregistrés directement depuis l'extension.",
    payH2:    "Paiements Sécurisés",
    payText:  "Les paiements Premium sont traités par <strong>Stripe</strong>. Vos informations bancaires ne transitent <strong>jamais</strong> par nos serveurs. Nous ne stockons <strong>aucune donnée</strong> de carte bancaire.",
    retentionH2:   "Durée de conservation",
    retentionText: "Vos données sont conservées uniquement le temps nécessaire :",
    retentionLi1:  "<strong>Compte actif :</strong> données conservées pour toute la durée de l'abonnement",
    retentionLi2:  "<strong>Après résiliation :</strong> suppression sous 30 jours",
    retentionLi3:  "<strong>Données locales :</strong> supprimées immédiatement à la désinstallation de l'extension",
    rightsH2:      "Vos droits (RGPD)",
    rightsText:    "Conformément au RGPD, vous disposez des droits suivants sur vos données :",
    rightsLi1:     "✅ <strong>Accès</strong> — Obtenir une copie de vos données personnelles",
    rightsLi2:     "✅ <strong>Rectification</strong> — Corriger des données inexactes",
    rightsLi3:     "✅ <strong>Effacement</strong> — Demander la suppression de votre compte et de vos données",
    rightsLi4:     "✅ <strong>Portabilité</strong> — Recevoir vos données dans un format lisible",
    rightsLi5:     "✅ <strong>Réclamation</strong> — Déposer une plainte auprès de la CNIL (cnil.fr)",
    rightsExercise:"Pour exercer ces droits, contactez-nous à : seymoon.cell@gmail.com ou sur Discord (Seymoon)",
    deleteH2:    "Suppression de vos données",
    deleteText1: "<strong>1. Désinstallation de l'extension</strong><br>En désinstallant Reborn Assistant, toutes les données locales sont automatiquement supprimées.",
    deleteText2: "<strong>2. Réinitialisation manuelle</strong><br>Vous pouvez réinitialiser les paramètres depuis l'interface de Reborn à tout moment.",
    deleteText3: "<strong>3. Suppression du compte (Premium)</strong><br>Pour supprimer votre compte Premium et toutes les données associées, contactez-nous par email.",
    contactH2:   "Contact",
    contactText: "Pour toute question concernant les informations légales ou la politique de confidentialité :",
    changelogH2: "📋 Changelog",
    v130H3:          "Version 1.3.0 (Mars 2026) · Actuelle",
    v130newLabel:    "✨ Nouveautés",
    v130improvLabel: "🔧 Améliorations",
    v130fixLabel:    "🐛 Corrections",
    v130Li1:  "⏱ Mini-timer flottant déplaçable — petite fenêtre flottante affichant les timers de buff et ceux de plus d'1 minute, se rouvre automatiquement au prochain lancement et suit le skin actif.",
    v130Li2:  "⚡ Macros prioritaires — les macros passent avant les soins/PV/mana, avec un gel du soin de 0,5s avant et après chaque exécution pour éviter les conflits.",
    v130Li3:  "🧠 Gestion intelligente du buff — le buff s'exécute en priorité, les macros silencées sont mises en file et relancées automatiquement après sa fin (délai réduit à 2s).",
    v130Li4:  "💾 Mémorisation des positions — les fenêtres flottantes retiennent leur position entre les sessions.",
    v130Li5:  "🇸🇦 Support de l'arabe — 15ème langue disponible dans l'extension.",
    v130Li6:  "💳 Paiement Stripe en popup — s'ouvre dans une fenêtre dédiée avec fermeture automatique, sans quitter l'extension.",
    v130Li7:  "🐾 Familier : correction du bug où le pet ne sortait pas au premier buff + meilleur suivi du mode F1/F2 pour le rangement au stop.",
    v130Li8:  "⏱ Timer : refonte visuelle du design premium + opacité 55% au repos → 95% au survol pour une meilleure lisibilité.",
    v130Li9:  "💳 Portail billing : une seule fenêtre active en mémoire avec fermeture automatique.",
    v130Li10:  "Correction de plusieurs fuites mémoire dans le contenu et le popup.",
    v130Li16:  "Alignement UI sur la limite de 2 appareils max (cohérence avec le backend).",
    v120H3:  "Version 1.2.0 (Mars 2026)",
    v120Li1: "✨ Les 6 skins ont été retravaillés avec un effet de transparence subtil.",
    v120Li2: "🔐 Visualisez et gérez votre appareil enregistré directement depuis l'extension.",
    v120Li3: "💳 Accédez à votre abonnement en un clic depuis l'extension.",
    v120Li4: "🔔 Notification instantanée si votre compte est utilisé sur un autre appareil.",
    v12H3:   "Version 1.2 (Février 2026)",
    v12Li1:  "Support de 15 langues (ajout Turc 🇹🇷)",
    v12Li2:  "Refonte visuelle du site web",
    v12Li3:  "Fusion des pages légales en une seule page unifiée",
    v12Li4:  "Traduction complète FR/EN du site",
    v11H3:   "Version 1.1.1 (Février 2026)",
    v11Li1:  "Ajout de la macro périodique automatique (15s + auto-stockage)",
    v11Li2:  "Raccourcis clavier CTRL+A / CTRL+O",
    v11Li3:  "Support de 15 langues (ajout Filipino + Turc)",
    v11Li4:  "Amélioration de la stabilité de la licence Premium",
    v11Li5:  "Corrections de bugs sur la rotation de séquences",
    v10H3:   "Version 1.0 (2025) · Initiale",
    v10Li1:  "Lancement de Reborn Assistant",
    v10Li2:  "Actions automatiques de type 1 et 2",
    v10Li3:  "Rotation séquence automatique (F2 → 1-9 → 0 → F1)",
    v10Li4:  "3 macros personnalisables",
    v10Li5:  "6 thèmes visuels et 12 langues",
    v10Li6:  "Système de licence Premium via Firebase",
    pageFooter:"© 2026 Reborn Assistant — Développé par Seymoon · Tous droits réservés",
  },
  nav: {
    docsFull:    "📚 Documentation",
    docsShort:   "📚 Docs",
    manageFull:  "Gérer mon abonnement",
    manageShort: "Gérer",
  },
};