export default {
  hero: {
    description: "Estensione di automazione del browser con macro avanzate. Automatizza le tue azioni ripetitive, scorciatoie e sequenze per ottimizzare la tua produttività.",
    ctaPrimary: "Inizia ora",
    ctaSecondary: "Scopri di più",
    trust1: "Versione gratuita disponibile",
    trust2: "Senza impegno",
    trust3: "Pagamento 100% sicuro",
    trust4: "Aggiornamenti automatici",
  },
  features: {
    tag: "Abilità & Competenze",
    titleBefore: "Tutto ciò che ",
    titleEm: "ti serve",
    subtitle: "Scopri le straordinarie capacità di Reborn Assistant.",
    card1: { badge: "Attivo",    title: "Automazione Completa",       description: "Macro di tasti, sequenze automatiche e azioni configurabili per un'automazione completa." },
    card2: { badge: "Passivo",  title: "Sicurezza Massima",           description: "I tuoi dati rimangono locali. Nessun tracciamento, nessuna telemetria." },
    card3: { badge: "Attivo",    title: "Macro Personalizzabili",     description: "3 macro configurabili con attivatori automatici e scorciatoie da tastiera." },
    card4: { badge: "Passivo",  title: "Interfaccia Personalizzabile",description: "Scegli tra 6 temi e adatta l'interfaccia alle tue esigenze." },
    card5: { badge: "Passivo",  title: "Multi-Lingua",                description: "Disponibile in 15 lingue. Supporto mondiale con interfacce localizzate." },
    card6: { badge: "Gratuito", title: "Versione Gratuita",           description: "Prova gratis con le funzioni di base incluse." },
  },
  security: {
    tag: "Sicurezza",
    titleBefore: "Sicurezza di livello ",
    titleEm: "professionale",
    titleAfter: "",
    description: "Reborn Assistant utilizza gli stessi standard di sicurezza delle piattaforme di streaming mondiali. Le tue credenziali sono protette da <strong style='color:var(--gold);'>crittografia JWT</strong>, i tuoi pagamenti garantiti tramite <strong style='color:var(--gold);'>Stripe</strong>, e i tuoi dati rimangono <strong style='color:var(--gold);'>100% locali</strong>. Nessun tracciamento, nessuna rivendita di dati.",
    card1Title: "Crittografia JWT",
    card1Text:  "Autenticazione sicura di livello bancario",
    card2Title: "Pagamento con Stripe",
    card2Text:  "Processore utilizzato da Amazon e Google",
    card3Title: "Zero Tracciamento",
    card3Text:  "I tuoi dati non lasciano mai il tuo dispositivo",
    card4Text:  "Infrastruttura sicura di Google Cloud",
  },
  pricing: {
    tag:         "Scegli la tua Classe",
    titleBefore: "Scegli il tuo ",
    titleEm:     "rango",
    subtitle:    "Scegli la formula più adatta a te. Senza impegno.",
    voyageur: {
      rank: "Rango I · Viaggiatore", plan: "Gratuito", period: "per sempre",
      feat1: "Macro di cura", feat2: "6 temi visivi", feat3: "15 lingue disponibili", feat4: "Interfaccia flottante",
      btn: "Inizia", download: "Aggiungi a Chrome", guarantee: "🔒 Gratuito per sempre",
    },
    aventurier: {
      rank: "Rango II · Avventuriero", plan: "Mensile", period: "al mese",
      feat1: "Tutte le funzioni Premium", feat2: "Supporto prioritario", feat3: "Aggiornamenti gratuiti",
      btn: "Prova Gratis", guarantee: "🎁 7 giorni gratis · Senza carta di credito",
      download: "Aggiungi a Chrome",
    },
    champion: {
      badge: "⭐ Popolare -17%",
      rank: "Rango III · Campione", plan: "Annuale", period: "all'anno · 2,50€/mese",
      feat1: "Tutte le funzioni Premium", feat2: "Supporto prioritario", feat3: "Aggiornamenti gratuiti",
      btn: "Prova Gratis", guarantee: "🎁 7 giorni gratis · Senza carta di credito",
      download: "Aggiungi a Chrome",
    },
    legende: {
      badge: "⚡ Offerta Limitata",
      rank: "Rango IV · Leggenda", plan: "A Vita", period: "pagamento unico · mai più",
      feat1: "Accesso a vita", feat2: "Tutti gli aggiornamenti futuri", feat3: "Supporto premium dedicato", feat4: "Miglior rapporto qualità-prezzo",
      btn: "Acquista", guarantee: "🔒 Pagamento unico · Accesso garantito a vita",
      download: "Aggiungi a Chrome",
    },
  },
  stats: {
    label1: "Lingue disponibili", label2: "Temi visivi", label3: "Dati locali", label4: "Estensione attiva",
  },
  trust: {
    badge1: "Pagamento sicuro SSL", badge2: "Accesso immediato", badge3: "Dati 100% privati", badge4: "Supporto reattivo",
  },
  store: {
    status: "Estensione ufficiale",
    title:  "Disponibile sul Chrome Web Store",
    install: "Installa",
    available: "Disponibile gratuitamente · Estensione ufficiale verificata da Google",
  },
  faq: {
    titleBefore: "Domande ",
    titleEm:     "frequenti",
    subtitle:    "Tutto quello che devi sapere prima di iniziare.",
    q1: "La prova gratuita richiede una carta di credito?",
    a1: "No, non è necessaria alcuna carta di credito. I primi 7 giorni sono completamente gratuiti, senza impegno. Crea semplicemente il tuo account per iniziare subito.",
    q2: "Posso cambiare piano in qualsiasi momento?",
    a2: "Sì, puoi passare a un piano superiore o inferiore in qualsiasi momento dal tuo account. Nessun costo di cambio.",
    q3: "Il piano A Vita include davvero tutti gli aggiornamenti futuri?",
    a3: "Assolutamente. Il piano A Vita ti garantisce l'accesso a tutti gli aggiornamenti e alle nuove funzioni future, senza pagare nulla in più.",
    q4: "I miei dati sono al sicuro?",
    a4: "Tutti i tuoi dati sono memorizzati localmente sul tuo dispositivo. Non raccogliamo dati personali né utilizziamo tracciamento o telemetria.",
    q5: "Come contattare il supporto?",
    a5: "Contattaci via e-mail all'indirizzo seymoon.cell@gmail.com o su Discord (Seymoon). Gli abbonati premium ricevono una risposta prioritaria.",
    q6: "Reborn Assistant è un bot?",
    a6: "No, Reborn Assistant non è un bot. È un'estensione di macro configurabili che automatizza sequenze di tasti che definisci tu stesso. Nessuna intelligenza artificiale, nessuna interazione con il server di gioco, nessuna lettura della memoria. L'estensione non legge né modifica i dati di gioco — simula solo i tasti che premeresti manualmente. Devi rimanere davanti al tuo computer per giocare: Reborn Assistant non risolve i captcha, non resuscita il tuo personaggio e non ti riporta allo spot dopo una morte. È uno strumento per semplificarti il gioco, non per sostituirti.",
  },
  footer: {
    privacy:   "Privacy",
    terms:     "Termini di Utilizzo",
    copyright: "© 2026 Reborn Assistant. Tutti i diritti riservati.<br>Sviluppato da Seymoon",
  },

  // ── Navigazione condivisa docs ────────────────────────────────────
  docsNav: {
    backToDocs:      "← Torna alla documentazione",
    mainSite:        "⌂ Sito principale",
    backToMainSite:  "← Torna al sito principale",
    footer:          "© 2026 Reborn Assistant — Sviluppato da Seymoon · Tutti i diritti riservati",
  },

  // ── docs/index.html ───────────────────────────────────────────────
  docsHome: {
    version:              "VERSIONE 1.3 · DOCUMENTAZIONE COMPLETA",
    userGuide:            "Guida utente",
    support:              "Supporto",
    legal:                "Informazioni legali",
    quickstartTitle:      "Avvio Rapido",
    quickstartDesc:       "Installazione, configurazione iniziale e primi passi con Reborn Assistant.",
    featuresTitle:        "Funzionalità",
    featuresDesc:         "Dettaglio completo delle funzioni gratuite e Premium con tabella comparativa.",
    premiumTitle:         "Guida Premium",
    premiumDesc:          "Sequenze automatiche, macro personalizzabili e macro periodica.",
    interfaceTitle:       "Interfaccia & Personalizzazione",
    interfaceDesc:        "Temi visivi, lingue e opzioni di personalizzazione.",
    troubleshootingTitle: "Risoluzione dei problemi",
    troubleshootingDesc:  "Soluzioni ai problemi comuni, domande frequenti e ottimizzazione delle prestazioni.",
    legalTitle:           "Legale & Privacy",
    legalDesc:            "Avviso legale, note legali, termini di licenza, informativa sulla privacy e registro delle modifiche.",
    footer:               "© 2026 Reborn Assistant — Sviluppato da Seymoon · Tutti i diritti riservati",
  },

  // ── docs/features.html ────────────────────────────────────────────
  docFeatures: {
    h1:        "⚡ Funzionalità",
    subtitle:  "Scopri tutto ciò che Reborn Assistant può fare per te",
    h2Free:    "Funzionalità GRATUITE",
    freeBadge: "GRATIS",
    c1Title: "Azione automatica tipo 1",
    c1Desc:  "Attiva automaticamente la tua azione tipo 1 (HP) in base a un timer configurabile.",
    c1li1:   "Timer azione configurabile",
    c1li2:   "Funziona in background",
    c2Title: "Temi visivi",
    c2Desc:  "Personalizza l'aspetto dell'interfaccia con 6 temi diversi.",
    c2li1:   "MMO Gold (predefinito)",
    c2li2:   "Dark Mode & White Mode",
    c3Title: "Multi-lingua",
    c3Desc:  "Interfaccia disponibile in 15 lingue per un'esperienza internazionale.",
    c3li3:   "Cambio istantaneo",
    h2Premium: "Funzionalità PREMIUM 💎",
    p1Title: "Macro attivatore 1 automatico",
    p1Desc:  "Attivazione automatica della tua azione tipo 1 (HP) in base a un timer configurabile.",
    p1li1:   "Timer attivatore 1 configurabile",
    p1li2:   "Tasto di scelta rapida configurabile",
    p1li3:   "Funziona in background",
    p2Title: "Macro attivatore 2 automatico",
    p2Desc:  "Uso automatico delle tue azioni tipo 2 in base a un timer configurabile.",
    p2li1:   "Timer attivatore 2 configurabile",
    p2li2:   "Tasto di scelta rapida configurabile",
    p2li3:   "Funziona in background",
    p3Title: "Scorciatoie da tastiera",
    p3Desc:  "Controlla Reborn Assistant al volo con scorciatoie globali personalizzabili.",
    p3li1:   "CTRL+A: Avvia il bot",
    p3li2:   "CTRL+O: Ferma il bot",
    p4Title: "Rotazione sequenze",
    p4Desc:  "Sistema automatico di mantenimento delle sequenze con una sequenza predefinita.",
    p4li1:   "Sequenza: F2 → 1-9 → 0 → F1",
    p4li2:   "Intervallo configurabile (minuti)",
    p4li3:   "Ritardo tra i tasti regolabile",
    p5Title: "Macro Personalizzabili",
    p5Desc:  "Crea fino a 3 macro con le tue sequenze di tasti personalizzate.",
    p5li1:   "3 macro indipendenti",
    p5li2:   "Sequenze personalizzate",
    p5li3:   "Intervalli di ripetizione regolabili",
    p6Title: "Macro periodica",
    p6Desc:  "Chiamata e memorizzazione automatica della tua macro periodica ogni 15 secondi.",
    p6li1:   "Chiamata automatica della macro periodica",
    p6li2:   "Auto-memorizzazione dopo la chiamata",
    p6li3:   "Intervallo fisso di 15 secondi",
    tableH2:      "Tabella comparativa",
    tableFeature: "Funzionalità",
    tableFree:    "Gratis",
    row1:  "Azione automatica tipo 1 (HP)",
    row2:  "Temi visivi (6)",
    row3:  "Multi-lingua (15)",
    row4:  "Macro attivatore 1 automatico",
    row5:  "Macro attivatore 2 automatico",
    row6:  "Scorciatoie da tastiera (CTRL+A / CTRL+O)",
    row7:  "Rotazione sequenze automatica",
    row8:  "Macro personalizzabili (3x)",
    row9:  "Macro periodica automatica",
    learnMore: "→ Scopri di più sulle funzioni Premium",
  },

  // ── docs/quickstart.html ──────────────────────────────────────────
  docQuickstart: {
    h1:       "🚀 Avvio Rapido",
    subtitle: "Installa e configura Reborn Assistant in pochi minuti",
    reqH2:    "Requisiti",
    req1:     "<strong>Browser compatibile:</strong> Google Chrome, Microsoft Edge, Brave o qualsiasi browser basato su Chromium",
    req2:     "<strong>Account Google:</strong> Richiesto solo per l'autenticazione Premium (opzionale per la versione gratuita)",
    req3:     "<strong>Sito compatibile:</strong> Compatibile con siti web standard",
    installH2:  "Installazione",
    step1Title: "Visita il Chrome Web Store",
    step1p:     "Vai alla pagina di Reborn Assistant sul <a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome Web Store</a> e clicca su <strong>«Aggiungi a Chrome»</strong>.",
    step1tip:   "💡 Compatibile con Google Chrome, Microsoft Edge, Brave e qualsiasi browser basato su Chromium.",
    step2Title: "Conferma l'installazione",
    step2p:     "Clicca su <strong>«Aggiungi estensione»</strong> nella finestra di conferma. L'estensione viene installata automaticamente.",
    step3Title: "Fissa l'estensione",
    step3p:     "Clicca sull'icona puzzle 🧩 nella barra degli strumenti del browser, poi fissa Reborn Assistant per un accesso rapido.",
    step4Title: "Accesso (opzionale per Premium)",
    step4p:     "• Clicca sull'icona di Reborn nella barra degli strumenti<br>• Per Premium: Accedi con il tuo account Google<br>• Per Gratuito: Usalo direttamente senza accesso",
    alertTitle: "✅ Installazione completata!",
    alertText:  "L'icona di Reborn diventa verde quando l'estensione è attiva. Ora puoi configurare le tue funzioni.",
    configH2:   "Configurazione iniziale",
    freeH3:     "Versione GRATUITA",
    freeTitle:  "<strong>Funzioni disponibili senza accesso:</strong>",
    freeText:   "• Azione automatica tipo 1 (solo HP)<br>• 6 temi visivi<br>• Supporto 15 lingue",
    freeStepTitle: "Configurazione dell'azione automatica tipo 1",
    freeStepText:  "1. Apri il pannello di Reborn (clicca sull'icona)<br>2. Regola il timer dell'azione HP (predefinito: 2s)<br>3. L'azione si attiva automaticamente<br>4. Nessun accesso richiesto",
    premiumH3:       "Versione PREMIUM 💎",
    premiumFeatTitle:"<strong>Funzioni aggiuntive (richiede accesso con Google):</strong>",
    premiumFeatText: "• Macro attivatore 1 automatico (timer configurabile + scorciatoia)<br>• Macro attivatore 2 automatico (timer configurabile + scorciatoia)<br>• Scorciatoie da tastiera (CTRL+A / CTRL+O)<br>• Rotazione automatica delle sequenze (F2 → 1-9 → 0 → F1)<br>• 3 macro personalizzabili con sequenze di tasti<br>• Sistema di macro periodica automatico (chiamata + memorizzazione ogni 15s)",
    premConfigTitle: "Configurazione Premium",
    premConfigSeq:   "<strong>Sequenze automatiche:</strong><br>• Attiva «Rotazione Sequenze» nel pannello<br>• Configura l'intervallo tra i cicli (predefinito: 5 min)<br>• Regola il ritardo tra ogni tasto (predefinito: 1s)",
    premConfigMacro: "<strong>Macro:</strong><br>• Attiva Macro 1, 2 o 3<br>• Definisci la sequenza di tasti (es: <code>1,2,3,4</code>)<br>• Configura l'intervallo di ripetizione",
    premConfigPer:   "<strong>Macro periodica:</strong><br>• Attiva l'interruttore «Macro periodica»<br>• Il sistema chiama automaticamente la tua macro periodica ogni 15s<br>• Memorizzazione automatica dopo la chiamata",
    warnTitle: "⚠️ Nota importante",
    warnText:  "Le funzioni Premium (Macro attivatori 1 e 2, Sequenze automatiche, Macro periodica automatica, 3 macro configurabili) richiedono una licenza Premium valida e un accesso Google. Senza licenza, è disponibile solo la macro di base.",
    shortcutsH2:   "Scorciatoie da tastiera",
    shortcutsText: "<code>CTRL + A</code>: Avvia il bot<br><code>CTRL + O</code>: Ferma il bot",
    nextH2: "Prossimi passi",
    link1:  "Scopri tutte le funzionalità",
    link2:  "Guida completa Premium",
    link3:  "Soluzioni ai problemi comuni",
  },

  // ── docs/interface.html ───────────────────────────────────────────
  docInterface: {
    h1:       "🎨 Interfaccia & Personalizzazione",
    subtitle: "Personalizza Reborn Assistant secondo le tue preferenze",
    themesH2:    "Temi visivi",
    themesDesc:  "Reborn Assistant offre 6 temi per personalizzare l'aspetto dell'interfaccia:",
    changeThemeH3:   "Cambiare tema",
    changeThemeText: "1. Apri il pannello di Reborn<br>2. Clicca sulla scheda \"⚙️ IMPOSTAZIONI\"<br>3. Seleziona il tuo tema nel menu a discesa<br>4. Il cambio è istantaneo",
    langsH2:    "Lingue disponibili",
    langsDesc:  "Interfaccia disponibile in 15 lingue:",
    changeLangH3:   "Cambiare lingua",
    changeLangText: "1. Apri il pannello di Reborn<br>2. Clicca su \"⚙️ IMPOSTAZIONI\"<br>3. Seleziona la tua lingua nel menu a discesa<br>4. Tutta l'interfaccia si traduce istantaneamente",
    shortcutsH2:   "Scorciatoie da tastiera",
    shortcutsDesc: "Reborn Assistant include scorciatoie globali per un controllo rapido:",
    systemH3: "Scorciatoie di sistema",
    sysSC1:   "<code>CTRL + A</code>: Avvia il bot",
    sysSC2:   "<code>CTRL + O</code>: Ferma il bot",
    customH3:   "Scorciatoie personalizzabili",
    customDesc: "Puoi configurare i tasti per:",
    customLi1:  "Azioni tipo 1 e 2",
    customLi2:  "Macro (sequenze di tasti)",
    customLi3:  "Macro periodica",
    displayH2:    "Opzioni di visualizzazione",
    panelPosH3:   "Posizione del pannello",
    panelPosDesc: "Il pannello di Reborn è trascinabile:",
    panelLi1: "Clicca sull'intestazione del pannello",
    panelLi2: "Tieni premuto e trascina",
    panelLi3: "Rilascia nel punto desiderato",
    panelLi4: "La posizione viene salvata automaticamente",
    opacityH3:   "Opacità del pannello",
    opacityDesc: "Regola la trasparenza per non interferire con la navigazione mentre controlli le tue statistiche.",
    logH3:   "Registro attività",
    logDesc: "Il registro mostra in tempo reale tutte le azioni eseguite:",
    logLi1:  "Attivazione/disattivazione dei sistemi",
    logLi2:  "Uso delle pozioni",
    logLi3:  "Esecuzione di macro e sequenze",
    logLi4:  "Chiamate alla macro periodica",
    logLi5:  "Eventuali errori",
    saveH2:    "Salvataggio dei parametri",
    saveDesc:  "Tutte le tue impostazioni vengono salvate automaticamente in locale:",
    saveLi1:   "Tema selezionato",
    saveLi2:   "Lingua dell'interfaccia",
    saveLi3:   "Soglie di attivazione",
    saveLi4:   "Tasti assegnati",
    saveLi5:   "Configurazione delle macro",
    saveLi6:   "Posizione del pannello",
    savePersist: "Persistono tra le sessioni, anche dopo aver chiuso il browser.",
  },

  // ── docs/premium.html ─────────────────────────────────────────────
  docPremium: {
    h1:       "💎 Guida Premium",
    subtitle: "Padroneggia tutte le funzioni avanzate di Reborn Assistant",
    rotH2:    "🛡️ Rotazione sequenze automatica",
    rotDesc:  "Il sistema di rotazione mantiene automaticamente tutte le tue sequenze attive premendo una sequenza predefinita di tasti a intervalli regolari.",
    rotSeqH3:   "Sequenza di tasti",
    rotSeqText: "La rotazione segue sempre questo ordine fisso:",
    rotConfigH3:   "Configurazione",
    rotIntName:    "Intervallo tra i cicli",
    rotIntDesc:    "Tempo di attesa prima di riavviare l'intera sequenza. Predefinito: 5 minuti. Regola in base alla durata delle tue sequenze più brevi.",
    rotDelName:    "Ritardo tra i tasti",
    rotDelDesc:    "Tempo di attesa tra ogni tasto della sequenza. Predefinito: 1 secondo. Regola in base alla velocità del servizio (animazioni, cooldown...).",
    rotExTitle:    "💡 Esempio d'uso",
    rotExScenario: "<strong>Scenario:</strong> Le tue sequenze durano 5 minuti e hai 8 sequenze sui tasti 1-8.",
    rotExConfig:   "<strong>Configurazione:</strong>",
    rotExLi1:      "Intervallo: 5 minuti",
    rotExLi2:      "Ritardo: 1 secondo",
    rotExLi3:      "Il bot premerà F2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1 ogni 5 minuti",
    rotExLi4:      "13 tasti in totale con 1 secondo tra ognuno = ~13 secondi per ciclo",
    macH2:    "⚙️ Macro Personalizzabili",
    macDesc:  "Crea fino a 3 macro indipendenti con le tue sequenze di tasti personalizzate. Perfetto per automatizzare compiti ripetitivi, combo ricorrenti o rotazioni di abilità.",
    macHowH3:   "Funzionamento",
    macHowText: "Ogni macro esegue una sequenza di tasti a intervalli regolari, indipendentemente dagli altri sistemi.",
    macConfigH3:  "Configurazione",
    macSeqName:   "Sequenza di tasti",
    macSeqDesc:   "Definisci i tasti da premere in ordine, separati da virgole. Esempio: 1,2,3,4 o q,w,e,r,f",
    macRepName:   "Intervallo di ripetizione",
    macRepDesc:   "Tempo di attesa prima di ripetere la sequenza. Configura in base alle tue esigenze (secondi o minuti).",
    macDelName:   "Ritardo tra i tasti",
    macDelDesc:   "Tempo di attesa tra ogni tasto della sequenza (generalmente 0,5-2 secondi).",
    macExTitle:   "💡 Esempi d'uso",
    mac1Title:    "<strong>Macro 1 – Automazione ripetitiva:</strong>",
    mac1Li1:      "Sequenza: 1,2,3,space",
    mac1Li2:      "Intervallo: 10 secondi",
    mac1Li3:      "Uso: Rotazione degli attacchi base in loop",
    mac2Title:    "<strong>Macro 2 – Combo di abilità:</strong>",
    mac2Li1:      "Sequenza: q,w,e,r",
    mac2Li2:      "Intervallo: 30 secondi",
    mac2Li3:      "Uso: Rotazione DPS ottimale",
    mac3Title:    "<strong>Macro 3 – Supporto automatico:</strong>",
    mac3Li1:      "Sequenza: f,g,h",
    mac3Li2:      "Intervallo: 15 secondi",
    mac3Li3:      "Uso: Sequenze di gruppo o azioni periodiche",
    perH2:    "🐉 Macro periodica",
    perDesc:  "Questo sistema esegue automaticamente un'azione periodica ogni 15 secondi. Ideale per compiti ripetitivi che devono essere attivati regolarmente.",
    perHowH3:   "Funzionamento",
    perHowText: "Il sistema esegue automaticamente questa sequenza ogni 15 secondi:",
    perLi1:     "Chiama la macro periodica (tasto configurabile, predefinito §)",
    perLi2:     "Attende 500ms",
    perLi3:     "Memorizza automaticamente la macro periodica",
    perConfigH3:  "Configurazione",
    perCallName:  "Tasto di chiamata",
    perCallDesc:  "Il tasto che attiva la tua macro periodica. Predefinito: §. Modificalo in base alla tua configurazione.",
    perIntName:   "Intervallo (fisso)",
    perIntDesc:   "Il sistema utilizza sempre un intervallo fisso di 15 secondi. Non configurabile.",
    perExTitle:   "💡 Caso d'uso",
    perExText:    "In alcuni servizi, la macro periodica deve essere chiamata regolarmente per raccogliere oggetti, fornire sequenze temporanee o guadagnare esperienza. Questo sistema automatizza completamente questo processo.",
    perImpH3:     "⚠️ Importante",
    perImpLi1:    "Verifica che il tasto configurato corrisponda al tuo tasto di invocazione",
    perImpLi2:    "La macro periodica viene memorizzata automaticamente dopo ogni chiamata",
    perImpLi3:    "Funziona in parallelo con gli altri sistemi (sequenze, macro, azioni)",
    optH2:   "Consigli di ottimizzazione",
    combH3:  "🎯 Combinazione di sistemi",
    combDesc:"Tutte le funzioni Premium funzionano simultaneamente. Puoi:",
    combLi1: "Attivare sequenze automatiche + 3 macro + macro periodica contemporaneamente",
    combLi2: "Le azioni attivatori 1 &amp; 2 funzionano sempre in parallelo",
    combLi3: "Ogni sistema ha il suo timer indipendente",
    perfH3:  "⚡ Prestazioni",
    perfLi1: "Più sistemi attivi, più risorse consuma l'estensione",
    perfLi2: "Regola gli intervalli per evitare azioni troppo frequenti",
    perfLi3: "Monitora il registro attività per verificare il corretto funzionamento",
    secH3:   "🔑 Sicurezza",
    secLi1:  "La tua licenza Premium viene verificata in tempo reale",
    secLi2:  "Se la connessione viene persa, le funzioni Premium vengono disattivate",
    secLi3:  "Accedi nuovamente per riattivare tutte le funzioni",
  },

  // ── docs/troubleshooting.html ─────────────────────────────────────
  docTroubleshooting: {
    h1:       "🔧 Risoluzione dei problemi",
    subtitle: "Soluzioni ai problemi comuni e domande frequenti",
    installH2: "Problemi di installazione",
    faq1Q: "❌ L'estensione non appare nella barra degli strumenti",
    faq1A: "<strong>Soluzioni:</strong><br>1. Verifica che l'estensione sia installata dal <strong>Chrome Web Store</strong><br>2. Fissa l'estensione: clicca sull'icona puzzle 🧩 nella barra degli strumenti e fissa Reborn Assistant<br>3. Riavvia il browser<br>4. Se il problema persiste, disinstalla e reinstalla l'estensione dal Chrome Web Store",
    connH2: "Problemi di connessione",
    faq2Q: "❌ \"Connessione fallita\" o \"Licenza non valida\"",
    faq2A: "<strong>Possibili cause:</strong><br>• Connessione internet instabile<br>• Server di Google Cloud temporaneamente non disponibili<br>• Licenza scaduta o revocata<br><br><strong>Soluzioni:</strong><br>1. Verifica la tua connessione internet<br>2. Esci e accedi nuovamente con Google<br>3. Verifica lo stato della tua licenza nel portale Stripe<br>4. Contatta il supporto se il problema persiste",
    faq3Q: "❌ Il pannello mostra \"FREE\" anche con Premium",
    faq3A: "1. Esci dal tuo account Google<br>2. Chiudi completamente il browser<br>3. Riapri ed esegui l'accesso<br>4. Se il problema persiste, verifica di essere connesso con l'account Google corretto (quello usato per l'acquisto)",
    funcH2: "Problemi di funzionamento",
    faq4Q:     "❌ Le azioni tipo 1/2 non si attivano",
    faq4Alert: "<strong>⚠️ IMPORTANTE</strong><br>Le azioni tipo 1 e 2 sono funzioni <strong>ESCLUSIVAMENTE PREMIUM</strong>. Solo l'azione automatica tipo 1 (HP) è disponibile nella versione gratuita.",
    faq4Prem:  "<strong>Se hai Premium:</strong><br>1. Il bot è avviato? <code>CTRL+A</code><br>2. Gli interruttori attivatori sono abilitati? (indicatore verde «ON»)<br>3. I tasti configurati sono corretti?",
    faq5Q:     "❌ Le sequenze / macro / macro periodica / scorciatoie non funzionano",
    faq5Alert: "<strong>⚠️ IMPORTANTE</strong><br>Le scorciatoie da tastiera, le sequenze, le macro e la macro periodica sono funzioni <strong>ESCLUSIVAMENTE PREMIUM</strong>. Nella versione gratuita è disponibile solo l'azione automatica tipo 1 (HP).",
    faq5Prem:  "<strong>Se hai Premium:</strong><br>1. Verifica che la tua licenza Premium sia attiva (icona 💎 nel pannello)<br>2. Gli interruttori corrispondenti sono abilitati?<br>3. Verifica gli intervalli e i ritardi configurati",
    faq6Q: "❌ Il bot si ferma da solo",
    faq6A: "<strong>Possibili cause:</strong><br>• Perdita di connessione a Google Cloud<br>• Rilevamento di DevTools<br>• L'URL della pagina è cambiato<br><br><strong>Soluzioni:</strong><br>1. Riavvia il bot con <code>CTRL+A</code> (Premium) o dal pannello<br>2. Ricarica la pagina interessata<br>3. Verifica la tua connessione internet<br>4. Non aprire DevTools se sei in Premium",
    optH2: "Ottimizzazione & Prestazioni",
    faq7Q: "💡 Il bot consuma troppe risorse",
    faq7A: "<strong>Raccomandazioni:</strong><br>• Aumenta gli intervalli di macro e sequenze (meno azioni = meno CPU)<br>• Disattiva i sistemi che non ti servono<br>• Chiudi le schede non necessarie<br>• Usa un browser ottimizzato (Brave, Edge sono più leggeri di Chrome)",
    faq8Q: "💡 Come ottimizzare la configurazione?",
    faq8A: "<strong>Configurazione consigliata:</strong><br>• <strong>Intervallo sequenze:</strong> 5-25 minuti (in base alla durata delle tue sequenze)<br>• <strong>Ritardo tra i tasti:</strong> 1-2 secondi (evita errori)<br>• <strong>Macro:</strong> Intervalli di 10-30s in base all'uso",
    genH2:  "Domande Frequenti",
    faq9Q:  "❓ Posso usare Reborn su più browser?",
    faq9A:  "Sì, ma devi installare l'estensione su ogni browser. La tua licenza Premium funziona su tutti i tuoi dispositivi finché accedi con lo stesso account Google (max. 1 connessione simultanea).",
    faq10Q: "❓ I miei dati vengono salvati?",
    faq10A: "Tutte le tue impostazioni (tasti, macro, tema, lingua) vengono salvate <strong>localmente</strong> nel browser. Persistono tra le sessioni. Tuttavia, se disinstalli l'estensione, perderai questi dati.",
    faq11Q: "❓ Reborn può causare un ban?",
    faq11A: "L'uso di strumenti di automazione può violare i Termini di Servizio di alcuni servizi. <strong>Sei l'unico responsabile</strong> di come usi Reborn. Consulta i termini di utilizzo del servizio prima di usare questo strumento.",
    faq12Q: "❓ Come annullare l'abbonamento Premium?",
    faq12A: "Puoi annullare in qualsiasi momento dal tuo portale di gestione Stripe (link ricevuto via e-mail dopo il pagamento). L'annullamento ha effetto alla fine del periodo corrente. Nessun costo di annullamento.",
    faq13Q: "❓ Cosa succede al piano A Vita se il servizio chiude?",
    faq13A: "Il piano A Vita garantisce l'accesso finché il servizio è attivo. Una volta installata, l'estensione funziona localmente; solo la verifica della licenza richiede una connessione internet.",
    supportH2:    "Hai bisogno di ulteriore aiuto?",
    supportTitle: "📧 Supporto",
    supportText:  "Se il tuo problema persiste, contatta il supporto direttamente via e-mail. Includi nel tuo messaggio:<br><br>• Una descrizione dettagliata del problema<br>• I passaggi già tentati<br>• Screenshot se pertinenti<br>• Il tuo browser e sistema operativo",
  },

  // ── docs/privacy.html ─────────────────────────────────────────────
  docPrivacy: {
    h1:       "⚖️ Legale & Privacy",
    subtitle: "Avviso legale, note legali, termini di licenza e informativa sulla privacy",
    navLegal:  "⚖️ Informazioni Legali",
    navLicence:"© Licenza",
    navPrivacy:"🔒 Privacy",
    disclaimerH2:  "⚠️ Avviso Legale",
    disclaimerBox: "<strong>⚠️ Avviso importante:</strong> Reborn Assistant è uno strumento di automazione. Il suo utilizzo può violare i Termini di Servizio di certi servizi online. L'uso di questo strumento è completamente a tuo rischio e pericolo.",
    respH3:    "Responsabilità dell'utente",
    respIntro: "Utilizzando Reborn Assistant, riconosci e accetti che:",
    respLi1:   "Sei l'unico responsabile dell'uso che fai di questo software",
    respLi2:   "Verificherai i termini di utilizzo di ogni servizio prima di usare questo strumento",
    respLi3:   "L'autore non può essere ritenuto responsabile di alcun ban, restrizione dell'account o azione legale derivante dall'uso di Reborn",
    respLi4:   "Usi questo software consapevolmente e a tuo rischio",
    respLi5:   "Questo strumento non deve essere usato in modo da pregiudicare l'esperienza degli altri utenti",
    warrantH3:   "Nessuna garanzia",
    warrantText: "Il software viene fornito «COSÌ COM'È» senza garanzia di alcun tipo. L'autore non garantisce che il software funzionerà in modo ininterrotto o privo di errori, né che sia compatibile con tutti i servizi o browser.",
    legalH2:    "📄 Note legali",
    copyrightH3:   "Diritti d'autore & Proprietà intellettuale",
    copyrightText: "<strong>© 2026 Reborn Assistant – Tutti i diritti riservati</strong><br>Sviluppato da <strong>Seymoon</strong>",
    copyrightText2:"Questo software e tutti i materiali associati sono proprietà intellettuale esclusiva del loro autore. Qualsiasi riproduzione, modifica, distribuzione o ingegneria inversa senza autorizzazione scritta è severamente vietata.",
    liabilityH3:   "Limitazione di responsabilità",
    liabilityIntro:"In nessun caso l'autore sarà responsabile per qualsiasi reclamo o danno derivante dall'uso o dall'impossibilità di usare questo software, incluso ma non limitato a:",
    liabilityLi1:  "Perdita di dati o account utente",
    liabilityLi2:  "Ban o restrizioni imposti dagli editori dei servizi",
    liabilityLi3:  "Danni ai sistemi informatici",
    liabilityLi4:  "Qualsiasi conseguenza legale derivante da un uso non conforme ai termini di servizio",
    dataH3:    "Dati personali",
    dataText:  "Reborn Assistant utilizza Firebase (Google Cloud) per la gestione degli account e delle licenze. I dati raccolti si limitano al tuo indirizzo e-mail e identificatore dell'account, esclusivamente a fini di autenticazione e verifica della licenza.",
    dataText2: "<strong>Nessun dato di attività viene raccolto o trasmesso.</strong> Le tue impostazioni rimangono memorizzate localmente sul tuo dispositivo.",
    jurisH3:   "Giurisdizione",
    jurisText: "Questo accordo è regolato dalla legge applicabile nella giurisdizione di residenza del titolare dei diritti d'autore. Installando e utilizzando questo software, riconosci di aver letto, compreso e accettato la totalità di queste condizioni.",
    licenceH2:     "© Termini di licenza",
    licenceH3:     "Licenza d'uso",
    licenceIntro:  "L'acquisto di un piano di Reborn Assistant ti concede una licenza personale, non esclusiva e non trasferibile per utilizzare il software.",
    licenceAllows: "<strong>Questa licenza ti autorizza a:</strong>",
    licenceLi1:    "Usare il software per scopi personali sui tuoi dispositivi",
    licenceLi2:    "Beneficiare degli aggiornamenti inclusi nel tuo piano",
    licenceForbids:"<strong>Questa licenza non ti autorizza a:</strong>",
    licenceLi3:    "Ridistribuire, rivendere o condividere il tuo accesso",
    licenceLi4:    "Modificare, decompilare o eseguire ingegneria inversa del software",
    licenceLi5:    "Usare il software per scopi commerciali senza previo accordo scritto",
    licenceLi6:    "Trasferire la tua licenza a terzi",
    terminationH3:   "Rescissione",
    terminationText: "La licenza può essere rescissa immediatamente in caso di violazione di questi termini. Per i piani in abbonamento, puoi annullare in qualsiasi momento dal tuo portale Stripe.",
    refundBox: "<strong>✅ Politica di rimborso:</strong> Se non sei soddisfatto nei 7 giorni successivi all'acquisto, contatta il nostro supporto per un rimborso completo. Trascorso questo periodo, non sarà concesso alcun rimborso salvo casi eccezionali.",
    privacyH1:      "🔒 Informativa sulla Privacy",
    privacySubtitle:"Come proteggiamo i tuoi dati personali",
    privacyBox:     "<strong>✅ La tua privacy è la nostra priorità</strong><br>Versione gratuita: nessun dato personale viene raccolto. Versione Premium: vengono trattati solo i dati strettamente necessari per verificare la tua licenza.",
    collectH2:        "Raccolta dei dati",
    collectFreeH3:    "Versione Gratuita",
    collectFreeText:  "Nessun dato personale viene raccolto o trasmesso. Tutte le tue preferenze sono memorizzate esclusivamente sul tuo dispositivo.",
    collectPremH3:    "Versione Premium",
    collectPremIntro: "Per verificare la tua licenza e proteggere il tuo account, vengono trattati i seguenti dati:",
    collectPremLi1:   "Il tuo indirizzo e-mail Google (tramite autenticazione Google)",
    collectPremLi2:   "Un identificatore univoco del dispositivo (generato localmente)",
    collectPremLi3:   "Il tuo stato di abbonamento e i timestamp di sessione",
    collectPremLi4:   "Massimo 2 dispositivi registrati per account",
    collectPremBasis: "<strong>Base giuridica:</strong> esecuzione del contratto (art. 6.1.b GDPR).",
    collectNotH3:     "Dati mai raccolti",
    collectNotLi1:    "❌ Nessun dato di gioco o attività",
    collectNotLi2:    "❌ Nessuna cronologia di navigazione",
    collectNotLi3:    "❌ Nessun cookie pubblicitario o di tracciamento",
    localH2:    "Dati memorizzati localmente",
    localIntro: "Le seguenti informazioni vengono salvate <strong>esclusivamente sul tuo dispositivo</strong>:",
    localLi1:   "<strong>Preferenze di lingua</strong>: La tua scelta di lingua dell'interfaccia",
    localLi2:   "<strong>Selezione del tema visivo</strong>: Il tema scelto tra i 6 disponibili",
    localLi3:   "<strong>Scorciatoie da tastiera configurate</strong>: I tasti assegnati alle tue azioni",
    localLi4:   "<strong>Intervalli timer personalizzati</strong>: I timer configurati per le tue macro",
    localLi5:   "<strong>Posizione dell'interfaccia</strong>: La posizione del pannello di Reborn sullo schermo",
    localLi6:   "<strong>Cache licenza (Premium)</strong>: identificatore del dispositivo e stato dell'abbonamento, per evitare la verifica ad ogni avvio",
    thirdH2:       "Servizi di terze parti",
    thirdH3:       "Servizi utilizzati (versione Premium)",
    thirdDesc:     "Per l'autenticazione e i pagamenti, Reborn Assistant utilizza:",
    thirdLi1:      "🔐 <strong>Google</strong> — Autenticazione e archiviazione sicura dei dati della licenza",
    thirdLi2:      "💳 <strong>Stripe</strong> — Elaborazione dei pagamenti Premium (i tuoi dati bancari non passano mai attraverso i nostri server)",
    thirdTransfer: "Questi fornitori sono conformi al GDPR e dispongono delle garanzie adeguate per i trasferimenti internazionali di dati.",
    thirdNoH3:     "Nessun tracciamento, nessuna pubblicità",
    thirdLi3:      "❌ Nessun servizio di analisi o statistiche",
    thirdLi4:      "❌ Nessuna pubblicità o marketing mirato",
    thirdLi5:      "❌ Nessun cookie di terze parti o tracciamento comportamentale",
    authH2:    "Autenticazione e gestione dei dispositivi",
    authH3:    "Accesso con Google (versione Premium)",
    authText:  "Il tuo account Google viene utilizzato esclusivamente per autenticare la tua identità e verificare la tua licenza. Il tuo dispositivo viene registrato nel nostro sistema sicuro (massimo 2 dispositivi per account).",
    authText2: "Riceverai una notifica se il tuo account viene utilizzato su un dispositivo non riconosciuto. Puoi gestire i tuoi dispositivi registrati direttamente dall'estensione.",
    payH2:    "Pagamenti Sicuri",
    payText:  "I pagamenti Premium sono elaborati da <strong>Stripe</strong>. Le tue informazioni bancarie <strong>non passano mai</strong> attraverso i nostri server. Non memorizziamo <strong>alcun dato</strong> di carta di credito.",
    retentionH2:   "Periodo di conservazione",
    retentionText: "I tuoi dati vengono conservati solo per il tempo necessario:",
    retentionLi1:  "<strong>Account attivo:</strong> dati conservati per tutta la durata dell'abbonamento",
    retentionLi2:  "<strong>Dopo la cancellazione:</strong> eliminazione entro 30 giorni",
    retentionLi3:  "<strong>Dati locali:</strong> eliminati immediatamente alla disinstallazione dell'estensione",
    rightsH2:      "I tuoi diritti (GDPR)",
    rightsText:    "In conformità con il GDPR, hai i seguenti diritti sui tuoi dati:",
    rightsLi1:     "✅ <strong>Accesso</strong> — Ottenere una copia dei tuoi dati personali",
    rightsLi2:     "✅ <strong>Rettifica</strong> — Correggere dati inesatti",
    rightsLi3:     "✅ <strong>Cancellazione</strong> — Richiedere l'eliminazione del tuo account e dei dati",
    rightsLi4:     "✅ <strong>Portabilità</strong> — Ricevere i tuoi dati in un formato leggibile",
    rightsLi5:     "✅ <strong>Reclamo</strong> — Presentare un reclamo all'autorità di protezione dei dati del tuo paese",
    rightsExercise:"Per esercitare questi diritti, contattaci: seymoon.cell@gmail.com o su Discord (Seymoon)",
    deleteH2:    "Eliminazione dei tuoi dati",
    deleteText1: "<strong>1. Disinstallare l'estensione</strong><br>Disinstallando Reborn Assistant, tutti i dati locali vengono eliminati automaticamente.",
    deleteText2: "<strong>2. Ripristino manuale</strong><br>Puoi ripristinare le impostazioni dall'interfaccia di Reborn in qualsiasi momento.",
    deleteText3: "<strong>3. Eliminazione account (Premium)</strong><br>Per eliminare il tuo account Premium e tutti i dati associati, contattaci via e-mail.",
    contactH2:   "Contatto",
    contactText: "Per qualsiasi domanda sulle informazioni legali o sull'informativa sulla privacy:",
    changelogH2: "📋 Registro delle modifiche",
    v130H3:          "Versione 1.3.0 (Marzo 2026) · Attuale",
    v130newLabel:    "✨ Novità",
    v130improvLabel: "🔧 Miglioramenti",
    v130fixLabel:    "🐛 Correzioni",
    v130Li1:  "⏱ Mini-timer flottante trascinabile — piccola finestra flottante che mostra i timer buff e quelli superiori a 1 minuto, si riapre automaticamente al prossimo avvio e segue lo skin attivo.",
    v130Li2:  "⚡ Macro prioritarie — le macro vengono eseguite prima di guarigioni/PV/mana, con un blocco cura di 0,5s prima e dopo ogni esecuzione per evitare conflitti.",
    v130Li3:  "🧠 Gestione intelligente del buff — il buff viene eseguito per primo, le macro silenziose vengono messe in coda e riavviate automaticamente dopo la fine (ritardo ridotto a 2s).",
    v130Li4:  "💾 Memoria delle posizioni — le finestre flottanti mantengono la loro posizione tra le sessioni.",
    v130Li5:  "🇸🇦 Supporto arabo — 15ª lingua disponibile nell'estensione.",
    v130Li6:  "💳 Pagamento Stripe in popup — si apre in una finestra dedicata con chiusura automatica, senza uscire dall'estensione.",
    v130Li7:  "🐾 Famiglio: corretta il bug dove il pet non usciva al primo buff + migliore tracciamento della modalità F1/F2 per la rimessa al stop.",
    v130Li8:  "⏱ Timer: redesign visivo del design premium + opacità 55% a riposo → 95% al passaggio del mouse per una migliore leggibilità.",
    v130Li9:  "💳 Portale di fatturazione: unica finestra attiva in memoria con chiusura automatica.",
    v130Li10:  "Corretti diversi memory leak nel contenuto e nel popup.",
    v130Li16:  "Allineamento UI al limite massimo di 2 dispositivi (coerenza con il backend).",
    v120H3:  "Versione 1.2.0 (Marzo 2026)",
    v120Li1: "✨ I 6 skin sono stati ridisegnati con un sottile effetto di trasparenza.",
    v120Li2: "🔐 Visualizza e gestisci il tuo dispositivo registrato direttamente dall'estensione.",
    v120Li3: "💳 Accedi al tuo abbonamento con un clic dall'estensione.",
    v120Li4: "🔔 Notifica istantanea se il tuo account viene usato su un altro dispositivo.",
    v12H3:   "Versione 1.2 (Febbraio 2026)",
    v12Li1:  "Supporto 15 lingue (aggiunto Turco 🇹🇷)",
    v12Li2:  "Redesign visivo del sito web",
    v12Li3:  "Fusione delle pagine legali in un'unica pagina unificata",
    v12Li4:  "Traduzione completa FR/EN del sito",
    v11H3:   "Versione 1.1.1 (Febbraio 2026)",
    v11Li1:  "Aggiunta macro periodica automatica (15s + auto-memorizzazione)",
    v11Li2:  "Scorciatoie da tastiera CTRL+A / CTRL+O",
    v11Li3:  "Supporto 15 lingue (aggiunto Filipino + Turco)",
    v11Li4:  "Miglioramento della stabilità della licenza Premium",
    v11Li5:  "Correzioni di bug nella rotazione delle sequenze",
    v10H3:   "Versione 1.0 (2025) · Iniziale",
    v10Li1:  "Lancio di Reborn Assistant",
    v10Li2:  "Azioni automatiche tipo 1 e 2",
    v10Li3:  "Rotazione sequenze automatica (F2 → 1-9 → 0 → F1)",
    v10Li4:  "3 macro personalizzabili",
    v10Li5:  "6 temi visivi e 12 lingue",
    v10Li6:  "Sistema di licenza Premium tramite Firebase",
    pageFooter:"© 2026 Reborn Assistant — Sviluppato da Seymoon · Tutti i diritti riservati",
  },
  nav: {
    docsFull:    "📚 Documentazione",
    docsShort:   "📚 Docs",
    manageFull:  "Gestisci abbonamento",
    manageShort: "Gestisci",
  },
};