export default {
  hero: {
    description: "高度なマクロを搭載したブラウザ自動化拡張機能。繰り返し作業、ショートカット、シーケンスを自動化して生産性を最適化しましょう。",
    ctaPrimary: "今すぐ始める",
    ctaSecondary: "詳しく見る",
    trust1: "無料版あり",
    trust2: "コミットメント不要",
    trust3: "100%安全な決済",
    trust4: "自動アップデート",
  },
  features: {
    tag: "スキル＆機能",
    titleBefore: "必要な",
    titleEm: "すべてが揃う",
    subtitle: "Reborn Assistantの卓越した機能を発見してください。",
    card1: { badge: "アクティブ", title: "完全自動化",               description: "完全な自動化のためのキーマクロ、自動シーケンス、設定可能なアクション。" },
    card2: { badge: "パッシブ",   title: "最大セキュリティ",         description: "データはローカルに保存されます。トラッキングなし、テレメトリなし。" },
    card3: { badge: "アクティブ", title: "カスタマイズ可能なマクロ", description: "自動トリガーとキーボードショートカットを備えた3つの設定可能なマクロ。" },
    card4: { badge: "パッシブ",   title: "カスタマイズ可能なUI",     description: "6つのテーマから選び、インターフェースをニーズに合わせてカスタマイズ。" },
    card5: { badge: "パッシブ",   title: "多言語対応",               description: "15言語対応。ローカライズされたインターフェースで世界中をサポート。" },
    card6: { badge: "無料",       title: "無料版",                   description: "基本機能を含む無料トライアル。" },
  },
  security: {
    tag: "セキュリティ",
    titleBefore: "プロフェッショナルレベルの",
    titleEm: "セキュリティ",
    titleAfter: "",
    description: "Reborn Assistantは世界的なストリーミングプラットフォームと同じセキュリティ基準を使用しています。認証情報は<strong style='color:var(--gold);'>JWT暗号化</strong>で保護され、支払いは<strong style='color:var(--gold);'>Stripe</strong>で保証され、データは<strong style='color:var(--gold);'>100%ローカル</strong>に保存されます。トラッキングなし、データ販売なし。",
    card1Title: "JWT暗号化",
    card1Text:  "銀行レベルの安全な認証",
    card2Title: "Stripe決済",
    card2Text:  "AmazonとGoogleが使用するプロセッサ",
    card3Title: "ゼロトラッキング",
    card3Text:  "データがデバイスを離れることはありません",
    card4Text:  "安全なGoogle Cloudインフラ",
  },
  pricing: {
    tag:         "クラスを選択",
    titleBefore: "ランクを",
    titleEm:     "選択する",
    subtitle:    "最適なプランを選択してください。コミットメント不要。",
    voyageur: {
      rank: "ランクI・トラベラー", plan: "無料", period: "永久に",
      feat1: "ヒールマクロ", feat2: "6つのビジュアルテーマ", feat3: "15言語対応", feat4: "フローティングUI",
      btn: "始める", download: "Chromeに追加", guarantee: "🔒 永久無料",
    },
    aventurier: {
      rank: "ランクII・アドベンチャラー", plan: "月額", period: "月",
      feat1: "全プレミアム機能", feat2: "優先サポート", feat3: "無料アップデート",
      btn: "無料で試す", guarantee: "🎁 7日間無料・クレジットカード不要",
      download: "Chromeに追加",
    },
    champion: {
      badge: "⭐ 人気 -17%",
      rank: "ランクIII・チャンピオン", plan: "年額", period: "年・2.50€/月",
      feat1: "全プレミアム機能", feat2: "優先サポート", feat3: "無料アップデート",
      btn: "無料で試す", guarantee: "🎁 7日間無料・クレジットカード不要",
      download: "Chromeに追加",
    },
    legende: {
      badge: "⚡ 限定オファー",
      rank: "ランクIV・レジェンド", plan: "生涯", period: "一回払い・以降不要",
      feat1: "生涯アクセス", feat2: "全ての将来のアップデート", feat3: "専用プレミアムサポート", feat4: "最高のコストパフォーマンス",
      btn: "購入", guarantee: "🔒 一回払い・生涯アクセス保証",
      download: "Chromeに追加",
    },
  },
  stats: {
    label1: "対応言語数", label2: "ビジュアルテーマ", label3: "ローカルデータ", label4: "アクティブ拡張機能",
  },
  trust: {
    badge1: "SSL安全決済", badge2: "即時アクセス", badge3: "100%プライベートデータ", badge4: "迅速サポート",
  },
  store: {
    status: "公式拡張機能",
    title:  "Chrome ウェブストアで入手可能",
    install: "インストール",
    available: "無料で入手可能・Googleが認定した公式拡張機能",
  },
  faq: {
    titleBefore: "よくある",
    titleEm:     "質問",
    subtitle:    "始める前に知っておくべきこと。",
    q1: "無料トライアルにクレジットカードは必要ですか？",
    a1: "いいえ、クレジットカードは不要です。最初の7日間はコミットメント不要で完全無料です。すぐに始めるためにアカウントを作成するだけです。",
    q2: "いつでもプランを変更できますか？",
    a2: "はい、アカウントからいつでも上位または下位のプランに変更できます。変更手数料はありません。",
    q3: "生涯プランには本当に全ての将来のアップデートが含まれますか？",
    a3: "はい。生涯プランは追加費用なしで全ての将来のアップデートと新機能へのアクセスを保証します。",
    q4: "データは安全ですか？",
    a4: "全てのデータはデバイスにローカルに保存されます。個人データの収集はなく、トラッキングやテレメトリも使用しません。",
    q5: "サポートへの連絡方法は？",
    a5: "seymoon.cell@gmail.comまたはDiscord（Seymoon）でお問い合わせください。プレミアム会員は優先対応を受けられます。",
    q6: "Reborn Assistantはボットですか？",
    a6: "厳密に言えば、Reborn Assistantは従来のボットではありません。自分で定義したキーシーケンスを自動化する、設定可能なマクロの拡張機能です。人工知能なし、ゲームサーバーとの対話なし、メモリの読み取りなし。拡張機能はゲームデータを読み取ったり変更したりしません — 手動で押すキーをシミュレートするだけです。利用するサービスの利用規約を遵守する責任はあなたにあります。",
  },
  footer: {
    privacy:   "プライバシー",
    terms:     "利用規約",
    copyright: "© 2026 Reborn Assistant. 全著作権所有。<br>Seymoon開発",
  },

  docsNav: {
    backToDocs:      "← ドキュメントに戻る",
    mainSite:        "⌂ メインサイト",
    backToMainSite:  "← メインサイトに戻る",
    footer:          "© 2026 Reborn Assistant — Seymoon開発・全著作権所有",
  },

  docsHome: {
    version:              "バージョン1.3・完全ドキュメント",
    userGuide:            "ユーザーガイド",
    support:              "サポート",
    legal:                "法的情報",
    quickstartTitle:      "クイックスタート",
    quickstartDesc:       "Reborn Assistantのインストール、初期設定、最初のステップ。",
    featuresTitle:        "機能",
    featuresDesc:         "比較表付きの無料機能とプレミアム機能の完全説明。",
    premiumTitle:         "プレミアムガイド",
    premiumDesc:          "自動シーケンス、カスタマイズ可能なマクロ、定期マクロ。",
    interfaceTitle:       "インターフェース＆カスタマイズ",
    interfaceDesc:        "ビジュアルテーマ、言語、カスタマイズオプション。",
    troubleshootingTitle: "トラブルシューティング",
    troubleshootingDesc:  "一般的な問題の解決策、よくある質問、パフォーマンス最適化。",
    legalTitle:           "法的情報＆プライバシー",
    legalDesc:            "法的免責事項、法的記載、ライセンス条件、プライバシーポリシー、変更履歴。",
    footer:               "© 2026 Reborn Assistant — Seymoon開発・全著作権所有",
  },

  docFeatures: {
    h1:        "⚡ 機能",
    subtitle:  "Reborn Assistantが提供する全機能を発見してください",
    h2Free:    "無料機能",
    freeBadge: "無料",
    c1Title: "タイプ1自動アクション",
    c1Desc:  "設定可能なタイマーに基づいてタイプ1アクション（HP）を自動的に起動します。",
    c1li1:   "設定可能なアクションタイマー",
    c1li2:   "バックグラウンドで動作",
    c2Title: "ビジュアルテーマ",
    c2Desc:  "6つの異なるテーマでインターフェースの外観をカスタマイズ。",
    c2li1:   "MMO Gold（デフォルト）",
    c2li2:   "ダークモード＆ホワイトモード",
    c3Title: "多言語対応",
    c3Desc:  "国際的な体験のために15言語で利用可能なインターフェース。",
    c3li3:   "即時切り替え",
    h2Premium: "プレミアム機能 💎",
    p1Title: "自動トリガー1マクロ",
    p1Desc:  "設定可能なタイマーに基づくタイプ1アクション（HP）の自動起動。",
    p1li1:   "設定可能なトリガー1タイマー",
    p1li2:   "設定可能なショートカットキー",
    p1li3:   "バックグラウンドで動作",
    p2Title: "自動トリガー2マクロ",
    p2Desc:  "設定可能なタイマーに基づくタイプ2アクションの自動使用。",
    p2li1:   "設定可能なトリガー2タイマー",
    p2li2:   "設定可能なショートカットキー",
    p2li3:   "バックグラウンドで動作",
    p3Title: "キーボードショートカット",
    p3Desc:  "カスタマイズ可能なグローバルショートカットでReborn Assistantを素早く操作。",
    p3li1:   "CTRL+A: ボットを開始",
    p3li2:   "CTRL+O: ボットを停止",
    p4Title: "シーケンスローテーション",
    p4Desc:  "事前定義されたシーケンスによる自動シーケンスメンテナンスシステム。",
    p4li1:   "シーケンス: F2 → 1-9 → 0 → F1",
    p4li2:   "設定可能な間隔（分）",
    p4li3:   "キー間の調整可能な遅延",
    p5Title: "カスタマイズ可能なマクロ",
    p5Desc:  "独自のキーシーケンスで最大3つのマクロを作成。",
    p5li1:   "3つの独立したマクロ",
    p5li2:   "カスタムシーケンス",
    p5li3:   "調整可能な繰り返し間隔",
    p6Title: "定期マクロ",
    p6Desc:  "15秒ごとに定期マクロを自動呼び出し＆保存。",
    p6li1:   "定期マクロの自動呼び出し",
    p6li2:   "呼び出し後の自動保存",
    p6li3:   "固定15秒間隔",
    tableH2:      "比較表",
    tableFeature: "機能",
    tableFree:    "無料",
    row1:  "タイプ1自動アクション（HP）",
    row2:  "ビジュアルテーマ（6）",
    row3:  "多言語対応（15）",
    row4:  "自動トリガー1マクロ",
    row5:  "自動トリガー2マクロ",
    row6:  "キーボードショートカット（CTRL+A / CTRL+O）",
    row7:  "自動シーケンスローテーション",
    row8:  "カスタマイズ可能なマクロ（3x）",
    row9:  "自動定期マクロ",
    learnMore: "→ プレミアム機能の詳細",
  },

  docQuickstart: {
    h1:       "🚀 クイックスタート",
    subtitle: "数分でReborn Assistantをインストール＆設定",
    reqH2:    "必要条件",
    req1:     "<strong>対応ブラウザ:</strong> Google Chrome、Microsoft Edge、BraveまたはChromiumベースのブラウザ",
    req2:     "<strong>Googleアカウント:</strong> プレミアム認証にのみ必要（無料版はオプション）",
    req3:     "<strong>対応サイト:</strong> 標準的なウェブサイトに対応",
    installH2:  "インストール",
    step1Title: "Chromeウェブストアを訪問",
    step1p:     "<a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chromeウェブストア</a>のReborn Assistantページにアクセスして、<strong>「Chromeに追加」</strong>をクリックしてください。",
    step1tip:   "💡 Google Chrome、Microsoft Edge、BraveおよびChromiumベースのブラウザに対応。",
    step2Title: "インストールを確認",
    step2p:     "確認ウィンドウで<strong>「拡張機能を追加」</strong>をクリックしてください。拡張機能は自動的にインストールされます。",
    step3Title: "拡張機能を固定",
    step3p:     "ブラウザのツールバーのパズルアイコン🧩をクリックし、Reborn Assistantを固定してクイックアクセスできるようにしてください。",
    step4Title: "ログイン（プレミアムはオプション）",
    step4p:     "• ツールバーのRebornアイコンをクリック<br>• プレミアムの場合: Googleアカウントでログイン<br>• 無料の場合: ログインせずに直接使用",
    alertTitle: "✅ インストール完了！",
    alertText:  "拡張機能がアクティブな場合、RebornアイコンはGreenに変わります。機能を設定できます。",
    configH2:   "初期設定",
    freeH3:     "無料版",
    freeTitle:  "<strong>ログインなしで使用可能な機能:</strong>",
    freeText:   "• タイプ1自動アクション（HPのみ）<br>• 6つのビジュアルテーマ<br>• 15言語サポート",
    freeStepTitle: "タイプ1自動アクションの設定",
    freeStepText:  "1. Rebornパネルを開く（アイコンをクリック）<br>2. HPアクションタイマーを調整（デフォルト: 2秒）<br>3. アクションは自動的に起動<br>4. ログイン不要",
    premiumH3:       "プレミアム版 💎",
    premiumFeatTitle:"<strong>追加機能（Googleログイン必要）:</strong>",
    premiumFeatText: "• 自動トリガー1マクロ（設定可能タイマー+ショートカット）<br>• 自動トリガー2マクロ（設定可能タイマー+ショートカット）<br>• キーボードショートカット（CTRL+A / CTRL+O）<br>• 自動シーケンスローテーション（F2 → 1-9 → 0 → F1）<br>• キーシーケンス付き3つのカスタマイズ可能なマクロ<br>• 自動定期マクロシステム（15秒ごとに呼び出し+保存）",
    premConfigTitle: "プレミアム設定",
    premConfigSeq:   "<strong>自動シーケンス:</strong><br>• パネルで「シーケンスローテーション」を有効化<br>• サイクル間の間隔を設定（デフォルト: 5分）<br>• 各キー間の遅延を調整（デフォルト: 1秒）",
    premConfigMacro: "<strong>マクロ:</strong><br>• マクロ1、2または3を有効化<br>• キーシーケンスを定義（例: <code>1,2,3,4</code>）<br>• 繰り返し間隔を設定",
    premConfigPer:   "<strong>定期マクロ:</strong><br>• 「定期マクロ」スイッチを有効化<br>• システムが15秒ごとに定期マクロを自動呼び出し<br>• 呼び出し後に自動保存",
    warnTitle: "⚠️ 重要な注意",
    warnText:  "プレミアム機能（トリガーマクロ1と2、自動シーケンス、自動定期マクロ、3つの設定可能なマクロ）には有効なプレミアムライセンスとGoogleログインが必要です。ライセンスなしでは基本マクロのみ使用可能です。",
    shortcutsH2:   "キーボードショートカット",
    shortcutsText: "<code>CTRL + A</code>: ボットを開始<br><code>CTRL + O</code>: ボットを停止",
    nextH2: "次のステップ",
    link1:  "全機能を発見する",
    link2:  "完全なプレミアムガイド",
    link3:  "一般的な問題の解決策",
  },

  docInterface: {
    h1:       "🎨 インターフェース＆カスタマイズ",
    subtitle: "好みに合わせてReborn Assistantをカスタマイズ",
    themesH2:    "ビジュアルテーマ",
    themesDesc:  "Reborn Assistantはインターフェースの外観をカスタマイズするための6つのテーマを提供:",
    changeThemeH3:   "テーマの変更",
    changeThemeText: "1. Rebornパネルを開く<br>2. 「⚙️ 設定」タブをクリック<br>3. ドロップダウンメニューでテーマを選択<br>4. 変更は即時に適用",
    langsH2:    "利用可能な言語",
    langsDesc:  "15言語で利用可能なインターフェース:",
    changeLangH3:   "言語の変更",
    changeLangText: "1. Rebornパネルを開く<br>2. 「⚙️ 設定」をクリック<br>3. ドロップダウンメニューで言語を選択<br>4. インターフェース全体が即座に翻訳される",
    shortcutsH2:   "キーボードショートカット",
    shortcutsDesc: "Reborn Assistantには素早い操作のためのグローバルショートカットが含まれています:",
    systemH3: "システムショートカット",
    sysSC1:   "<code>CTRL + A</code>: ボットを開始",
    sysSC2:   "<code>CTRL + O</code>: ボットを停止",
    customH3:   "カスタマイズ可能なショートカット",
    customDesc: "以下のためにキーを設定できます:",
    customLi1:  "タイプ1と2のアクション",
    customLi2:  "マクロ（キーシーケンス）",
    customLi3:  "定期マクロ",
    displayH2:    "表示オプション",
    panelPosH3:   "パネルの位置",
    panelPosDesc: "Rebornパネルはドラッグ可能です:",
    panelLi1: "パネルのヘッダーをクリック",
    panelLi2: "押したまま移動",
    panelLi3: "希望の場所で離す",
    panelLi4: "位置は自動的に保存される",
    opacityH3:   "パネルの透明度",
    opacityDesc: "統計を管理しながらナビゲーションを妨げないよう透明度を調整。",
    logH3:   "アクティビティログ",
    logDesc: "ログはリアルタイムで全ての実行されたアクションを表示:",
    logLi1:  "システムの有効化/無効化",
    logLi2:  "ポーションの使用",
    logLi3:  "マクロとシーケンスの実行",
    logLi4:  "定期マクロの呼び出し",
    logLi5:  "エラーの可能性",
    saveH2:    "設定の保存",
    saveDesc:  "全ての設定はローカルに自動保存されます:",
    saveLi1:   "選択したテーマ",
    saveLi2:   "インターフェース言語",
    saveLi3:   "起動しきい値",
    saveLi4:   "割り当てられたキー",
    saveLi5:   "マクロ設定",
    saveLi6:   "パネルの位置",
    savePersist: "ブラウザを閉じた後もセッション間で保持されます。",
  },

  docPremium: {
    h1:       "💎 プレミアムガイド",
    subtitle: "Reborn Assistantの全高度機能をマスター",
    rotH2:    "🛡️ 自動シーケンスローテーション",
    rotDesc:  "ローテーションシステムは定期的なインターバルで事前定義されたキーシーケンスを押すことで、全てのシーケンスを自動的にアクティブに保ちます。",
    rotSeqH3:   "キーシーケンス",
    rotSeqText: "ローテーションは常にこの固定順序に従います:",
    rotConfigH3:   "設定",
    rotIntName:    "サイクル間の間隔",
    rotIntDesc:    "シーケンス全体を再起動する前の待機時間。デフォルト: 5分。最短シーケンスの長さに応じて調整してください。",
    rotDelName:    "キー間の遅延",
    rotDelDesc:    "シーケンスの各キー間の待機時間。デフォルト: 1秒。サービスの速度（アニメーション、クールダウン...）に応じて調整してください。",
    rotExTitle:    "💡 使用例",
    rotExScenario: "<strong>シナリオ:</strong> シーケンスは5分間続き、キー1-8に8つのシーケンスがある場合。",
    rotExConfig:   "<strong>設定:</strong>",
    rotExLi1:      "間隔: 5分",
    rotExLi2:      "遅延: 1秒",
    rotExLi3:      "ボットは5分ごとにF2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1を押す",
    rotExLi4:      "合計13キー、各キー間1秒 = サイクルあたり約13秒",
    macH2:    "⚙️ カスタマイズ可能なマクロ",
    macDesc:  "独自のキーシーケンスで最大3つの独立したマクロを作成。繰り返しタスク、定期的なコンボ、スキルローテーションの自動化に最適。",
    macHowH3:   "動作原理",
    macHowText: "各マクロは他のシステムとは独立して、定期的なインターバルでキーシーケンスを実行します。",
    macConfigH3:  "設定",
    macSeqName:   "キーシーケンス",
    macSeqDesc:   "カンマ区切りで順番に押すキーを定義。例: 1,2,3,4 または q,w,e,r,f",
    macRepName:   "繰り返し間隔",
    macRepDesc:   "シーケンスを繰り返す前の待機時間。ニーズに応じて設定（秒または分）。",
    macDelName:   "キー間の遅延",
    macDelDesc:   "シーケンスの各キー間の待機時間（通常0.5〜2秒）。",
    macExTitle:   "💡 使用例",
    mac1Title:    "<strong>マクロ1 – 繰り返し自動化:</strong>",
    mac1Li1:      "シーケンス: 1,2,3,space",
    mac1Li2:      "間隔: 10秒",
    mac1Li3:      "使用: ループでの基本攻撃ローテーション",
    mac2Title:    "<strong>マクロ2 – スキルコンボ:</strong>",
    mac2Li1:      "シーケンス: q,w,e,r",
    mac2Li2:      "間隔: 30秒",
    mac2Li3:      "使用: 最適なDPSローテーション",
    mac3Title:    "<strong>マクロ3 – 自動サポート:</strong>",
    mac3Li1:      "シーケンス: f,g,h",
    mac3Li2:      "間隔: 15秒",
    mac3Li3:      "使用: グループシーケンスまたは定期アクション",
    perH2:    "🐉 定期マクロ",
    perDesc:  "このシステムは15秒ごとに自動的に定期アクションを実行します。定期的に起動する必要がある繰り返しタスクに最適。",
    perHowH3:   "動作原理",
    perHowText: "システムは15秒ごとにこのシーケンスを自動実行:",
    perLi1:     "定期マクロを呼び出す（設定可能なキー、デフォルト§）",
    perLi2:     "500ms待機",
    perLi3:     "定期マクロを自動保存",
    perConfigH3:  "設定",
    perCallName:  "呼び出しキー",
    perCallDesc:  "定期マクロを起動するキー。デフォルト: §。設定に応じて変更してください。",
    perIntName:   "間隔（固定）",
    perIntDesc:   "システムは常に固定の15秒間隔を使用します。設定不可。",
    perExTitle:   "💡 ユースケース",
    perExText:    "一部のサービスでは、アイテムの収集、一時的なシーケンスの提供、または経験値獲得のために定期マクロを定期的に呼び出す必要があります。このシステムはこのプロセスを完全に自動化します。",
    perImpH3:     "⚠️ 重要",
    perImpLi1:    "設定されたキーが呼び出しキーに対応していることを確認",
    perImpLi2:    "定期マクロは各呼び出し後に自動保存される",
    perImpLi3:    "他のシステム（シーケンス、マクロ、アクション）と並行して動作",
    optH2:   "最適化のヒント",
    combH3:  "🎯 システムの組み合わせ",
    combDesc:"全てのプレミアム機能は同時に動作します。以下が可能:",
    combLi1: "自動シーケンス + 3つのマクロ + 定期マクロを同時に有効化",
    combLi2: "トリガーアクション1と2は常に並行して動作",
    combLi3: "各システムは独立したタイマーを持つ",
    perfH3:  "⚡ パフォーマンス",
    perfLi1: "有効にするシステムが多いほど、拡張機能がより多くのリソースを消費",
    perfLi2: "過度に頻繁なアクションを避けるために間隔を調整",
    perfLi3: "正しい動作を確認するためにアクティビティログを監視",
    secH3:   "🔑 セキュリティ",
    secLi1:  "プレミアムライセンスはリアルタイムで検証される",
    secLi2:  "接続が失われた場合、プレミアム機能は無効化される",
    secLi3:  "全機能を再有効化するには再度ログイン",
  },

  docTroubleshooting: {
    h1:       "🔧 トラブルシューティング",
    subtitle: "一般的な問題の解決策とよくある質問",
    installH2: "インストールの問題",
    faq1Q: "❌ 拡張機能がツールバーに表示されない",
    faq1A: "<strong>解決策:</strong><br>1. 拡張機能が<strong>Chromeウェブストア</strong>からインストールされていることを確認<br>2. 拡張機能を固定: ツールバーのパズルアイコン🧩をクリックしてReborn Assistantを固定<br>3. ブラウザを再起動<br>4. 問題が続く場合は、Chromeウェブストアから拡張機能をアンインストールして再インストール",
    connH2: "接続の問題",
    faq2Q: "❌ 「接続に失敗」または「無効なライセンス」",
    faq2A: "<strong>考えられる原因:</strong><br>• インターネット接続が不安定<br>• Google Cloudサーバーが一時的に利用不可<br>• ライセンスの期限切れまたは無効化<br><br><strong>解決策:</strong><br>1. インターネット接続を確認<br>2. Googleからログアウトして再ログイン<br>3. StripeポータルでライセンスのステータSを確認<br>4. 問題が続く場合はサポートに連絡",
    faq3Q: "❌ プレミアムなのにパネルが「FREE」と表示される",
    faq3A: "1. Googleアカウントからログアウト<br>2. ブラウザを完全に閉じる<br>3. 再度開いてログイン<br>4. 問題が続く場合は、正しいGoogleアカウント（購入時に使用したもの）でログインしていることを確認",
    funcH2: "動作の問題",
    faq4Q:     "❌ タイプ1/2のアクションが起動しない",
    faq4Alert: "<strong>⚠️ 重要</strong><br>タイプ1と2のアクションは<strong>プレミアム専用</strong>機能です。タイプ1自動アクション（HP）のみが無料版で利用可能です。",
    faq4Prem:  "<strong>プレミアムをお持ちの場合:</strong><br>1. ボットは起動していますか？ <code>CTRL+A</code><br>2. トリガースイッチは有効ですか？（緑色の「ON」インジケーター）<br>3. 設定されたキーは正しいですか？",
    faq5Q:     "❌ シーケンス/マクロ/定期マクロ/ショートカットが動作しない",
    faq5Alert: "<strong>⚠️ 重要</strong><br>キーボードショートカット、シーケンス、マクロ、定期マクロは<strong>プレミアム専用</strong>機能です。無料版ではタイプ1自動アクション（HP）のみ利用可能です。",
    faq5Prem:  "<strong>プレミアムをお持ちの場合:</strong><br>1. プレミアムライセンスがアクティブであることを確認（パネルの💎アイコン）<br>2. 対応するスイッチは有効ですか？<br>3. 設定された間隔と遅延を確認",
    faq6Q: "❌ ボットが自動的に停止する",
    faq6A: "<strong>考えられる原因:</strong><br>• Google Cloudへの接続が失われた<br>• DevToolsが検出された<br>• ページのURLが変更された<br><br><strong>解決策:</strong><br>1. <code>CTRL+A</code>（プレミアム）またはパネルからボットを再起動<br>2. 影響を受けたページをリロード<br>3. インターネット接続を確認<br>4. プレミアムモードではDevToolsを開かないこと",
    optH2: "最適化＆パフォーマンス",
    faq7Q: "💡 ボットがリソースを消費しすぎる",
    faq7A: "<strong>推奨事項:</strong><br>• マクロとシーケンスの間隔を増やす（アクションが少ない = CPU消費が少ない）<br>• 不要なシステムを無効化<br>• 不要なタブを閉じる<br>• 最適化されたブラウザを使用（Brave、EdgeはChromeより軽量）",
    faq8Q: "💡 設定を最適化するには？",
    faq8A: "<strong>推奨設定:</strong><br>• <strong>シーケンス間隔:</strong> 5〜25分（シーケンスの長さによる）<br>• <strong>キー間の遅延:</strong> 1〜2秒（エラーを防ぐ）<br>• <strong>マクロ:</strong> 使用法に応じて10〜30秒の間隔",
    genH2:  "よくある質問",
    faq9Q:  "❓ 複数のブラウザでRebornを使用できますか？",
    faq9A:  "はい、ただし各ブラウザに拡張機能をインストールする必要があります。同じGoogleアカウントでログインしている限り、プレミアムライセンスは全デバイスで機能します（最大1つの同時接続）。",
    faq10Q: "❓ データは保存されますか？",
    faq10A: "全ての設定（キー、マクロ、テーマ、言語）はブラウザに<strong>ローカルに</strong>保存されます。セッション間で保持されます。ただし、拡張機能をアンインストールするとこれらのデータは失われます。",
    faq11Q: "❓ Rebornはバンされる可能性がありますか？",
    faq11A: "自動化ツールの使用は一部のサービスの利用規約に違反する可能性があります。Rebornの使用方法については<strong>あなただけが責任を負います</strong>。このツールを使用する前にサービスの利用規約を確認してください。",
    faq12Q: "❓ プレミアムサブスクリプションをキャンセルするには？",
    faq12A: "Stripe管理ポータル（支払い後にメールで受け取ったリンク）からいつでもキャンセルできます。キャンセルは現在の期間の終了時に有効になります。キャンセル手数料なし。",
    faq13Q: "❓ サービスが終了した場合、生涯プランはどうなりますか？",
    faq13A: "生涯プランはサービスがアクティブな限りアクセスを保証します。インストール後、拡張機能はローカルで動作します。ライセンス検証のみインターネット接続が必要です。",
    supportH2:    "さらにサポートが必要ですか？",
    supportTitle: "📧 サポート",
    supportText:  "問題が続く場合は、メールで直接サポートに連絡してください。メッセージに以下を含めてください:<br><br>• 問題の詳細な説明<br>• 既に試みたステップ<br>• 関連するスクリーンショット<br>• ブラウザとOSの情報",
  },

  docPrivacy: {
    h1:       "⚖️ 法的情報＆プライバシー",
    subtitle: "法的免責事項、法的記載、ライセンス条件、プライバシーポリシー",
    navLegal:  "⚖️ 法的情報",
    navLicence:"© ライセンス",
    navPrivacy:"🔒 プライバシー",
    disclaimerH2:  "⚠️ 法的免責事項",
    disclaimerBox: "<strong>⚠️ 重要なお知らせ:</strong> Reborn Assistantは自動化ツールです。使用により一部のオンラインサービスの利用規約に違反する可能性があります。このツールの使用は完全に自己責任です。",
    respH3:    "ユーザーの責任",
    respIntro: "Reborn Assistantを使用することで、以下を認め同意します:",
    respLi1:   "このソフトウェアの使用について、あなただけが責任を負います",
    respLi2:   "このツールを使用する前に各サービスの利用規約を確認します",
    respLi3:   "Rebornの使用から生じるバン、アカウント制限、法的措置について作者は責任を負いません",
    respLi4:   "このソフトウェアを意識的に自己責任で使用します",
    respLi5:   "このツールは他のユーザーの体験を損なう方法で使用してはなりません",
    warrantH3:   "保証なし",
    warrantText: "ソフトウェアは「現状のまま」いかなる保証もなく提供されます。作者はソフトウェアが中断なくまたはエラーなく動作すること、または全てのサービスやブラウザと互換性があることを保証しません。",
    legalH2:    "📄 法的記載",
    copyrightH3:   "著作権＆知的財産",
    copyrightText: "<strong>© 2026 Reborn Assistant – 全著作権所有</strong><br><strong>Seymoon</strong>開発",
    copyrightText2:"このソフトウェアと関連する全ての素材は作者の独占的な知的財産です。書面による許可なしにいかなる複製、改変、配布、リバースエンジニアリングも厳しく禁止されています。",
    liabilityH3:   "責任の制限",
    liabilityIntro:"いかなる場合も、作者は以下を含むがこれに限られない、このソフトウェアの使用または使用不能から生じるいかなる請求または損害についても責任を負いません:",
    liabilityLi1:  "データまたはユーザーアカウントの損失",
    liabilityLi2:  "サービス発行者によるバンまたは制限",
    liabilityLi3:  "コンピュータシステムへの損害",
    liabilityLi4:  "サービス条件に準拠しない使用から生じる法的結果",
    dataH3:    "個人データ",
    dataText:  "Reborn AssistantはアカウントとライセンSs管理にFirebase（Google Cloud）を使用します。収集されるデータは、認証とライセンス検証の目的のみのメールアドレスとアカウントIDに限定されます。",
    dataText2: "<strong>アクティビティデータは収集・転送されません。</strong>設定はデバイスにローカルに保存されます。",
    jurisH3:   "裁判管轄",
    jurisText: "この契約は著作権者の居住地の管轄において適用される法律に従います。このソフトウェアをインストールおよび使用することで、これらの条件の全てを読み、理解し、受け入れたことを認めます。",
    licenceH2:     "© ライセンス条件",
    licenceH3:     "使用ライセンス",
    licenceIntro:  "Reborn Assistantプランの購入により、ソフトウェアを使用するための個人的、非独占的、譲渡不可のライセンスが付与されます。",
    licenceAllows: "<strong>このライセンスで許可されること:</strong>",
    licenceLi1:    "自分のデバイスで個人的な目的でソフトウェアを使用すること",
    licenceLi2:    "プランに含まれるアップデートを利用すること",
    licenceForbids:"<strong>このライセンスで禁止されること:</strong>",
    licenceLi3:    "アクセスを再配布、再販、または共有すること",
    licenceLi4:    "ソフトウェアを修正、逆コンパイル、またはリバースエンジニアリングすること",
    licenceLi5:    "事前の書面による合意なしにソフトウェアを商業目的で使用すること",
    licenceLi6:    "ライセンスを第三者に譲渡すること",
    terminationH3:   "終了",
    terminationText: "これらの条件に違反した場合、ライセンスは直ちに終了することができます。サブスクリプションプランの場合、Stripeポータルからいつでもキャンセルできます。",
    refundBox: "<strong>✅ 返金ポリシー:</strong> 購入後7日以内に満足できない場合は、完全返金のためサポートに連絡してください。この期間を過ぎると、例外的な場合を除き返金は行われません。",
    privacyH1:      "🔒 プライバシーポリシー",
    privacySubtitle:"個人データの保護方法",
    privacyBox:     "<strong>✅ プライバシーは最優先事項です</strong><br>無料版: 個人データは収集されません。プレミアム版: ライセンス検証に厳密に必要なデータのみが処理されます。",
    collectH2:        "データの収集",
    collectFreeH3:    "無料版",
    collectFreeText:  "個人データは収集・転送されません。全ての設定はデバイスにのみ保存されます。",
    collectPremH3:    "プレミアム版",
    collectPremIntro: "ライセンスを検証しアカウントを保護するために、以下のデータが処理されます:",
    collectPremLi1:   "GooglesメールアドレS（Google認証経由）",
    collectPremLi2:   "一意のデバイス識別子（ローカルで生成）",
    collectPremLi3:   "サブスクリプションのステータスとセッションタイムスタンプ",
    collectPremLi4:   "アカウントあたり最大2つの登録デバイス",
    collectPremBasis: "<strong>法的根拠:</strong> 契約の履行（GDPR第6条1項b）。",
    collectNotH3:     "収集されないデータ",
    collectNotLi1:    "❌ ゲームまたはアクティビティデータなし",
    collectNotLi2:    "❌ 閲覧履歴なし",
    collectNotLi3:    "❌ 広告またはトラッキングCookieなし",
    localH2:    "ローカルに保存されるデータ",
    localIntro: "以下の情報は<strong>デバイスにのみ</strong>保存されます:",
    localLi1:   "<strong>言語設定</strong>: インターフェース言語の選択",
    localLi2:   "<strong>ビジュアルテーマの選択</strong>: 6つから選択されたテーマ",
    localLi3:   "<strong>設定されたキーボードショートカット</strong>: アクションに割り当てられたキー",
    localLi4:   "<strong>カスタムタイマー間隔</strong>: マクロに設定されたタイマー",
    localLi5:   "<strong>インターフェースの位置</strong>: 画面上のRebornパネルの場所",
    localLi6:   "<strong>ライセンスキャッシュ（プレミアム）</strong>: 起動ごとの検証を避けるためのデバイスIDとサブスクリプションステータス",
    thirdH2:       "サードパーティサービス",
    thirdH3:       "使用されるサービス（プレミアム版）",
    thirdDesc:     "認証と支払いのために、Reborn Assistantは以下を使用:",
    thirdLi1:      "🔐 <strong>Google</strong> — 認証とライセンスデータの安全な保存",
    thirdLi2:      "💳 <strong>Stripe</strong> — プレミアム支払いの処理（銀行情報は絶対にサーバーを通過しません）",
    thirdTransfer: "これらのプロバイダーはGDPRに準拠し、国際データ転送のための適切な保護措置を備えています。",
    thirdNoH3:     "トラッキングなし、広告なし",
    thirdLi3:      "❌ 分析または統計サービスなし",
    thirdLi4:      "❌ 広告またはターゲットマーケティングなし",
    thirdLi5:      "❌ サードパーティCookieまたは行動追跡なし",
    authH2:    "認証とデバイス管理",
    authH3:    "Googleでログイン（プレミアム版）",
    authText:  "Googleアカウントは身元の認証とライセンス検証にのみ使用されます。デバイスは安全なシステムに登録されます（アカウントあたり最大2デバイス）。",
    authText2: "認識されていないデバイスでアカウントが使用された場合、通知を受け取ります。登録されたデバイスは拡張機能から直接管理できます。",
    payH2:    "安全な支払い",
    payText:  "プレミアム支払いは<strong>Stripe</strong>によって処理されます。銀行情報は<strong>絶対に</strong>サーバーを通過しません。<strong>銀行カードデータは一切保存しません。</strong>",
    retentionH2:   "保存期間",
    retentionText: "データは必要な期間のみ保存されます:",
    retentionLi1:  "<strong>アクティブなアカウント:</strong> サブスクリプション期間中データを保存",
    retentionLi2:  "<strong>キャンセル後:</strong> 30日以内に削除",
    retentionLi3:  "<strong>ローカルデータ:</strong> 拡張機能のアンインストール時に即時削除",
    rightsH2:      "あなたの権利（GDPR）",
    rightsText:    "GDPRに従い、データに関して以下の権利があります:",
    rightsLi1:     "✅ <strong>アクセス</strong> — 個人データのコピーを取得",
    rightsLi2:     "✅ <strong>訂正</strong> — 不正確なデータの修正",
    rightsLi3:     "✅ <strong>削除</strong> — アカウントとデータの削除を要求",
    rightsLi4:     "✅ <strong>ポータビリティ</strong> — 読み取り可能な形式でデータを受け取る",
    rightsLi5:     "✅ <strong>苦情</strong> — 国のデータ保護機関に苦情を申し立てる",
    rightsExercise:"これらの権利を行使するには: seymoon.cell@gmail.com またはDiscord（Seymoon）にご連絡ください",
    deleteH2:    "データの削除",
    deleteText1: "<strong>1. 拡張機能のアンインストール</strong><br>Reborn Assistantをアンインストールすると、全てのローカルデータが自動的に削除されます。",
    deleteText2: "<strong>2. 手動リセット</strong><br>Rebornインターフェースからいつでも設定をリセットできます。",
    deleteText3: "<strong>3. アカウントの削除（プレミアム）</strong><br>プレミアムアカウントと関連するデータを削除するには、メールでご連絡ください。",
    contactH2:   "お問い合わせ",
    contactText: "法的情報またはプライバシーポリシーに関するご質問は:",
    changelogH2: "📋 変更履歴",
    v130H3:          "バージョン1.3.0（2026年3月）・現行",
    v130newLabel:    "✨ 新機能",
    v130improvLabel: "🔧 改善",
    v130fixLabel:    "🐛 バグ修正",
    v130Li1:  "⏱ ドラッグ可能なフローティングミニタイマー — バフタイマーと1分以上のタイマーを表示する小さなフローティングウィンドウで、次回起動時に自動的に再表示し、アクティブスキンに追従します。",
    v130Li2:  "⚡ 優先マクロ — マクロはヒール/HP/マナより先に実行され、競合を避けるため各実行の前後に0.5秒のヒールフリーズが入ります。",
    v130Li3:  "🧠 スマートバフ管理 — バフが最初に実行され、無音マクロはキューに入れられてバフ終了後に自動的に再起動されます（遅延2秒に短縮）。",
    v130Li4:  "💾 位置メモリ — フローティングウィンドウはセッション間で位置を保持します。",
    v130Li5:  "🇸🇦 アラビア語サポート — 拡張機能で利用可能な15番目の言語。",
    v130Li6:  "💳 ポップアップでのStripe決済 — 拡張機能を離れることなく、専用ウィンドウで開き自動的に閉じます。",
    v130Li7:  "🐾 ペット：最初のバフでペットが出てこなかったバグを修正 + 停止時の格納のためのF1/F2モード追跡を改善。",
    v130Li8:  "⏱ タイマー：プレミアムデザインのビジュアルリワーク + 静止時透明度55% → ホバー時95%で視認性向上。",
    v130Li9:  "💳 請求ポータル：メモリ内に単一のアクティブウィンドウ、自動的に閉じます。",
    v130Li10:  "コンテンツとポップアップの複数のメモリリークを修正。",
    v130Li16:  "最大2デバイス制限でのUIの整合（バックエンドとの一貫性）。",
    v120H3:  "バージョン1.2.0（2026年3月）",
    v120Li1: "✨ 6つのスキンが微妙な透明効果で再設計されました。",
    v120Li2: "🔐 拡張機能から直接登録されたデバイスを表示・管理。",
    v120Li3: "💳 拡張機能からワンクリックでサブスクリプションにアクセス。",
    v120Li4: "🔔 別のデバイスでアカウントが使用された場合に即時通知。",
    v12H3:   "バージョン1.2（2026年2月）",
    v12Li1:  "15言語サポート（トルコ語🇹🇷追加）",
    v12Li2:  "ウェブサイトのビジュアルリデザイン",
    v12Li3:  "法的ページを1つの統合ページに統合",
    v12Li4:  "サイトの完全なFR/EN翻訳",
    v11H3:   "バージョン1.1.1（2026年2月）",
    v11Li1:  "自動定期マクロを追加（15秒+自動保存）",
    v11Li2:  "キーボードショートカットCTRL+A / CTRL+O",
    v11Li3:  "15言語サポート（フィリピン語+トルコ語追加）",
    v11Li4:  "プレミアムライセンスの安定性向上",
    v11Li5:  "シーケンスローテーションのバグ修正",
    v10H3:   "バージョン1.0（2025年）・初期",
    v10Li1:  "Reborn Assistantのリリース",
    v10Li2:  "タイプ1と2の自動アクション",
    v10Li3:  "自動シーケンスローテーション（F2 → 1-9 → 0 → F1）",
    v10Li4:  "3つのカスタマイズ可能なマクロ",
    v10Li5:  "6つのビジュアルテーマと12言語",
    v10Li6:  "Firebase経由のプレミアムライセンスシステム",
    pageFooter:"© 2026 Reborn Assistant — Seymoon開発・全著作権所有",
  },
  nav: {
    docsFull:    "📚 ドキュメント",
    docsShort:   "📚 Docs",
    manageFull:  "サブスクリプションを管理",
    manageShort: "管理",
  },
};