export default {
  hero: {
    description: "고급 매크로를 갖춘 브라우저 자동화 확장 프로그램. 반복적인 작업, 단축키, 시퀀스를 자동화하여 생산성을 최적화하세요.",
    ctaPrimary: "지금 시작하기",
    ctaSecondary: "더 알아보기",
    trust1: "무료 버전 제공",
    trust2: "약정 없음",
    trust3: "100% 안전한 결제",
    trust4: "자동 업데이트",
  },
  features: {
    tag: "기술 & 능력",
    titleBefore: "필요한 ",
    titleEm: "모든 것",
    subtitle: "Reborn Assistant의 탁월한 기능을 발견하세요.",
    card1: { badge: "활성",   title: "완전 자동화",          description: "완전한 자동화를 위한 키 매크로, 자동 시퀀스, 구성 가능한 액션." },
    card2: { badge: "수동",   title: "최대 보안",             description: "데이터는 로컬에 유지됩니다. 추적 없음, 원격 측정 없음." },
    card3: { badge: "활성",   title: "사용자 정의 매크로",   description: "자동 트리거와 키보드 단축키가 있는 3개의 구성 가능한 매크로." },
    card4: { badge: "수동",   title: "사용자 정의 인터페이스",description: "6가지 테마 중에서 선택하고 인터페이스를 필요에 맞게 조정하세요." },
    card5: { badge: "수동",   title: "다국어 지원",           description: "15개 언어로 제공됩니다. 로컬화된 인터페이스로 전 세계 지원." },
    card6: { badge: "무료",   title: "무료 버전",             description: "기본 기능이 포함된 무료 체험." },
  },
  security: {
    tag: "보안",
    titleBefore: "전문가 수준의 ",
    titleEm: "보안",
    titleAfter: "",
    description: "Reborn Assistant는 세계 스트리밍 플랫폼과 동일한 보안 표준을 사용합니다. 자격 증명은 <strong style='color:var(--gold);'>JWT 암호화</strong>로 보호되고, 결제는 <strong style='color:var(--gold);'>Stripe</strong>로 보장되며, 데이터는 <strong style='color:var(--gold);'>100% 로컬</strong>에 유지됩니다. 추적 없음, 데이터 판매 없음.",
    card1Title: "JWT 암호화",
    card1Text:  "은행 수준의 안전한 인증",
    card2Title: "Stripe 결제",
    card2Text:  "Amazon과 Google이 사용하는 프로세서",
    card3Title: "제로 추적",
    card3Text:  "데이터가 기기를 떠나지 않습니다",
    card4Text:  "안전한 Google Cloud 인프라",
  },
  pricing: {
    tag:         "클래스 선택",
    titleBefore: "등급을 ",
    titleEm:     "선택하세요",
    subtitle:    "가장 적합한 플랜을 선택하세요. 약정 없음.",
    voyageur: {
      rank: "등급 I · 여행자", plan: "무료", period: "영원히",
      feat1: "힐링 매크로", feat2: "6가지 시각적 테마", feat3: "15개 언어 제공", feat4: "플로팅 인터페이스",
      btn: "시작하기", download: "Chrome에 추가", guarantee: "🔒 영원히 무료",
    },
    aventurier: {
      rank: "등급 II · 모험가", plan: "월간", period: "월",
      feat1: "모든 프리미엄 기능", feat2: "우선 지원", feat3: "무료 업데이트",
      btn: "무료 체험", guarantee: "🎁 7일 무료 · 신용카드 불필요",
      download: "Chrome에 추가",
    },
    champion: {
      badge: "⭐ 인기 -17%",
      rank: "등급 III · 챔피언", plan: "연간", period: "년 · 2.50€/월",
      feat1: "모든 프리미엄 기능", feat2: "우선 지원", feat3: "무료 업데이트",
      btn: "무료 체험", guarantee: "🎁 7일 무료 · 신용카드 불필요",
      download: "Chrome에 추가",
    },
    legende: {
      badge: "⚡ 한정 제공",
      rank: "등급 IV · 레전드", plan: "평생", period: "일회성 결제 · 다시는 없음",
      feat1: "평생 액세스", feat2: "모든 미래 업데이트", feat3: "전담 프리미엄 지원", feat4: "최고의 가성비",
      btn: "구매", guarantee: "🔒 일회성 결제 · 평생 액세스 보장",
      download: "Chrome에 추가",
    },
  },
  stats: {
    label1: "지원 언어", label2: "시각적 테마", label3: "로컬 데이터", label4: "활성 확장 프로그램",
  },
  trust: {
    badge1: "SSL 안전 결제", badge2: "즉시 액세스", badge3: "100% 비공개 데이터", badge4: "빠른 지원",
  },
  store: {
    status: "공식 확장 프로그램",
    title:  "Chrome 웹 스토어에서 이용 가능",
    install: "설치",
    available: "무료로 이용 가능 · Google이 인증한 공식 확장 프로그램",
  },
  faq: {
    titleBefore: "자주 묻는 ",
    titleEm:     "질문",
    subtitle:    "시작하기 전에 알아야 할 모든 것.",
    q1: "무료 체험에 신용카드가 필요한가요?",
    a1: "아니요, 신용카드가 필요하지 않습니다. 처음 7일은 약정 없이 완전 무료입니다. 즉시 시작하려면 계정을 만들기만 하면 됩니다.",
    q2: "언제든지 플랜을 변경할 수 있나요?",
    a2: "네, 계정에서 언제든지 상위 또는 하위 플랜으로 변경할 수 있습니다. 변경 수수료 없음.",
    q3: "평생 플랜에는 정말로 모든 미래 업데이트가 포함되나요?",
    a3: "물론입니다. 평생 플랜은 추가 비용 없이 모든 미래 업데이트와 새 기능에 대한 액세스를 보장합니다.",
    q4: "내 데이터는 안전한가요?",
    a4: "모든 데이터는 기기에 로컬로 저장됩니다. 개인 데이터를 수집하지 않으며, 추적이나 원격 측정을 사용하지 않습니다.",
    q5: "지원에 어떻게 연락하나요?",
    a5: "seymoon.cell@gmail.com 이메일 또는 Discord(Seymoon)로 문의하세요. 프리미엄 구독자는 우선 응답을 받습니다.",
    q6: "Reborn Assistant은 봇입니까?",
    a6: "엄밀히 말하면 Reborn Assistant은 기존의 봇이 아닙니다. 직접 정의한 키 시퀀스를 자동화하는 구성 가능한 매크로의 확장 프로그램입니다. 인공 지능 없음, 게임 서버와의 상호 작용 없음, 메모리 읽기 없음. 확장 프로그램은 게임 데이터를 읽거나 수정하지 않으며 — 수동으로 누르는 키를 시뮬레이션할 뿐입니다. 사용하는 서비스의 이용 약관을 준수하는 것은 사용자의 책임입니다.",
  },
  footer: {
    privacy:   "개인정보",
    terms:     "이용약관",
    copyright: "© 2026 Reborn Assistant. 모든 권리 보유.<br>Seymoon 개발",
  },

  docsNav: {
    backToDocs:      "← 문서로 돌아가기",
    mainSite:        "⌂ 메인 사이트",
    backToMainSite:  "← 메인 사이트로 돌아가기",
    footer:          "© 2026 Reborn Assistant — Seymoon 개발 · 모든 권리 보유",
  },

  docsHome: {
    version:              "버전 1.3 · 전체 문서",
    userGuide:            "사용자 가이드",
    support:              "지원",
    legal:                "법적 정보",
    quickstartTitle:      "빠른 시작",
    quickstartDesc:       "Reborn Assistant 설치, 초기 설정 및 첫 단계.",
    featuresTitle:        "기능",
    featuresDesc:         "비교표가 있는 무료 및 프리미엄 기능의 전체 설명.",
    premiumTitle:         "프리미엄 가이드",
    premiumDesc:          "자동 시퀀스, 사용자 정의 매크로, 주기적 매크로.",
    interfaceTitle:       "인터페이스 & 개인화",
    interfaceDesc:        "시각적 테마, 언어, 개인화 옵션.",
    troubleshootingTitle: "문제 해결",
    troubleshootingDesc:  "일반적인 문제 해결책, 자주 묻는 질문, 성능 최적화.",
    legalTitle:           "법적 & 개인정보",
    legalDesc:            "법적 면책, 법적 고지, 라이선스 조건, 개인정보 보호정책, 변경 로그.",
    footer:               "© 2026 Reborn Assistant — Seymoon 개발 · 모든 권리 보유",
  },

  docFeatures: {
    h1:        "⚡ 기능",
    subtitle:  "Reborn Assistant가 할 수 있는 모든 것을 발견하세요",
    h2Free:    "무료 기능",
    freeBadge: "무료",
    c1Title: "타입 1 자동 액션",
    c1Desc:  "구성 가능한 타이머를 기반으로 타입 1 액션(HP)을 자동으로 활성화합니다.",
    c1li1:   "구성 가능한 액션 타이머",
    c1li2:   "백그라운드에서 작동",
    c2Title: "시각적 테마",
    c2Desc:  "6가지 다른 테마로 인터페이스 외관을 사용자 정의하세요.",
    c2li1:   "MMO Gold (기본값)",
    c2li2:   "다크 모드 & 화이트 모드",
    c3Title: "다국어",
    c3Desc:  "국제적 경험을 위한 15개 언어로 제공되는 인터페이스.",
    c3li3:   "즉시 전환",
    h2Premium: "프리미엄 기능 💎",
    p1Title: "자동 트리거 1 매크로",
    p1Desc:  "구성 가능한 타이머를 기반으로 타입 1 액션(HP)의 자동 활성화.",
    p1li1:   "구성 가능한 트리거 1 타이머",
    p1li2:   "구성 가능한 단축키",
    p1li3:   "백그라운드에서 작동",
    p2Title: "자동 트리거 2 매크로",
    p2Desc:  "구성 가능한 타이머를 기반으로 타입 2 액션의 자동 사용.",
    p2li1:   "구성 가능한 트리거 2 타이머",
    p2li2:   "구성 가능한 단축키",
    p2li3:   "백그라운드에서 작동",
    p3Title: "키보드 단축키",
    p3Desc:  "사용자 정의 가능한 전역 단축키로 Reborn Assistant를 즉시 제어하세요.",
    p3li1:   "CTRL+A: 봇 시작",
    p3li2:   "CTRL+O: 봇 중지",
    p4Title: "시퀀스 로테이션",
    p4Desc:  "미리 정의된 시퀀스가 있는 자동 시퀀스 유지 시스템.",
    p4li1:   "시퀀스: F2 → 1-9 → 0 → F1",
    p4li2:   "구성 가능한 간격(분)",
    p4li3:   "키 사이 조정 가능한 지연",
    p5Title: "사용자 정의 매크로",
    p5Desc:  "자신만의 키 시퀀스로 최대 3개의 매크로를 만드세요.",
    p5li1:   "3개의 독립적인 매크로",
    p5li2:   "사용자 정의 시퀀스",
    p5li3:   "조정 가능한 반복 간격",
    p6Title: "주기적 매크로",
    p6Desc:  "15초마다 주기적 매크로를 자동 호출 및 저장.",
    p6li1:   "주기적 매크로 자동 호출",
    p6li2:   "호출 후 자동 저장",
    p6li3:   "고정 15초 간격",
    tableH2:      "비교표",
    tableFeature: "기능",
    tableFree:    "무료",
    row1:  "타입 1 자동 액션(HP)",
    row2:  "시각적 테마(6)",
    row3:  "다국어(15)",
    row4:  "자동 트리거 1 매크로",
    row5:  "자동 트리거 2 매크로",
    row6:  "키보드 단축키(CTRL+A / CTRL+O)",
    row7:  "자동 시퀀스 로테이션",
    row8:  "사용자 정의 매크로(3x)",
    row9:  "자동 주기적 매크로",
    learnMore: "→ 프리미엄 기능에 대해 더 알아보기",
  },

  docQuickstart: {
    h1:       "🚀 빠른 시작",
    subtitle: "몇 분 안에 Reborn Assistant 설치 및 설정",
    reqH2:    "요구 사항",
    req1:     "<strong>호환 브라우저:</strong> Google Chrome, Microsoft Edge, Brave 또는 Chromium 기반 브라우저",
    req2:     "<strong>Google 계정:</strong> 프리미엄 인증에만 필요(무료 버전은 선택 사항)",
    req3:     "<strong>호환 사이트:</strong> 표준 웹사이트와 호환",
    installH2:  "설치",
    step1Title: "Chrome 웹 스토어 방문",
    step1p:     "<a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome 웹 스토어</a>의 Reborn Assistant 페이지로 이동하여 <strong>«Chrome에 추가»</strong>를 클릭하세요.",
    step1tip:   "💡 Google Chrome, Microsoft Edge, Brave 및 Chromium 기반 브라우저와 호환됩니다.",
    step2Title: "설치 확인",
    step2p:     "확인 창에서 <strong>«확장 프로그램 추가»</strong>를 클릭하세요. 확장 프로그램이 자동으로 설치됩니다.",
    step3Title: "확장 프로그램 고정",
    step3p:     "브라우저 도구 모음의 퍼즐 아이콘 🧩을 클릭하고 빠른 액세스를 위해 Reborn Assistant를 고정하세요.",
    step4Title: "로그인(프리미엄의 경우 선택 사항)",
    step4p:     "• 도구 모음의 Reborn 아이콘 클릭<br>• 프리미엄의 경우: Google 계정으로 로그인<br>• 무료의 경우: 로그인 없이 직접 사용",
    alertTitle: "✅ 설치 완료!",
    alertText:  "확장 프로그램이 활성화되면 Reborn 아이콘이 초록색으로 변합니다. 이제 기능을 구성할 수 있습니다.",
    configH2:   "초기 설정",
    freeH3:     "무료 버전",
    freeTitle:  "<strong>로그인 없이 사용 가능한 기능:</strong>",
    freeText:   "• 타입 1 자동 액션(HP만)<br>• 6가지 시각적 테마<br>• 15개 언어 지원",
    freeStepTitle: "타입 1 자동 액션 설정",
    freeStepText:  "1. Reborn 패널 열기(아이콘 클릭)<br>2. HP 액션 타이머 조정(기본값: 2초)<br>3. 액션이 자동으로 활성화됨<br>4. 로그인 불필요",
    premiumH3:       "프리미엄 버전 💎",
    premiumFeatTitle:"<strong>추가 기능(Google 로그인 필요):</strong>",
    premiumFeatText: "• 자동 트리거 1 매크로(구성 가능한 타이머 + 단축키)<br>• 자동 트리거 2 매크로(구성 가능한 타이머 + 단축키)<br>• 키보드 단축키(CTRL+A / CTRL+O)<br>• 자동 시퀀스 로테이션(F2 → 1-9 → 0 → F1)<br>• 키 시퀀스가 있는 3개의 사용자 정의 매크로<br>• 자동 주기적 매크로 시스템(15초마다 호출 + 저장)",
    premConfigTitle: "프리미엄 설정",
    premConfigSeq:   "<strong>자동 시퀀스:</strong><br>• 패널에서 «시퀀스 로테이션»을 활성화<br>• 사이클 간 간격 설정(기본값: 5분)<br>• 각 키 사이의 지연 조정(기본값: 1초)",
    premConfigMacro: "<strong>매크로:</strong><br>• 매크로 1, 2 또는 3 활성화<br>• 키 시퀀스 정의(예: <code>1,2,3,4</code>)<br>• 반복 간격 설정",
    premConfigPer:   "<strong>주기적 매크로:</strong><br>• «주기적 매크로» 스위치 활성화<br>• 시스템이 15초마다 주기적 매크로를 자동 호출<br>• 호출 후 자동 저장",
    warnTitle: "⚠️ 중요 참고 사항",
    warnText:  "프리미엄 기능(트리거 매크로 1과 2, 자동 시퀀스, 자동 주기적 매크로, 3개의 구성 가능한 매크로)은 유효한 프리미엄 라이선스와 Google 로그인이 필요합니다. 라이선스 없이는 기본 매크로만 사용 가능합니다.",
    shortcutsH2:   "키보드 단축키",
    shortcutsText: "<code>CTRL + A</code>: 봇 시작<br><code>CTRL + O</code>: 봇 중지",
    nextH2: "다음 단계",
    link1:  "모든 기능 발견하기",
    link2:  "전체 프리미엄 가이드",
    link3:  "일반적인 문제 해결책",
  },

  docInterface: {
    h1:       "🎨 인터페이스 & 개인화",
    subtitle: "선호도에 맞게 Reborn Assistant 사용자 정의",
    themesH2:    "시각적 테마",
    themesDesc:  "Reborn Assistant는 인터페이스 외관을 개인화하기 위한 6가지 테마를 제공합니다:",
    changeThemeH3:   "테마 변경",
    changeThemeText: "1. Reborn 패널 열기<br>2. \"⚙️ 설정\" 탭 클릭<br>3. 드롭다운 메뉴에서 테마 선택<br>4. 변경 사항이 즉시 적용됨",
    langsH2:    "지원 언어",
    langsDesc:  "15개 언어로 제공되는 인터페이스:",
    changeLangH3:   "언어 변경",
    changeLangText: "1. Reborn 패널 열기<br>2. \"⚙️ 설정\" 클릭<br>3. 드롭다운 메뉴에서 언어 선택<br>4. 전체 인터페이스가 즉시 번역됨",
    shortcutsH2:   "키보드 단축키",
    shortcutsDesc: "Reborn Assistant에는 빠른 제어를 위한 전역 단축키가 포함되어 있습니다:",
    systemH3: "시스템 단축키",
    sysSC1:   "<code>CTRL + A</code>: 봇 시작",
    sysSC2:   "<code>CTRL + O</code>: 봇 중지",
    customH3:   "사용자 정의 단축키",
    customDesc: "다음을 위한 키를 설정할 수 있습니다:",
    customLi1:  "타입 1과 2 액션",
    customLi2:  "매크로(키 시퀀스)",
    customLi3:  "주기적 매크로",
    displayH2:    "표시 옵션",
    panelPosH3:   "패널 위치",
    panelPosDesc: "Reborn 패널을 드래그할 수 있습니다:",
    panelLi1: "패널 헤더 클릭",
    panelLi2: "누른 채로 드래그",
    panelLi3: "원하는 위치에 놓기",
    panelLi4: "위치가 자동으로 저장됨",
    opacityH3:   "패널 불투명도",
    opacityDesc: "통계를 관리하면서 탐색을 방해하지 않도록 투명도를 조정하세요.",
    logH3:   "활동 로그",
    logDesc: "로그는 실시간으로 모든 수행된 액션을 표시합니다:",
    logLi1:  "시스템 활성화/비활성화",
    logLi2:  "포션 사용",
    logLi3:  "매크로 및 시퀀스 실행",
    logLi4:  "주기적 매크로 호출",
    logLi5:  "가능한 오류",
    saveH2:    "설정 저장",
    saveDesc:  "모든 설정이 로컬에 자동 저장됩니다:",
    saveLi1:   "선택한 테마",
    saveLi2:   "인터페이스 언어",
    saveLi3:   "활성화 임계값",
    saveLi4:   "할당된 키",
    saveLi5:   "매크로 구성",
    saveLi6:   "패널 위치",
    savePersist: "브라우저를 닫은 후에도 세션 간에 유지됩니다.",
  },

  docPremium: {
    h1:       "💎 프리미엄 가이드",
    subtitle: "Reborn Assistant의 모든 고급 기능 마스터",
    rotH2:    "🛡️ 자동 시퀀스 로테이션",
    rotDesc:  "로테이션 시스템은 정기적인 간격으로 미리 정의된 키 시퀀스를 눌러 모든 시퀀스를 자동으로 활성 상태로 유지합니다.",
    rotSeqH3:   "키 시퀀스",
    rotSeqText: "로테이션은 항상 이 고정된 순서를 따릅니다:",
    rotConfigH3:   "설정",
    rotIntName:    "사이클 간 간격",
    rotIntDesc:    "전체 시퀀스를 다시 시작하기 전 대기 시간. 기본값: 5분. 가장 짧은 시퀀스의 지속 시간에 따라 조정하세요.",
    rotDelName:    "키 사이 지연",
    rotDelDesc:    "시퀀스의 각 키 사이 대기 시간. 기본값: 1초. 서비스 속도에 따라 조정하세요(애니메이션, 쿨다운...).",
    rotExTitle:    "💡 사용 예시",
    rotExScenario: "<strong>시나리오:</strong> 시퀀스가 5분 지속되고 키 1-8에 8개의 시퀀스가 있는 경우.",
    rotExConfig:   "<strong>설정:</strong>",
    rotExLi1:      "간격: 5분",
    rotExLi2:      "지연: 1초",
    rotExLi3:      "봇은 5분마다 F2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1을 누름",
    rotExLi4:      "총 13키, 각 키 사이 1초 = 사이클당 약 13초",
    macH2:    "⚙️ 사용자 정의 매크로",
    macDesc:  "자신만의 키 시퀀스로 최대 3개의 독립적인 매크로를 만드세요. 반복 작업, 정기적인 콤보, 스킬 로테이션 자동화에 완벽합니다.",
    macHowH3:   "작동 원리",
    macHowText: "각 매크로는 다른 시스템과 독립적으로 정기적인 간격으로 키 시퀀스를 실행합니다.",
    macConfigH3:  "설정",
    macSeqName:   "키 시퀀스",
    macSeqDesc:   "쉼표로 구분된 순서로 누를 키를 정의하세요. 예: 1,2,3,4 또는 q,w,e,r,f",
    macRepName:   "반복 간격",
    macRepDesc:   "시퀀스를 반복하기 전 대기 시간. 필요에 따라 설정하세요(초 또는 분).",
    macDelName:   "키 사이 지연",
    macDelDesc:   "시퀀스의 각 키 사이 대기 시간(일반적으로 0.5~2초).",
    macExTitle:   "💡 사용 예시",
    mac1Title:    "<strong>매크로 1 – 반복 자동화:</strong>",
    mac1Li1:      "시퀀스: 1,2,3,space",
    mac1Li2:      "간격: 10초",
    mac1Li3:      "사용: 루프에서 기본 공격 로테이션",
    mac2Title:    "<strong>매크로 2 – 스킬 콤보:</strong>",
    mac2Li1:      "시퀀스: q,w,e,r",
    mac2Li2:      "간격: 30초",
    mac2Li3:      "사용: 최적 DPS 로테이션",
    mac3Title:    "<strong>매크로 3 – 자동 지원:</strong>",
    mac3Li1:      "시퀀스: f,g,h",
    mac3Li2:      "간격: 15초",
    mac3Li3:      "사용: 그룹 시퀀스 또는 주기적 액션",
    perH2:    "🐉 주기적 매크로",
    perDesc:  "이 시스템은 15초마다 자동으로 주기적 액션을 실행합니다. 정기적으로 활성화해야 하는 반복 작업에 이상적입니다.",
    perHowH3:   "작동 원리",
    perHowText: "시스템은 15초마다 이 시퀀스를 자동으로 실행합니다:",
    perLi1:     "주기적 매크로 호출(구성 가능한 키, 기본값 §)",
    perLi2:     "500ms 대기",
    perLi3:     "주기적 매크로 자동 저장",
    perConfigH3:  "설정",
    perCallName:  "호출 키",
    perCallDesc:  "주기적 매크로를 활성화하는 키. 기본값: §. 구성에 따라 변경하세요.",
    perIntName:   "간격(고정)",
    perIntDesc:   "시스템은 항상 고정된 15초 간격을 사용합니다. 구성 불가.",
    perExTitle:   "💡 사용 사례",
    perExText:    "일부 서비스에서는 아이템 수집, 임시 시퀀스 제공 또는 경험치 획득을 위해 주기적 매크로를 정기적으로 호출해야 합니다. 이 시스템은 이 과정을 완전히 자동화합니다.",
    perImpH3:     "⚠️ 중요",
    perImpLi1:    "설정된 키가 호출 키에 해당하는지 확인",
    perImpLi2:    "주기적 매크로는 각 호출 후 자동으로 저장됨",
    perImpLi3:    "다른 시스템(시퀀스, 매크로, 액션)과 병렬로 작동",
    optH2:   "최적화 팁",
    combH3:  "🎯 시스템 결합",
    combDesc:"모든 프리미엄 기능이 동시에 작동합니다. 다음이 가능합니다:",
    combLi1: "자동 시퀀스 + 3개의 매크로 + 주기적 매크로를 동시에 활성화",
    combLi2: "트리거 액션 1과 2는 항상 병렬로 작동",
    combLi3: "각 시스템은 독립적인 타이머를 가짐",
    perfH3:  "⚡ 성능",
    perfLi1: "활성화하는 시스템이 많을수록 확장 프로그램이 더 많은 리소스를 소비",
    perfLi2: "과도하게 빈번한 액션을 피하기 위해 간격 조정",
    perfLi3: "올바른 작동을 확인하기 위해 활동 로그 모니터링",
    secH3:   "🔑 보안",
    secLi1:  "프리미엄 라이선스가 실시간으로 검증됨",
    secLi2:  "연결이 끊어지면 프리미엄 기능이 비활성화됨",
    secLi3:  "모든 기능을 다시 활성화하려면 다시 로그인하세요",
  },

  docTroubleshooting: {
    h1:       "🔧 문제 해결",
    subtitle: "일반적인 문제 해결책과 자주 묻는 질문",
    installH2: "설치 문제",
    faq1Q: "❌ 확장 프로그램이 도구 모음에 나타나지 않음",
    faq1A: "<strong>해결책:</strong><br>1. 확장 프로그램이 <strong>Chrome 웹 스토어</strong>에서 설치되었는지 확인<br>2. 확장 프로그램 고정: 도구 모음의 퍼즐 아이콘 🧩을 클릭하고 Reborn Assistant 고정<br>3. 브라우저 재시작<br>4. 문제가 지속되면 Chrome 웹 스토어에서 확장 프로그램을 제거하고 다시 설치",
    connH2: "연결 문제",
    faq2Q: "❌ \"연결 실패\" 또는 \"유효하지 않은 라이선스\"",
    faq2A: "<strong>가능한 원인:</strong><br>• 불안정한 인터넷 연결<br>• Google Cloud 서버 일시적 사용 불가<br>• 만료되거나 취소된 라이선스<br><br><strong>해결책:</strong><br>1. 인터넷 연결 확인<br>2. Google에서 로그아웃 후 다시 로그인<br>3. Stripe 포털에서 라이선스 상태 확인<br>4. 문제가 지속되면 지원팀에 연락",
    faq3Q: "❌ 프리미엄인데 패널에 \"FREE\"가 표시됨",
    faq3A: "1. Google 계정에서 로그아웃<br>2. 브라우저 완전히 닫기<br>3. 다시 열고 로그인<br>4. 문제가 지속되면 올바른 Google 계정(구매 시 사용한 것)으로 로그인했는지 확인",
    funcH2: "작동 문제",
    faq4Q:     "❌ 타입 1/2 액션이 활성화되지 않음",
    faq4Alert: "<strong>⚠️ 중요</strong><br>타입 1과 2 액션은 <strong>프리미엄 전용</strong> 기능입니다. 타입 1 자동 액션(HP)만 무료 버전에서 사용 가능합니다.",
    faq4Prem:  "<strong>프리미엄이 있는 경우:</strong><br>1. 봇이 시작되었나요? <code>CTRL+A</code><br>2. 트리거 스위치가 활성화되어 있나요? (녹색 «ON» 표시기)<br>3. 설정된 키가 올바른가요?",
    faq5Q:     "❌ 시퀀스/매크로/주기적 매크로/단축키가 작동하지 않음",
    faq5Alert: "<strong>⚠️ 중요</strong><br>키보드 단축키, 시퀀스, 매크로, 주기적 매크로는 <strong>프리미엄 전용</strong> 기능입니다. 무료 버전에서는 타입 1 자동 액션(HP)만 사용 가능합니다.",
    faq5Prem:  "<strong>프리미엄이 있는 경우:</strong><br>1. 프리미엄 라이선스가 활성 상태인지 확인(패널의 💎 아이콘)<br>2. 해당 스위치가 활성화되어 있나요?<br>3. 설정된 간격과 지연 확인",
    faq6Q: "❌ 봇이 스스로 중지됨",
    faq6A: "<strong>가능한 원인:</strong><br>• Google Cloud 연결 끊김<br>• DevTools 감지됨<br>• 페이지 URL 변경됨<br><br><strong>해결책:</strong><br>1. <code>CTRL+A</code>(프리미엄) 또는 패널에서 봇 재시작<br>2. 영향 받은 페이지 새로고침<br>3. 인터넷 연결 확인<br>4. 프리미엄 모드에서 DevTools를 열지 마세요",
    optH2: "최적화 & 성능",
    faq7Q: "💡 봇이 리소스를 너무 많이 소비함",
    faq7A: "<strong>권장 사항:</strong><br>• 매크로와 시퀀스의 간격을 늘리세요(액션이 적을수록 CPU 사용 감소)<br>• 필요하지 않은 시스템 비활성화<br>• 불필요한 탭 닫기<br>• 최적화된 브라우저 사용(Brave, Edge는 Chrome보다 가볍습니다)",
    faq8Q: "💡 설정을 최적화하는 방법은?",
    faq8A: "<strong>권장 설정:</strong><br>• <strong>시퀀스 간격:</strong> 5~25분(시퀀스 지속 시간에 따라)<br>• <strong>키 사이 지연:</strong> 1~2초(오류 방지)<br>• <strong>매크로:</strong> 사용에 따라 10~30초 간격",
    genH2:  "자주 묻는 질문",
    faq9Q:  "❓ 여러 브라우저에서 Reborn을 사용할 수 있나요?",
    faq9A:  "네, 하지만 각 브라우저에 확장 프로그램을 설치해야 합니다. 동일한 Google 계정으로 로그인하는 한 프리미엄 라이선스는 모든 기기에서 작동합니다(최대 1개의 동시 연결).",
    faq10Q: "❓ 내 데이터가 저장되나요?",
    faq10A: "모든 설정(키, 매크로, 테마, 언어)은 브라우저에 <strong>로컬로</strong> 저장됩니다. 세션 간에 유지됩니다. 그러나 확장 프로그램을 제거하면 이 데이터가 손실됩니다.",
    faq11Q: "❓ Reborn이 밴을 유발할 수 있나요?",
    faq11A: "자동화 도구 사용은 일부 서비스의 서비스 약관을 위반할 수 있습니다. Reborn 사용 방법에 대해서는 <strong>귀하만이 책임을 집니다</strong>. 이 도구를 사용하기 전에 서비스의 이용 약관을 확인하세요.",
    faq12Q: "❓ 프리미엄 구독을 취소하는 방법은?",
    faq12A: "Stripe 관리 포털(결제 후 이메일로 받은 링크)에서 언제든지 취소할 수 있습니다. 취소는 현재 기간이 끝날 때 적용됩니다. 취소 수수료 없음.",
    faq13Q: "❓ 서비스가 종료되면 평생 플랜은 어떻게 되나요?",
    faq13A: "평생 플랜은 서비스가 활성 상태인 한 액세스를 보장합니다. 설치 후 확장 프로그램은 로컬로 작동합니다. 라이선스 확인만 인터넷 연결이 필요합니다.",
    supportH2:    "추가 도움이 필요하신가요?",
    supportTitle: "📧 지원",
    supportText:  "문제가 지속되면 이메일로 직접 지원팀에 연락하세요. 메시지에 다음을 포함하세요:<br><br>• 문제에 대한 자세한 설명<br>• 이미 시도한 단계<br>• 관련된 경우 스크린샷<br>• 브라우저 및 운영 체제",
  },

  docPrivacy: {
    h1:       "⚖️ 법적 정보 & 개인정보",
    subtitle: "법적 면책, 법적 고지, 라이선스 조건, 개인정보 보호정책",
    navLegal:  "⚖️ 법적 정보",
    navLicence:"© 라이선스",
    navPrivacy:"🔒 개인정보",
    disclaimerH2:  "⚠️ 법적 면책",
    disclaimerBox: "<strong>⚠️ 중요 공지:</strong> Reborn Assistant는 자동화 도구입니다. 사용이 일부 온라인 서비스의 서비스 약관을 위반할 수 있습니다. 이 도구의 사용은 완전히 자신의 책임입니다.",
    respH3:    "사용자 책임",
    respIntro: "Reborn Assistant를 사용함으로써 귀하는 다음을 인정하고 동의합니다:",
    respLi1:   "이 소프트웨어 사용에 대해 귀하만이 책임을 집니다",
    respLi2:   "이 도구를 사용하기 전에 각 서비스의 이용 약관을 확인합니다",
    respLi3:   "Reborn 사용으로 인한 밴, 계정 제한, 법적 조치에 대해 작성자는 책임을 지지 않습니다",
    respLi4:   "이 소프트웨어를 의식적으로 자신의 위험을 감수하며 사용합니다",
    respLi5:   "이 도구는 다른 사용자의 경험을 해치는 방식으로 사용되어서는 안 됩니다",
    warrantH3:   "보증 없음",
    warrantText: "소프트웨어는 어떠한 보증도 없이 «있는 그대로» 제공됩니다. 작성자는 소프트웨어가 중단 없이 또는 오류 없이 작동하거나 모든 서비스 또는 브라우저와 호환된다는 것을 보장하지 않습니다.",
    legalH2:    "📄 법적 고지",
    copyrightH3:   "저작권 & 지적 재산권",
    copyrightText: "<strong>© 2026 Reborn Assistant – 모든 권리 보유</strong><br><strong>Seymoon</strong> 개발",
    copyrightText2:"이 소프트웨어와 관련된 모든 자료는 작성자의 독점 지적 재산입니다. 서면 허가 없이 복제, 수정, 배포 또는 리버스 엔지니어링은 엄격히 금지됩니다.",
    liabilityH3:   "책임 제한",
    liabilityIntro:"어떠한 경우에도 작성자는 다음을 포함하되 이에 국한되지 않는, 이 소프트웨어의 사용 또는 사용 불가로 인한 청구 또는 손해에 대해 책임을 지지 않습니다:",
    liabilityLi1:  "데이터 또는 사용자 계정 손실",
    liabilityLi2:  "서비스 게시자가 부과한 밴 또는 제한",
    liabilityLi3:  "컴퓨터 시스템 손상",
    liabilityLi4:  "서비스 약관에 맞지 않는 사용으로 인한 법적 결과",
    dataH3:    "개인 데이터",
    dataText:  "Reborn Assistant는 계정 및 라이선스 관리를 위해 Firebase(Google Cloud)를 사용합니다. 수집된 데이터는 인증 및 라이선스 확인 목적으로만 이메일 주소와 계정 식별자로 제한됩니다.",
    dataText2: "<strong>활동 데이터는 수집되거나 전송되지 않습니다.</strong> 설정은 기기에 로컬로 저장됩니다.",
    jurisH3:   "관할권",
    jurisText: "이 계약은 저작권자의 거주지 관할권에서 적용되는 법률에 따릅니다. 이 소프트웨어를 설치하고 사용함으로써 귀하는 이 조건의 전부를 읽고, 이해하고, 수락했음을 인정합니다.",
    licenceH2:     "© 라이선스 조건",
    licenceH3:     "사용 라이선스",
    licenceIntro:  "Reborn Assistant 플랜 구매는 소프트웨어 사용을 위한 개인적, 비독점적, 양도 불가능한 라이선스를 부여합니다.",
    licenceAllows: "<strong>이 라이선스로 허용되는 사항:</strong>",
    licenceLi1:    "개인 목적으로 자신의 기기에서 소프트웨어 사용",
    licenceLi2:    "플랜에 포함된 업데이트 활용",
    licenceForbids:"<strong>이 라이선스로 허용되지 않는 사항:</strong>",
    licenceLi3:    "액세스 재배포, 재판매 또는 공유",
    licenceLi4:    "소프트웨어 수정, 역컴파일 또는 리버스 엔지니어링",
    licenceLi5:    "사전 서면 계약 없이 상업적 목적으로 소프트웨어 사용",
    licenceLi6:    "라이선스를 제3자에게 이전",
    terminationH3:   "해지",
    terminationText: "이 조건을 위반할 경우 라이선스는 즉시 종료될 수 있습니다. 구독 플랜의 경우 Stripe 포털에서 언제든지 취소할 수 있습니다.",
    refundBox: "<strong>✅ 환불 정책:</strong> 구매 후 7일 이내에 만족하지 못하면 전액 환불을 위해 지원팀에 연락하세요. 이 기간이 지나면 예외적인 경우를 제외하고 환불이 불가능합니다.",
    privacyH1:      "🔒 개인정보 보호정책",
    privacySubtitle:"개인 데이터 보호 방법",
    privacyBox:     "<strong>✅ 귀하의 개인정보가 최우선입니다</strong><br>무료 버전: 개인 데이터가 수집되지 않습니다. 프리미엄 버전: 라이선스 확인에 엄격히 필요한 데이터만 처리됩니다.",
    collectH2:        "데이터 수집",
    collectFreeH3:    "무료 버전",
    collectFreeText:  "개인 데이터가 수집되거나 전송되지 않습니다. 모든 기본 설정은 기기에만 저장됩니다.",
    collectPremH3:    "프리미엄 버전",
    collectPremIntro: "라이선스를 확인하고 계정을 보호하기 위해 다음 데이터가 처리됩니다:",
    collectPremLi1:   "Google 이메일 주소(Google 인증을 통해)",
    collectPremLi2:   "고유 기기 식별자(로컬로 생성)",
    collectPremLi3:   "구독 상태 및 세션 타임스탬프",
    collectPremLi4:   "계정당 최대 2개의 등록된 기기",
    collectPremBasis: "<strong>법적 근거:</strong> 계약 이행(GDPR 제6조 1항 b).",
    collectNotH3:     "절대 수집되지 않는 데이터",
    collectNotLi1:    "❌ 게임 또는 활동 데이터 없음",
    collectNotLi2:    "❌ 브라우저 기록 없음",
    collectNotLi3:    "❌ 광고 또는 추적 쿠키 없음",
    localH2:    "로컬에 저장된 데이터",
    localIntro: "다음 정보는 <strong>기기에만</strong> 저장됩니다:",
    localLi1:   "<strong>언어 설정</strong>: 인터페이스 언어 선택",
    localLi2:   "<strong>시각적 테마 선택</strong>: 6개 중 선택한 테마",
    localLi3:   "<strong>설정된 키보드 단축키</strong>: 액션에 할당된 키",
    localLi4:   "<strong>사용자 정의 타이머 간격</strong>: 매크로에 설정된 타이머",
    localLi5:   "<strong>인터페이스 위치</strong>: 화면에서 Reborn 패널의 위치",
    localLi6:   "<strong>라이선스 캐시(프리미엄)</strong>: 매번 시작 시 확인을 피하기 위한 기기 식별자와 구독 상태",
    thirdH2:       "제3자 서비스",
    thirdH3:       "사용된 서비스(프리미엄 버전)",
    thirdDesc:     "인증과 결제를 위해 Reborn Assistant는 다음을 사용합니다:",
    thirdLi1:      "🔐 <strong>Google</strong> — 인증 및 라이선스 데이터의 안전한 저장",
    thirdLi2:      "💳 <strong>Stripe</strong> — 프리미엄 결제 처리(은행 정보가 절대로 서버를 통과하지 않음)",
    thirdTransfer: "이 공급업체들은 GDPR을 준수하며 국제 데이터 전송을 위한 적절한 보호 조치를 갖추고 있습니다.",
    thirdNoH3:     "추적 없음, 광고 없음",
    thirdLi3:      "❌ 분석 또는 통계 서비스 없음",
    thirdLi4:      "❌ 광고 또는 타겟 마케팅 없음",
    thirdLi5:      "❌ 제3자 쿠키 또는 행동 추적 없음",
    authH2:    "인증 및 기기 관리",
    authH3:    "Google로 로그인(프리미엄 버전)",
    authText:  "Google 계정은 신원 인증과 라이선스 확인에만 사용됩니다. 기기는 안전한 시스템에 등록됩니다(계정당 최대 2개의 기기).",
    authText2: "귀하의 계정이 인식되지 않은 기기에서 사용되면 알림을 받습니다. 등록된 기기는 확장 프로그램에서 직접 관리할 수 있습니다.",
    payH2:    "안전한 결제",
    payText:  "프리미엄 결제는 <strong>Stripe</strong>에 의해 처리됩니다. 은행 정보는 <strong>절대로</strong> 서버를 통과하지 않습니다. <strong>신용카드 데이터를 일절 저장하지 않습니다.</strong>",
    retentionH2:   "보존 기간",
    retentionText: "데이터는 필요한 기간 동안만 보존됩니다:",
    retentionLi1:  "<strong>활성 계정:</strong> 구독 기간 전체 동안 데이터 보존",
    retentionLi2:  "<strong>취소 후:</strong> 30일 이내에 삭제",
    retentionLi3:  "<strong>로컬 데이터:</strong> 확장 프로그램 제거 시 즉시 삭제",
    rightsH2:      "귀하의 권리(GDPR)",
    rightsText:    "GDPR에 따라 귀하는 데이터에 관해 다음 권리를 갖습니다:",
    rightsLi1:     "✅ <strong>액세스</strong> — 개인 데이터 사본 받기",
    rightsLi2:     "✅ <strong>수정</strong> — 부정확한 데이터 수정",
    rightsLi3:     "✅ <strong>삭제</strong> — 계정 및 데이터 삭제 요청",
    rightsLi4:     "✅ <strong>이동성</strong> — 읽을 수 있는 형식으로 데이터 받기",
    rightsLi5:     "✅ <strong>민원</strong> — 국가 데이터 보호 기관에 불만 제기",
    rightsExercise:"이 권리를 행사하려면 다음으로 연락하세요: seymoon.cell@gmail.com 또는 Discord(Seymoon)",
    deleteH2:    "데이터 삭제",
    deleteText1: "<strong>1. 확장 프로그램 제거</strong><br>Reborn Assistant를 제거하면 모든 로컬 데이터가 자동으로 삭제됩니다.",
    deleteText2: "<strong>2. 수동 초기화</strong><br>언제든지 Reborn 인터페이스에서 설정을 초기화할 수 있습니다.",
    deleteText3: "<strong>3. 계정 삭제(프리미엄)</strong><br>프리미엄 계정과 관련된 모든 데이터를 삭제하려면 이메일로 문의하세요.",
    contactH2:   "연락처",
    contactText: "법적 정보 또는 개인정보 보호정책에 관한 질문:",
    changelogH2: "📋 변경 로그",
    v130H3:          "버전 1.3.0(2026년 3월) · 현재",
    v130newLabel:    "✨ 새 기능",
    v130improvLabel: "🔧 개선사항",
    v130fixLabel:    "🐛 버그 수정",
    v130Li1:  "⏱ 드래그 가능한 플로팅 미니 타이머 — 버프 타이머와 1분 이상의 타이머를 표시하는 작은 플로팅 창으로, 다음 실행 시 자동으로 다시 열리며 활성 스킨을 따릅니다.",
    v130Li2:  "⚡ 우선순위 매크로 — 매크로가 힐/HP/마나보다 먼저 실행되며, 충돌 방지를 위해 각 실행 전후에 0.5초 힐 프리즈가 적용됩니다.",
    v130Li3:  "🧠 스마트 버프 관리 — 버프가 먼저 실행되고, 무음 매크로는 큐에 들어가 버프 종료 후 자동으로 재시작됩니다 (지연 2초로 단축).",
    v130Li4:  "💾 위치 기억 — 플로팅 창이 세션 간에 위치를 유지합니다.",
    v130Li5:  "🇸🇦 아랍어 지원 — 확장 프로그램에서 사용 가능한 15번째 언어.",
    v130Li6:  "💳 팝업에서 Stripe 결제 — 확장 프로그램을 벗어나지 않고 자동 닫기가 있는 전용 창에서 열립니다.",
    v130Li7:  "🐾 펫: 첫 번째 버프에서 펫이 나오지 않는 버그 수정 + 정지 시 보관을 위한 F1/F2 모드 추적 개선.",
    v130Li8:  "⏱ 타이머: 프리미엄 디자인 비주얼 리워크 + 정지 시 불투명도 55% → 가독성 향상을 위한 호버 시 95%.",
    v130Li9:  "💳 결제 포털: 자동 닫기가 있는 메모리의 단일 활성 창.",
    v130Li10:  "콘텐츠와 팝업에서 여러 메모리 누수를 수정했습니다.",
    v130Li16:  "최대 2기기 제한의 UI 정렬 (백엔드와의 일관성).",
    v120H3:  "버전 1.2.0(2026년 3월)",
    v120Li1: "✨ 6개의 스킨이 미묘한 투명 효과로 재설계되었습니다.",
    v120Li2: "🔐 확장 프로그램에서 직접 등록된 기기를 보고 관리하세요.",
    v120Li3: "💳 확장 프로그램에서 원클릭으로 구독에 액세스.",
    v120Li4: "🔔 다른 기기에서 계정이 사용되면 즉시 알림.",
    v12H3:   "버전 1.2(2026년 2월)",
    v12Li1:  "15개 언어 지원(터키어 🇹🇷 추가)",
    v12Li2:  "웹사이트 비주얼 리디자인",
    v12Li3:  "법적 페이지를 단일 통합 페이지로 통합",
    v12Li4:  "사이트의 완전한 FR/EN 번역",
    v11H3:   "버전 1.1.1(2026년 2월)",
    v11Li1:  "자동 주기적 매크로 추가(15초 + 자동 저장)",
    v11Li2:  "키보드 단축키 CTRL+A / CTRL+O",
    v11Li3:  "15개 언어 지원(필리핀어 + 터키어 추가)",
    v11Li4:  "프리미엄 라이선스 안정성 향상",
    v11Li5:  "시퀀스 로테이션 버그 수정",
    v10H3:   "버전 1.0(2025년) · 초기",
    v10Li1:  "Reborn Assistant 출시",
    v10Li2:  "타입 1과 2 자동 액션",
    v10Li3:  "자동 시퀀스 로테이션(F2 → 1-9 → 0 → F1)",
    v10Li4:  "3개의 사용자 정의 매크로",
    v10Li5:  "6가지 시각적 테마와 12개 언어",
    v10Li6:  "Firebase를 통한 프리미엄 라이선스 시스템",
    pageFooter:"© 2026 Reborn Assistant — Seymoon 개발 · 모든 권리 보유",
  },
  nav: {
    docsFull:    "📚 문서",
    docsShort:   "📚 Docs",
    manageFull:  "구독 관리",
    manageShort: "관리",
  },
};