export default {
  hero: {
    description: "Browser-automatiseringsextensie met geavanceerde macro's. Automatiseer uw herhalende acties, sneltoetsen en reeksen om uw productiviteit te optimaliseren.",
    ctaPrimary: "Nu beginnen",
    ctaSecondary: "Meer weten",
    trust1: "Gratis versie beschikbaar",
    trust2: "Geen verplichtingen",
    trust3: "100% veilige betaling",
    trust4: "Automatische updates",
  },
  features: {
    tag: "Vaardigheden & Competenties",
    titleBefore: "Alles wat ",
    titleEm: "u nodig heeft",
    subtitle: "Ontdek de uitzonderlijke mogelijkheden van Reborn Assistant.",
    card1: { badge: "Actief",  title: "Volledige Automatisering",     description: "Toetsmacro's, automatische reeksen en configureerbare acties voor volledige automatisering." },
    card2: { badge: "Passief", title: "Maximale Veiligheid",          description: "Uw gegevens blijven lokaal. Geen tracking, geen telemetrie." },
    card3: { badge: "Actief",  title: "Aanpasbare Macro's",           description: "3 configureerbare macro's met automatische activatoren en sneltoetsen." },
    card4: { badge: "Passief", title: "Aanpasbare Interface",         description: "Kies uit 6 thema's en pas de interface aan uw behoeften aan." },
    card5: { badge: "Passief", title: "Meertalig",                    description: "Beschikbaar in 15 talen. Wereldwijde ondersteuning met gelokaliseerde interfaces." },
    card6: { badge: "Gratis",  title: "Gratis Versie",                description: "Gratis uitproberen met de ingebouwde basisfuncties." },
  },
  security: {
    tag: "Veiligheid",
    titleBefore: "Beveiliging op ",
    titleEm: "professioneel niveau",
    titleAfter: "",
    description: "Reborn Assistant gebruikt dezelfde beveiligingsstandaarden als wereldwijde streamingplatforms. Uw inloggegevens zijn beschermd door <strong style='color:var(--gold);'>JWT-encryptie</strong>, uw betalingen beveiligd via <strong style='color:var(--gold);'>Stripe</strong>, en uw gegevens blijven <strong style='color:var(--gold);'>100% lokaal</strong>. Geen tracking, geen datadoorverkoop.",
    card1Title: "JWT-encryptie",
    card1Text:  "Veilige authenticatie op bankniveau",
    card2Title: "Betaling met Stripe",
    card2Text:  "Processor gebruikt door Amazon en Google",
    card3Title: "Nul Tracking",
    card3Text:  "Uw gegevens verlaten nooit uw apparaat",
    card4Text:  "Veilige Google Cloud-infrastructuur",
  },
  pricing: {
    tag:         "Kies uw Klasse",
    titleBefore: "Kies uw ",
    titleEm:     "rang",
    subtitle:    "Kies de formule die het beste bij u past. Zonder verplichtingen.",
    voyageur: {
      rank: "Rang I · Reiziger", plan: "Gratis", period: "voor altijd",
      feat1: "Genezingsmacro", feat2: "6 visuele thema's", feat3: "15 talen beschikbaar", feat4: "Zwevende interface",
      btn: "Beginnen", download: "Toevoegen aan Chrome", guarantee: "🔒 Voor altijd gratis",
    },
    aventurier: {
      rank: "Rang II · Avonturier", plan: "Maandelijks", period: "per maand",
      feat1: "Alle Premium functies", feat2: "Prioritaire ondersteuning", feat3: "Gratis updates",
      btn: "Gratis Proberen", guarantee: "🎁 7 dagen gratis · Geen bankkaart vereist",
      download: "Toevoegen aan Chrome",
    },
    champion: {
      badge: "⭐ Populair -17%",
      rank: "Rang III · Kampioen", plan: "Jaarlijks", period: "per jaar · 2,50€/maand",
      feat1: "Alle Premium functies", feat2: "Prioritaire ondersteuning", feat3: "Gratis updates",
      btn: "Gratis Proberen", guarantee: "🎁 7 dagen gratis · Geen bankkaart vereist",
      download: "Toevoegen aan Chrome",
    },
    legende: {
      badge: "⚡ Beperkt Aanbod",
      rank: "Rang IV · Legende", plan: "Levenslang", period: "eenmalige betaling · nooit meer",
      feat1: "Levenslange toegang", feat2: "Alle toekomstige updates", feat3: "Dedicated premium ondersteuning", feat4: "Beste prijs-kwaliteitverhouding",
      btn: "Kopen", guarantee: "🔒 Eenmalige betaling · Levenslange toegang gegarandeerd",
      download: "Toevoegen aan Chrome",
    },
  },
  stats: {
    label1: "Beschikbare talen", label2: "Visuele thema's", label3: "Lokale gegevens", label4: "Actieve extensie",
  },
  trust: {
    badge1: "Veilige SSL-betaling", badge2: "Directe toegang", badge3: "100% privégegevens", badge4: "Reactieve ondersteuning",
  },
  store: {
    status: "Officiële extensie",
    title:  "Beschikbaar in de Chrome Web Store",
    install: "Installeren",
    available: "Gratis beschikbaar · Officiële extensie geverifieerd door Google",
  },
  faq: {
    titleBefore: "Veelgestelde ",
    titleEm:     "vragen",
    subtitle:    "Alles wat u moet weten voordat u begint.",
    q1: "Vereist de gratis proefperiode een bankkaart?",
    a1: "Nee, er is geen bankkaart vereist. De eerste 7 dagen zijn volledig gratis, zonder verplichtingen. Maak gewoon uw account aan om meteen te beginnen.",
    q2: "Kan ik op elk moment van abonnement wisselen?",
    a2: "Ja, u kunt op elk moment upgraden of downgraden via uw account. Geen wisselkosten.",
    q3: "Zijn bij het Levenslang abonnement echt alle toekomstige updates inbegrepen?",
    a3: "Absoluut. Het Levenslang abonnement garandeert u toegang tot alle toekomstige updates en nieuwe functies, zonder extra kosten.",
    q4: "Zijn mijn gegevens veilig?",
    a4: "Al uw gegevens worden lokaal op uw apparaat opgeslagen. We verzamelen geen persoonlijke gegevens en gebruiken geen tracking of telemetrie.",
    q5: "Hoe contact opnemen met de ondersteuning?",
    a5: "Contacteer ons via e-mail op seymoon@constellation-89.fr of op Discord (Seymoon). Premium-abonnees ontvangen een prioritaire reactie.",
    q6: "Is Reborn Assistant een bot?",
    a6: "Nee, Reborn Assistant is geen bot. Het is een extensie met configureerbare macro's die toetsenreeksen automatiseert die je zelf definieert. Geen kunstmatige intelligentie, geen interactie met de gameserver, geen geheugen lezen. De extensie leest of wijzigt geen spelgegevens — het simuleert alleen de toetsen die je handmatig zou indrukken. Je moet bij je computer blijven om te spelen: Reborn Assistant lost geen captcha's op, brengt je personage niet weer tot leven en brengt je na een dood niet terug naar de spot. Het is een tool om je gameplay te vereenvoudigen, niet om jou te vervangen.",
  },
  footer: {
    privacy:   "Privacy",
    terms:     "Gebruiksvoorwaarden",
    copyright: "© 2026 Reborn Assistant. Alle rechten voorbehouden.<br>Ontwikkeld door Seymoon",
  },

  docsNav: {
    backToDocs:      "← Terug naar documentatie",
    mainSite:        "⌂ Hoofdsite",
    backToMainSite:  "← Terug naar hoofdsite",
    footer:          "© 2026 Reborn Assistant — Ontwikkeld door Seymoon · Alle rechten voorbehouden",
  },

  docsHome: {
    version:              "VERSIE 1.3.3 · VOLLEDIGE DOCUMENTATIE",
    userGuide:            "Gebruikershandleiding",
    support:              "Ondersteuning",
    legal:                "Juridische informatie",
    quickstartTitle:      "Snelstart",
    quickstartDesc:       "Installatie, eerste configuratie en eerste stappen met Reborn Assistant.",
    featuresTitle:        "Functionaliteiten",
    featuresDesc:         "Volledig overzicht van de gratis en Premium functies met vergelijkingstabel.",
    premiumTitle:         "Premium Handleiding",
    premiumDesc:          "Automatische reeksen, aanpasbare macro's en periodieke macro.",
    interfaceTitle:       "Interface & Aanpassing",
    interfaceDesc:        "Visuele thema's, talen en aanpassingsopties.",
    troubleshootingTitle: "Probleemoplossing",
    troubleshootingDesc:  "Oplossingen voor veelvoorkomende problemen, veelgestelde vragen en prestatieoptimalisatie.",
    legalTitle:           "Juridisch & Privacy",
    legalDesc:            "Juridische disclaimer, wettelijke vermeldingen, licentievoorwaarden, privacybeleid en wijzigingslogboek.",
    footer:               "© 2026 Reborn Assistant — Ontwikkeld door Seymoon · Alle rechten voorbehouden",
  },

  docFeatures: {
    h1:        "⚡ Functionaliteiten",
    subtitle:  "Ontdek alles wat Reborn Assistant voor u kan doen",
    h2Free:    "GRATIS Functionaliteiten",
    freeBadge: "GRATIS",
    c1Title: "Automatische actie type 1",
    c1Desc:  "Activeert automatisch uw type 1-actie (HP) op basis van een configureerbare timer.",
    c1li1:   "Configureerbare actietimer",
    c1li2:   "Werkt op de achtergrond",
    c2Title: "Visuele thema's",
    c2Desc:  "Pas het uiterlijk van de interface aan met 6 verschillende thema's.",
    c2li1:   "MMO Gold (standaard)",
    c2li2:   "Dark Mode & White Mode",
    c3Title: "Meertalig",
    c3Desc:  "Interface beschikbaar in 15 talen voor een internationale ervaring.",
    c3li3:   "Onmiddellijk wisselen",
    h2Premium: "PREMIUM Functionaliteiten 💎",
    p1Title: "Automatische activator macro 1",
    p1Desc:  "Automatische activering van uw type 1-actie (HP) op basis van een configureerbare timer.",
    p1li1:   "Configureerbare activator 1-timer",
    p1li2:   "Configureerbare sneltoets",
    p1li3:   "Werkt op de achtergrond",
    p2Title: "Automatische activator macro 2",
    p2Desc:  "Automatisch gebruik van uw type 2-acties op basis van een configureerbare timer.",
    p2li1:   "Configureerbare activator 2-timer",
    p2li2:   "Configureerbare sneltoets",
    p2li3:   "Werkt op de achtergrond",
    p3Title: "Sneltoetsen",
    p3Desc:  "Beheer Reborn Assistant direct met aanpasbare globale sneltoetsen.",
    p3li1:   "CTRL+A: Start de automatisering",
    p3li2:   "CTRL+O: Stop de automatisering",
    p4Title: "Reeksrotatie",
    p4Desc:  "Automatisch reeksonderhoudssysteem met een voorgedefinieerde reeks.",
    p4li1:   "Reeks: F2 → 1-9 → 0 → F1",
    p4li2:   "Configureerbaar interval (minuten)",
    p4li3:   "Instelbare vertraging tussen toetsen",
    p5Title: "Aanpasbare Macro's",
    p5Desc:  "Maak tot 3 macro's met uw eigen toetsreeksen.",
    p5li1:   "3 onafhankelijke macro's",
    p5li2:   "Aangepaste reeksen",
    p5li3:   "Instelbare herhalingsintervallen",
    p6Title: "Periodieke macro",
    p6Desc:  "Automatisch oproepen en opslaan van uw periodieke macro elke 15 seconden.",
    p6li1:   "Automatisch oproepen van periodieke macro",
    p6li2:   "Auto-opslaan na oproep",
    p6li3:   "Vast interval van 15 seconden",
    tableH2:      "Vergelijkingstabel",
    tableFeature: "Functionaliteit",
    tableFree:    "Gratis",
    row1:  "Automatische type 1-actie (HP)",
    row2:  "Visuele thema's (6)",
    row3:  "Meertalig (15)",
    row4:  "Automatische activator macro 1",
    row5:  "Automatische activator macro 2",
    row6:  "Sneltoetsen (CTRL+A / CTRL+O)",
    row7:  "Automatische reeksrotatie",
    row8:  "Aanpasbare macro's (3x)",
    row9:  "Automatische periodieke macro",
    learnMore: "→ Meer informatie over Premium-functies",
  },

  docQuickstart: {
    h1:       "🚀 Snelstart",
    subtitle: "Installeer en configureer Reborn Assistant in enkele minuten",
    reqH2:    "Vereisten",
    req1:     "<strong>Compatibele browser:</strong> Google Chrome, Microsoft Edge, Brave of elke op Chromium gebaseerde browser",
    req2:     "<strong>Google-account:</strong> Alleen vereist voor Premium-authenticatie (optioneel voor gratis versie)",
    req3:     "<strong>Compatibele site:</strong> Compatibel met standaard websites",
    installH2:  "Installatie",
    step1Title: "Bezoek de Chrome Web Store",
    step1p:     "Ga naar de pagina van Reborn Assistant in de <a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome Web Store</a> en klik op <strong>«Toevoegen aan Chrome»</strong>.",
    step1tip:   "💡 Compatibel met Google Chrome, Microsoft Edge, Brave en elke op Chromium gebaseerde browser.",
    step2Title: "Bevestig de installatie",
    step2p:     "Klik op <strong>«Extensie toevoegen»</strong> in het bevestigingsvenster. De extensie wordt automatisch geïnstalleerd.",
    step3Title: "Extensie vastzetten",
    step3p:     "Klik op het puzzelicoon 🧩 in de werkbalk van uw browser en zet Reborn Assistant vast voor snelle toegang.",
    step4Title: "Aanmelden (optioneel voor Premium)",
    step4p:     "• Klik op het Reborn-icoon in de werkbalk<br>• Voor Premium: Meld u aan met uw Google-account<br>• Voor Gratis: Gebruik het direct zonder aanmelden",
    alertTitle: "✅ Installatie geslaagd!",
    alertText:  "Het Reborn-icoon wordt groen wanneer de extensie actief is. U kunt nu uw functies configureren.",
    configH2:   "Eerste configuratie",
    freeH3:     "GRATIS Versie",
    freeTitle:  "<strong>Functies beschikbaar zonder aanmelden:</strong>",
    freeText:   "• Automatische type 1-actie (alleen HP)<br>• 6 visuele thema's<br>• Ondersteuning voor 15 talen",
    freeStepTitle: "Configuratie van de automatische type 1-actie",
    freeStepText:  "1. Open het Reborn-paneel (klik op het icoon)<br>2. Stel de HP-actietimer in (standaard: 2s)<br>3. De actie wordt automatisch geactiveerd<br>4. Geen aanmelding vereist",
    premiumH3:       "PREMIUM Versie 💎",
    premiumFeatTitle:"<strong>Extra functies (vereist aanmelden met Google):</strong>",
    premiumFeatText: "• Automatische activator macro 1 (configureerbare timer + sneltoets)<br>• Automatische activator macro 2 (configureerbare timer + sneltoets)<br>• Sneltoetsen (CTRL+A / CTRL+O)<br>• Automatische reeksrotatie (F2 → 1-9 → 0 → F1)<br>• 3 aanpasbare macro's met toetsreeksen<br>• Automatisch periodiek macrosysteem (oproep + opslaan elke 15s)",
    premConfigTitle: "Premium Configuratie",
    premConfigSeq:   "<strong>Automatische reeksen:</strong><br>• Activeer «Reeksrotatie» in het paneel<br>• Stel het interval tussen cycli in (standaard: 5 min)<br>• Pas de vertraging tussen elke toets aan (standaard: 1s)",
    premConfigMacro: "<strong>Macro's:</strong><br>• Activeer Macro 1, 2 of 3<br>• Definieer de toetsreeks (bijv. <code>1,2,3,4</code>)<br>• Stel het herhalingsinterval in",
    premConfigPer:   "<strong>Periodieke macro:</strong><br>• Activeer de schakelaar «Periodieke macro»<br>• Het systeem roept automatisch uw periodieke macro elke 15s op<br>• Automatisch opslaan na de oproep",
    warnTitle: "⚠️ Belangrijke opmerking",
    warnText:  "De Premium-functies (Activatormacro's 1 en 2, Automatische reeksen, Automatische periodieke macro, 3 configureerbare macro's) vereisen een geldige Premium-licentie en een Google-aanmelding. Zonder licentie is alleen de basismacro beschikbaar.",
    shortcutsH2:   "Sneltoetsen",
    shortcutsText: "<code>CTRL + A</code>: Start de automatisering<br><code>CTRL + O</code>: Stop de automatisering",
    nextH2: "Volgende stappen",
    link1:  "Ontdek alle functionaliteiten",
    link2:  "Volledige Premium handleiding",
    link3:  "Oplossingen voor veelvoorkomende problemen",
  },

  docInterface: {
    h1:       "🎨 Interface & Aanpassing",
    subtitle: "Pas Reborn Assistant aan naar uw voorkeuren",
    themesH2:    "Visuele thema's",
    themesDesc:  "Reborn Assistant biedt 6 thema's om het uiterlijk van de interface aan te passen:",
    changeThemeH3:   "Thema wijzigen",
    changeThemeText: "1. Open het Reborn-paneel<br>2. Klik op het tabblad \"⚙️ INSTELLINGEN\"<br>3. Selecteer uw thema in het vervolgkeuzemenu<br>4. De wijziging is onmiddellijk",
    langsH2:    "Beschikbare talen",
    langsDesc:  "Interface beschikbaar in 15 talen:",
    changeLangH3:   "Taal wijzigen",
    changeLangText: "1. Open het Reborn-paneel<br>2. Klik op \"⚙️ INSTELLINGEN\"<br>3. Selecteer uw taal in het vervolgkeuzemenu<br>4. De volledige interface wordt onmiddellijk vertaald",
    shortcutsH2:   "Sneltoetsen",
    shortcutsDesc: "Reborn Assistant bevat globale sneltoetsen voor snel beheer:",
    systemH3: "Systeemsneltoetsen",
    sysSC1:   "<code>CTRL + A</code>: Start de automatisering",
    sysSC2:   "<code>CTRL + O</code>: Stop de automatisering",
    customH3:   "Aanpasbare sneltoetsen",
    customDesc: "U kunt de toetsen configureren voor:",
    customLi1:  "Type 1 en 2 acties",
    customLi2:  "Macro's (toetsreeksen)",
    customLi3:  "Periodieke macro",
    displayH2:    "Weergaveopties",
    panelPosH3:   "Paneelpositie",
    panelPosDesc: "Het Reborn-paneel is versleepbaar:",
    panelLi1: "Klik op de paneelkoptekst",
    panelLi2: "Houd ingedrukt en sleep",
    panelLi3: "Laat los op de gewenste locatie",
    panelLi4: "De positie wordt automatisch opgeslagen",
    opacityH3:   "Paneeldoorzichtigheid",
    opacityDesc: "Pas de transparantie aan om niet te interfereren met uw navigatie terwijl u uw statistieken beheert.",
    logH3:   "Activiteitslogboek",
    logDesc: "Het logboek toont in realtime alle uitgevoerde acties:",
    logLi1:  "Activering/deactivering van systemen",
    logLi2:  "Gebruik van drankjes",
    logLi3:  "Uitvoering van macro's en reeksen",
    logLi4:  "Oproepen van de periodieke macro",
    logLi5:  "Mogelijke fouten",
    saveH2:    "Opslaan van instellingen",
    saveDesc:  "Al uw instellingen worden automatisch lokaal opgeslagen:",
    saveLi1:   "Geselecteerd thema",
    saveLi2:   "Interfacetaal",
    saveLi3:   "Activeringsdrempels",
    saveLi4:   "Toegewezen toetsen",
    saveLi5:   "Macroconfiguratie",
    saveLi6:   "Paneelpositie",
    savePersist: "Blijven bewaard tussen sessies, zelfs na het sluiten van de browser.",
  },

  docPremium: {
    h1:       "💎 Premium Handleiding",
    subtitle: "Beheers alle geavanceerde functies van Reborn Assistant",
    rotH2:    "🛡️ Automatische reeksrotatie",
    rotDesc:  "Het rotatiesysteem houdt automatisch al uw reeksen actief door op regelmatige intervallen een voorgedefinieerde toetsreeks in te drukken.",
    rotSeqH3:   "Toetsreeks",
    rotSeqText: "De rotatie volgt altijd deze vaste volgorde:",
    rotConfigH3:   "Configuratie",
    rotIntName:    "Interval tussen cycli",
    rotIntDesc:    "Wachttijd voor het herstarten van de volledige reeks. Standaard: 5 minuten. Pas aan op basis van de duur van uw kortste reeksen.",
    rotDelName:    "Vertraging tussen toetsen",
    rotDelDesc:    "Wachttijd tussen elke toets van de reeks. Standaard: 1 seconde. Pas aan op basis van de servicesnelheid (animaties, cooldowns...).",
    rotExTitle:    "💡 Gebruiksvoorbeeld",
    rotExScenario: "<strong>Scenario:</strong> Uw reeksen duren 5 minuten en u heeft 8 reeksen op toetsen 1-8.",
    rotExConfig:   "<strong>Configuratie:</strong>",
    rotExLi1:      "Interval: 5 minuten",
    rotExLi2:      "Vertraging: 1 seconde",
    rotExLi3:      "De extensie drukt elke 5 minuten op F2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1",
    rotExLi4:      "13 toetsen totaal met 1 seconde ertussen = ~13 seconden per cyclus",
    macH2:    "⚙️ Aanpasbare Macro's",
    macDesc:  "Maak tot 3 onafhankelijke macro's met uw eigen toetsreeksen. Ideaal voor het automatiseren van repetitieve taken, terugkerende combo's of vaardigheidsrotaties.",
    macHowH3:   "Werking",
    macHowText: "Elke macro voert een toetsreeks uit op regelmatige intervallen, onafhankelijk van de andere systemen.",
    macConfigH3:  "Configuratie",
    macSeqName:   "Toetsreeks",
    macSeqDesc:   "Definieer de in te drukken toetsen op volgorde, gescheiden door komma's. Voorbeeld: 1,2,3,4 of q,w,e,r,f",
    macRepName:   "Herhalingsinterval",
    macRepDesc:   "Wachttijd voor het herhalen van de reeks. Configureer naar uw behoeften (seconden of minuten).",
    macDelName:   "Vertraging tussen toetsen",
    macDelDesc:   "Wachttijd tussen elke toets van de reeks (doorgaans 0,5 tot 2 seconden).",
    macExTitle:   "💡 Gebruiksvoorbeelden",
    mac1Title:    "<strong>Macro 1 – Repetitieve automatisering:</strong>",
    mac1Li1:      "Reeks: 1,2,3,space",
    mac1Li2:      "Interval: 10 seconden",
    mac1Li3:      "Gebruik: Basisaanvalsrotatie in lus",
    mac2Title:    "<strong>Macro 2 – Vaardigheidcombo:</strong>",
    mac2Li1:      "Reeks: q,w,e,r",
    mac2Li2:      "Interval: 30 seconden",
    mac2Li3:      "Gebruik: Optimale DPS-rotatie",
    mac3Title:    "<strong>Macro 3 – Automatische ondersteuning:</strong>",
    mac3Li1:      "Reeks: f,g,h",
    mac3Li2:      "Interval: 15 seconden",
    mac3Li3:      "Gebruik: Groepsreeksen of periodieke acties",
    perH2:    "🐉 Periodieke macro",
    perDesc:  "Dit systeem voert automatisch een periodieke actie uit elke 15 seconden. Ideaal voor repetitieve taken die regelmatig moeten worden geactiveerd.",
    perHowH3:   "Werking",
    perHowText: "Het systeem voert automatisch deze reeks elke 15 seconden uit:",
    perLi1:     "Roept de periodieke macro op (configureerbare toets, standaard §)",
    perLi2:     "Wacht 500ms",
    perLi3:     "Slaat de periodieke macro automatisch op",
    perConfigH3:  "Configuratie",
    perCallName:  "Oproeptoets",
    perCallDesc:  "De toets die uw periodieke macro activeert. Standaard: §. Pas aan op basis van uw configuratie.",
    perIntName:   "Interval (vast)",
    perIntDesc:   "Het systeem gebruikt altijd een vast interval van 15 seconden. Niet configureerbaar.",
    perExTitle:   "💡 Gebruiksgeval",
    perExText:    "In sommige services moet de periodieke macro regelmatig worden opgeroepen om items te verzamelen, tijdelijke reeksen te bieden of ervaring te verdienen. Dit systeem automatiseert dit proces volledig.",
    perImpH3:     "⚠️ Belangrijk",
    perImpLi1:    "Controleer of de geconfigureerde toets overeenkomt met uw oproeptoets",
    perImpLi2:    "De periodieke macro wordt automatisch opgeslagen na elke oproep",
    perImpLi3:    "Werkt parallel met de andere systemen (reeksen, macro's, acties)",
    optH2:   "Optimalisatietips",
    combH3:  "🎯 Systeemcombinatie",
    combDesc:"Alle Premium-functies werken tegelijkertijd. U kunt:",
    combLi1: "Automatische reeksen + 3 macro's + periodieke macro tegelijk activeren",
    combLi2: "Activatoracties 1 &amp; 2 werken altijd parallel",
    combLi3: "Elk systeem heeft zijn eigen onafhankelijke timer",
    perfH3:  "⚡ Prestaties",
    perfLi1: "Hoe meer systemen u activeert, hoe meer resources de extensie verbruikt",
    perfLi2: "Pas intervallen aan om te frequente acties te vermijden",
    perfLi3: "Controleer het activiteitslogboek om correct functioneren te verifiëren",
    secH3:   "🔑 Beveiliging",
    secLi1:  "Uw Premium-licentie wordt in realtime geverifieerd",
    secLi2:  "Als de verbinding verbroken wordt, worden Premium-functies uitgeschakeld",
    secLi3:  "Meld u opnieuw aan om alle functies te heractiveren",
  },

  docTroubleshooting: {
    h1:       "🔧 Probleemoplossing",
    subtitle: "Oplossingen voor veelvoorkomende problemen en veelgestelde vragen",
    installH2: "Installatieproblemen",
    faq1Q: "❌ De extensie verschijnt niet in de werkbalk",
    faq1A: "<strong>Oplossingen:</strong><br>1. Controleer of de extensie geïnstalleerd is via de <strong>Chrome Web Store</strong><br>2. Zet de extensie vast: klik op het puzzelicoon 🧩 in de werkbalk en zet Reborn Assistant vast<br>3. Herstart uw browser<br>4. Als het probleem aanhoudt, verwijder dan de extensie en installeer deze opnieuw via de Chrome Web Store",
    connH2: "Verbindingsproblemen",
    faq2Q: "❌ \"Verbinding mislukt\" of \"Ongeldige licentie\"",
    faq2A: "<strong>Mogelijke oorzaken:</strong><br>• Slechte internetverbinding<br>• Google Cloud-servers tijdelijk niet beschikbaar<br>• Verlopen of ingetrokken licentie<br><br><strong>Oplossingen:</strong><br>1. Controleer uw internetverbinding<br>2. Meld u af en opnieuw aan met Google<br>3. Controleer de status van uw licentie in uw Stripe-portaal<br>4. Neem contact op met de ondersteuning als het probleem aanhoudt",
    faq3Q: "❌ Het paneel toont \"FREE\" terwijl ik Premium heb",
    faq3A: "1. Meld u af van uw Google-account<br>2. Sluit de browser volledig<br>3. Open opnieuw en meld u aan<br>4. Als het probleem aanhoudt, controleer dan of u bent aangemeld met het juiste Google-account (gebruikt voor de aankoop)",
    funcH2: "Functioneringsproblemen",
    faq4Q:     "❌ Type 1/2-acties worden niet geactiveerd",
    faq4Alert: "<strong>⚠️ BELANGRIJK</strong><br>Type 1 en 2-acties zijn <strong>EXCLUSIEF PREMIUM</strong>-functies. Alleen de automatische type 1-actie (HP) is beschikbaar in de gratis versie.",
    faq4Prem:  "<strong>Als je Premium hebt:</strong><br>1. Is de automatisering actief? <code>CTRL+A</code><br>2. Zijn de trigger-toggles ingeschakeld? (groene indicator «ON»)<br>3. Zijn de geconfigureerde toetsen correct?",
    faq5Q:     "❌ Reeksen / macro's / periodieke macro / sneltoetsen werken niet",
    faq5Alert: "<strong>⚠️ BELANGRIJK</strong><br>Sneltoetsen, reeksen, macro's en periodieke macro zijn <strong>EXCLUSIEF PREMIUM</strong>-functies. In de gratis versie is alleen de automatische type 1-actie (HP) beschikbaar.",
    faq5Prem:  "<strong>Als u Premium heeft:</strong><br>1. Controleer of uw Premium-licentie actief is (💎-icoon in het paneel)<br>2. Zijn de bijbehorende schakelaars ingeschakeld?<br>3. Controleer de geconfigureerde intervallen en vertragingen",
    faq6Q: "❌ De automatisering stopt vanzelf",
    faq6A: "<strong>Mogelijke oorzaken:</strong><br>• Verloren Google Cloud-verbinding<br>• DevTools-detectie<br>• Pagina-URL gewijzigd<br><br><strong>Oplossingen:</strong><br>1. Herstart de automatisering met <code>CTRL+A</code> (Premium) of via het paneel<br>2. Herlaad de betreffende pagina<br>3. Controleer je internetverbinding<br>4. Open geen DevTools als je Premium hebt",
    optH2: "Optimalisatie & Prestaties",
    faq7Q: "💡 De extensie gebruikt te veel bronnen",
    faq7A: "<strong>Aanbevelingen:</strong><br>• Vergroot de intervallen van macro's en reeksen (minder acties = minder CPU)<br>• Deactiveer systemen die u niet nodig heeft<br>• Sluit onnodige tabbladen<br>• Gebruik een geoptimaliseerde browser (Brave, Edge zijn lichter dan Chrome)",
    faq8Q: "💡 Hoe de configuratie optimaliseren?",
    faq8A: "<strong>Aanbevolen configuratie:</strong><br>• <strong>Reeksinterval:</strong> 5-25 minuten (afhankelijk van de duur van uw reeksen)<br>• <strong>Vertraging tussen toetsen:</strong> 1-2 seconden (vermijdt fouten)<br>• <strong>Macro's:</strong> Intervallen van 10-30s afhankelijk van het gebruik",
    genH2:  "Veelgestelde Vragen",
    faq9Q:  "❓ Kan ik Reborn op meerdere browsers gebruiken?",
    faq9A:  "Ja, maar u moet de extensie op elke browser installeren. Uw Premium-licentie werkt op al uw apparaten zolang u aangemeld bent met hetzelfde Google-account (max. 1 gelijktijdige verbinding).",
    faq10Q: "❓ Worden mijn gegevens opgeslagen?",
    faq10A: "Al uw instellingen (toetsen, macro's, thema, taal) worden <strong>lokaal</strong> in de browser opgeslagen. Ze blijven bewaard tussen sessies. Als u echter de extensie verwijdert, verliest u deze gegevens.",
    faq11Q: "❓ Kan Reborn een ban veroorzaken?",
    faq11A: "Het gebruik van automatiseringstools kan de Servicevoorwaarden van sommige services schenden. <strong>U bent als enige verantwoordelijk</strong> voor hoe u Reborn gebruikt. Raadpleeg de gebruiksvoorwaarden van de service voordat u deze tool gebruikt.",
    faq12Q: "❓ Hoe mijn Premium-abonnement opzeggen?",
    faq12A: "U kunt op elk moment opzeggen via uw Stripe-beheerportaal (link ontvangen per e-mail na betaling). De opzegging heeft effect aan het einde van uw huidige periode. Geen opzegkosten.",
    faq13Q: "❓ Wat gebeurt er met het Levenslang abonnement als de service sluit?",
    faq13A: "Het Levenslang abonnement garandeert toegang zolang de service actief is. Eenmaal geïnstalleerd werkt de extensie lokaal; alleen de licentieverificatie vereist een internetverbinding.",
    supportH2:    "Meer hulp nodig?",
    supportTitle: "📧 Ondersteuning",
    supportText:  "Als uw probleem aanhoudt, neem dan rechtstreeks contact op met de ondersteuning via e-mail. Vermeld in uw bericht:<br><br>• Een gedetailleerde beschrijving van het probleem<br>• De stappen die u al heeft geprobeerd<br>• Screenshots indien relevant<br>• Uw browser en besturingssysteem",
  },

  docPrivacy: {
    h1:       "⚖️ Juridisch & Privacy",
    subtitle: "Juridische disclaimer, wettelijke vermeldingen, licentievoorwaarden en privacybeleid",
    navLegal:  "⚖️ Juridische Informatie",
    navLicence:"© Licentie",
    navPrivacy:"🔒 Privacy",
    disclaimerH2:  "⚠️ Juridische Disclaimer",
    disclaimerBox: "<strong>⚠️ Belangrijke mededeling:</strong> Reborn Assistant is een automatiseringstool. Het gebruik ervan kan de Servicevoorwaarden van bepaalde online services schenden. Het gebruik van deze tool is volledig op eigen risico.",
    respH3:    "Gebruikersverantwoordelijkheid",
    respIntro: "Door Reborn Assistant te gebruiken, erkent en aanvaardt u dat:",
    respLi1:   "U als enige verantwoordelijk bent voor het gebruik van deze software",
    respLi2:   "U de gebruiksvoorwaarden van elke service zult controleren voordat u deze tool gebruikt",
    respLi3:   "De auteur niet aansprakelijk kan worden gesteld voor enig verbod, accountbeperking of juridische actie als gevolg van het gebruik van Reborn",
    respLi4:   "U deze software bewust en op eigen risico gebruikt",
    respLi5:   "Deze tool niet mag worden gebruikt op een manier die de ervaring van andere gebruikers schaadt",
    warrantH3:   "Geen garantie",
    warrantText: "De software wordt geleverd «ZOALS ZE IS» zonder enige garantie. De auteur garandeert niet dat de software ononderbroken of foutloos zal werken, noch dat deze compatibel is met alle services of browsers.",
    legalH2:    "📄 Wettelijke Vermeldingen",
    copyrightH3:   "Auteursrecht & Intellectuele Eigendom",
    copyrightText: "<strong>© 2026 Reborn Assistant – Alle rechten voorbehouden</strong><br>Ontwikkeld door <strong>Seymoon</strong>",
    copyrightText2:"Deze software en alle bijbehorende materialen zijn het exclusieve intellectuele eigendom van de auteur. Elke reproductie, wijziging, distributie of reverse engineering zonder schriftelijke toestemming is strikt verboden.",
    liabilityH3:   "Beperking van aansprakelijkheid",
    liabilityIntro:"In geen geval is de auteur aansprakelijk voor enige claim of schade voortvloeiend uit het gebruik of de onmogelijkheid om deze software te gebruiken, inclusief maar niet beperkt tot:",
    liabilityLi1:  "Verlies van gegevens of gebruikersaccount",
    liabilityLi2:  "Verboden of beperkingen opgelegd door service-uitgevers",
    liabilityLi3:  "Schade aan informaticasystemen",
    liabilityLi4:  "Juridische gevolgen voortvloeiend uit gebruik dat niet conform de servicevoorwaarden is",
    dataH3:    "Persoonsgegevens",
    dataText:  "Reborn Assistant gebruikt Firebase (Google Cloud) voor account- en licentiebeheer. De verzamelde gegevens beperken zich tot uw e-mailadres en account-ID, uitsluitend voor authenticatie en licentieverificatie.",
    dataText2: "<strong>Er worden geen activiteitsgegevens verzameld of verzonden.</strong> Uw instellingen blijven lokaal op uw apparaat opgeslagen.",
    jurisH3:   "Jurisdictie",
    jurisText: "Deze overeenkomst wordt beheerst door het toepasselijke recht in de jurisdictie van de woonplaats van de auteursrechthebbende. Door deze software te installeren en te gebruiken, erkent u deze voorwaarden te hebben gelezen, begrepen en aanvaard.",
    licenceH2:     "© Licentievoorwaarden",
    licenceH3:     "Gebruikslicentie",
    licenceIntro:  "De aankoop van een Reborn Assistant-abonnement verleent u een persoonlijke, niet-exclusieve en niet-overdraagbare licentie om de software te gebruiken.",
    licenceAllows: "<strong>Deze licentie staat u toe om:</strong>",
    licenceLi1:    "De software te gebruiken voor persoonlijke doeleinden op uw eigen apparaten",
    licenceLi2:    "Te profiteren van de updates die zijn inbegrepen in uw abonnement",
    licenceForbids:"<strong>Deze licentie staat u niet toe om:</strong>",
    licenceLi3:    "Uw toegang te herverdelen, door te verkopen of te delen",
    licenceLi4:    "De software te wijzigen, te decompileren of te reverse-engineeren",
    licenceLi5:    "De software te gebruiken voor commerciële doeleinden zonder voorafgaande schriftelijke overeenkomst",
    licenceLi6:    "Uw licentie over te dragen aan een derde partij",
    terminationH3:   "Beëindiging",
    terminationText: "De licentie kan onmiddellijk worden beëindigd bij schending van deze voorwaarden. Voor abonnementen kunt u op elk moment opzeggen via uw Stripe-portaal.",
    refundBox: "<strong>✅ Terugbetalingsbeleid:</strong> Als u niet tevreden bent binnen 7 dagen na uw aankoop, neem dan contact op met onze ondersteuning voor volledige terugbetaling. Na deze periode wordt geen terugbetaling meer verleend, behalve in uitzonderlijke gevallen.",
    privacyH1:      "🔒 Privacybeleid",
    privacySubtitle:"Hoe wij uw persoonsgegevens beschermen",
    privacyBox:     "<strong>✅ Uw privacy is onze prioriteit</strong><br>Gratis versie: er worden geen persoonsgegevens verzameld. Premium versie: alleen de strikt noodzakelijke gegevens voor het verifiëren van uw licentie worden verwerkt.",
    collectH2:        "Gegevensverzameling",
    collectFreeH3:    "Gratis Versie",
    collectFreeText:  "Er worden geen persoonsgegevens verzameld of verzonden. Al uw voorkeuren worden uitsluitend op uw apparaat opgeslagen.",
    collectPremH3:    "Premium Versie",
    collectPremIntro: "Om uw licentie te verifiëren en uw account te beschermen, worden de volgende gegevens verwerkt:",
    collectPremLi1:   "Uw Google e-mailadres (via Google-authenticatie)",
    collectPremLi2:   "Een uniek apparaat-ID (lokaal gegenereerd)",
    collectPremLi3:   "Uw abonnementsstatus en sessie-tijdstempels",
    collectPremLi4:   "Maximaal 2 geregistreerde apparaten per account",
    collectPremBasis: "<strong>Rechtsgrondslag:</strong> uitvoering van de overeenkomst (art. 6.1.b AVG).",
    collectNotH3:     "Nooit verzamelde gegevens",
    collectNotLi1:    "❌ Geen spel- of activiteitsgegevens",
    collectNotLi2:    "❌ Geen browsergeschiedenis",
    collectNotLi3:    "❌ Geen advertentie- of trackingcookies",
    localH2:    "Lokaal opgeslagen gegevens",
    localIntro: "De volgende informatie wordt <strong>uitsluitend op uw apparaat</strong> opgeslagen:",
    localLi1:   "<strong>Taalvoorkeuren</strong>: Uw keuze van interfacetaal",
    localLi2:   "<strong>Visuele thema-selectie</strong>: Het gekozen thema uit de 6 beschikbare",
    localLi3:   "<strong>Geconfigureerde sneltoetsen</strong>: De toegewezen toetsen voor uw acties",
    localLi4:   "<strong>Aangepaste timer-intervallen</strong>: De geconfigureerde timers voor uw macro's",
    localLi5:   "<strong>Interfacepositie</strong>: De locatie van het Reborn-paneel op uw scherm",
    localLi6:   "<strong>Licentiecache (Premium)</strong>: apparaat-ID en abonnementsstatus, om verificatie bij elke start te vermijden",
    thirdH2:       "Diensten van derden",
    thirdH3:       "Gebruikte diensten (Premium versie)",
    thirdDesc:     "Voor authenticatie en betalingen gebruikt Reborn Assistant:",
    thirdLi1:      "🔐 <strong>Google</strong> — Authenticatie en veilige opslag van licentiegegevens",
    thirdLi2:      "💳 <strong>Stripe</strong> — Verwerking van Premium-betalingen (uw bankgegevens passeren nooit onze servers)",
    thirdTransfer: "Deze providers voldoen aan de AVG en beschikken over passende waarborgen voor internationale gegevensoverdrachten.",
    thirdNoH3:     "Geen tracking, geen reclame",
    thirdLi3:      "❌ Geen analyse- of statistiekdiensten",
    thirdLi4:      "❌ Geen reclame of gerichte marketing",
    thirdLi5:      "❌ Geen cookies van derden of gedragsvolging",
    authH2:    "Authenticatie en apparaatbeheer",
    authH3:    "Aanmelden met Google (Premium versie)",
    authText:  "Uw Google-account wordt uitsluitend gebruikt om uw identiteit te authenticeren en uw licentie te verifiëren. Uw apparaat wordt geregistreerd in ons beveiligde systeem (maximaal 2 apparaten per account).",
    authText2: "U ontvangt een melding als uw account wordt gebruikt op een onbekend apparaat. U kunt uw geregistreerde apparaten rechtstreeks via de extensie beheren.",
    payH2:    "Veilige Betalingen",
    payText:  "Premium-betalingen worden verwerkt door <strong>Stripe</strong>. Uw bankgegevens passeren <strong>nooit</strong> onze servers. We slaan <strong>geen</strong> creditcardgegevens op.",
    retentionH2:   "Bewaartermijn",
    retentionText: "Uw gegevens worden slechts zo lang bewaard als noodzakelijk:",
    retentionLi1:  "<strong>Actief account:</strong> gegevens bewaard gedurende de volledige abonnementsduur",
    retentionLi2:  "<strong>Na opzegging:</strong> verwijdering binnen 30 dagen",
    retentionLi3:  "<strong>Lokale gegevens:</strong> onmiddellijk verwijderd bij het verwijderen van de extensie",
    rightsH2:      "Uw rechten (AVG)",
    rightsText:    "Conform de AVG heeft u de volgende rechten met betrekking tot uw gegevens:",
    rightsLi1:     "✅ <strong>Inzage</strong> — Een kopie van uw persoonsgegevens verkrijgen",
    rightsLi2:     "✅ <strong>Rectificatie</strong> — Onjuiste gegevens corrigeren",
    rightsLi3:     "✅ <strong>Verwijdering</strong> — Verzoeken om verwijdering van uw account en gegevens",
    rightsLi4:     "✅ <strong>Overdraagbaarheid</strong> — Uw gegevens ontvangen in een leesbaar formaat",
    rightsLi5:     "✅ <strong>Klacht</strong> — Een klacht indienen bij de gegevensbeschermingsautoriteit van uw land",
    rightsExercise:"Om deze rechten uit te oefenen, neem contact met ons op: seymoon@constellation-89.fr of op Discord (Seymoon)",
    deleteH2:    "Verwijdering van uw gegevens",
    deleteText1: "<strong>1. De extensie verwijderen</strong><br>Bij het verwijderen van Reborn Assistant worden alle lokale gegevens automatisch verwijderd.",
    deleteText2: "<strong>2. Handmatige reset</strong><br>U kunt de instellingen op elk moment resetten via de Reborn-interface.",
    deleteText3: "<strong>3. Account verwijderen (Premium)</strong><br>Om uw Premium-account en alle bijbehorende gegevens te verwijderen, neem contact met ons op via e-mail.",
    contactH2:   "Contact",
    contactText: "Voor vragen over juridische informatie of privacybeleid:",
    changelogH2: "📋 Wijzigingslogboek",
    v130H3:          "Versie 1.3.0 (Maart 2026) · Huidig",
    v130newLabel:    "✨ Nieuw",
    v130improvLabel: "🔧 Verbeteringen",
    v130fixLabel:    "🐛 Bugfixes",
    v130Li1:  "⏱ Versleepbare zwevende mini-timer — klein zwevend venster dat buff-timers en timers boven 1 minuut weergeeft, opent automatisch opnieuw bij de volgende start en volgt de actieve skin.",
    v130Li2:  "⚡ Prioriteitsmacro's — macro's worden uitgevoerd vóór heals/HP/mana, met een 0,5s heal-blokkering voor en na elke uitvoering om conflicten te vermijden.",
    v130Li3:  "🧠 Slim buff-beheer — buff wordt eerst uitgevoerd, gedemute macro's worden in de wachtrij gezet en automatisch herstart na afloop (vertraging verlaagd naar 2s).",
    v130Li4:  "💾 Positieopslag — zwevende vensters onthouden hun positie tussen sessies.",
    v130Li5:  "🇸🇦 Arabische ondersteuning — 15e taal beschikbaar in de extensie.",
    v130Li6:  "💳 Stripe-betaling in popup — opent in een speciaal venster met automatische sluiting, zonder de extensie te verlaten.",
    v130Li7:  "🐾 Huisdier: bug opgelost waarbij het huisdier niet uitkwam bij de eerste buff + betere F1/F2-modusregistratie voor opslag bij stoppen.",
    v130Li8:  "⏱ Timer: visuele herontwerp van het premium-ontwerp + dekking 55% in rust → 95% bij hover voor betere leesbaarheid.",
    v130Li9:  "💳 Factureringsportal: één actief venster in het geheugen met automatische sluiting.",
    v130Li10:  "Meerdere geheugenlekkages in de content en popup opgelost.",
    v130Li16:  "UI-uitlijning op het maximum van 2 apparaten (consistentie met de backend).",
    v120H3:  "Versie 1.2.0 (Maart 2026)",
    v120Li1: "✨ De 6 skins zijn opnieuw ontworpen met een subtiel transparantie-effect.",
    v120Li2: "🔐 Bekijk en beheer uw geregistreerde apparaat rechtstreeks via de extensie.",
    v120Li3: "💳 Toegang tot uw abonnement met één klik via de extensie.",
    v120Li4: "🔔 Onmiddellijke melding als uw account op een ander apparaat wordt gebruikt.",
    v12H3:   "Versie 1.2 (Februari 2026)",
    v12Li1:  "Ondersteuning voor 15 talen (Turks 🇹🇷 toegevoegd)",
    v12Li2:  "Visueel herontwerp van de website",
    v12Li3:  "Samenvoeging van juridische pagina's in één uniforme pagina",
    v12Li4:  "Volledige FR/EN-vertaling van de site",
    v11H3:   "Versie 1.1.1 (Februari 2026)",
    v11Li1:  "Automatische periodieke macro toegevoegd (15s + auto-opslaan)",
    v11Li2:  "Sneltoetsen CTRL+A / CTRL+O",
    v11Li3:  "Ondersteuning voor 15 talen (Filipijns + Turks toegevoegd)",
    v11Li4:  "Verbeterde stabiliteit van Premium-licentie",
    v11Li5:  "Bugfixes in reeksrotatie",
    v10H3:   "Versie 1.0 (2025) · Initieel",
    v10Li1:  "Lancering van Reborn Assistant",
    v10Li2:  "Automatische type 1 en 2-acties",
    v10Li3:  "Automatische reeksrotatie (F2 → 1-9 → 0 → F1)",
    v10Li4:  "3 aanpasbare macro's",
    v10Li5:  "6 visuele thema's en 12 talen",
    v10Li6:  "Premium-licentiesysteem via Firebase",
    pageFooter:"© 2026 Reborn Assistant — Ontwikkeld door Seymoon · Alle rechten voorbehouden",
  },
  nav: {
    docsFull:    "📚 Documentatie",
    docsShort:   "📚 Docs",
    manageFull:  "Abonnement beheren",
    manageShort: "Beheren",
  },
};