export default {
  hero: {
    description: "Rozszerzenie automatyzacji przeglądarki z zaawansowanymi makrami. Automatyzuj powtarzające się czynności, skróty i sekwencje, aby zoptymalizować swoją produktywność.",
    ctaPrimary: "Zacznij teraz",
    ctaSecondary: "Dowiedz się więcej",
    trust1: "Dostępna wersja darmowa",
    trust2: "Bez zobowiązań",
    trust3: "100% bezpieczna płatność",
    trust4: "Automatyczne aktualizacje",
  },
  features: {
    tag: "Umiejętności & Możliwości",
    titleBefore: "Wszystko, czego ",
    titleEm: "potrzebujesz",
    subtitle: "Odkryj wyjątkowe możliwości Reborn Assistant.",
    card1: { badge: "Aktywny",  title: "Pełna Automatyzacja",        description: "Makra klawiszy, automatyczne sekwencje i konfigurowalne akcje dla kompletnej automatyzacji." },
    card2: { badge: "Pasywny",  title: "Maksymalne Bezpieczeństwo",  description: "Twoje dane pozostają lokalne. Bez śledzenia, bez telemetrii." },
    card3: { badge: "Aktywny",  title: "Konfigurowalne Makra",       description: "3 konfigurowalne makra z automatycznymi wyzwalaczami i skrótami klawiszowymi." },
    card4: { badge: "Pasywny",  title: "Konfigurowalny Interfejs",   description: "Wybierz spośród 6 motywów i dostosuj interfejs do swoich potrzeb." },
    card5: { badge: "Pasywny",  title: "Wielojęzyczny",              description: "Dostępny w 15 językach. Wsparcie na całym świecie z zlokalizowanymi interfejsami." },
    card6: { badge: "Darmowy",  title: "Darmowa Wersja",             description: "Wypróbuj za darmo z podstawowymi funkcjami w zestawie." },
  },
  security: {
    tag: "Bezpieczeństwo",
    titleBefore: "Bezpieczeństwo na poziomie ",
    titleEm: "profesjonalnym",
    titleAfter: "",
    description: "Reborn Assistant stosuje te same standardy bezpieczeństwa co światowe platformy streamingowe. Twoje dane uwierzytelniające są chronione przez <strong style='color:var(--gold);'>szyfrowanie JWT</strong>, płatności zabezpieczone przez <strong style='color:var(--gold);'>Stripe</strong>, a dane pozostają <strong style='color:var(--gold);'>w 100% lokalne</strong>. Bez śledzenia, bez odsprzedaży danych.",
    card1Title: "Szyfrowanie JWT",
    card1Text:  "Bezpieczne uwierzytelnianie na poziomie bankowym",
    card2Title: "Płatność przez Stripe",
    card2Text:  "Procesor używany przez Amazon i Google",
    card3Title: "Zero Śledzenia",
    card3Text:  "Twoje dane nigdy nie opuszczają Twojego urządzenia",
    card4Text:  "Bezpieczna infrastruktura Google Cloud",
  },
  pricing: {
    tag:         "Wybierz swoją Klasę",
    titleBefore: "Wybierz swoją ",
    titleEm:     "rangę",
    subtitle:    "Wybierz formułę, która najbardziej Ci odpowiada. Bez zobowiązań.",
    voyageur: {
      rank: "Ranga I · Podróżnik", plan: "Darmowy", period: "na zawsze",
      feat1: "Makro leczenia", feat2: "6 motywów wizualnych", feat3: "15 dostępnych języków", feat4: "Pływający interfejs",
      btn: "Zacznij", download: "Dodaj do Chrome", guarantee: "🔒 Darmowy na zawsze",
    },
    aventurier: {
      rank: "Ranga II · Przygodnik", plan: "Miesięczny", period: "miesięcznie",
      feat1: "Wszystkie funkcje Premium", feat2: "Priorytetowe wsparcie", feat3: "Darmowe aktualizacje",
      btn: "Wypróbuj Za Darmo", guarantee: "🎁 7 dni za darmo · Bez karty bankowej",
      download: "Dodaj do Chrome",
    },
    champion: {
      badge: "⭐ Popularny -17%",
      rank: "Ranga III · Mistrz", plan: "Roczny", period: "rocznie · 2,50€/mies.",
      feat1: "Wszystkie funkcje Premium", feat2: "Priorytetowe wsparcie", feat3: "Darmowe aktualizacje",
      btn: "Wypróbuj Za Darmo", guarantee: "🎁 7 dni za darmo · Bez karty bankowej",
      download: "Dodaj do Chrome",
    },
    legende: {
      badge: "⚡ Oferta Limitowana",
      rank: "Ranga IV · Legenda", plan: "Dożywotni", period: "jednorazowa płatność · już nigdy",
      feat1: "Dostęp dożywotni", feat2: "Wszystkie przyszłe aktualizacje", feat3: "Dedykowane wsparcie premium", feat4: "Najlepsza relacja jakość-cena",
      btn: "Kup", guarantee: "🔒 Jednorazowa płatność · Gwarantowany dostęp dożywotni",
      download: "Dodaj do Chrome",
    },
  },
  stats: {
    label1: "Dostępne języki", label2: "Motywy wizualne", label3: "Dane lokalne", label4: "Aktywne rozszerzenie",
  },
  trust: {
    badge1: "Bezpieczna płatność SSL", badge2: "Natychmiastowy dostęp", badge3: "Dane w 100% prywatne", badge4: "Reaktywne wsparcie",
  },
  store: {
    status: "Oficjalne rozszerzenie",
    title:  "Dostępne w Chrome Web Store",
    install: "Zainstaluj",
    available: "Dostępne za darmo · Oficjalne rozszerzenie zweryfikowane przez Google",
  },
  faq: {
    titleBefore: "Często zadawane ",
    titleEm:     "pytania",
    subtitle:    "Wszystko, co musisz wiedzieć przed rozpoczęciem.",
    q1: "Czy bezpłatny okres próbny wymaga karty bankowej?",
    a1: "Nie, żadna karta bankowa nie jest wymagana. Pierwsze 7 dni jest całkowicie bezpłatne, bez zobowiązań. Wystarczy założyć konto, aby natychmiast zacząć.",
    q2: "Czy mogę zmienić plan w dowolnym momencie?",
    a2: "Tak, możesz przejść na wyższy lub niższy plan w dowolnym momencie ze swojego konta. Bez opłat za zmianę.",
    q3: "Czy plan Dożywotni naprawdę obejmuje wszystkie przyszłe aktualizacje?",
    a3: "Absolutnie. Plan Dożywotni gwarantuje dostęp do wszystkich przyszłych aktualizacji i nowych funkcji, bez żadnych dodatkowych opłat.",
    q4: "Czy moje dane są bezpieczne?",
    a4: "Wszystkie Twoje dane są przechowywane lokalnie na Twoim urządzeniu. Nie zbieramy danych osobowych ani nie używamy śledzenia czy telemetrii.",
    q5: "Jak skontaktować się z pomocą techniczną?",
    a5: "Skontaktuj się z nami przez e-mail na adres seymoon@constellation-89.fr lub na Discordzie (Seymoon). Subskrybenci premium otrzymują priorytetową odpowiedź.",
    q6: "Czy Reborn Assistant to bot?",
    a6: "Nie, Reborn Assistant nie jest botem. To rozszerzenie z konfigurowalnymi makrami, które automatyzuje sekwencje klawiszy zdefiniowane przez Ciebie. Bez sztucznej inteligencji, bez interakcji z serwerem gry, bez odczytu pamięci. Rozszerzenie nie odczytuje ani nie modyfikuje danych gry — symuluje tylko klawisze, które wcisnąłbyś ręcznie. Musisz pozostać przy komputerze, aby grać: Reborn Assistant nie rozwiązuje captcha, nie wskrzesza Twojej postaci ani nie odsyła Cię z powrotem do miejsca po śmierci. To narzędzie do uproszczenia gry, a nie do zastąpienia Ciebie.",
  },
  footer: {
    privacy:   "Prywatność",
    terms:     "Warunki Użytkowania",
    copyright: "© 2026 Reborn Assistant. Wszelkie prawa zastrzeżone.<br>Opracowany przez Seymoon",
  },

  docsNav: {
    backToDocs:      "← Powrót do dokumentacji",
    mainSite:        "⌂ Strona główna",
    backToMainSite:  "← Powrót do strony głównej",
    footer:          "© 2026 Reborn Assistant — Opracowany przez Seymoon · Wszelkie prawa zastrzeżone",
  },

  docsHome: {
    version:              "WERSJA 1.3.3 · PEŁNA DOKUMENTACJA",
    userGuide:            "Przewodnik użytkownika",
    support:              "Wsparcie",
    legal:                "Informacje prawne",
    quickstartTitle:      "Szybki Start",
    quickstartDesc:       "Instalacja, konfiguracja początkowa i pierwsze kroki z Reborn Assistant.",
    featuresTitle:        "Funkcjonalności",
    featuresDesc:         "Pełny opis darmowych i Premium funkcji z tabelą porównawczą.",
    premiumTitle:         "Przewodnik Premium",
    premiumDesc:          "Automatyczne sekwencje, konfigurowalne makra i makro okresowe.",
    interfaceTitle:       "Interfejs & Personalizacja",
    interfaceDesc:        "Motywy wizualne, języki i opcje personalizacji.",
    troubleshootingTitle: "Rozwiązywanie problemów",
    troubleshootingDesc:  "Rozwiązania typowych problemów, często zadawane pytania i optymalizacja wydajności.",
    legalTitle:           "Prawne & Prywatność",
    legalDesc:            "Zastrzeżenie prawne, wzmianki prawne, warunki licencji, polityka prywatności i dziennik zmian.",
    footer:               "© 2026 Reborn Assistant — Opracowany przez Seymoon · Wszelkie prawa zastrzeżone",
  },

  docFeatures: {
    h1:        "⚡ Funkcjonalności",
    subtitle:  "Odkryj wszystko, co Reborn Assistant może dla Ciebie zrobić",
    h2Free:    "DARMOWE Funkcjonalności",
    freeBadge: "DARMOWY",
    c1Title: "Automatyczna akcja typu 1",
    c1Desc:  "Automatycznie aktywuje akcję typu 1 (HP) na podstawie konfigurowalnego timera.",
    c1li1:   "Konfigurowalny timer akcji",
    c1li2:   "Działa w tle",
    c2Title: "Motywy wizualne",
    c2Desc:  "Dostosuj wygląd interfejsu za pomocą 6 różnych motywów.",
    c2li1:   "MMO Gold (domyślny)",
    c2li2:   "Dark Mode & White Mode",
    c3Title: "Wielojęzyczny",
    c3Desc:  "Interfejs dostępny w 15 językach dla międzynarodowego doświadczenia.",
    c3li3:   "Natychmiastowe przełączanie",
    h2Premium: "PREMIUM Funkcjonalności 💎",
    p1Title: "Automatyczne makro wyzwalacza 1",
    p1Desc:  "Automatyczna aktywacja akcji typu 1 (HP) na podstawie konfigurowalnego timera.",
    p1li1:   "Konfigurowalny timer wyzwalacza 1",
    p1li2:   "Konfigurowalny skrót klawiszowy",
    p1li3:   "Działa w tle",
    p2Title: "Automatyczne makro wyzwalacza 2",
    p2Desc:  "Automatyczne używanie akcji typu 2 na podstawie konfigurowalnego timera.",
    p2li1:   "Konfigurowalny timer wyzwalacza 2",
    p2li2:   "Konfigurowalny skrót klawiszowy",
    p2li3:   "Działa w tle",
    p3Title: "Skróty klawiszowe",
    p3Desc:  "Steruj Reborn Assistant w locie za pomocą konfigurowalnych skrótów globalnych.",
    p3li1:   "CTRL+A: Uruchom automatyzację",
    p3li2:   "CTRL+O: Zatrzymaj automatyzację",
    p4Title: "Rotacja sekwencji",
    p4Desc:  "Automatyczny system utrzymywania sekwencji z predefiniowaną sekwencją.",
    p4li1:   "Sekwencja: F2 → 1-9 → 0 → F1",
    p4li2:   "Konfigurowalny interwał (minuty)",
    p4li3:   "Regulowane opóźnienie między klawiszami",
    p5Title: "Konfigurowalne Makra",
    p5Desc:  "Twórz do 3 makr z własnymi sekwencjami klawiszy.",
    p5li1:   "3 niezależne makra",
    p5li2:   "Niestandardowe sekwencje",
    p5li3:   "Regulowane interwały powtarzania",
    p6Title: "Makro okresowe",
    p6Desc:  "Automatyczne wywoływanie i zapisywanie makra okresowego co 15 sekund.",
    p6li1:   "Automatyczne wywołanie makra okresowego",
    p6li2:   "Auto-zapisywanie po wywołaniu",
    p6li3:   "Stały interwał 15 sekund",
    tableH2:      "Tabela porównawcza",
    tableFeature: "Funkcjonalność",
    tableFree:    "Darmowy",
    row1:  "Automatyczna akcja typu 1 (HP)",
    row2:  "Motywy wizualne (6)",
    row3:  "Wielojęzyczny (15)",
    row4:  "Automatyczne makro wyzwalacza 1",
    row5:  "Automatyczne makro wyzwalacza 2",
    row6:  "Skróty klawiszowe (CTRL+A / CTRL+O)",
    row7:  "Automatyczna rotacja sekwencji",
    row8:  "Konfigurowalne makra (3x)",
    row9:  "Automatyczne makro okresowe",
    learnMore: "→ Dowiedz się więcej o funkcjach Premium",
  },

  docQuickstart: {
    h1:       "🚀 Szybki Start",
    subtitle: "Zainstaluj i skonfiguruj Reborn Assistant w kilka minut",
    reqH2:    "Wymagania",
    req1:     "<strong>Kompatybilna przeglądarka:</strong> Google Chrome, Microsoft Edge, Brave lub dowolna przeglądarka oparta na Chromium",
    req2:     "<strong>Konto Google:</strong> Wymagane tylko do uwierzytelnienia Premium (opcjonalne dla wersji darmowej)",
    req3:     "<strong>Kompatybilna strona:</strong> Kompatybilna ze standardowymi stronami internetowymi",
    installH2:  "Instalacja",
    step1Title: "Odwiedź Chrome Web Store",
    step1p:     "Przejdź do strony Reborn Assistant w <a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome Web Store</a> i kliknij <strong>«Dodaj do Chrome»</strong>.",
    step1tip:   "💡 Kompatybilny z Google Chrome, Microsoft Edge, Brave i dowolną przeglądarką opartą na Chromium.",
    step2Title: "Potwierdź instalację",
    step2p:     "Kliknij <strong>«Dodaj rozszerzenie»</strong> w oknie potwierdzenia. Rozszerzenie zostanie zainstalowane automatycznie.",
    step3Title: "Przypnij rozszerzenie",
    step3p:     "Kliknij ikonę puzzli 🧩 na pasku narzędzi przeglądarki, a następnie przypnij Reborn Assistant dla szybkiego dostępu.",
    step4Title: "Logowanie (opcjonalne dla Premium)",
    step4p:     "• Kliknij ikonę Reborn na pasku narzędzi<br>• Dla Premium: Zaloguj się na swoje konto Google<br>• Dla Darmowego: Używaj bezpośrednio bez logowania",
    alertTitle: "✅ Instalacja zakończona sukcesem!",
    alertText:  "Ikona Reborn zmienia kolor na zielony, gdy rozszerzenie jest aktywne. Możesz teraz skonfigurować swoje funkcje.",
    configH2:   "Konfiguracja początkowa",
    freeH3:     "Wersja DARMOWA",
    freeTitle:  "<strong>Funkcje dostępne bez logowania:</strong>",
    freeText:   "• Automatyczna akcja typu 1 (tylko HP)<br>• 6 motywów wizualnych<br>• Obsługa 15 języków",
    freeStepTitle: "Konfiguracja automatycznej akcji typu 1",
    freeStepText:  "1. Otwórz panel Reborn (kliknij ikonę)<br>2. Dostosuj timer akcji HP (domyślnie: 2s)<br>3. Akcja aktywuje się automatycznie<br>4. Logowanie nie jest wymagane",
    premiumH3:       "Wersja PREMIUM 💎",
    premiumFeatTitle:"<strong>Dodatkowe funkcje (wymaga logowania Google):</strong>",
    premiumFeatText: "• Automatyczne makro wyzwalacza 1 (konfigurowalny timer + skrót)<br>• Automatyczne makro wyzwalacza 2 (konfigurowalny timer + skrót)<br>• Skróty klawiszowe (CTRL+A / CTRL+O)<br>• Automatyczna rotacja sekwencji (F2 → 1-9 → 0 → F1)<br>• 3 konfigurowalne makra z sekwencjami klawiszy<br>• Automatyczny system makra okresowego (wywołanie + zapisywanie co 15s)",
    premConfigTitle: "Konfiguracja Premium",
    premConfigSeq:   "<strong>Automatyczne sekwencje:</strong><br>• Aktywuj «Rotację Sekwencji» w panelu<br>• Skonfiguruj interwał między cyklami (domyślnie: 5 min)<br>• Dostosuj opóźnienie między każdym klawiszem (domyślnie: 1s)",
    premConfigMacro: "<strong>Makra:</strong><br>• Aktywuj Makro 1, 2 lub 3<br>• Zdefiniuj sekwencję klawiszy (np. <code>1,2,3,4</code>)<br>• Skonfiguruj interwał powtarzania",
    premConfigPer:   "<strong>Makro okresowe:</strong><br>• Aktywuj przełącznik «Makro okresowe»<br>• System automatycznie wywołuje makro okresowe co 15s<br>• Automatyczne zapisywanie po wywołaniu",
    warnTitle: "⚠️ Ważna uwaga",
    warnText:  "Funkcje Premium (Makra wyzwalaczy 1 i 2, Automatyczne sekwencje, Automatyczne makro okresowe, 3 konfigurowalne makra) wymagają ważnej licencji Premium i logowania Google. Bez licencji dostępne jest tylko podstawowe makro.",
    shortcutsH2:   "Skróty klawiszowe",
    shortcutsText: "<code>CTRL + A</code>: Uruchom automatyzację<br><code>CTRL + O</code>: Zatrzymaj automatyzację",
    nextH2: "Kolejne kroki",
    link1:  "Odkryj wszystkie funkcjonalności",
    link2:  "Pełny przewodnik Premium",
    link3:  "Rozwiązania typowych problemów",
  },

  docInterface: {
    h1:       "🎨 Interfejs & Personalizacja",
    subtitle: "Dostosuj Reborn Assistant do swoich preferencji",
    themesH2:    "Motywy wizualne",
    themesDesc:  "Reborn Assistant oferuje 6 motywów do personalizacji wyglądu interfejsu:",
    changeThemeH3:   "Zmiana motywu",
    changeThemeText: "1. Otwórz panel Reborn<br>2. Kliknij zakładkę \"⚙️ USTAWIENIA\"<br>3. Wybierz motyw z menu rozwijanego<br>4. Zmiana jest natychmiastowa",
    langsH2:    "Dostępne języki",
    langsDesc:  "Interfejs dostępny w 15 językach:",
    changeLangH3:   "Zmiana języka",
    changeLangText: "1. Otwórz panel Reborn<br>2. Kliknij \"⚙️ USTAWIENIA\"<br>3. Wybierz język z menu rozwijanego<br>4. Cały interfejs zostaje natychmiast przetłumaczony",
    shortcutsH2:   "Skróty klawiszowe",
    shortcutsDesc: "Reborn Assistant zawiera globalne skróty do szybkiego sterowania:",
    systemH3: "Skróty systemowe",
    sysSC1:   "<code>CTRL + A</code>: Uruchom automatyzację",
    sysSC2:   "<code>CTRL + O</code>: Zatrzymaj automatyzację",
    customH3:   "Konfigurowalne skróty",
    customDesc: "Możesz skonfigurować klawisze dla:",
    customLi1:  "Akcji typu 1 i 2",
    customLi2:  "Makr (sekwencje klawiszy)",
    customLi3:  "Makra okresowego",
    displayH2:    "Opcje wyświetlania",
    panelPosH3:   "Pozycja panelu",
    panelPosDesc: "Panel Reborn można przeciągać:",
    panelLi1: "Kliknij nagłówek panelu",
    panelLi2: "Przytrzymaj i przeciągnij",
    panelLi3: "Upuść w żądanym miejscu",
    panelLi4: "Pozycja jest zapisywana automatycznie",
    opacityH3:   "Przezroczystość panelu",
    opacityDesc: "Dostosuj przezroczystość, aby nie zakłócać nawigacji podczas zarządzania statystykami.",
    logH3:   "Dziennik aktywności",
    logDesc: "Dziennik wyświetla w czasie rzeczywistym wszystkie wykonane akcje:",
    logLi1:  "Aktywacja/dezaktywacja systemów",
    logLi2:  "Użycie mikstur",
    logLi3:  "Wykonanie makr i sekwencji",
    logLi4:  "Wywołania makra okresowego",
    logLi5:  "Możliwe błędy",
    saveH2:    "Zapisywanie ustawień",
    saveDesc:  "Wszystkie ustawienia są automatycznie zapisywane lokalnie:",
    saveLi1:   "Wybrany motyw",
    saveLi2:   "Język interfejsu",
    saveLi3:   "Progi aktywacji",
    saveLi4:   "Przypisane klawisze",
    saveLi5:   "Konfiguracja makr",
    saveLi6:   "Pozycja panelu",
    savePersist: "Zachowywane między sesjami, nawet po zamknięciu przeglądarki.",
  },

  docPremium: {
    h1:       "💎 Przewodnik Premium",
    subtitle: "Opanuj wszystkie zaawansowane funkcje Reborn Assistant",
    rotH2:    "🛡️ Automatyczna rotacja sekwencji",
    rotDesc:  "System rotacji automatycznie utrzymuje wszystkie sekwencje aktywne, naciskając predefiniowaną sekwencję klawiszy w regularnych odstępach czasu.",
    rotSeqH3:   "Sekwencja klawiszy",
    rotSeqText: "Rotacja zawsze przebiega w tej stałej kolejności:",
    rotConfigH3:   "Konfiguracja",
    rotIntName:    "Interwał między cyklami",
    rotIntDesc:    "Czas oczekiwania przed ponownym uruchomieniem całej sekwencji. Domyślnie: 5 minut. Dostosuj do czasu trwania najkrótszych sekwencji.",
    rotDelName:    "Opóźnienie między klawiszami",
    rotDelDesc:    "Czas oczekiwania między każdym klawiszem sekwencji. Domyślnie: 1 sekunda. Dostosuj do szybkości serwisu (animacje, cooldowny...).",
    rotExTitle:    "💡 Przykład użycia",
    rotExScenario: "<strong>Scenariusz:</strong> Twoje sekwencje trwają 5 minut i masz 8 sekwencji na klawiszach 1-8.",
    rotExConfig:   "<strong>Konfiguracja:</strong>",
    rotExLi1:      "Interwał: 5 minut",
    rotExLi2:      "Opóźnienie: 1 sekunda",
    rotExLi3:      "Rozszerzenie naciśnie F2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1 co 5 minut",
    rotExLi4:      "13 klawiszy łącznie z 1 sekundą między każdym = ~13 sekund na cykl",
    macH2:    "⚙️ Konfigurowalne Makra",
    macDesc:  "Twórz do 3 niezależnych makr z własnymi sekwencjami klawiszy. Idealne do automatyzowania powtarzalnych zadań, powracających combo lub rotacji umiejętności.",
    macHowH3:   "Działanie",
    macHowText: "Każde makro wykonuje sekwencję klawiszy w regularnych odstępach czasu, niezależnie od innych systemów.",
    macConfigH3:  "Konfiguracja",
    macSeqName:   "Sekwencja klawiszy",
    macSeqDesc:   "Zdefiniuj klawisze do naciśnięcia w kolejności, oddzielone przecinkami. Przykład: 1,2,3,4 lub q,w,e,r,f",
    macRepName:   "Interwał powtarzania",
    macRepDesc:   "Czas oczekiwania przed powtórzeniem sekwencji. Skonfiguruj według potrzeb (sekundy lub minuty).",
    macDelName:   "Opóźnienie między klawiszami",
    macDelDesc:   "Czas oczekiwania między każdym klawiszem sekwencji (zwykle 0,5 do 2 sekund).",
    macExTitle:   "💡 Przykłady użycia",
    mac1Title:    "<strong>Makro 1 – Automatyzacja powtarzalna:</strong>",
    mac1Li1:      "Sekwencja: 1,2,3,space",
    mac1Li2:      "Interwał: 10 sekund",
    mac1Li3:      "Użycie: Rotacja podstawowych ataków w pętli",
    mac2Title:    "<strong>Makro 2 – Combo umiejętności:</strong>",
    mac2Li1:      "Sekwencja: q,w,e,r",
    mac2Li2:      "Interwał: 30 sekund",
    mac2Li3:      "Użycie: Optymalna rotacja DPS",
    mac3Title:    "<strong>Makro 3 – Automatyczne wsparcie:</strong>",
    mac3Li1:      "Sekwencja: f,g,h",
    mac3Li2:      "Interwał: 15 sekund",
    mac3Li3:      "Użycie: Sekwencje grupowe lub akcje okresowe",
    perH2:    "🐉 Makro okresowe",
    perDesc:  "System automatycznie wykonuje akcję okresową co 15 sekund. Idealny do powtarzalnych zadań, które muszą być regularnie aktywowane.",
    perHowH3:   "Działanie",
    perHowText: "System automatycznie wykonuje tę sekwencję co 15 sekund:",
    perLi1:     "Wywołuje makro okresowe (konfigurowalny klawisz, domyślnie §)",
    perLi2:     "Czeka 500ms",
    perLi3:     "Automatycznie zapisuje makro okresowe",
    perConfigH3:  "Konfiguracja",
    perCallName:  "Klawisz wywołania",
    perCallDesc:  "Klawisz aktywujący makro okresowe. Domyślnie: §. Zmień zgodnie z konfiguracją.",
    perIntName:   "Interwał (stały)",
    perIntDesc:   "System zawsze używa stałego interwału 15 sekund. Nie konfigurowalny.",
    perExTitle:   "💡 Przypadek użycia",
    perExText:    "W niektórych serwisach makro okresowe musi być regularnie wywoływane, aby zbierać przedmioty, dostarczać tymczasowe sekwencje lub zdobywać doświadczenie. System ten całkowicie automatyzuje ten proces.",
    perImpH3:     "⚠️ Ważne",
    perImpLi1:    "Sprawdź, czy skonfigurowany klawisz odpowiada klawiszowi wywołania",
    perImpLi2:    "Makro okresowe jest automatycznie zapisywane po każdym wywołaniu",
    perImpLi3:    "Działa równolegle z innymi systemami (sekwencje, makra, akcje)",
    optH2:   "Wskazówki optymalizacji",
    combH3:  "🎯 Łączenie systemów",
    combDesc:"Wszystkie funkcje Premium działają jednocześnie. Możesz:",
    combLi1: "Aktywować automatyczne sekwencje + 3 makra + makro okresowe jednocześnie",
    combLi2: "Akcje wyzwalaczy 1 i 2 zawsze działają równolegle",
    combLi3: "Każdy system ma własny niezależny timer",
    perfH3:  "⚡ Wydajność",
    perfLi1: "Im więcej systemów aktywujesz, tym więcej zasobów zużywa rozszerzenie",
    perfLi2: "Dostosuj interwały, aby unikać zbyt częstych akcji",
    perfLi3: "Monitoruj dziennik aktywności, aby zweryfikować prawidłowe działanie",
    secH3:   "🔑 Bezpieczeństwo",
    secLi1:  "Licencja Premium jest weryfikowana w czasie rzeczywistym",
    secLi2:  "Jeśli połączenie zostanie utracone, funkcje Premium są dezaktywowane",
    secLi3:  "Zaloguj się ponownie, aby reaktywować wszystkie funkcje",
  },

  docTroubleshooting: {
    h1:       "🔧 Rozwiązywanie problemów",
    subtitle: "Rozwiązania typowych problemów i często zadawane pytania",
    installH2: "Problemy z instalacją",
    faq1Q: "❌ Rozszerzenie nie pojawia się na pasku narzędzi",
    faq1A: "<strong>Rozwiązania:</strong><br>1. Sprawdź, czy rozszerzenie jest zainstalowane z <strong>Chrome Web Store</strong><br>2. Przypnij rozszerzenie: kliknij ikonę puzzli 🧩 na pasku narzędzi i przypnij Reborn Assistant<br>3. Uruchom ponownie przeglądarkę<br>4. Jeśli problem nadal występuje, odinstaluj i ponownie zainstaluj rozszerzenie z Chrome Web Store",
    connH2: "Problemy z połączeniem",
    faq2Q: "❌ \"Połączenie nieudane\" lub \"Nieprawidłowa licencja\"",
    faq2A: "<strong>Możliwe przyczyny:</strong><br>• Słabe połączenie internetowe<br>• Serwery Google Cloud tymczasowo niedostępne<br>• Wygasła lub odwołana licencja<br><br><strong>Rozwiązania:</strong><br>1. Sprawdź połączenie internetowe<br>2. Wyloguj się i zaloguj ponownie przez Google<br>3. Sprawdź status licencji w portalu Stripe<br>4. Skontaktuj się z pomocą techniczną, jeśli problem nadal występuje",
    faq3Q: "❌ Panel pokazuje \"FREE\" mimo posiadania Premium",
    faq3A: "1. Wyloguj się z konta Google<br>2. Całkowicie zamknij przeglądarkę<br>3. Otwórz ponownie i zaloguj się<br>4. Jeśli problem nadal występuje, sprawdź, czy jesteś zalogowany na właściwe konto Google (użyte przy zakupie)",
    funcH2: "Problemy z działaniem",
    faq4Q:     "❌ Akcje typu 1/2 nie są aktywowane",
    faq4Alert: "<strong>⚠️ WAŻNE</strong><br>Akcje typu 1 i 2 są funkcjami <strong>WYŁĄCZNIE PREMIUM</strong>. Tylko automatyczna akcja typu 1 (HP) jest dostępna w wersji darmowej.",
    faq4Prem:  "<strong>Jeśli masz Premium:</strong><br>1. Czy automatyzacja jest aktywna? <code>CTRL+A</code><br>2. Czy włączone są przełączniki wyzwalaczy? (zielony wskaźnik «ON»)<br>3. Czy skonfigurowane klawisze są poprawne?",
    faq5Q:     "❌ Sekwencje / makra / makro okresowe / skróty nie działają",
    faq5Alert: "<strong>⚠️ WAŻNE</strong><br>Skróty klawiszowe, sekwencje, makra i makro okresowe są funkcjami <strong>WYŁĄCZNIE PREMIUM</strong>. W wersji darmowej dostępna jest tylko automatyczna akcja typu 1 (HP).",
    faq5Prem:  "<strong>Jeśli masz Premium:</strong><br>1. Sprawdź, czy licencja Premium jest aktywna (ikona 💎 w panelu)<br>2. Czy odpowiednie przełączniki są włączone?<br>3. Sprawdź skonfigurowane interwały i opóźnienia",
    faq6Q: "❌ Automatyzacja zatrzymuje się sama",
    faq6A: "<strong>Możliwe przyczyny:</strong><br>• Utracone połączenie z Google Cloud<br>• Wykrycie DevTools<br>• URL strony się zmienił<br><br><strong>Rozwiązania:</strong><br>1. Zrestartuj automatyzację za pomocą <code>CTRL+A</code> (Premium) lub przez panel<br>2. Przeładuj odpowiednią stronę<br>3. Sprawdź połączenie internetowe<br>4. Nie otwieraj DevTools, jeśli masz Premium",
    optH2: "Optymalizacja & Wydajność",
    faq7Q: "💡 Rozszerzenie zużywa za dużo zasobów",
    faq7A: "<strong>Zalecenia:</strong><br>• Zwiększ interwały makr i sekwencji (mniej akcji = mniej CPU)<br>• Dezaktywuj systemy, których nie potrzebujesz<br>• Zamknij niepotrzebne karty<br>• Używaj zoptymalizowanej przeglądarki (Brave, Edge są lżejsze niż Chrome)",
    faq8Q: "💡 Jak zoptymalizować konfigurację?",
    faq8A: "<strong>Zalecana konfiguracja:</strong><br>• <strong>Interwał sekwencji:</strong> 5-25 minut (zależnie od czasu trwania sekwencji)<br>• <strong>Opóźnienie między klawiszami:</strong> 1-2 sekundy (unika błędów)<br>• <strong>Makra:</strong> Interwały 10-30s zależnie od użycia",
    genH2:  "Często Zadawane Pytania",
    faq9Q:  "❓ Czy mogę używać Reborn na wielu przeglądarkach?",
    faq9A:  "Tak, ale musisz zainstalować rozszerzenie na każdej przeglądarce. Licencja Premium działa na wszystkich urządzeniach, gdy logujesz się tym samym kontem Google (maks. 1 jednoczesne połączenie).",
    faq10Q: "❓ Czy moje dane są zapisywane?",
    faq10A: "Wszystkie ustawienia (klawisze, makra, motyw, język) są zapisywane <strong>lokalnie</strong> w przeglądarce. Zachowywane między sesjami. Jednak odinstalowanie rozszerzenia spowoduje utratę tych danych.",
    faq11Q: "❓ Czy Reborn może spowodować bana?",
    faq11A: "Używanie narzędzi automatyzacji może naruszać Warunki Korzystania z Usługi niektórych serwisów. <strong>Tylko Ty jesteś odpowiedzialny</strong> za sposób używania Reborn. Zapoznaj się z warunkami użytkowania serwisu przed użyciem tego narzędzia.",
    faq12Q: "❓ Jak anulować subskrypcję Premium?",
    faq12A: "Możesz anulować w dowolnym momencie z portalu zarządzania Stripe (link otrzymany e-mailem po płatności). Anulowanie wchodzi w życie na końcu bieżącego okresu. Bez opłat za anulowanie.",
    faq13Q: "❓ Co się stanie z planem Dożywotnim, jeśli serwis zostanie zamknięty?",
    faq13A: "Plan Dożywotni gwarantuje dostęp, dopóki serwis jest aktywny. Po zainstalowaniu rozszerzenie działa lokalnie; tylko weryfikacja licencji wymaga połączenia internetowego.",
    supportH2:    "Potrzebujesz więcej pomocy?",
    supportTitle: "📧 Wsparcie",
    supportText:  "Jeśli problem nadal występuje, skontaktuj się bezpośrednio z pomocą techniczną przez e-mail. Dołącz do wiadomości:<br><br>• Szczegółowy opis problemu<br>• Kroki, które już podjąłeś<br>• Zrzuty ekranu, jeśli są istotne<br>• Przeglądarkę i system operacyjny",
  },

  docPrivacy: {
    h1:       "⚖️ Prawne & Prywatność",
    subtitle: "Zastrzeżenie prawne, wzmianki prawne, warunki licencji i polityka prywatności",
    navLegal:  "⚖️ Informacje Prawne",
    navLicence:"© Licencja",
    navPrivacy:"🔒 Prywatność",
    disclaimerH2:  "⚠️ Zastrzeżenie Prawne",
    disclaimerBox: "<strong>⚠️ Ważna uwaga:</strong> Reborn Assistant to narzędzie automatyzacji. Jego użycie może naruszać Warunki Korzystania z Usługi niektórych serwisów online. Korzystanie z tego narzędzia jest całkowicie na własne ryzyko.",
    respH3:    "Odpowiedzialność użytkownika",
    respIntro: "Używając Reborn Assistant, uznajesz i akceptujesz, że:",
    respLi1:   "Jesteś jedyną osobą odpowiedzialną za użycie tego oprogramowania",
    respLi2:   "Sprawdzisz warunki użytkowania każdego serwisu przed użyciem tego narzędzia",
    respLi3:   "Autor nie może być pociągnięty do odpowiedzialności za żaden ban, ograniczenie konta lub działanie prawne wynikające z użycia Reborn",
    respLi4:   "Używasz tego oprogramowania świadomie i na własne ryzyko",
    respLi5:   "To narzędzie nie może być używane w sposób, który szkodzi doświadczeniu innych użytkowników",
    warrantH3:   "Brak gwarancji",
    warrantText: "Oprogramowanie jest dostarczane «TAKIE JAKIE JEST» bez żadnych gwarancji. Autor nie gwarantuje, że oprogramowanie będzie działać nieprzerwanie lub bez błędów, ani że będzie kompatybilne ze wszystkimi serwisami lub przeglądarkami.",
    legalH2:    "📄 Wzmianki prawne",
    copyrightH3:   "Prawa autorskie & Własność intelektualna",
    copyrightText: "<strong>© 2026 Reborn Assistant – Wszelkie prawa zastrzeżone</strong><br>Opracowany przez <strong>Seymoon</strong>",
    copyrightText2:"To oprogramowanie i wszystkie powiązane materiały są wyłączną własnością intelektualną autora. Wszelka reprodukcja, modyfikacja, dystrybucja lub inżynieria odwrotna bez pisemnego zezwolenia jest surowo zabroniona.",
    liabilityH3:   "Ograniczenie odpowiedzialności",
    liabilityIntro:"W żadnym wypadku autor nie ponosi odpowiedzialności za roszczenia lub szkody wynikające z użycia lub niemożności użycia tego oprogramowania, w tym między innymi:",
    liabilityLi1:  "Utrata danych lub konta użytkownika",
    liabilityLi2:  "Bany lub ograniczenia nałożone przez wydawców serwisów",
    liabilityLi3:  "Uszkodzenia systemów informatycznych",
    liabilityLi4:  "Wszelkie konsekwencje prawne wynikające z użycia niezgodnego z warunkami korzystania z usługi",
    dataH3:    "Dane osobowe",
    dataText:  "Reborn Assistant używa Firebase (Google Cloud) do zarządzania kontami i licencjami. Zbierane dane ograniczają się do adresu e-mail i identyfikatora konta, wyłącznie do celów uwierzytelnienia i weryfikacji licencji.",
    dataText2: "<strong>Żadne dane o aktywności nie są zbierane ani przesyłane.</strong> Ustawienia pozostają przechowywane lokalnie na urządzeniu.",
    jurisH3:   "Jurysdykcja",
    jurisText: "Umowa ta podlega prawu właściwemu dla jurysdykcji miejsca zamieszkania właściciela praw autorskich. Instalując i używając tego oprogramowania, uznajesz, że przeczytałeś, zrozumiałeś i zaakceptowałeś całość tych warunków.",
    licenceH2:     "© Warunki licencji",
    licenceH3:     "Licencja użytkowania",
    licenceIntro:  "Zakup planu Reborn Assistant przyznaje osobistą, niewyłączną i niezbywalną licencję na użytkowanie oprogramowania.",
    licenceAllows: "<strong>Ta licencja upoważnia Cię do:</strong>",
    licenceLi1:    "Używania oprogramowania do celów osobistych na własnych urządzeniach",
    licenceLi2:    "Korzystania z aktualizacji zawartych w planie",
    licenceForbids:"<strong>Ta licencja nie upoważnia Cię do:</strong>",
    licenceLi3:    "Redystrybuowania, odsprzedaży lub udostępniania dostępu",
    licenceLi4:    "Modyfikowania, dekompilowania lub przeprowadzania inżynierii odwrotnej oprogramowania",
    licenceLi5:    "Używania oprogramowania do celów komercyjnych bez uprzedniej pisemnej umowy",
    licenceLi6:    "Przenoszenia licencji na osobę trzecią",
    terminationH3:   "Rozwiązanie",
    terminationText: "Licencja może zostać natychmiast rozwiązana w przypadku naruszenia tych warunków. W przypadku planów subskrypcyjnych możesz anulować w dowolnym momencie z portalu Stripe.",
    refundBox: "<strong>✅ Polityka zwrotów:</strong> Jeśli nie jesteś zadowolony w ciągu 7 dni od zakupu, skontaktuj się z pomocą techniczną, aby uzyskać pełny zwrot. Po tym terminie zwroty nie są udzielane, z wyjątkiem wyjątkowych przypadków.",
    privacyH1:      "🔒 Polityka Prywatności",
    privacySubtitle:"Jak chronimy Twoje dane osobowe",
    privacyBox:     "<strong>✅ Twoja prywatność jest naszym priorytetem</strong><br>Wersja darmowa: żadne dane osobowe nie są zbierane. Wersja Premium: przetwarzane są tylko dane ściśle niezbędne do weryfikacji licencji.",
    collectH2:        "Zbieranie danych",
    collectFreeH3:    "Wersja Darmowa",
    collectFreeText:  "Żadne dane osobowe nie są zbierane ani przesyłane. Wszystkie preferencje są przechowywane wyłącznie na urządzeniu.",
    collectPremH3:    "Wersja Premium",
    collectPremIntro: "Aby zweryfikować licencję i chronić konto, przetwarzane są następujące dane:",
    collectPremLi1:   "Adres e-mail Google (przez uwierzytelnienie Google)",
    collectPremLi2:   "Unikalny identyfikator urządzenia (generowany lokalnie)",
    collectPremLi3:   "Status subskrypcji i znaczniki czasu sesji",
    collectPremLi4:   "Maksymalnie 2 zarejestrowane urządzenia na konto",
    collectPremBasis: "<strong>Podstawa prawna:</strong> wykonanie umowy (art. 6.1.b RODO).",
    collectNotH3:     "Dane nigdy niezgromadzone",
    collectNotLi1:    "❌ Żadne dane o grze lub aktywności",
    collectNotLi2:    "❌ Żadna historia przeglądania",
    collectNotLi3:    "❌ Żadne reklamowe ani śledzące pliki cookie",
    localH2:    "Dane przechowywane lokalnie",
    localIntro: "Poniższe informacje są zapisywane <strong>wyłącznie na urządzeniu</strong>:",
    localLi1:   "<strong>Preferencje językowe</strong>: Wybór języka interfejsu",
    localLi2:   "<strong>Wybór motywu wizualnego</strong>: Wybrany motyw spośród 6 dostępnych",
    localLi3:   "<strong>Skonfigurowane skróty klawiszowe</strong>: Przypisane klawisze do akcji",
    localLi4:   "<strong>Niestandardowe interwały timera</strong>: Skonfigurowane timery dla makr",
    localLi5:   "<strong>Pozycja interfejsu</strong>: Położenie panelu Reborn na ekranie",
    localLi6:   "<strong>Cache licencji (Premium)</strong>: identyfikator urządzenia i status subskrypcji, aby uniknąć weryfikacji przy każdym uruchomieniu",
    thirdH2:       "Usługi stron trzecich",
    thirdH3:       "Używane usługi (wersja Premium)",
    thirdDesc:     "Do uwierzytelnienia i płatności Reborn Assistant używa:",
    thirdLi1:      "🔐 <strong>Google</strong> — Uwierzytelnienie i bezpieczne przechowywanie danych licencji",
    thirdLi2:      "💳 <strong>Stripe</strong> — Przetwarzanie płatności Premium (dane bankowe nigdy nie przechodzą przez nasze serwery)",
    thirdTransfer: "Ci dostawcy są zgodni z RODO i posiadają odpowiednie gwarancje dla międzynarodowych transferów danych.",
    thirdNoH3:     "Bez śledzenia, bez reklam",
    thirdLi3:      "❌ Żadne usługi analityczne lub statystyczne",
    thirdLi4:      "❌ Żadne reklamy ani ukierunkowany marketing",
    thirdLi5:      "❌ Żadne pliki cookie stron trzecich ani śledzenie zachowań",
    authH2:    "Uwierzytelnienie i zarządzanie urządzeniami",
    authH3:    "Logowanie przez Google (wersja Premium)",
    authText:  "Konto Google jest używane wyłącznie do uwierzytelnienia tożsamości i weryfikacji licencji. Urządzenie jest rejestrowane w bezpiecznym systemie (maksymalnie 2 urządzenia na konto).",
    authText2: "Otrzymasz powiadomienie, jeśli konto zostanie użyte na nierozpoznanym urządzeniu. Zarejestrowanymi urządzeniami możesz zarządzać bezpośrednio z rozszerzenia.",
    payH2:    "Bezpieczne Płatności",
    payText:  "Płatności Premium są przetwarzane przez <strong>Stripe</strong>. Dane bankowe <strong>nigdy</strong> nie przechodzą przez nasze serwery. Nie przechowujemy <strong>żadnych</strong> danych karty bankowej.",
    retentionH2:   "Okres przechowywania",
    retentionText: "Dane są przechowywane tylko przez niezbędny czas:",
    retentionLi1:  "<strong>Aktywne konto:</strong> dane przechowywane przez cały okres subskrypcji",
    retentionLi2:  "<strong>Po anulowaniu:</strong> usunięcie w ciągu 30 dni",
    retentionLi3:  "<strong>Dane lokalne:</strong> usunięte natychmiast po odinstalowaniu rozszerzenia",
    rightsH2:      "Twoje prawa (RODO)",
    rightsText:    "Zgodnie z RODO masz następujące prawa dotyczące danych:",
    rightsLi1:     "✅ <strong>Dostęp</strong> — Uzyskanie kopii danych osobowych",
    rightsLi2:     "✅ <strong>Sprostowanie</strong> — Korekta nieprawidłowych danych",
    rightsLi3:     "✅ <strong>Usunięcie</strong> — Żądanie usunięcia konta i danych",
    rightsLi4:     "✅ <strong>Przenoszalność</strong> — Otrzymanie danych w czytelnym formacie",
    rightsLi5:     "✅ <strong>Skarga</strong> — Złożenie skargi do organu ochrony danych w swoim kraju",
    rightsExercise:"Aby skorzystać z tych praw, skontaktuj się: seymoon@constellation-89.fr lub na Discordzie (Seymoon)",
    deleteH2:    "Usunięcie danych",
    deleteText1: "<strong>1. Odinstalowanie rozszerzenia</strong><br>Odinstalowanie Reborn Assistant automatycznie usuwa wszystkie dane lokalne.",
    deleteText2: "<strong>2. Ręczny reset</strong><br>Możesz zresetować ustawienia z interfejsu Reborn w dowolnym momencie.",
    deleteText3: "<strong>3. Usunięcie konta (Premium)</strong><br>Aby usunąć konto Premium i wszystkie powiązane dane, skontaktuj się z nami przez e-mail.",
    contactH2:   "Kontakt",
    contactText: "W przypadku pytań dotyczących informacji prawnych lub polityki prywatności:",
    changelogH2: "📋 Dziennik zmian",
    v130H3:          "Wersja 1.3.0 (Marzec 2026) · Aktualna",
    v130newLabel:    "✨ Nowości",
    v130improvLabel: "🔧 Ulepszenia",
    v130fixLabel:    "🐛 Poprawki",
    v130Li1:  "⏱ Przeciągalny pływający mini-timer — małe pływające okno wyświetlające timery buffów i te powyżej 1 minuty, automatycznie otwiera się przy następnym uruchomieniu i śledzi aktywny skin.",
    v130Li2:  "⚡ Makra priorytetowe — makra wykonują się przed leczeniem/HP/maną, z zamrożeniem leczenia 0,5s przed i po każdym wykonaniu dla uniknięcia konfliktów.",
    v130Li3:  "🧠 Inteligentne zarządzanie buffem — buff wykonuje się jako pierwszy, wyciszone makra są kolejkowane i automatycznie restartowane po jego zakończeniu (opóźnienie zmniejszone do 2s).",
    v130Li4:  "💾 Zapamiętywanie pozycji — pływające okna zachowują swoją pozycję między sesjami.",
    v130Li5:  "🇸🇦 Obsługa arabskiego — 15. język dostępny w rozszerzeniu.",
    v130Li6:  "💳 Płatność Stripe w popup — otwiera się w dedykowanym oknie z automatycznym zamknięciem, bez opuszczania rozszerzenia.",
    v130Li7:  "🐾 Znajomy: naprawiono błąd, gdy znajomy nie wychodził przy pierwszym buffie + lepsze śledzenie trybu F1/F2 dla chowania przy zatrzymaniu.",
    v130Li8:  "⏱ Timer: przeprojektowanie wizualne designu premium + przezroczystość 55% w spoczynku → 95% przy najechaniu dla lepszej czytelności.",
    v130Li9:  "💳 Portal rozliczeniowy: jedno aktywne okno w pamięci z automatycznym zamknięciem.",
    v130Li10:  "Naprawiono kilka wycieków pamięci w zawartości i popupie.",
    v130Li16:  "Wyrównanie UI do limitu max 2 urządzeń (spójność z backendem).",
    v120H3:  "Wersja 1.2.0 (Marzec 2026)",
    v120Li1: "✨ 6 skórek zostało przeprojektowanych z subtelnym efektem przezroczystości.",
    v120Li2: "🔐 Przeglądaj i zarządzaj zarejestrowanym urządzeniem bezpośrednio z rozszerzenia.",
    v120Li3: "💳 Dostęp do subskrypcji jednym kliknięciem z rozszerzenia.",
    v120Li4: "🔔 Natychmiastowe powiadomienie, jeśli konto jest używane na innym urządzeniu.",
    v12H3:   "Wersja 1.2 (Luty 2026)",
    v12Li1:  "Obsługa 15 języków (dodano turecki 🇹🇷)",
    v12Li2:  "Wizualny redesign strony internetowej",
    v12Li3:  "Połączenie stron prawnych w jedną ujednoliconą stronę",
    v12Li4:  "Pełne tłumaczenie FR/EN strony",
    v11H3:   "Wersja 1.1.1 (Luty 2026)",
    v11Li1:  "Dodano automatyczne makro okresowe (15s + auto-zapisywanie)",
    v11Li2:  "Skróty klawiszowe CTRL+A / CTRL+O",
    v11Li3:  "Obsługa 15 języków (dodano filipiński + turecki)",
    v11Li4:  "Poprawa stabilności licencji Premium",
    v11Li5:  "Poprawki błędów w rotacji sekwencji",
    v10H3:   "Wersja 1.0 (2025) · Pierwsza",
    v10Li1:  "Premiera Reborn Assistant",
    v10Li2:  "Automatyczne akcje typu 1 i 2",
    v10Li3:  "Automatyczna rotacja sekwencji (F2 → 1-9 → 0 → F1)",
    v10Li4:  "3 konfigurowalne makra",
    v10Li5:  "6 motywów wizualnych i 12 języków",
    v10Li6:  "System licencji Premium przez Firebase",
    pageFooter:"© 2026 Reborn Assistant — Opracowany przez Seymoon · Wszelkie prawa zastrzeżone",
  },
  nav: {
    docsFull:    "📚 Dokumentacja",
    docsShort:   "📚 Docs",
    manageFull:  "Zarządzaj subskrypcją",
    manageShort: "Zarządzaj",
  },
};