export default {
  hero: {
    description: "Extensão de automação do navegador com macros avançadas. Automatize suas ações repetitivas, atalhos e sequências para otimizar sua produtividade.",
    ctaPrimary: "Começar agora",
    ctaSecondary: "Saiba mais",
    trust1: "Versão gratuita disponível",
    trust2: "Sem compromisso",
    trust3: "Pagamento 100% seguro",
    trust4: "Atualizações automáticas",
  },
  features: {
    tag: "Habilidades & Capacidades",
    titleBefore: "Tudo o que ",
    titleEm: "você precisa",
    subtitle: "Descubra as capacidades excepcionais do Reborn Assistant.",
    card1: { badge: "Ativo",    title: "Automação Completa",       description: "Macros de teclas, sequências automáticas e ações configuráveis para uma automação completa." },
    card2: { badge: "Passivo",  title: "Segurança Máxima",         description: "Seus dados permanecem locais. Sem rastreamento, sem telemetria." },
    card3: { badge: "Ativo",    title: "Macros Personalizáveis",   description: "3 macros configuráveis com ativadores automáticos e atalhos de teclado." },
    card4: { badge: "Passivo",  title: "Interface Personalizável", description: "Escolha entre 6 temas e adapte a interface às suas necessidades." },
    card5: { badge: "Passivo",  title: "Multi-Idioma",             description: "Disponível em 15 idiomas. Suporte mundial com interfaces localizadas." },
    card6: { badge: "Gratuito", title: "Versão Gratuita",          description: "Teste gratuitamente com as funções básicas incluídas." },
  },
  security: {
    tag: "Segurança",
    titleBefore: "Segurança de nível ",
    titleEm: "profissional",
    titleAfter: "",
    description: "O Reborn Assistant utiliza os mesmos padrões de segurança das plataformas de streaming mundiais. Suas credenciais são protegidas por <strong style='color:var(--gold);'>criptografia JWT</strong>, seus pagamentos garantidos via <strong style='color:var(--gold);'>Stripe</strong>, e seus dados permanecem <strong style='color:var(--gold);'>100% locais</strong>. Sem rastreamento, sem revenda de dados.",
    card1Title: "Criptografia JWT",
    card1Text:  "Autenticação segura de nível bancário",
    card2Title: "Pagamento com Stripe",
    card2Text:  "Processador utilizado pela Amazon e Google",
    card3Title: "Zero Rastreamento",
    card3Text:  "Seus dados nunca saem do seu dispositivo",
    card4Text:  "Infraestrutura segura do Google Cloud",
  },
  pricing: {
    tag:         "Escolha sua Classe",
    titleBefore: "Escolha seu ",
    titleEm:     "rank",
    subtitle:    "Escolha a fórmula que melhor se adapta a você. Sem compromisso.",
    voyageur: {
      rank: "Rank I · Viajante", plan: "Gratuito", period: "para sempre",
      feat1: "Macro de cura", feat2: "6 temas visuais", feat3: "15 idiomas disponíveis", feat4: "Interface flutuante",
      btn: "Começar", download: "Adicionar ao Chrome", guarantee: "🔒 Gratuito para sempre",
    },
    aventurier: {
      rank: "Rank II · Aventureiro", plan: "Mensal", period: "por mês",
      feat1: "Todas as funções Premium", feat2: "Suporte prioritário", feat3: "Atualizações gratuitas",
      btn: "Testar Grátis", guarantee: "🎁 7 dias grátis · Sem cartão de crédito",
      download: "Adicionar ao Chrome",
    },
    champion: {
      badge: "⭐ Popular -17%",
      rank: "Rank III · Campeão", plan: "Anual", period: "por ano · 2,50€/mês",
      feat1: "Todas as funções Premium", feat2: "Suporte prioritário", feat3: "Atualizações gratuitas",
      btn: "Testar Grátis", guarantee: "🎁 7 dias grátis · Sem cartão de crédito",
      download: "Adicionar ao Chrome",
    },
    legende: {
      badge: "⚡ Oferta Limitada",
      rank: "Rank IV · Lenda", plan: "Vitalício", period: "pagamento único · nunca mais",
      feat1: "Acesso vitalício", feat2: "Todas as atualizações futuras", feat3: "Suporte premium dedicado", feat4: "Melhor custo-benefício",
      btn: "Comprar", guarantee: "🔒 Pagamento único · Acesso garantido vitalício",
      download: "Adicionar ao Chrome",
    },
  },
  stats: {
    label1: "Idiomas disponíveis", label2: "Temas visuais", label3: "Dados locais", label4: "Extensão ativa",
  },
  trust: {
    badge1: "Pagamento seguro SSL", badge2: "Acesso instantâneo", badge3: "Dados 100% privados", badge4: "Suporte reativo",
  },
  store: {
    status: "Extensão oficial",
    title:  "Disponível na Chrome Web Store",
    install: "Instalar",
    available: "Disponível gratuitamente · Extensão oficial verificada pelo Google",
  },
  faq: {
    titleBefore: "Perguntas ",
    titleEm:     "frequentes",
    subtitle:    "Tudo o que você precisa saber antes de começar.",
    q1: "O teste gratuito exige cartão de crédito?",
    a1: "Não, nenhum cartão de crédito é necessário. Os primeiros 7 dias são completamente gratuitos, sem compromisso. Basta criar sua conta para começar imediatamente.",
    q2: "Posso mudar de plano a qualquer momento?",
    a2: "Sim, você pode migrar para um plano superior ou inferior a qualquer momento pela sua conta. Sem taxas de mudança.",
    q3: "O plano Vitalício inclui realmente todas as atualizações futuras?",
    a3: "Absolutamente. O plano Vitalício garante acesso a todas as atualizações e novas funções futuras, sem pagar nada a mais.",
    q4: "Meus dados estão seguros?",
    a4: "Todos os seus dados são armazenados localmente no seu dispositivo. Não coletamos dados pessoais nem usamos rastreamento ou telemetria.",
    q5: "Como entrar em contato com o suporte?",
    a5: "Entre em contato por e-mail em seymoon@constellation-89.fr ou no Discord (Seymoon). Os assinantes premium recebem resposta prioritária.",
    q6: "O Reborn Assistant é um bot?",
    a6: "Não, o Reborn Assistant não é um bot. É uma extensão de macros configuráveis que automatiza sequências de teclas que você mesmo define. Sem inteligência artificial, sem interação com o servidor do jogo, sem leitura de memória. A extensão não lê nem modifica os dados do jogo — apenas simula as teclas que você pressionaria manualmente. Você deve permanecer em frente ao computador para jogar: Reborn Assistant não resolve captchas, não ressuscita seu personagem e não o leva de volta ao spot após uma morte. É uma ferramenta para simplificar seu jogo, não para substituí-lo.",
  },
  footer: {
    privacy:   "Privacidade",
    terms:     "Termos de Uso",
    copyright: "© 2026 Reborn Assistant. Todos os direitos reservados.<br>Desenvolvido por Seymoon",
  },

  // ── Navegação compartilhada docs ──────────────────────────────────
  docsNav: {
    backToDocs:      "← Voltar à documentação",
    mainSite:        "⌂ Site principal",
    backToMainSite:  "← Voltar ao site principal",
    footer:          "© 2026 Reborn Assistant — Desenvolvido por Seymoon · Todos os direitos reservados",
  },

  // ── docs/index.html ───────────────────────────────────────────────
  docsHome: {
    version:              "VERSÃO 1.3.3 · DOCUMENTAÇÃO COMPLETA",
    userGuide:            "Guia do usuário",
    support:              "Suporte",
    legal:                "Informações legais",
    quickstartTitle:      "Início Rápido",
    quickstartDesc:       "Instalação, configuração inicial e primeiros passos com o Reborn Assistant.",
    featuresTitle:        "Funcionalidades",
    featuresDesc:         "Detalhe completo das funções gratuitas e Premium com tabela comparativa.",
    premiumTitle:         "Guia Premium",
    premiumDesc:          "Sequências automáticas, macros personalizáveis e macro periódica.",
    interfaceTitle:       "Interface & Personalização",
    interfaceDesc:        "Temas visuais, idiomas e opções de personalização.",
    troubleshootingTitle: "Solução de problemas",
    troubleshootingDesc:  "Soluções para problemas comuns, perguntas frequentes e otimização de desempenho.",
    legalTitle:           "Legal & Privacidade",
    legalDesc:            "Aviso legal, menções legais, termos de licença, política de privacidade e registro de alterações.",
    footer:               "© 2026 Reborn Assistant — Desenvolvido por Seymoon · Todos os direitos reservados",
  },

  // ── docs/features.html ────────────────────────────────────────────
  docFeatures: {
    h1:        "⚡ Funcionalidades",
    subtitle:  "Descubra tudo o que o Reborn Assistant pode fazer por você",
    h2Free:    "Funcionalidades GRATUITAS",
    freeBadge: "GRÁTIS",
    c1Title: "Ação automática tipo 1",
    c1Desc:  "Ativa automaticamente sua ação tipo 1 (HP) com base em um temporizador configurável.",
    c1li1:   "Temporizador de ação configurável",
    c1li2:   "Funciona em segundo plano",
    c2Title: "Temas visuais",
    c2Desc:  "Personalize a aparência da interface com 6 temas diferentes.",
    c2li1:   "MMO Gold (padrão)",
    c2li2:   "Dark Mode & White Mode",
    c3Title: "Multi-idioma",
    c3Desc:  "Interface disponível em 15 idiomas para uma experiência internacional.",
    c3li3:   "Troca instantânea",
    h2Premium: "Funcionalidades PREMIUM 💎",
    p1Title: "Macro ativador 1 automático",
    p1Desc:  "Ativação automática da sua ação tipo 1 (HP) com base em um temporizador configurável.",
    p1li1:   "Temporizador ativador 1 configurável",
    p1li2:   "Tecla de atalho configurável",
    p1li3:   "Funciona em segundo plano",
    p2Title: "Macro ativador 2 automático",
    p2Desc:  "Uso automático das suas ações tipo 2 com base em um temporizador configurável.",
    p2li1:   "Temporizador ativador 2 configurável",
    p2li2:   "Tecla de atalho configurável",
    p2li3:   "Funciona em segundo plano",
    p3Title: "Atalhos de teclado",
    p3Desc:  "Controle o Reborn Assistant instantaneamente com atalhos globais personalizáveis.",
    p3li1:   "CTRL+A: Iniciar a automação",
    p3li2:   "CTRL+O: Parar a automação",
    p4Title: "Rotação de sequências",
    p4Desc:  "Sistema automático de manutenção de sequências com uma sequência predefinida.",
    p4li1:   "Sequência: F2 → 1-9 → 0 → F1",
    p4li2:   "Intervalo configurável (minutos)",
    p4li3:   "Atraso entre teclas ajustável",
    p5Title: "Macros Personalizáveis",
    p5Desc:  "Crie até 3 macros com suas próprias sequências de teclas.",
    p5li1:   "3 macros independentes",
    p5li2:   "Sequências personalizadas",
    p5li3:   "Intervalos de repetição ajustáveis",
    p6Title: "Macro periódica",
    p6Desc:  "Chamada e armazenamento automático da sua macro periódica a cada 15 segundos.",
    p6li1:   "Chamada automática da macro periódica",
    p6li2:   "Auto-armazenamento após a chamada",
    p6li3:   "Intervalo fixo de 15 segundos",
    tableH2:      "Tabela comparativa",
    tableFeature: "Funcionalidade",
    tableFree:    "Grátis",
    row1:  "Ação automática tipo 1 (HP)",
    row2:  "Temas visuais (6)",
    row3:  "Multi-idioma (15)",
    row4:  "Macro ativador 1 automático",
    row5:  "Macro ativador 2 automático",
    row6:  "Atalhos de teclado (CTRL+A / CTRL+O)",
    row7:  "Rotação de sequências automática",
    row8:  "Macros personalizáveis (3x)",
    row9:  "Macro periódica automática",
    learnMore: "→ Saiba mais sobre as funções Premium",
  },

  // ── docs/quickstart.html ──────────────────────────────────────────
  docQuickstart: {
    h1:       "🚀 Início Rápido",
    subtitle: "Instale e configure o Reborn Assistant em poucos minutos",
    reqH2:    "Requisitos",
    req1:     "<strong>Navegador compatível:</strong> Google Chrome, Microsoft Edge, Brave ou qualquer navegador baseado em Chromium",
    req2:     "<strong>Conta Google:</strong> Necessária apenas para autenticação Premium (opcional para versão gratuita)",
    req3:     "<strong>Site compatível:</strong> Compatível com sites padrão",
    installH2:  "Instalação",
    step1Title: "Acessar a Chrome Web Store",
    step1p:     "Acesse a página do Reborn Assistant na <a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome Web Store</a> e clique em <strong>«Adicionar ao Chrome»</strong>.",
    step1tip:   "💡 Compatível com Google Chrome, Microsoft Edge, Brave e qualquer navegador baseado em Chromium.",
    step2Title: "Confirmar a instalação",
    step2p:     "Clique em <strong>«Adicionar extensão»</strong> na janela de confirmação. A extensão é instalada automaticamente.",
    step3Title: "Fixar a extensão",
    step3p:     "Clique no ícone de quebra-cabeça 🧩 na barra de ferramentas do seu navegador e fixe o Reborn Assistant para acesso rápido.",
    step4Title: "Login (opcional para Premium)",
    step4p:     "• Clique no ícone do Reborn na barra de ferramentas<br>• Para Premium: Faça login com sua conta Google<br>• Para Gratuito: Use diretamente sem login",
    alertTitle: "✅ Instalação concluída!",
    alertText:  "O ícone do Reborn fica verde quando a extensão está ativa. Agora você pode configurar suas funções.",
    configH2:   "Configuração inicial",
    freeH3:     "Versão GRATUITA",
    freeTitle:  "<strong>Funções disponíveis sem login:</strong>",
    freeText:   "• Ação automática tipo 1 (apenas HP)<br>• 6 temas visuais<br>• Suporte a 15 idiomas",
    freeStepTitle: "Configuração da ação automática tipo 1",
    freeStepText:  "1. Abra o painel do Reborn (clique no ícone)<br>2. Ajuste o temporizador da ação HP (padrão: 2s)<br>3. A ação é ativada automaticamente<br>4. Nenhum login necessário",
    premiumH3:       "Versão PREMIUM 💎",
    premiumFeatTitle:"<strong>Funções adicionais (requer login com Google):</strong>",
    premiumFeatText: "• Macro ativador 1 automático (temporizador configurável + atalho)<br>• Macro ativador 2 automático (temporizador configurável + atalho)<br>• Atalhos de teclado (CTRL+A / CTRL+O)<br>• Rotação automática de sequências (F2 → 1-9 → 0 → F1)<br>• 3 macros personalizáveis com sequências de teclas<br>• Sistema de macro periódica automático (chamada + armazenamento a cada 15s)",
    premConfigTitle: "Configuração Premium",
    premConfigSeq:   "<strong>Sequências automáticas:</strong><br>• Ative «Rotação de Sequências» no painel<br>• Configure o intervalo entre ciclos (padrão: 5 min)<br>• Ajuste o atraso entre cada tecla (padrão: 1s)",
    premConfigMacro: "<strong>Macros:</strong><br>• Ative Macro 1, 2 ou 3<br>• Defina a sequência de teclas (ex: <code>1,2,3,4</code>)<br>• Configure o intervalo de repetição",
    premConfigPer:   "<strong>Macro periódica:</strong><br>• Ative o interruptor «Macro periódica»<br>• O sistema chama automaticamente sua macro periódica a cada 15s<br>• Armazenamento automático após a chamada",
    warnTitle: "⚠️ Nota importante",
    warnText:  "As funções Premium (Macros ativadores 1 e 2, Sequências automáticas, Macro periódica automática, 3 macros configuráveis) exigem uma licença Premium válida e login com Google. Sem licença, apenas a macro básica está disponível.",
    shortcutsH2:   "Atalhos de teclado",
    shortcutsText: "<code>CTRL + A</code>: Iniciar a automação<br><code>CTRL + O</code>: Parar a automação",
    nextH2: "Próximos passos",
    link1:  "Descubra todas as funcionalidades",
    link2:  "Guia completo Premium",
    link3:  "Soluções para problemas comuns",
  },

  // ── docs/interface.html ───────────────────────────────────────────
  docInterface: {
    h1:       "🎨 Interface & Personalização",
    subtitle: "Personalize o Reborn Assistant de acordo com suas preferências",
    themesH2:    "Temas visuais",
    themesDesc:  "O Reborn Assistant oferece 6 temas para personalizar a aparência da interface:",
    changeThemeH3:   "Mudar de tema",
    changeThemeText: "1. Abra o painel do Reborn<br>2. Clique na aba \"⚙️ CONFIGURAÇÕES\"<br>3. Selecione seu tema no menu suspenso<br>4. A mudança é instantânea",
    langsH2:    "Idiomas disponíveis",
    langsDesc:  "Interface disponível em 15 idiomas:",
    changeLangH3:   "Mudar de idioma",
    changeLangText: "1. Abra o painel do Reborn<br>2. Clique em \"⚙️ CONFIGURAÇÕES\"<br>3. Selecione seu idioma no menu suspenso<br>4. Toda a interface é traduzida instantaneamente",
    shortcutsH2:   "Atalhos de teclado",
    shortcutsDesc: "O Reborn Assistant inclui atalhos globais para controle rápido:",
    systemH3: "Atalhos do sistema",
    sysSC1:   "<code>CTRL + A</code>: Iniciar a automação",
    sysSC2:   "<code>CTRL + O</code>: Parar a automação",
    customH3:   "Atalhos personalizáveis",
    customDesc: "Você pode configurar as teclas para:",
    customLi1:  "Ações tipo 1 e 2",
    customLi2:  "Macros (sequências de teclas)",
    customLi3:  "Macro periódica",
    displayH2:    "Opções de exibição",
    panelPosH3:   "Posição do painel",
    panelPosDesc: "O painel do Reborn é arrastável:",
    panelLi1: "Clique no cabeçalho do painel",
    panelLi2: "Mantenha pressionado e arraste",
    panelLi3: "Solte no local desejado",
    panelLi4: "A posição é salva automaticamente",
    opacityH3:   "Opacidade do painel",
    opacityDesc: "Ajuste a transparência para não interferir na sua navegação enquanto controla suas estatísticas.",
    logH3:   "Registro de atividade",
    logDesc: "O registro mostra em tempo real todas as ações realizadas:",
    logLi1:  "Ativação/desativação de sistemas",
    logLi2:  "Uso de poções",
    logLi3:  "Execução de macros e sequências",
    logLi4:  "Chamadas à macro periódica",
    logLi5:  "Possíveis erros",
    saveH2:    "Salvamento de parâmetros",
    saveDesc:  "Todas as suas configurações são salvas automaticamente de forma local:",
    saveLi1:   "Tema selecionado",
    saveLi2:   "Idioma da interface",
    saveLi3:   "Limites de ativação",
    saveLi4:   "Teclas atribuídas",
    saveLi5:   "Configuração de macros",
    saveLi6:   "Posição do painel",
    savePersist: "Persistem entre sessões, mesmo após fechar o navegador.",
  },

  // ── docs/premium.html ─────────────────────────────────────────────
  docPremium: {
    h1:       "💎 Guia Premium",
    subtitle: "Domine todas as funções avançadas do Reborn Assistant",
    rotH2:    "🛡️ Rotação de sequências automática",
    rotDesc:  "O sistema de rotação mantém automaticamente todas as suas sequências ativas pressionando uma sequência predefinida de teclas em intervalos regulares.",
    rotSeqH3:   "Sequência de teclas",
    rotSeqText: "A rotação sempre segue esta ordem fixa:",
    rotConfigH3:   "Configuração",
    rotIntName:    "Intervalo entre ciclos",
    rotIntDesc:    "Tempo de espera antes de reiniciar toda a sequência. Padrão: 5 minutos. Ajuste de acordo com a duração das suas sequências mais curtas.",
    rotDelName:    "Atraso entre teclas",
    rotDelDesc:    "Tempo de espera entre cada tecla da sequência. Padrão: 1 segundo. Ajuste conforme a velocidade do serviço (animações, cooldowns...).",
    rotExTitle:    "💡 Exemplo de uso",
    rotExScenario: "<strong>Cenário:</strong> Suas sequências duram 5 minutos e você tem 8 sequências nas teclas 1-8.",
    rotExConfig:   "<strong>Configuração:</strong>",
    rotExLi1:      "Intervalo: 5 minutos",
    rotExLi2:      "Atraso: 1 segundo",
    rotExLi3:      "A extensão pressionará F2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1 a cada 5 minutos",
    rotExLi4:      "13 teclas no total com 1 segundo entre cada uma = ~13 segundos por ciclo",
    macH2:    "⚙️ Macros Personalizáveis",
    macDesc:  "Crie até 3 macros independentes com suas próprias sequências de teclas. Perfeito para automatizar tarefas repetitivas, combos recorrentes ou rotações de habilidades.",
    macHowH3:   "Funcionamento",
    macHowText: "Cada macro executa uma sequência de teclas em intervalos regulares, de forma independente dos demais sistemas.",
    macConfigH3:  "Configuração",
    macSeqName:   "Sequência de teclas",
    macSeqDesc:   "Defina as teclas a pressionar em ordem, separadas por vírgulas. Exemplo: 1,2,3,4 ou q,w,e,r,f",
    macRepName:   "Intervalo de repetição",
    macRepDesc:   "Tempo de espera antes de repetir a sequência. Configure conforme suas necessidades (segundos ou minutos).",
    macDelName:   "Atraso entre teclas",
    macDelDesc:   "Tempo de espera entre cada tecla da sequência (geralmente 0,5 a 2 segundos).",
    macExTitle:   "💡 Exemplos de uso",
    mac1Title:    "<strong>Macro 1 – Automação repetitiva:</strong>",
    mac1Li1:      "Sequência: 1,2,3,space",
    mac1Li2:      "Intervalo: 10 segundos",
    mac1Li3:      "Uso: Rotação de ataques básicos em loop",
    mac2Title:    "<strong>Macro 2 – Combo de habilidades:</strong>",
    mac2Li1:      "Sequência: q,w,e,r",
    mac2Li2:      "Intervalo: 30 segundos",
    mac2Li3:      "Uso: Rotação DPS otimizada",
    mac3Title:    "<strong>Macro 3 – Suporte automático:</strong>",
    mac3Li1:      "Sequência: f,g,h",
    mac3Li2:      "Intervalo: 15 segundos",
    mac3Li3:      "Uso: Sequências de grupo ou ações periódicas",
    perH2:    "🐉 Macro periódica",
    perDesc:  "Este sistema executa automaticamente uma ação periódica a cada 15 segundos. Ideal para tarefas repetitivas que devem ser ativadas regularmente.",
    perHowH3:   "Funcionamento",
    perHowText: "O sistema executa automaticamente esta sequência a cada 15 segundos:",
    perLi1:     "Chama a macro periódica (tecla configurável, padrão §)",
    perLi2:     "Aguarda 500ms",
    perLi3:     "Armazena a macro periódica automaticamente",
    perConfigH3:  "Configuração",
    perCallName:  "Tecla de chamada",
    perCallDesc:  "A tecla que ativa sua macro periódica. Padrão: §. Modifique conforme sua configuração.",
    perIntName:   "Intervalo (fixo)",
    perIntDesc:   "O sistema sempre usa um intervalo fixo de 15 segundos. Não configurável.",
    perExTitle:   "💡 Caso de uso",
    perExText:    "Em alguns serviços, a macro periódica deve ser chamada regularmente para coletar itens, fornecer sequências temporárias ou ganhar experiência. Este sistema automatiza completamente esse processo.",
    perImpH3:     "⚠️ Importante",
    perImpLi1:    "Verifique se a tecla configurada corresponde à sua tecla de invocação",
    perImpLi2:    "A macro periódica é armazenada automaticamente após cada chamada",
    perImpLi3:    "Funciona em paralelo com os demais sistemas (sequências, macros, ações)",
    optH2:   "Dicas de otimização",
    combH3:  "🎯 Combinação de sistemas",
    combDesc:"Todas as funções Premium funcionam simultaneamente. Você pode:",
    combLi1: "Ativar sequências automáticas + 3 macros + macro periódica ao mesmo tempo",
    combLi2: "As ações ativadoras 1 &amp; 2 sempre funcionam em paralelo",
    combLi3: "Cada sistema tem seu próprio temporizador independente",
    perfH3:  "⚡ Desempenho",
    perfLi1: "Quanto mais sistemas você ativar, mais recursos a extensão consome",
    perfLi2: "Ajuste os intervalos para evitar ações muito frequentes",
    perfLi3: "Monitore o registro de atividade para verificar o funcionamento correto",
    secH3:   "🔑 Segurança",
    secLi1:  "Sua licença Premium é verificada em tempo real",
    secLi2:  "Se a conexão for perdida, as funções Premium são desativadas",
    secLi3:  "Faça login novamente para reativar todas as funções",
  },

  // ── docs/troubleshooting.html ─────────────────────────────────────
  docTroubleshooting: {
    h1:       "🔧 Solução de problemas",
    subtitle: "Soluções para problemas comuns e perguntas frequentes",
    installH2: "Problemas de instalação",
    faq1Q: "❌ A extensão não aparece na barra de ferramentas",
    faq1A: "<strong>Soluções:</strong><br>1. Verifique se a extensão está instalada pela <strong>Chrome Web Store</strong><br>2. Fixe a extensão: clique no ícone de quebra-cabeça 🧩 na barra de ferramentas e fixe o Reborn Assistant<br>3. Reinicie seu navegador<br>4. Se o problema persistir, desinstale e reinstale a extensão pela Chrome Web Store",
    connH2: "Problemas de conexão",
    faq2Q: "❌ \"Conexão falhou\" ou \"Licença inválida\"",
    faq2A: "<strong>Possíveis causas:</strong><br>• Conexão de internet ruim<br>• Servidores do Google Cloud temporariamente indisponíveis<br>• Licença expirada ou revogada<br><br><strong>Soluções:</strong><br>1. Verifique sua conexão com a internet<br>2. Saia e faça login novamente com o Google<br>3. Verifique o status da sua licença no portal Stripe<br>4. Entre em contato com o suporte se o problema persistir",
    faq3Q: "❌ O painel mostra \"FREE\" mesmo tendo Premium",
    faq3A: "1. Saia da sua conta Google<br>2. Feche completamente o navegador<br>3. Reabra e faça login novamente<br>4. Se o problema persistir, verifique se está conectado com a conta Google correta (a usada na compra)",
    funcH2: "Problemas de funcionamento",
    faq4Q:     "❌ As ações tipo 1/2 não são ativadas",
    faq4Alert: "<strong>⚠️ IMPORTANTE</strong><br>As ações tipo 1 e 2 são funções <strong>EXCLUSIVAMENTE PREMIUM</strong>. Apenas a ação automática tipo 1 (HP) está disponível na versão gratuita.",
    faq4Prem:  "<strong>Se você tem Premium:</strong><br>1. A automação está ativa? <code>CTRL+A</code><br>2. Os toggles de disparo estão ativados? (indicador verde «ON»)<br>3. As teclas configuradas estão corretas?",
    faq5Q:     "❌ As sequências / macros / macro periódica / atalhos não funcionam",
    faq5Alert: "<strong>⚠️ IMPORTANTE</strong><br>Os atalhos de teclado, sequências, macros e macro periódica são funções <strong>EXCLUSIVAMENTE PREMIUM</strong>. Na versão gratuita, apenas a ação automática tipo 1 (HP) está disponível.",
    faq5Prem:  "<strong>Se você tem Premium:</strong><br>1. Verifique se sua licença Premium está ativa (ícone 💎 no painel)<br>2. Os interruptores correspondentes estão ligados?<br>3. Verifique os intervalos e atrasos configurados",
    faq6Q: "❌ A automação para sozinha",
    faq6A: "<strong>Causas possíveis:</strong><br>• Conexão perdida com Google Cloud<br>• Detecção de DevTools<br>• A URL da página mudou<br><br><strong>Soluções:</strong><br>1. Reinicie a automação com <code>CTRL+A</code> (Premium) ou pelo painel<br>2. Recarregue a página afetada<br>3. Verifique sua conexão à internet<br>4. Não abra DevTools se estiver no Premium",
    optH2: "Otimização & Desempenho",
    faq7Q: "💡 A extensão consome muitos recursos",
    faq7A: "<strong>Recomendações:</strong><br>• Aumente os intervalos de macros e sequências (menos ações = menos CPU)<br>• Desative os sistemas que não precisa<br>• Feche abas desnecessárias<br>• Use um navegador otimizado (Brave, Edge são mais leves que o Chrome)",
    faq8Q: "💡 Como otimizar a configuração?",
    faq8A: "<strong>Configuração recomendada:</strong><br>• <strong>Intervalo sequências:</strong> 5-25 minutos (conforme duração das suas sequências)<br>• <strong>Atraso entre teclas:</strong> 1-2 segundos (evita erros)<br>• <strong>Macros:</strong> Intervalos de 10-30s conforme o uso",
    genH2:  "Perguntas Frequentes",
    faq9Q:  "❓ Posso usar o Reborn em vários navegadores?",
    faq9A:  "Sim, mas você deve instalar a extensão em cada navegador. Sua licença Premium funciona em todos os seus dispositivos enquanto você fizer login com a mesma conta Google (máx. 1 conexão simultânea).",
    faq10Q: "❓ Meus dados são salvos?",
    faq10A: "Todas as suas configurações (teclas, macros, tema, idioma) são salvas <strong>localmente</strong> no navegador. Persistem entre sessões. No entanto, se você desinstalar a extensão, perderá esses dados.",
    faq11Q: "❓ O Reborn pode causar um banimento?",
    faq11A: "O uso de ferramentas de automação pode violar os Termos de Serviço de alguns serviços. <strong>Você é o único responsável</strong> pela forma como usa o Reborn. Consulte os termos de uso do serviço antes de usar esta ferramenta.",
    faq12Q: "❓ Como cancelar minha assinatura Premium?",
    faq12A: "Você pode cancelar a qualquer momento pelo seu portal de gerenciamento Stripe (link recebido por e-mail após o pagamento). O cancelamento tem efeito no final do seu período atual. Sem taxas de cancelamento.",
    faq13Q: "❓ O que acontece com o plano Vitalício se o serviço encerrar?",
    faq13A: "O plano Vitalício garante o acesso enquanto o serviço estiver ativo. Uma vez instalada, a extensão funciona localmente; apenas a verificação de licença requer conexão com a internet.",
    supportH2:    "Precisa de mais ajuda?",
    supportTitle: "📧 Suporte",
    supportText:  "Se o seu problema persistir, entre em contato com o suporte diretamente por e-mail. Inclua na sua mensagem:<br><br>• Uma descrição detalhada do problema<br>• Os passos que você já tentou<br>• Capturas de tela, se relevantes<br>• Seu navegador e sistema operacional",
  },

  // ── docs/privacy.html ─────────────────────────────────────────────
  docPrivacy: {
    h1:       "⚖️ Legal & Privacidade",
    subtitle: "Aviso legal, menções legais, termos de licença e política de privacidade",
    navLegal:  "⚖️ Informações Legais",
    navLicence:"© Licença",
    navPrivacy:"🔒 Privacidade",
    disclaimerH2:  "⚠️ Aviso Legal",
    disclaimerBox: "<strong>⚠️ Aviso importante:</strong> O Reborn Assistant é uma ferramenta de automação. Seu uso pode violar os Termos de Serviço de certos serviços online. O uso desta ferramenta é de sua inteira responsabilidade.",
    respH3:    "Responsabilidade do usuário",
    respIntro: "Ao usar o Reborn Assistant, você reconhece e aceita que:",
    respLi1:   "Você é o único responsável pelo uso que faz deste software",
    respLi2:   "Verificará os termos de uso de cada serviço antes de usar esta ferramenta",
    respLi3:   "O autor não pode ser responsabilizado por qualquer banimento, restrição de conta ou ação legal resultante do uso do Reborn",
    respLi4:   "Você usa este software conscientemente e por sua conta e risco",
    respLi5:   "Esta ferramenta não deve ser usada de forma que prejudique a experiência de outros usuários",
    warrantH3:   "Sem garantia",
    warrantText: "O software é fornecido \"COMO ESTÁ\" sem garantia de qualquer tipo. O autor não garante que o software funcionará de forma ininterrupta ou sem erros, nem que seja compatível com todos os serviços ou navegadores.",
    legalH2:    "📄 Menções legais",
    copyrightH3:   "Direitos autorais & Propriedade intelectual",
    copyrightText: "<strong>© 2026 Reborn Assistant – Todos os direitos reservados</strong><br>Desenvolvido por <strong>Seymoon</strong>",
    copyrightText2:"Este software e todos os materiais associados são propriedade intelectual exclusiva do seu autor. Qualquer reprodução, modificação, distribuição ou engenharia reversa sem autorização escrita é estritamente proibida.",
    liabilityH3:   "Limitação de responsabilidade",
    liabilityIntro:"Em nenhuma hipótese o autor será responsável por qualquer reclamação ou dano decorrente do uso ou da impossibilidade de usar este software, incluindo, mas não se limitando a:",
    liabilityLi1:  "Perda de dados ou conta de usuário",
    liabilityLi2:  "Banimentos ou restrições impostos por editores de serviços",
    liabilityLi3:  "Danos a sistemas informáticos",
    liabilityLi4:  "Qualquer consequência legal decorrente de uso não conforme com os termos de serviço",
    dataH3:    "Dados pessoais",
    dataText:  "O Reborn Assistant utiliza o Firebase (Google Cloud) para gerenciamento de contas e licenças. Os dados coletados limitam-se ao seu endereço de e-mail e identificador de conta, exclusivamente para fins de autenticação e verificação de licença.",
    dataText2: "<strong>Nenhum dado de atividade é coletado ou transmitido.</strong> Suas configurações permanecem armazenadas localmente no seu dispositivo.",
    jurisH3:   "Jurisdição",
    jurisText: "Este acordo é regido pela lei aplicável na jurisdição de residência do titular dos direitos autorais. Ao instalar e usar este software, você reconhece ter lido, compreendido e aceito a totalidade destas condições.",
    licenceH2:     "© Termos de licença",
    licenceH3:     "Licença de uso",
    licenceIntro:  "A compra de um plano do Reborn Assistant concede a você uma licença pessoal, não exclusiva e intransferível para usar o software.",
    licenceAllows: "<strong>Esta licença autoriza você a:</strong>",
    licenceLi1:    "Usar o software para fins pessoais nos seus próprios dispositivos",
    licenceLi2:    "Beneficiar-se das atualizações incluídas no seu plano",
    licenceForbids:"<strong>Esta licença não autoriza você a:</strong>",
    licenceLi3:    "Redistribuir, revender ou compartilhar seu acesso",
    licenceLi4:    "Modificar, descompilar ou fazer engenharia reversa do software",
    licenceLi5:    "Usar o software para fins comerciais sem acordo escrito prévio",
    licenceLi6:    "Transferir sua licença para terceiros",
    terminationH3:   "Rescisão",
    terminationText: "A licença pode ser rescindida imediatamente em caso de descumprimento destes termos. Para planos de assinatura, você pode cancelar a qualquer momento pelo seu portal Stripe.",
    refundBox: "<strong>✅ Política de reembolso:</strong> Se não estiver satisfeito nos 7 dias seguintes à sua compra, entre em contato com nosso suporte para reembolso integral. Após esse período, nenhum reembolso será concedido, salvo casos excepcionais.",
    privacyH1:      "🔒 Política de Privacidade",
    privacySubtitle:"Como protegemos seus dados pessoais",
    privacyBox:     "<strong>✅ Sua privacidade é nossa prioridade</strong><br>Versão gratuita: nenhum dado pessoal é coletado. Versão Premium: apenas os dados estritamente necessários para verificar sua licença são tratados.",
    collectH2:        "Coleta de dados",
    collectFreeH3:    "Versão Gratuita",
    collectFreeText:  "Nenhum dado pessoal é coletado ou transmitido. Todas as suas preferências são armazenadas apenas no seu dispositivo.",
    collectPremH3:    "Versão Premium",
    collectPremIntro: "Para verificar sua licença e proteger sua conta, os seguintes dados são tratados:",
    collectPremLi1:   "Seu endereço de e-mail do Google (via autenticação Google)",
    collectPremLi2:   "Um identificador de dispositivo único (gerado localmente)",
    collectPremLi3:   "Seu status de assinatura e marcas de tempo de sessão",
    collectPremLi4:   "Máximo de 2 dispositivos registrados por conta",
    collectPremBasis: "<strong>Base legal:</strong> execução do contrato (art. 6.1.b RGPD).",
    collectNotH3:     "Dados nunca coletados",
    collectNotLi1:    "❌ Nenhum dado de jogo ou atividade",
    collectNotLi2:    "❌ Nenhum histórico de navegação",
    collectNotLi3:    "❌ Nenhum cookie publicitário ou de rastreamento",
    localH2:    "Dados armazenados localmente",
    localIntro: "As seguintes informações são salvas <strong>apenas no seu dispositivo</strong>:",
    localLi1:   "<strong>Preferências de idioma</strong>: Sua escolha de idioma da interface",
    localLi2:   "<strong>Seleção do tema visual</strong>: O tema escolhido entre os 6 disponíveis",
    localLi3:   "<strong>Atalhos de teclado configurados</strong>: As teclas atribuídas para suas ações",
    localLi4:   "<strong>Intervalos de temporizador personalizados</strong>: Os temporizadores configurados para suas macros",
    localLi5:   "<strong>Posição da interface</strong>: A localização do painel do Reborn na sua tela",
    localLi6:   "<strong>Cache de licença (Premium)</strong>: identificador de dispositivo e status de assinatura, para evitar verificação a cada inicialização",
    thirdH2:       "Serviços de terceiros",
    thirdH3:       "Serviços utilizados (versão Premium)",
    thirdDesc:     "Para autenticação e pagamentos, o Reborn Assistant utiliza:",
    thirdLi1:      "🔐 <strong>Google</strong> — Autenticação e armazenamento seguro de dados de licença",
    thirdLi2:      "💳 <strong>Stripe</strong> — Processamento de pagamentos Premium (seus dados bancários nunca passam pelos nossos servidores)",
    thirdTransfer: "Esses provedores estão em conformidade com o RGPD e possuem as garantias adequadas para transferências internacionais de dados.",
    thirdNoH3:     "Sem rastreamento, sem publicidade",
    thirdLi3:      "❌ Nenhum serviço de análise ou estatísticas",
    thirdLi4:      "❌ Nenhuma publicidade ou marketing direcionado",
    thirdLi5:      "❌ Nenhum cookie de terceiros ou rastreamento de comportamento",
    authH2:    "Autenticação e gerenciamento de dispositivos",
    authH3:    "Login com Google (versão Premium)",
    authText:  "Sua conta Google é usada exclusivamente para autenticar sua identidade e verificar sua licença. Seu dispositivo é registrado em nosso sistema seguro (máximo de 2 dispositivos por conta).",
    authText2: "Você receberá uma notificação se sua conta for usada em um dispositivo não reconhecido. Você pode gerenciar seus dispositivos registrados diretamente pela extensão.",
    payH2:    "Pagamentos Seguros",
    payText:  "Os pagamentos Premium são processados pela <strong>Stripe</strong>. Suas informações bancárias <strong>nunca</strong> passam pelos nossos servidores. Não armazenamos <strong>nenhum dado</strong> de cartão de crédito.",
    retentionH2:   "Período de retenção",
    retentionText: "Seus dados são conservados apenas pelo tempo necessário:",
    retentionLi1:  "<strong>Conta ativa:</strong> dados conservados durante toda a duração da assinatura",
    retentionLi2:  "<strong>Após o cancelamento:</strong> exclusão em 30 dias",
    retentionLi3:  "<strong>Dados locais:</strong> excluídos imediatamente ao desinstalar a extensão",
    rightsH2:      "Seus direitos (RGPD)",
    rightsText:    "De acordo com o RGPD, você tem os seguintes direitos sobre seus dados:",
    rightsLi1:     "✅ <strong>Acesso</strong> — Obter uma cópia dos seus dados pessoais",
    rightsLi2:     "✅ <strong>Retificação</strong> — Corrigir dados incorretos",
    rightsLi3:     "✅ <strong>Exclusão</strong> — Solicitar a remoção da sua conta e dados",
    rightsLi4:     "✅ <strong>Portabilidade</strong> — Receber seus dados em um formato legível",
    rightsLi5:     "✅ <strong>Reclamação</strong> — Registrar uma queixa junto à autoridade de proteção de dados do seu país",
    rightsExercise:"Para exercer esses direitos, entre em contato: seymoon@constellation-89.fr ou no Discord (Seymoon)",
    deleteH2:    "Exclusão dos seus dados",
    deleteText1: "<strong>1. Desinstalar a extensão</strong><br>Ao desinstalar o Reborn Assistant, todos os dados locais são excluídos automaticamente.",
    deleteText2: "<strong>2. Redefinição manual</strong><br>Você pode redefinir as configurações pela interface do Reborn a qualquer momento.",
    deleteText3: "<strong>3. Exclusão de conta (Premium)</strong><br>Para excluir sua conta Premium e todos os dados associados, entre em contato conosco por e-mail.",
    contactH2:   "Contato",
    contactText: "Para qualquer dúvida sobre informações legais ou política de privacidade:",
    changelogH2: "📋 Registro de alterações",
    v130H3:          "Versão 1.3.0 (Março 2026) · Atual",
    v130newLabel:    "✨ Novidades",
    v130improvLabel: "🔧 Melhorias",
    v130fixLabel:    "🐛 Correções",
    v130Li1:  "⏱ Mini-temporizador flutuante arrastável — pequena janela flutuante que exibe os temporizadores de buff e os de mais de 1 minuto, reabre automaticamente no próximo início e segue o skin ativo.",
    v130Li2:  "⚡ Macros prioritários — as macros são executadas antes de curas/PV/mana, com um bloqueio de cura de 0,5s antes e depois de cada execução para evitar conflitos.",
    v130Li3:  "🧠 Gestão inteligente de buff — o buff executa primeiro, as macros silenciadas são enfileiradas e reiniciadas automaticamente após o fim (atraso reduzido para 2s).",
    v130Li4:  "💾 Memória de posição — as janelas flutuantes mantêm a sua posição entre sessões.",
    v130Li5:  "🇸🇦 Suporte ao árabe — 15.º idioma disponível na extensão.",
    v130Li6:  "💳 Pagamento Stripe em popup — abre numa janela dedicada com fecho automático, sem sair da extensão.",
    v130Li7:  "🐾 Familiar: corrigido bug onde o familiar não saía no primeiro buff + melhor rastreamento do modo F1/F2 para armazenamento ao parar.",
    v130Li8:  "⏱ Temporizador: redesign visual do design premium + opacidade 55% em repouso → 95% ao passar o rato para melhor legibilidade.",
    v130Li9:  "💳 Portal de faturação: uma única janela ativa em memória com fecho automático.",
    v130Li10:  "Corrigidas várias fugas de memória no conteúdo e no popup.",
    v130Li16:  "Alinhamento UI no limite máximo de 2 dispositivos (consistência com o backend).",
    v120H3:  "Versão 1.2.0 (Março 2026)",
    v120Li1: "✨ Os 6 skins foram redesenhados com um sutil efeito de transparência.",
    v120Li2: "🔐 Visualize e gerencie seu dispositivo registrado diretamente pela extensão.",
    v120Li3: "💳 Acesse sua assinatura com um clique pela extensão.",
    v120Li4: "🔔 Notificação instantânea se sua conta for usada em outro dispositivo.",
    v12H3:   "Versão 1.2 (Fevereiro 2026)",
    v12Li1:  "Suporte a 15 idiomas (adicionado Turco 🇹🇷)",
    v12Li2:  "Redesign visual do site",
    v12Li3:  "Fusão de páginas legais em uma única página unificada",
    v12Li4:  "Tradução completa FR/EN do site",
    v11H3:   "Versão 1.1.1 (Fevereiro 2026)",
    v11Li1:  "Adicionada macro periódica automática (15s + auto-armazenamento)",
    v11Li2:  "Atalhos de teclado CTRL+A / CTRL+O",
    v11Li3:  "Suporte a 15 idiomas (adicionado Filipino + Turco)",
    v11Li4:  "Melhoria na estabilidade da licença Premium",
    v11Li5:  "Correções de bugs na rotação de sequências",
    v10H3:   "Versão 1.0 (2025) · Inicial",
    v10Li1:  "Lançamento do Reborn Assistant",
    v10Li2:  "Ações automáticas tipo 1 e 2",
    v10Li3:  "Rotação de sequências automática (F2 → 1-9 → 0 → F1)",
    v10Li4:  "3 macros personalizáveis",
    v10Li5:  "6 temas visuais e 12 idiomas",
    v10Li6:  "Sistema de licença Premium via Firebase",
    pageFooter:"© 2026 Reborn Assistant — Desenvolvido por Seymoon · Todos os direitos reservados",
  },
  nav: {
    docsFull:    "📚 Documentação",
    docsShort:   "📚 Docs",
    manageFull:  "Gerenciar assinatura",
    manageShort: "Gerenciar",
  },
};