export default {
  hero: {
    description: "Extension ng browser automation na may advanced macros. I-automate ang mga paulit-ulit na gawain, keyboard shortcuts, at sequences para ma-optimize ang iyong produktibidad.",
    ctaPrimary: "Magsimula Ngayon",
    ctaSecondary: "Matuto Pa",
    trust1: "May libreng bersyon",
    trust2: "Walang kontrata",
    trust3: "100% ligtas ang pagbabayad",
    trust4: "Awtomatikong update",
  },
  features: {
    tag: "Teknolohiya at Kakayahan",
    titleBefore: "Lahat ng ",
    titleEm: "Kailangan Mo",
    subtitle: "Tuklasin ang natatanging mga feature ng Reborn Assistant.",
    card1: { badge: "Aktibo",   title: "Ganap na Automation",          description: "Key macros, auto sequences, at mga na-configure na aksyon para sa kumpletong automation." },
    card2: { badge: "Manual",   title: "Maximum na Seguridad",          description: "Ang iyong data ay nananatili sa lokal. Walang tracking, walang telemetry." },
    card3: { badge: "Aktibo",   title: "Custom Macros",                 description: "3 macros na maaaring i-configure na may auto triggers at keyboard shortcuts." },
    card4: { badge: "Manual",   title: "Custom na Interface",           description: "Pumili mula sa 6 na tema at iaangkop ang interface sa iyong mga pangangailangan." },
    card5: { badge: "Manual",   title: "Multi-wika",                    description: "Available sa 15 na wika. Pandaigdigang suporta na may localized na interface." },
    card6: { badge: "Libre",    title: "Libreng Bersyon",               description: "Libreng pagsubok na may mga pangunahing feature." },
  },
  security: {
    tag: "Seguridad",
    titleBefore: "Seguridad na ",
    titleEm: "Pang-eksperto",
    titleAfter: "",
    description: "Gumagamit ang Reborn Assistant ng parehong pamantayan ng seguridad tulad ng mga nangungunang streaming platform sa mundo. Ang iyong mga kredensyal ay protektado ng <strong style='color:var(--gold);'>JWT encryption</strong>, ang mga pagbabayad ay sinisigurado ng <strong style='color:var(--gold);'>Stripe</strong>, at ang data ay nananatiling <strong style='color:var(--gold);'>100% lokal</strong>. Walang tracking, walang pagbebenta ng data.",
    card1Title: "JWT Encryption",
    card1Text:  "Ligtas na authentication sa antas ng bangko",
    card2Title: "Stripe Payments",
    card2Text:  "Ang processor na ginagamit ng Amazon at Google",
    card3Title: "Zero Tracking",
    card3Text:  "Ang data ay hindi umaalis sa iyong device",
    card4Text:  "Ligtas na Google Cloud infrastructure",
  },
  pricing: {
    tag:         "Pumili ng Klase",
    titleBefore: "Piliin ang Iyong ",
    titleEm:     "Antas",
    subtitle:    "Piliin ang plano na pinaka-angkop sa iyo. Walang pangako.",
    voyageur: {
      rank: "Antas I · Manlalakbay", plan: "Libre", period: "magpakailanman",
      feat1: "Healing macro", feat2: "6 na visual na tema", feat3: "15 na wika ang available", feat4: "Floating interface",
      btn: "Magsimula", download: "Idagdag sa Chrome", guarantee: "🔒 Libre magpakailanman",
    },
    aventurier: {
      rank: "Antas II · Mangangahasla", plan: "Buwanan", period: "buwan",
      feat1: "Lahat ng premium na feature", feat2: "Priority support", feat3: "Libreng update",
      btn: "Libreng Pagsubok", guarantee: "🎁 7 araw libre · Hindi kailangan ng credit card",
      download: "Idagdag sa Chrome",
    },
    champion: {
      badge: "⭐ Popular -17%",
      rank: "Antas III · Kampeon", plan: "Taunan", period: "taon · 2.50€/buwan",
      feat1: "Lahat ng premium na feature", feat2: "Priority support", feat3: "Libreng update",
      btn: "Libreng Pagsubok", guarantee: "🎁 7 araw libre · Hindi kailangan ng credit card",
      download: "Idagdag sa Chrome",
    },
    legende: {
      badge: "⚡ Limitadong Alok",
      rank: "Antas IV · Alamat", plan: "Habambuhay", period: "isang beses na pagbabayad · hindi na muli",
      feat1: "Habambuhay na access", feat2: "Lahat ng update sa hinaharap", feat3: "Dedicated premium support", feat4: "Pinakamahusay na halaga",
      btn: "Bilhin", guarantee: "🔒 Isang beses na pagbabayad · garantisadong habambuhay na access",
      download: "Idagdag sa Chrome",
    },
  },
  stats: {
    label1: "Mga wikang sinusuportahan", label2: "Visual na tema", label3: "Lokal na data", label4: "Aktibong extension",
  },
  trust: {
    badge1: "SSL ligtas na pagbabayad", badge2: "Agarang access", badge3: "100% pribadong data", badge4: "Mabilis na suporta",
  },
  store: {
    status: "Opisyal na extension",
    title:  "Available sa Chrome Web Store",
    install: "I-install",
    available: "Available nang libre · Opisyal na extension na sertipikado ng Google",
  },
  faq: {
    titleBefore: "Mga Madalas ",
    titleEm:     "Itanong",
    subtitle:    "Lahat ng kailangan mong malaman bago magsimula.",
    q1: "Kailangan ba ng credit card para sa libreng pagsubok?",
    a1: "Hindi, hindi kailangan ng credit card. Ang unang 7 araw ay ganap na libre at walang pangako. Gumawa lang ng account para magsimula kaagad.",
    q2: "Maaari ko bang baguhin ang plano kahit kailan?",
    a2: "Oo, maaari kang mag-upgrade o mag-downgrade kahit kailan mula sa iyong account. Walang bayad sa pagbabago.",
    q3: "Kasama ba talaga sa habambuhay na plano ang lahat ng update sa hinaharap?",
    a3: "Oo naman. Tinitiyak ng habambuhay na plano ang access sa lahat ng update at bagong feature sa hinaharap nang walang karagdagang bayad.",
    q4: "Ligtas ba ang aking data?",
    a4: "Lahat ng data ay naka-imbak nang lokal sa iyong device. Hindi kami nangongolekta ng personal na data, at hindi gumagamit ng tracking o telemetry.",
    q5: "Paano makipag-ugnayan sa suporta?",
    a5: "Makipag-ugnayan sa amin sa pamamagitan ng email sa seymoon.cell@gmail.com o Discord (Seymoon). Ang mga premium subscriber ay nakakatanggap ng priority na tugon.",
    q6: "Bot ba ang Reborn Assistant?",
    a6: "Sa mahigpit na kahulugan, ang Reborn Assistant ay hindi isang conventional bot. Ito ay isang extension ng configurable macros na nag-automate ng key sequences na ikaw mismo ang nag-define. Walang artificial intelligence, walang interaction sa game server, walang memory reading. Hindi nababasa o binabago ng extension ang game data — sinisimulate lamang nito ang mga keys na pinipindot mo nang manu-mano. Responsibilidad mo na sumunod sa Terms of Service.",
  },
  footer: {
    privacy:   "Privacy",
    terms:     "Mga Tuntunin",
    copyright: "© 2026 Reborn Assistant. Lahat ng karapatan ay nakalaan.<br>Ginawa ng Seymoon",
  },

  docsNav: {
    backToDocs:      "← Bumalik sa Dokumentasyon",
    mainSite:        "⌂ Pangunahing Site",
    backToMainSite:  "← Bumalik sa Pangunahing Site",
    footer:          "© 2026 Reborn Assistant — Ginawa ng Seymoon · Lahat ng karapatan ay nakalaan",
  },

  docsHome: {
    version:              "Bersyon 1.3 · Kumpletong Dokumentasyon",
    userGuide:            "Gabay ng Gumagamit",
    support:              "Suporta",
    legal:                "Legal na Impormasyon",
    quickstartTitle:      "Mabilis na Simula",
    quickstartDesc:       "Pag-install, paunang setup, at unang hakbang sa Reborn Assistant.",
    featuresTitle:        "Mga Feature",
    featuresDesc:         "Kumpletong paglalarawan ng libreng at premium na feature na may comparison table.",
    premiumTitle:         "Premium na Gabay",
    premiumDesc:          "Auto sequences, custom macros, periodic macros.",
    interfaceTitle:       "Interface & Personalisasyon",
    interfaceDesc:        "Mga visual na tema, wika, mga opsyon sa personalisasyon.",
    troubleshootingTitle: "Pag-troubleshoot",
    troubleshootingDesc:  "Mga solusyon sa karaniwang problema, madalas itanong, pag-optimize ng performance.",
    legalTitle:           "Legal & Privacy",
    legalDesc:            "Legal na disclaimer, legal na paunawa, mga kundisyon ng lisensya, patakaran sa privacy, changelog.",
    footer:               "© 2026 Reborn Assistant — Ginawa ng Seymoon · Lahat ng karapatan ay nakalaan",
  },

  docFeatures: {
    h1:        "⚡ Mga Feature",
    subtitle:  "Tuklasin ang lahat ng magagawa ng Reborn Assistant",
    h2Free:    "Libreng Mga Feature",
    freeBadge: "Libre",
    c1Title: "Auto Action Type 1",
    c1Desc:  "Awtomatikong pag-activate ng type 1 na aksyon (HP) batay sa configurable timer.",
    c1li1:   "Configurable action timer",
    c1li2:   "Gumagana sa background",
    c2Title: "Mga Visual na Tema",
    c2Desc:  "I-customize ang hitsura ng iyong interface gamit ang 6 na magkakaibang tema.",
    c2li1:   "MMO Gold (default)",
    c2li2:   "Dark mode at White mode",
    c3Title: "Multi-wika",
    c3Desc:  "Interface na available sa 15 na wika para sa internasyonal na karanasan.",
    c3li3:   "Instant na paglipat",
    h2Premium: "Mga Premium na Feature 💎",
    p1Title: "Auto Trigger 1 Macro",
    p1Desc:  "Awtomatikong pag-activate ng type 1 na aksyon (HP) batay sa configurable timer.",
    p1li1:   "Configurable trigger 1 timer",
    p1li2:   "Configurable shortcut",
    p1li3:   "Gumagana sa background",
    p2Title: "Auto Trigger 2 Macro",
    p2Desc:  "Awtomatikong paggamit ng type 2 na aksyon batay sa configurable timer.",
    p2li1:   "Configurable trigger 2 timer",
    p2li2:   "Configurable shortcut",
    p2li3:   "Gumagana sa background",
    p3Title: "Mga Keyboard Shortcut",
    p3Desc:  "Kontrolin ang Reborn Assistant kaagad gamit ang customizable na global shortcuts.",
    p3li1:   "CTRL+A: Simulan ang bot",
    p3li2:   "CTRL+O: Itigil ang bot",
    p4Title: "Sequence Rotation",
    p4Desc:  "Automatic sequence maintenance system na may predefined sequences.",
    p4li1:   "Sequence: F2 → 1-9 → 0 → F1",
    p4li2:   "Configurable na agwat (sa minuto)",
    p4li3:   "Adjustable na delay sa pagitan ng mga key",
    p5Title: "Mga Custom Macro",
    p5Desc:  "Gumawa ng hanggang 3 macros na may sariling key sequences.",
    p5li1:   "3 independent na macros",
    p5li2:   "Custom sequences",
    p5li3:   "Adjustable na repetition interval",
    p6Title: "Periodic Macro",
    p6Desc:  "Awtomatikong pag-call at pag-save ng periodic macro bawat 15 segundo.",
    p6li1:   "Awtomatikong pag-call ng periodic macro",
    p6li2:   "Awtomatikong pag-save pagkatapos ng call",
    p6li3:   "Fixed na 15-segundo na agwat",
    tableH2:      "Comparison Table",
    tableFeature: "Feature",
    tableFree:    "Libre",
    row1:  "Auto Action Type 1 (HP)",
    row2:  "Visual na Tema (6)",
    row3:  "Multi-wika (15)",
    row4:  "Auto Trigger 1 Macro",
    row5:  "Auto Trigger 2 Macro",
    row6:  "Mga Keyboard Shortcut (CTRL+A / CTRL+O)",
    row7:  "Auto Sequence Rotation",
    row8:  "Mga Custom Macro (3x)",
    row9:  "Auto Periodic Macro",
    learnMore: "→ Matuto pa tungkol sa mga premium na feature",
  },

  docQuickstart: {
    h1:       "🚀 Mabilis na Simula",
    subtitle: "I-install at i-configure ang Reborn Assistant sa ilang minuto",
    reqH2:    "Mga Kinakailangan",
    req1:     "<strong>Compatible na browser:</strong> Google Chrome, Microsoft Edge, Brave, o anumang browser na batay sa Chromium",
    req2:     "<strong>Google account:</strong> Kinakailangan lamang para sa premium authentication (opsyonal para sa libreng bersyon)",
    req3:     "<strong>Compatible na site:</strong> Compatible sa mga karaniwang website",
    installH2:  "Pag-install",
    step1Title: "Bisitahin ang Chrome Web Store",
    step1p:     "Pumunta sa page ng Reborn Assistant sa <a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome Web Store</a> at i-click ang <strong>«Idagdag sa Chrome»</strong>.",
    step1tip:   "💡 Compatible sa Google Chrome, Microsoft Edge, Brave, at mga browser na batay sa Chromium.",
    step2Title: "Kumpirmahin ang Pag-install",
    step2p:     "I-click ang <strong>«Idagdag ang extension»</strong> sa dialog ng kumpirmasyon. Awtomatikong mai-install ang extension.",
    step3Title: "I-pin ang Extension",
    step3p:     "I-click ang icon ng puzzle 🧩 sa toolbar ng browser at i-pin ang Reborn Assistant para sa mabilis na access.",
    step4Title: "Mag-login (opsyonal para sa premium)",
    step4p:     "• I-click ang Reborn icon sa toolbar<br>• Para sa premium: Mag-login gamit ang iyong Google account<br>• Para sa libre: Gamitin nang direkta nang walang pag-login",
    alertTitle: "✅ Matagumpay ang Pag-install!",
    alertText:  "Kapag naka-activate ang extension, ang Reborn icon ay magiging berde. Maaari ka nang mag-configure ng mga feature.",
    configH2:   "Paunang Configuration",
    freeH3:     "Libreng Bersyon",
    freeTitle:  "<strong>Mga feature na available nang walang pag-login:</strong>",
    freeText:   "• Auto Action Type 1 (HP lamang)<br>• 6 na visual na tema<br>• 15 na wikang sinusuportahan",
    freeStepTitle: "I-configure ang Auto Action Type 1",
    freeStepText:  "1. Buksan ang Reborn panel (i-click ang icon)<br>2. Ayusin ang HP action timer (default: 2 segundo)<br>3. Awtomatikong maa-activate ang aksyon<br>4. Hindi kailangan ng pag-login",
    premiumH3:       "Premium na Bersyon 💎",
    premiumFeatTitle:"<strong>Mga karagdagang feature (nangangailangan ng Google login):</strong>",
    premiumFeatText: "• Auto Trigger 1 Macro (configurable timer + shortcut)<br>• Auto Trigger 2 Macro (configurable timer + shortcut)<br>• Mga Keyboard Shortcut (CTRL+A / CTRL+O)<br>• Auto Sequence Rotation (F2 → 1-9 → 0 → F1)<br>• 3 Custom Macros na may key sequences<br>• Auto Periodic Macro System (call bawat 15s + auto save)",
    premConfigTitle: "Premium na Configuration",
    premConfigSeq:   "<strong>Auto Sequences:</strong><br>• I-activate ang «Sequence Rotation» sa panel<br>• I-set ang agwat sa pagitan ng mga cycle (default: 5 minuto)<br>• Ayusin ang delay sa pagitan ng mga key (default: 1 segundo)",
    premConfigMacro: "<strong>Macros:</strong><br>• I-activate ang Macro 1, 2, o 3<br>• Tukuyin ang key sequence (hal: <code>1,2,3,4</code>)<br>• I-set ang repetition interval",
    premConfigPer:   "<strong>Periodic Macro:</strong><br>• I-activate ang «Periodic Macro» switch<br>• Awtomatikong tatawagin ng system ang periodic macro bawat 15 segundo<br>• Awtomatikong ise-save pagkatapos ng call",
    warnTitle: "⚠️ Mahalagang Tandaan",
    warnText:  "Ang mga premium na feature (Trigger Macros 1 at 2, Auto Sequences, Auto Periodic Macro, 3 configurable macros) ay nangangailangan ng wastong premium license at Google login. Ang pangunahing macro lamang ang available nang walang license.",
    shortcutsH2:   "Mga Keyboard Shortcut",
    shortcutsText: "<code>CTRL + A</code>: Simulan ang bot<br><code>CTRL + O</code>: Itigil ang bot",
    nextH2: "Mga Susunod na Hakbang",
    link1:  "Tuklasin ang lahat ng feature",
    link2:  "Kumpletong premium na gabay",
    link3:  "Mga solusyon sa karaniwang problema",
  },

  docInterface: {
    h1:       "🎨 Interface at Personalisasyon",
    subtitle: "I-customize ang Reborn Assistant ayon sa iyong mga kagustuhan",
    themesH2:    "Mga Visual na Tema",
    themesDesc:  "Nag-aalok ang Reborn Assistant ng 6 na tema para i-personalize ang hitsura ng iyong interface:",
    changeThemeH3:   "Palitan ang Tema",
    changeThemeText: "1. Buksan ang Reborn panel<br>2. I-click ang tab na \"⚙️ Settings\"<br>3. Piliin ang tema mula sa dropdown menu<br>4. Agad na magkakabisa ang mga pagbabago",
    langsH2:    "Mga Wikang Sinusuportahan",
    langsDesc:  "Interface na available sa 15 na wika:",
    changeLangH3:   "Palitan ang Wika",
    changeLangText: "1. Buksan ang Reborn panel<br>2. I-click ang \"⚙️ Settings\"<br>3. Piliin ang wika mula sa dropdown menu<br>4. Agad na magsasaling-wika ang buong interface",
    shortcutsH2:   "Mga Keyboard Shortcut",
    shortcutsDesc: "Ang Reborn Assistant ay may kasamang global shortcuts para sa mabilis na kontrol:",
    systemH3: "Mga System Shortcut",
    sysSC1:   "<code>CTRL + A</code>: Simulan ang bot",
    sysSC2:   "<code>CTRL + O</code>: Itigil ang bot",
    customH3:   "Mga Custom Shortcut",
    customDesc: "Maaari kang mag-assign ng key para sa:",
    customLi1:  "Type 1 at 2 na aksyon",
    customLi2:  "Mga Macro (key sequences)",
    customLi3:  "Periodic Macro",
    displayH2:    "Mga Opsyon sa Display",
    panelPosH3:   "Posisyon ng Panel",
    panelPosDesc: "Maaaring i-drag ang Reborn panel:",
    panelLi1: "I-click ang header ng panel",
    panelLi2: "Hawakan at i-drag",
    panelLi3: "Ilagay sa nais na posisyon",
    panelLi4: "Awtomatikong ise-save ang posisyon",
    opacityH3:   "Opacity ng Panel",
    opacityDesc: "Ayusin ang transparency para hindi maabala ang pag-navigate habang pinamamahalaan ang iyong stats.",
    logH3:   "Activity Log",
    logDesc: "Ipinapakita ng log ang lahat ng aksyon na ginawa sa real time:",
    logLi1:  "Pag-activate/deactivate ng system",
    logLi2:  "Paggamit ng potion",
    logLi3:  "Pag-execute ng macros at sequences",
    logLi4:  "Pag-call ng periodic macro",
    logLi5:  "Mga posibleng error",
    saveH2:    "Pag-save ng mga Setting",
    saveDesc:  "Lahat ng mga setting ay awtomatikong nase-save nang lokal:",
    saveLi1:   "Napiling tema",
    saveLi2:   "Wika ng interface",
    saveLi3:   "Mga activation threshold",
    saveLi4:   "Mga assigned na key",
    saveLi5:   "Macro configurations",
    saveLi6:   "Posisyon ng panel",
    savePersist: "Nananatili sa pagitan ng mga session kahit pagkatapos isara ang browser.",
  },

  docPremium: {
    h1:       "💎 Premium na Gabay",
    subtitle: "Master ang lahat ng advanced na feature ng Reborn Assistant",
    rotH2:    "🛡️ Auto Sequence Rotation",
    rotDesc:  "Ang rotation system ay awtomatikong nagpapanatili ng lahat ng sequences sa pamamagitan ng pagpindot sa predefined key sequence sa regular na agwat.",
    rotSeqH3:   "Key Sequence",
    rotSeqText: "Ang rotation ay laging sumusunod sa fixed na pagkakasunod na ito:",
    rotConfigH3:   "Configuration",
    rotIntName:    "Agwat sa pagitan ng mga cycle",
    rotIntDesc:    "Oras ng paghihintay bago ulitin ang buong sequence. Default: 5 minuto. Ayusin ayon sa tagal ng pinakamaikling sequence.",
    rotDelName:    "Delay sa pagitan ng mga key",
    rotDelDesc:    "Oras ng paghihintay sa pagitan ng bawat key sa sequence. Default: 1 segundo. Ayusin ayon sa bilis ng serbisyo (animations, cooldowns...).",
    rotExTitle:    "💡 Halimbawa ng Paggamit",
    rotExScenario: "<strong>Scenario:</strong> Ang sequence ay tumatagal ng 5 minuto at mayroon kang 8 sequences sa mga key 1-8.",
    rotExConfig:   "<strong>Configuration:</strong>",
    rotExLi1:      "Agwat: 5 minuto",
    rotExLi2:      "Delay: 1 segundo",
    rotExLi3:      "Pipindutin ng bot ang F2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1 bawat 5 minuto",
    rotExLi4:      "13 key total, 1 segundo sa pagitan ng bawat isa = ~13 segundo bawat cycle",
    macH2:    "⚙️ Mga Custom Macro",
    macDesc:  "Gumawa ng hanggang 3 independent na macros na may sariling key sequences. Perpekto para sa pag-automate ng mga paulit-ulit na gawain, regular na combos, o skill rotations.",
    macHowH3:   "Paano Ito Gumagana",
    macHowText: "Ang bawat macro ay nagpapatakbo ng key sequence sa regular na agwat, nang independyente sa iba pang mga system.",
    macConfigH3:  "Configuration",
    macSeqName:   "Key Sequence",
    macSeqDesc:   "Tukuyin ang mga key na pipindutin sa pagkakasunod, na pinaghihiwalay ng kuwit. Hal: 1,2,3,4 o q,w,e,r,f",
    macRepName:   "Repetition Interval",
    macRepDesc:   "Oras ng paghihintay bago ulitin ang sequence. I-set ayon sa iyong pangangailangan (sa segundo o minuto).",
    macDelName:   "Delay sa pagitan ng mga key",
    macDelDesc:   "Oras ng paghihintay sa pagitan ng bawat key sa sequence (kadalasan 0.5 hanggang 2 segundo).",
    macExTitle:   "💡 Mga Halimbawa ng Paggamit",
    mac1Title:    "<strong>Macro 1 – Repetitive Automation:</strong>",
    mac1Li1:      "Sequence: 1,2,3,space",
    mac1Li2:      "Agwat: 10 segundo",
    mac1Li3:      "Paggamit: Pangunahing attack rotation sa loop",
    mac2Title:    "<strong>Macro 2 – Skill Combo:</strong>",
    mac2Li1:      "Sequence: q,w,e,r",
    mac2Li2:      "Agwat: 30 segundo",
    mac2Li3:      "Paggamit: Optimal DPS rotation",
    mac3Title:    "<strong>Macro 3 – Auto Support:</strong>",
    mac3Li1:      "Sequence: f,g,h",
    mac3Li2:      "Agwat: 15 segundo",
    mac3Li3:      "Paggamit: Group sequence o periodic action",
    perH2:    "🐉 Periodic Macro",
    perDesc:  "Awtomatikong nagpapatakbo ang system na ito ng periodic action bawat 15 segundo. Perpekto para sa mga paulit-ulit na gawain na kailangang i-activate nang regular.",
    perHowH3:   "Paano Ito Gumagana",
    perHowText: "Awtomatikong isinasagawa ng system ang sequence na ito bawat 15 segundo:",
    perLi1:     "Pag-call ng periodic macro (configurable key, default §)",
    perLi2:     "Maghintay ng 500ms",
    perLi3:     "Awtomatikong pag-save ng periodic macro",
    perConfigH3:  "Configuration",
    perCallName:  "Call Key",
    perCallDesc:  "Ang key na nag-a-activate ng periodic macro. Default: §. Baguhin ayon sa iyong configuration.",
    perIntName:   "Agwat (fixed)",
    perIntDesc:   "Laging gumagamit ang system ng fixed na 15-segundo na agwat. Hindi maaaring i-configure.",
    perExTitle:   "💡 Mga Use Case",
    perExText:    "Sa ilang serbisyo, kailangan mong regular na tawagan ang periodic macro para makakuha ng mga item, mag-trigger ng mga temporary sequence, o makakuha ng experience. Ganap na inaautomate ng system na ito ang prosesong ito.",
    perImpH3:     "⚠️ Mahalaga",
    perImpLi1:    "Tiyaking ang configured na key ay tumutugma sa call key",
    perImpLi2:    "Awtomatikong nase-save ang periodic macro pagkatapos ng bawat call",
    perImpLi3:    "Gumagana nang parallel sa iba pang mga system (sequences, macros, actions)",
    optH2:   "Mga Tip sa Pag-optimize",
    combH3:  "🎯 Pagsasama ng mga System",
    combDesc:"Lahat ng premium na feature ay gumagana nang sabay-sabay. Maaari kang:",
    combLi1: "Pagsamahin ang Auto Sequences + 3 Macros + Periodic Macro nang sabay",
    combLi2: "Ang Trigger Actions 1 at 2 ay laging gumagana nang parallel",
    combLi3: "Ang bawat system ay may sariling independent na timer",
    perfH3:  "⚡ Performance",
    perfLi1: "Habang mas maraming system ang inaktibo, mas maraming resources ang kino-consume ng extension",
    perfLi2: "Ayusin ang mga agwat para maiwasan ang masyadong madalas na mga aksyon",
    perfLi3: "Subaybayan ang activity log para matiyak ang tamang operasyon",
    secH3:   "🔑 Seguridad",
    secLi1:  "Ang premium license ay validated sa real time",
    secLi2:  "Kapag naputol ang koneksyon, nade-deactivate ang mga premium na feature",
    secLi3:  "Mag-login ulit para muling i-activate ang lahat ng feature",
  },

  docTroubleshooting: {
    h1:       "🔧 Pag-troubleshoot",
    subtitle: "Mga solusyon sa karaniwang problema at madalas itanong",
    installH2: "Mga Problema sa Pag-install",
    faq1Q: "❌ Hindi lumalabas ang extension sa toolbar",
    faq1A: "<strong>Solusyon:</strong><br>1. Tiyaking na-install ang extension mula sa <strong>Chrome Web Store</strong><br>2. I-pin ang extension: I-click ang puzzle icon 🧩 sa toolbar at i-pin ang Reborn Assistant<br>3. I-restart ang browser<br>4. Kung nagpapatuloy ang problema, alisin at muling i-install ang extension mula sa Chrome Web Store",
    connH2: "Mga Problema sa Koneksyon",
    faq2Q: "❌ \"Connection failure\" o \"Invalid license\"",
    faq2A: "<strong>Mga posibleng sanhi:</strong><br>• Hindi maaasahang koneksyon sa internet<br>• Pansamantalang unavailability ng Google Cloud server<br>• Expired o cancelled na license<br><br><strong>Solusyon:</strong><br>1. Suriin ang koneksyon sa internet<br>2. Mag-logout mula sa Google at mag-login ulit<br>3. Suriin ang status ng license sa Stripe portal<br>4. Makipag-ugnayan sa suporta kung nagpapatuloy ang problema",
    faq3Q: "❌ Ipinapakita ang \"FREE\" sa panel kahit premium ako",
    faq3A: "1. Mag-logout mula sa iyong Google account<br>2. Isara ang browser nang ganap<br>3. Buksan ulit at mag-login<br>4. Kung nagpapatuloy, tiyaking naka-login ka sa tamang Google account (ang ginamit sa pagbili)",
    funcH2: "Mga Problema sa Paggana",
    faq4Q:     "❌ Hindi naa-activate ang Type 1/2 na mga aksyon",
    faq4Alert: "<strong>⚠️ Mahalaga</strong><br>Ang Type 1 at 2 na aksyon ay <strong>premium-exclusive</strong> na mga feature. Ang Auto Action Type 1 (HP) lamang ang available sa libreng bersyon.",
    faq4Prem:  "<strong>Kung mayroon kang premium:</strong><br>1. Nagsimula ba ang bot? <code>CTRL+A</code><br>2. Naka-activate ba ang trigger switch? (berdeng «ON» indicator)<br>3. Tama ba ang configured na key?",
    faq5Q:     "❌ Hindi gumagana ang mga sequence/macro/periodic macro/shortcut",
    faq5Alert: "<strong>⚠️ Mahalaga</strong><br>Ang mga keyboard shortcut, sequences, macros, at periodic macros ay <strong>premium-exclusive</strong> na mga feature. Sa libreng bersyon, ang Auto Action Type 1 (HP) lamang ang available.",
    faq5Prem:  "<strong>Kung mayroon kang premium:</strong><br>1. Tiyaking aktibo ang premium license (💎 icon sa panel)<br>2. Naka-activate ba ang kaukulang switch?<br>3. Suriin ang configured na mga agwat at delay",
    faq6Q: "❌ Naghihinto ang bot nang kusa",
    faq6A: "<strong>Mga posibleng sanhi:</strong><br>• Naputol ang koneksyon sa Google Cloud<br>• Natukoy ang DevTools<br>• Nagbago ang page URL<br><br><strong>Solusyon:</strong><br>1. I-restart ang bot sa pamamagitan ng <code>CTRL+A</code> (premium) o mula sa panel<br>2. I-refresh ang apektadong page<br>3. Suriin ang koneksyon sa internet<br>4. Huwag buksan ang DevTools sa premium mode",
    optH2: "Pag-optimize at Performance",
    faq7Q: "💡 Masyadong maraming resources ang ginagamit ng bot",
    faq7A: "<strong>Mga rekomendasyon:</strong><br>• Dagdagan ang agwat ng macros at sequences (mas kaunting aksyon = mas kaunting paggamit ng CPU)<br>• I-deactivate ang mga system na hindi kailangan<br>• Isara ang mga hindi kinakailangang tab<br>• Gumamit ng optimized na browser (Brave, Edge ay mas magaan kaysa Chrome)",
    faq8Q: "💡 Paano i-optimize ang aking mga setting?",
    faq8A: "<strong>Mga inirekomendang setting:</strong><br>• <strong>Sequence interval:</strong> 5 hanggang 25 minuto (depende sa tagal ng sequence)<br>• <strong>Delay sa pagitan ng mga key:</strong> 1 hanggang 2 segundo (para maiwasan ang mga error)<br>• <strong>Macros:</strong> 10 hanggang 30 segundo na agwat depende sa paggamit",
    genH2:  "Mga Madalas Itanong",
    faq9Q:  "❓ Maaari ko bang gamitin ang Reborn sa maraming browser?",
    faq9A:  "Oo, ngunit kailangan mong i-install ang extension sa bawat browser. Ang premium license ay gumagana sa lahat ng device hangga't naka-login ka sa parehong Google account (maximum na 1 simultaneous na koneksyon).",
    faq10Q: "❓ Ine-save ba ang aking data?",
    faq10A: "Lahat ng setting (mga key, macros, tema, wika) ay naka-imbak nang <strong>lokal</strong> sa iyong browser. Nananatili ang mga ito sa pagitan ng mga session. Gayunpaman, kapag nag-uninstall ng extension, mawawala ang data na ito.",
    faq11Q: "❓ Maaari bang magdulot ng ban ang Reborn?",
    faq11A: "Ang paggamit ng automation tools ay maaaring lumabag sa mga tuntunin ng serbisyo ng ilang serbisyo. <strong>Ikaw lamang ang responsable</strong> sa kung paano mo ginagamit ang Reborn. Suriin ang mga tuntunin ng serbisyo bago gamitin ang tool na ito.",
    faq12Q: "❓ Paano i-cancel ang premium subscription?",
    faq12A: "Maaari kang mag-cancel kahit kailan mula sa Stripe management portal (ang link na natanggap mo sa email pagkatapos ng pagbili). Magkakabisa ang cancellation sa katapusan ng kasalukuyang panahon. Walang bayad sa pagkansela.",
    faq13Q: "❓ Ano ang mangyayari sa habambuhay na plano kung magsara ang serbisyo?",
    faq13A: "Tinitiyak ng habambuhay na plano ang access habang aktibo ang serbisyo. Kapag na-install na, gumagana ang extension nang lokal. Ang pag-verify ng license lamang ang nangangailangan ng koneksyon sa internet.",
    supportH2:    "Kailangan ng Karagdagang Tulong?",
    supportTitle: "📧 Suporta",
    supportText:  "Kung nagpapatuloy ang problema, makipag-ugnayan nang direkta sa aming support team sa pamamagitan ng email. Isama sa iyong mensahe ang:<br><br>• Detalyadong paglalarawan ng problema<br>• Mga hakbang na nasubukan mo na<br>• Mga screenshot kung may kaugnayan<br>• Iyong browser at operating system",
  },

  docPrivacy: {
    h1:       "⚖️ Legal na Impormasyon at Privacy",
    subtitle: "Legal na disclaimer, legal na paunawa, mga kundisyon ng lisensya, patakaran sa privacy",
    navLegal:  "⚖️ Legal na Impormasyon",
    navLicence:"© Lisensya",
    navPrivacy:"🔒 Privacy",
    disclaimerH2:  "⚠️ Legal na Disclaimer",
    disclaimerBox: "<strong>⚠️ Mahalagang Paunawa:</strong> Ang Reborn Assistant ay isang automation tool. Ang paggamit nito ay maaaring lumabag sa mga tuntunin ng serbisyo ng ilang online na serbisyo. Ang paggamit sa tool na ito ay ganap na nasa inyong sariling responsibilidad.",
    respH3:    "Responsibilidad ng Gumagamit",
    respIntro: "Sa paggamit ng Reborn Assistant, kinikilala at tinatanggap mo ang sumusunod:",
    respLi1:   "Ikaw lamang ang responsable para sa paggamit ng software na ito",
    respLi2:   "Susuriin mo ang mga tuntunin ng serbisyo ng bawat serbisyo bago gamitin ang tool na ito",
    respLi3:   "Ang may-akda ay hindi mananagot para sa mga ban, paghihigpit sa account, o legal na aksyon dahil sa paggamit ng Reborn",
    respLi4:   "Ginagamit mo ang software na ito nang malay at sa iyong sariling panganib",
    respLi5:   "Hindi dapat gamitin ang tool na ito sa paraang makapipinsala sa karanasan ng ibang mga gumagamit",
    warrantH3:   "Walang Warranty",
    warrantText: "Ibinibigay ang software «as is» nang walang anumang warranty. Hindi tinitiyak ng may-akda na ang software ay gagana nang walang pagkaantala o error, o na ito ay compatible sa lahat ng serbisyo o browser.",
    legalH2:    "📄 Legal na Paunawa",
    copyrightH3:   "Copyright at Intellectual Property",
    copyrightText: "<strong>© 2026 Reborn Assistant – Lahat ng karapatan ay nakalaan</strong><br>Ginawa ng <strong>Seymoon</strong>",
    copyrightText2:"Lahat ng materyal na nauugnay sa software na ito ay eksklusibong intelektwal na ari-arian ng may-akda. Ang reproduksyon, pagbabago, pamamahagi, o reverse engineering nang walang nakasulat na pahintulot ay mahigpit na ipinagbabawal.",
    liabilityH3:   "Limitasyon ng Responsibilidad",
    liabilityIntro:"Sa anumang kaso, ang may-akda ay hindi mananagot para sa mga claim o pinsala na nagmumula sa paggamit o hindi paggamit ng software, kabilang ngunit hindi limitado sa:",
    liabilityLi1:  "Pagkawala ng data o user account",
    liabilityLi2:  "Mga ban o paghihigpit na ipinataw ng publisher ng serbisyo",
    liabilityLi3:  "Pinsala sa computer system",
    liabilityLi4:  "Mga legal na kahihinatnan ng paggamit na hindi naaayon sa mga tuntunin ng serbisyo",
    dataH3:    "Personal na Data",
    dataText:  "Gumagamit ang Reborn Assistant ng Firebase (Google Cloud) para sa pamamahala ng account at lisensya. Ang nakolektang data ay limitado sa email address at account identifier para lamang sa layunin ng authentication at verification ng lisensya.",
    dataText2: "<strong>Walang activity data ang kinokolekta o ipinapadala.</strong> Ang mga setting ay naka-imbak nang lokal sa iyong device.",
    jurisH3:   "Jurisdiksyon",
    jurisText: "Ang kasunduang ito ay pinamamahalaan ng mga batas na naaangkop sa jurisdiksyon ng tirahan ng may hawak ng copyright. Sa pamamagitan ng pag-install at paggamit ng software na ito, kinikilala mo na nabasa, naunawaan, at tinanggap mo ang lahat ng kundisyong ito.",
    licenceH2:     "© Mga Kundisyon ng Lisensya",
    licenceH3:     "Lisensya sa Paggamit",
    licenceIntro:  "Ang pagbili ng Reborn Assistant plan ay nagbibigay ng personal, non-exclusive, at non-transferable na lisensya para gamitin ang software.",
    licenceAllows: "<strong>Pinapayagan ng lisensyang ito:</strong>",
    licenceLi1:    "Gamitin ang software sa iyong sariling device para sa personal na layunin",
    licenceLi2:    "Samantalahin ang mga update na kasama sa plan",
    licenceForbids:"<strong>Ipinagbabawal ng lisensyang ito:</strong>",
    licenceLi3:    "Muling ipamahagi, ibenta, o ibahagi ang access",
    licenceLi4:    "Baguhin, i-decompile, o i-reverse engineer ang software",
    licenceLi5:    "Gamitin ang software para sa komersyal na layunin nang walang paunang nakasulat na kasunduan",
    licenceLi6:    "Ilipat ang lisensya sa isang third party",
    terminationH3:   "Pagwawakas",
    terminationText: "Sa paglabag sa mga kundisyong ito, maaaring agad na wakasan ang lisensya. Para sa mga subscription plan, maaari kang mag-cancel kahit kailan mula sa Stripe portal.",
    refundBox: "<strong>✅ Patakaran sa Refund:</strong> Kung hindi ka nasiyahan sa loob ng 7 araw pagkatapos ng pagbili, makipag-ugnayan sa suporta para sa buong refund. Pagkatapos ng panahong ito, hindi na maibabalik ang bayad maliban sa mga pambihirang kaso.",
    privacyH1:      "🔒 Patakaran sa Privacy",
    privacySubtitle:"Paano namin pinoprotektahan ang iyong personal na data",
    privacyBox:     "<strong>✅ Ang iyong privacy ang aming pangunahing priyoridad</strong><br>Libreng bersyon: Walang personal na data ang kinokolekta. Premium na bersyon: Ang data na mahigpit na kinakailangan para sa pag-verify ng lisensya lamang ang pinoproseso.",
    collectH2:        "Koleksyon ng Data",
    collectFreeH3:    "Libreng Bersyon",
    collectFreeText:  "Walang personal na data ang kinokolekta o ipinapadala. Lahat ng kagustuhan ay naka-imbak nang lokal lamang sa iyong device.",
    collectPremH3:    "Premium na Bersyon",
    collectPremIntro: "Para i-verify ang lisensya at protektahan ang account, pinoproseso ang sumusunod na data:",
    collectPremLi1:   "Email address ng Google (sa pamamagitan ng Google authentication)",
    collectPremLi2:   "Natatanging device identifier (lokal na ginawa)",
    collectPremLi3:   "Status ng subscription at session timestamp",
    collectPremLi4:   "Hanggang 2 registered na device bawat account",
    collectPremBasis: "<strong>Legal na batayan:</strong> Pagganap ng kontrata (GDPR Article 6.1.b).",
    collectNotH3:     "Data na Hindi Kailanman Kinokolekta",
    collectNotLi1:    "❌ Walang data sa laro o aktibidad",
    collectNotLi2:    "❌ Walang kasaysayan ng browser",
    collectNotLi3:    "❌ Walang advertising o tracking cookies",
    localH2:    "Data na Naka-imbak nang Lokal",
    localIntro: "Ang sumusunod na impormasyon ay naka-imbak <strong>sa iyong device lamang</strong>:",
    localLi1:   "<strong>Kagustuhan sa wika</strong>: Napiling wika ng interface",
    localLi2:   "<strong>Napiling visual na tema</strong>: Napiling tema mula sa 6",
    localLi3:   "<strong>Mga na-configure na keyboard shortcut</strong>: Mga key na itinalaga sa mga aksyon",
    localLi4:   "<strong>Mga custom na timer interval</strong>: Mga timer na nakatakda para sa macros",
    localLi5:   "<strong>Posisyon ng interface</strong>: Lokasyon ng Reborn panel sa screen",
    localLi6:   "<strong>License cache (premium)</strong>: Device identifier at status ng subscription para maiwasang mag-verify sa bawat pagsisimula",
    thirdH2:       "Mga Serbisyo ng Third Party",
    thirdH3:       "Mga Serbisyong Ginagamit (Premium na Bersyon)",
    thirdDesc:     "Para sa authentication at pagbabayad, gumagamit ang Reborn Assistant ng:",
    thirdLi1:      "🔐 <strong>Google</strong> — Authentication at ligtas na pag-imbak ng data ng lisensya",
    thirdLi2:      "💳 <strong>Stripe</strong> — Pagproseso ng mga premium na pagbabayad (ang impormasyon ng bangko ay hindi kailanman dadaan sa aming server)",
    thirdTransfer: "Ang mga provider na ito ay sumusunod sa GDPR at may angkop na mga proteksyon para sa internasyonal na paglipat ng data.",
    thirdNoH3:     "Walang Tracking, Walang Advertising",
    thirdLi3:      "❌ Walang analytics o statistical services",
    thirdLi4:      "❌ Walang advertising o targeted marketing",
    thirdLi5:      "❌ Walang third-party cookies o behavioral tracking",
    authH2:    "Authentication at Pamamahala ng Device",
    authH3:    "Pag-login gamit ang Google (Premium na Bersyon)",
    authText:  "Ang Google account ay ginagamit lamang para sa pag-verify ng pagkakakilanlan at pag-check ng lisensya. Ang mga device ay inirehistro sa isang ligtas na system (maximum na 2 device bawat account).",
    authText2: "Makakatanggap ka ng notification kung ang iyong account ay ginagamit mula sa hindi kilalang device. Ang mga registered na device ay maaaring pamahalaan nang direkta mula sa extension.",
    payH2:    "Ligtas na Pagbabayad",
    payText:  "Ang mga premium na pagbabayad ay pinoproseso ng <strong>Stripe</strong>. Ang impormasyon ng bangko ay <strong>hindi kailanman</strong> dumadaan sa aming mga server. <strong>Hindi kami nag-iimbak ng anumang data ng credit card.</strong>",
    retentionH2:   "Panahon ng Pagtago",
    retentionText: "Ang data ay tinatago lamang sa loob ng kinakailangang panahon:",
    retentionLi1:  "<strong>Aktibong account:</strong> Data na tinatago sa buong panahon ng subscription",
    retentionLi2:  "<strong>Pagkatapos ng pagkansela:</strong> Tinanggal sa loob ng 30 araw",
    retentionLi3:  "<strong>Lokal na data:</strong> Agad na tinanggal kapag nag-uninstall ng extension",
    rightsH2:      "Iyong mga Karapatan (GDPR)",
    rightsText:    "Sa ilalim ng GDPR, mayroon kang mga sumusunod na karapatan patungkol sa iyong data:",
    rightsLi1:     "✅ <strong>Access</strong> — Makatanggap ng kopya ng iyong personal na data",
    rightsLi2:     "✅ <strong>Pagwawasto</strong> — Baguhin ang hindi tamang data",
    rightsLi3:     "✅ <strong>Pagtanggal</strong> — Humiling ng pagtanggal ng iyong account at data",
    rightsLi4:     "✅ <strong>Portability</strong> — Makatanggap ng iyong data sa nababasang format",
    rightsLi5:     "✅ <strong>Reklamo</strong> — Magreklamo sa pambansang awtoridad ng proteksyon ng data",
    rightsExercise:"Para gamitin ang mga karapatang ito, makipag-ugnayan sa: seymoon.cell@gmail.com o Discord (Seymoon)",
    deleteH2:    "Pagtanggal ng Data",
    deleteText1: "<strong>1. Pag-uninstall ng Extension</strong><br>Ang pag-uninstall ng Reborn Assistant ay awtomatikong nagtatanggal ng lahat ng lokal na data.",
    deleteText2: "<strong>2. Manu-manong Reset</strong><br>Maaari kang mag-reset ng iyong mga setting kahit kailan mula sa Reborn interface.",
    deleteText3: "<strong>3. Pagtanggal ng Account (Premium)</strong><br>Para tanggalin ang lahat ng data na nauugnay sa iyong premium account, makipag-ugnayan sa amin sa pamamagitan ng email.",
    contactH2:   "Makipag-ugnayan",
    contactText: "Para sa mga tanong tungkol sa legal na impormasyon o patakaran sa privacy:",
    changelogH2: "📋 Changelog",
    v130H3:          "Bersyon 1.3.0 (Marso 2026) · Kasalukuyan",
    v130newLabel:    "✨ Mga Bago",
    v130improvLabel: "🔧 Mga Pagpapabuti",
    v130fixLabel:    "🐛 Mga Ayos",
    v130Li1:  "⏱ Draggable na floating mini-timer — maliit na floating window na nagpapakita ng mga buff timer at mga timer na higit sa 1 minuto, awtomatikong muli itong bubukas sa susunod na paglulunsad at sumusunod sa aktibong skin.",
    v130Li2:  "⚡ Priority na mga macro — nag-eexecute ang mga macro bago ang mga heal/HP/mana, na may 0.5s na heal freeze bago at pagkatapos ng bawat execution para maiwasan ang mga salungatan.",
    v130Li3:  "🧠 Matalinong pamamahala ng buff — ang buff ay nag-eexecute muna, ang mga naka-mute na macro ay naka-queue at awtomatikong nire-restart pagkatapos nito (bawas na delay sa 2s).",
    v130Li4:  "💾 Pagtatandaan ng posisyon — ang mga floating na window ay nagtatandaan ng kanilang posisyon sa pagitan ng mga session.",
    v130Li5:  "🇸🇦 Suporta sa Arabe — ika-14 na wika sa extension.",
    v130Li6:  "💳 Stripe na pagbabayad sa popup — nagbubukas sa isang dedicated na window na may auto-close, nang hindi umaalis sa extension.",
    v130Li7:  "🐾 Pet: naayos ang bug kung saan hindi lumalabas ang pet sa unang buff + mas mahusay na pagsubaybay sa F1/F2 mode para sa pag-iimbak sa stop.",
    v130Li8:  "⏱ Timer: visual na muling disenyo ng premium na disenyo + opacity 55% sa pahinga → 95% sa hover para sa mas mahusay na pagiging nababasa.",
    v130Li9:  "💳 Billing portal: isang aktibong window sa memorya na may awtomatikong pagsasara.",
    v130Li10:  "Naayos ang ilang memory leak sa content at popup.",
    v130Li16:  "UI na pagkakatugma sa limitasyon ng max 2 device (kaayon sa backend).",
    v120H3:  "Bersyon 1.2.0 (Marso 2026)",
    v120Li1: "✨ 6 na skin ang nire-redesign na may banayad na transparent na epekto.",
    v120Li2: "🔐 Tingnan at pamahalaan ang mga registered na device nang direkta mula sa extension.",
    v120Li3: "💳 Mag-access ng subscription sa isang click mula sa extension.",
    v120Li4: "🔔 Agarang notification kung ang iyong account ay ginagamit mula sa ibang device.",
    v12H3:   "Bersyon 1.2 (Pebrero 2026)",
    v12Li1:  "Suporta sa 15 na wika (idinagdag ang Turkish 🇹🇷)",
    v12Li2:  "Visual na redesign ng website",
    v12Li3:  "Pagsasama ng legal na mga pahina sa isang unified na pahina",
    v12Li4:  "Kumpletong FR/EN na pagsasalin ng site",
    v11H3:   "Bersyon 1.1.1 (Pebrero 2026)",
    v11Li1:  "Idinagdag ang Auto Periodic Macro (15 segundo + auto save)",
    v11Li2:  "Mga Keyboard Shortcut CTRL+A / CTRL+O",
    v11Li3:  "Suporta sa 15 na wika (idinagdag ang Filipino at Turkish)",
    v11Li4:  "Napabuting katatagan ng premium license",
    v11Li5:  "Naitama ang bug sa sequence rotation",
    v10H3:   "Bersyon 1.0 (2025) · Paunang",
    v10Li1:  "Paglulunsad ng Reborn Assistant",
    v10Li2:  "Auto Actions Type 1 at 2",
    v10Li3:  "Auto Sequence Rotation (F2 → 1-9 → 0 → F1)",
    v10Li4:  "3 Custom Macros",
    v10Li5:  "6 na visual na tema at 12 na wika",
    v10Li6:  "Sistema ng premium license sa pamamagitan ng Firebase",
    pageFooter:"© 2026 Reborn Assistant — Ginawa ng Seymoon · Lahat ng karapatan ay nakalaan",
  },
  nav: {
    docsFull:    "📚 Dokumentasyon",
    docsShort:   "📚 Docs",
    manageFull:  "Pamahalaan ang subscription",
    manageShort: "Pamahalaan",
  },
};