export default {
  hero: {
    description: "Gelişmiş makrolarla tarayıcı otomasyon uzantısı. Tekrarlayan eylemlerinizi, kısayollarınızı ve dizilerinizi otomatikleştirerek verimliliğinizi optimize edin.",
    ctaPrimary: "Şimdi başla",
    ctaSecondary: "Daha fazla bilgi",
    trust1: "Ücretsiz sürüm mevcut",
    trust2: "Taahhüt yok",
    trust3: "%100 güvenli ödeme",
    trust4: "Otomatik güncellemeler",
  },
  features: {
    tag: "Beceriler & Yetenekler",
    titleBefore: "İhtiyacınız olan ",
    titleEm: "her şey",
    subtitle: "Reborn Assistant'ın olağanüstü yeteneklerini keşfedin.",
    card1: { badge: "Aktif",    title: "Tam Otomasyon",              description: "Tam otomasyon için tuş makroları, otomatik diziler ve yapılandırılabilir eylemler." },
    card2: { badge: "Pasif",    title: "Maksimum Güvenlik",          description: "Verileriniz yerel kalır. İzleme yok, telemetri yok." },
    card3: { badge: "Aktif",    title: "Özelleştirilebilir Makrolar",description: "Otomatik tetikleyiciler ve klavye kısayollarıyla 3 yapılandırılabilir makro." },
    card4: { badge: "Pasif",    title: "Özelleştirilebilir Arayüz",  description: "6 tema arasından seçin ve arayüzü ihtiyaçlarınıza göre uyarlayın." },
    card5: { badge: "Pasif",    title: "Çok Dilli",                  description: "15 dilde mevcuttur. Yerelleştirilmiş arayüzlerle dünya genelinde destek." },
    card6: { badge: "Ücretsiz", title: "Ücretsiz Sürüm",             description: "Dahil temel özelliklerle ücretsiz deneyin." },
  },
  security: {
    tag: "Güvenlik",
    titleBefore: "Profesyonel düzeyde ",
    titleEm: "güvenlik",
    titleAfter: "",
    description: "Reborn Assistant, dünya genelindeki yayın platformlarıyla aynı güvenlik standartlarını kullanır. Kimlik bilgileriniz <strong style='color:var(--gold);'>JWT şifrelemesiyle</strong> korunur, ödemeleriniz <strong style='color:var(--gold);'>Stripe</strong> aracılığıyla güvence altına alınır ve verileriniz <strong style='color:var(--gold);'>%100 yerel</strong> kalır. İzleme yok, veri satışı yok.",
    card1Title: "JWT Şifrelemesi",
    card1Text:  "Bankacılık düzeyinde güvenli kimlik doğrulama",
    card2Title: "Stripe ile Ödeme",
    card2Text:  "Amazon ve Google tarafından kullanılan işlemci",
    card3Title: "Sıfır İzleme",
    card3Text:  "Verileriniz asla cihazınızı terk etmez",
    card4Text:  "Güvenli Google Cloud altyapısı",
  },
  pricing: {
    tag:         "Sınıfını Seç",
    titleBefore: "Rütbenizi ",
    titleEm:     "seçin",
    subtitle:    "Size en uygun planı seçin. Taahhüt yok.",
    voyageur: {
      rank: "Rütbe I · Gezgin", plan: "Ücretsiz", period: "sonsuza kadar",
      feat1: "İyileştirme makrosu", feat2: "6 görsel tema", feat3: "15 dil mevcut", feat4: "Kayan arayüz",
      btn: "Başla", download: "Chrome'a ekle", guarantee: "🔒 Sonsuza kadar ücretsiz",
    },
    aventurier: {
      rank: "Rütbe II · Maceracı", plan: "Aylık", period: "aylık",
      feat1: "Tüm Premium özellikler", feat2: "Öncelikli destek", feat3: "Ücretsiz güncellemeler",
      btn: "Ücretsiz Dene", guarantee: "🎁 7 gün ücretsiz · Banka kartı gerekmez",
      download: "Chrome'a ekle",
    },
    champion: {
      badge: "⭐ Popüler -%17",
      rank: "Rütbe III · Şampiyon", plan: "Yıllık", period: "yıllık · 2,50€/ay",
      feat1: "Tüm Premium özellikler", feat2: "Öncelikli destek", feat3: "Ücretsiz güncellemeler",
      btn: "Ücretsiz Dene", guarantee: "🎁 7 gün ücretsiz · Banka kartı gerekmez",
      download: "Chrome'a ekle",
    },
    legende: {
      badge: "⚡ Sınırlı Teklif",
      rank: "Rütbe IV · Efsane", plan: "Ömür Boyu", period: "tek seferlik ödeme · bir daha asla",
      feat1: "Ömür boyu erişim", feat2: "Tüm gelecek güncellemeler", feat3: "Özel premium destek", feat4: "En iyi fiyat-performans oranı",
      btn: "Satın Al", guarantee: "🔒 Tek seferlik ödeme · Ömür boyu erişim garantisi",
      download: "Chrome'a ekle",
    },
  },
  stats: {
    label1: "Mevcut diller", label2: "Görsel temalar", label3: "Yerel veri", label4: "Aktif uzantı",
  },
  trust: {
    badge1: "Güvenli SSL ödemesi", badge2: "Anında erişim", badge3: "%100 özel veri", badge4: "Hızlı destek",
  },
  store: {
    status: "Resmi uzantı",
    title:  "Chrome Web Store'da mevcut",
    install: "Yükle",
    available: "Ücretsiz mevcut · Google tarafından doğrulanmış resmi uzantı",
  },
  faq: {
    titleBefore: "Sıkça sorulan ",
    titleEm:     "sorular",
    subtitle:    "Başlamadan önce bilmeniz gereken her şey.",
    q1: "Ücretsiz deneme banka kartı gerektiriyor mu?",
    a1: "Hayır, banka kartı gerekmez. İlk 7 gün taahhüt olmaksızın tamamen ücretsizdir. Hemen başlamak için hesabınızı oluşturmanız yeterlidir.",
    q2: "İstediğim zaman plan değiştirebilir miyim?",
    a2: "Evet, hesabınızdan istediğiniz zaman daha yüksek veya düşük bir plana geçebilirsiniz. Değişiklik ücreti yok.",
    q3: "Ömür Boyu planı gerçekten tüm gelecek güncellemeleri kapsıyor mu?",
    a3: "Kesinlikle. Ömür Boyu planı, herhangi bir ek ödeme yapmadan tüm gelecek güncellemelere ve yeni özelliklere erişimi garanti eder.",
    q4: "Verilerim güvende mi?",
    a4: "Tüm verileriniz cihazınızda yerel olarak depolanır. Kişisel veri toplamıyoruz, izleme veya telemetri kullanmıyoruz.",
    q5: "Destekle nasıl iletişime geçebilirim?",
    a5: "seymoon@constellation-89.fr e-posta adresinden veya Discord'da (Seymoon) bizimle iletişime geçin. Premium aboneler öncelikli yanıt alır.",
    q6: "Reborn Assistant bir bot mu?",
    a6: "Hayır, Reborn Assistant bir bot değildir. Kendi tanımladığınız tuş dizilerini otomatikleştiren, yapılandırılabilir makrolar içeren bir uzantıdır. Yapay zeka yok, oyun sunucusuyla etkileşim yok, bellek okuma yok. Uzantı oyun verilerini ne okur ne de değiştirir — yalnızca manuel olarak basacağınız tuşları simüle eder. Oynamak için bilgisayarınızın başında kalmalısınız: Reborn Assistant captcha çözmez, karakterinizi diriltmez ve öldükten sonra sizi spota geri götürmez. Sizi yerinize koymak için değil, oyununuzu kolaylaştırmak için bir araçtır.",
  },
  footer: {
    privacy:   "Gizlilik",
    terms:     "Kullanım Koşulları",
    copyright: "© 2026 Reborn Assistant. Tüm hakları saklıdır.<br>Seymoon tarafından geliştirildi",
  },

  docsNav: {
    backToDocs:      "← Belgelere dön",
    mainSite:        "⌂ Ana site",
    backToMainSite:  "← Ana siteye dön",
    footer:          "© 2026 Reborn Assistant — Seymoon tarafından geliştirildi · Tüm hakları saklıdır",
  },

  docsHome: {
    version:              "SÜRÜM 1.3.3 · TAM BELGELER",
    userGuide:            "Kullanıcı kılavuzu",
    support:              "Destek",
    legal:                "Hukuki bilgiler",
    quickstartTitle:      "Hızlı Başlangıç",
    quickstartDesc:       "Reborn Assistant ile kurulum, ilk yapılandırma ve ilk adımlar.",
    featuresTitle:        "Özellikler",
    featuresDesc:         "Karşılaştırma tablosuyla ücretsiz ve Premium özelliklerin tam açıklaması.",
    premiumTitle:         "Premium Kılavuzu",
    premiumDesc:          "Otomatik diziler, özelleştirilebilir makrolar ve periyodik makro.",
    interfaceTitle:       "Arayüz & Kişiselleştirme",
    interfaceDesc:        "Görsel temalar, diller ve kişiselleştirme seçenekleri.",
    troubleshootingTitle: "Sorun giderme",
    troubleshootingDesc:  "Yaygın sorunların çözümleri, sıkça sorulan sorular ve performans optimizasyonu.",
    legalTitle:           "Hukuki & Gizlilik",
    legalDesc:            "Yasal uyarı, yasal bildirimler, lisans koşulları, gizlilik politikası ve değişiklik günlüğü.",
    footer:               "© 2026 Reborn Assistant — Seymoon tarafından geliştirildi · Tüm hakları saklıdır",
  },

  docFeatures: {
    h1:        "⚡ Özellikler",
    subtitle:  "Reborn Assistant'ın sizin için yapabileceği her şeyi keşfedin",
    h2Free:    "ÜCRETSİZ Özellikler",
    freeBadge: "ÜCRETSİZ",
    c1Title: "Otomatik tip 1 eylemi",
    c1Desc:  "Yapılandırılabilir zamanlayıcıya göre tip 1 eyleminizi (HP) otomatik olarak etkinleştirir.",
    c1li1:   "Yapılandırılabilir eylem zamanlayıcısı",
    c1li2:   "Arka planda çalışır",
    c2Title: "Görsel temalar",
    c2Desc:  "6 farklı temayla arayüzün görünümünü özelleştirin.",
    c2li1:   "MMO Gold (varsayılan)",
    c2li2:   "Karanlık Mod & Beyaz Mod",
    c3Title: "Çok dilli",
    c3Desc:  "Uluslararası bir deneyim için 15 dilde mevcut arayüz.",
    c3li3:   "Anında geçiş",
    h2Premium: "PREMIUM Özellikler 💎",
    p1Title: "Otomatik tetikleyici 1 makrosu",
    p1Desc:  "Yapılandırılabilir zamanlayıcıya göre tip 1 eyleminizin (HP) otomatik aktivasyonu.",
    p1li1:   "Yapılandırılabilir tetikleyici 1 zamanlayıcısı",
    p1li2:   "Yapılandırılabilir kısayol tuşu",
    p1li3:   "Arka planda çalışır",
    p2Title: "Otomatik tetikleyici 2 makrosu",
    p2Desc:  "Yapılandırılabilir zamanlayıcıya göre tip 2 eylemlerinizin otomatik kullanımı.",
    p2li1:   "Yapılandırılabilir tetikleyici 2 zamanlayıcısı",
    p2li2:   "Yapılandırılabilir kısayol tuşu",
    p2li3:   "Arka planda çalışır",
    p3Title: "Klavye kısayolları",
    p3Desc:  "Özelleştirilebilir global kısayollarla Reborn Assistant'ı anında kontrol edin.",
    p3li1:   "CTRL+A: Otomasyonu başlat",
    p3li2:   "CTRL+O: Otomasyonu durdur",
    p4Title: "Dizi rotasyonu",
    p4Desc:  "Önceden tanımlanmış bir diziyle otomatik dizi bakım sistemi.",
    p4li1:   "Dizi: F2 → 1-9 → 0 → F1",
    p4li2:   "Yapılandırılabilir aralık (dakika)",
    p4li3:   "Tuşlar arası ayarlanabilir gecikme",
    p5Title: "Özelleştirilebilir Makrolar",
    p5Desc:  "Kendi tuş dizilerinizle en fazla 3 makro oluşturun.",
    p5li1:   "3 bağımsız makro",
    p5li2:   "Özel diziler",
    p5li3:   "Ayarlanabilir tekrar aralıkları",
    p6Title: "Periyodik makro",
    p6Desc:  "Periyodik makronuzu her 15 saniyede bir otomatik çağırma ve kaydetme.",
    p6li1:   "Periyodik makronun otomatik çağrılması",
    p6li2:   "Çağrı sonrası otomatik kaydetme",
    p6li3:   "15 saniyelik sabit aralık",
    tableH2:      "Karşılaştırma tablosu",
    tableFeature: "Özellik",
    tableFree:    "Ücretsiz",
    row1:  "Otomatik tip 1 eylemi (HP)",
    row2:  "Görsel temalar (6)",
    row3:  "Çok dilli (15)",
    row4:  "Otomatik tetikleyici 1 makrosu",
    row5:  "Otomatik tetikleyici 2 makrosu",
    row6:  "Klavye kısayolları (CTRL+A / CTRL+O)",
    row7:  "Otomatik dizi rotasyonu",
    row8:  "Özelleştirilebilir makrolar (3x)",
    row9:  "Otomatik periyodik makro",
    learnMore: "→ Premium özellikler hakkında daha fazla bilgi",
  },

  docQuickstart: {
    h1:       "🚀 Hızlı Başlangıç",
    subtitle: "Reborn Assistant'ı birkaç dakikada yükleyin ve yapılandırın",
    reqH2:    "Gereksinimler",
    req1:     "<strong>Uyumlu tarayıcı:</strong> Google Chrome, Microsoft Edge, Brave veya Chromium tabanlı herhangi bir tarayıcı",
    req2:     "<strong>Google hesabı:</strong> Yalnızca Premium kimlik doğrulaması için gereklidir (ücretsiz sürüm için isteğe bağlı)",
    req3:     "<strong>Uyumlu site:</strong> Standart web siteleriyle uyumlu",
    installH2:  "Kurulum",
    step1Title: "Chrome Web Store'u ziyaret edin",
    step1p:     "<a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome Web Store</a>'daki Reborn Assistant sayfasına gidin ve <strong>«Chrome'a ekle»</strong> düğmesine tıklayın.",
    step1tip:   "💡 Google Chrome, Microsoft Edge, Brave ve Chromium tabanlı herhangi bir tarayıcıyla uyumludur.",
    step2Title: "Kurulumu onaylayın",
    step2p:     "Onay penceresinde <strong>«Uzantı ekle»</strong> düğmesine tıklayın. Uzantı otomatik olarak yüklenir.",
    step3Title: "Uzantıyı sabitleyin",
    step3p:     "Tarayıcı araç çubuğundaki bulmaca simgesine 🧩 tıklayın ve hızlı erişim için Reborn Assistant'ı sabitleyin.",
    step4Title: "Giriş yapın (Premium için isteğe bağlı)",
    step4p:     "• Araç çubuğundaki Reborn simgesine tıklayın<br>• Premium için: Google hesabınızla giriş yapın<br>• Ücretsiz için: Giriş yapmadan doğrudan kullanın",
    alertTitle: "✅ Kurulum başarılı!",
    alertText:  "Uzantı aktifken Reborn simgesi yeşile döner. Artık özelliklerinizi yapılandırabilirsiniz.",
    configH2:   "İlk yapılandırma",
    freeH3:     "ÜCRETSİZ Sürüm",
    freeTitle:  "<strong>Giriş yapmadan kullanılabilen özellikler:</strong>",
    freeText:   "• Otomatik tip 1 eylemi (yalnızca HP)<br>• 6 görsel tema<br>• 15 dil desteği",
    freeStepTitle: "Otomatik tip 1 eylemini yapılandırın",
    freeStepText:  "1. Reborn panelini açın (simgeye tıklayın)<br>2. HP eylem zamanlayıcısını ayarlayın (varsayılan: 2sn)<br>3. Eylem otomatik olarak etkinleşir<br>4. Giriş gerekmez",
    premiumH3:       "PREMIUM Sürüm 💎",
    premiumFeatTitle:"<strong>Ek özellikler (Google girişi gerektirir):</strong>",
    premiumFeatText: "• Otomatik tetikleyici 1 makrosu (yapılandırılabilir zamanlayıcı + kısayol)<br>• Otomatik tetikleyici 2 makrosu (yapılandırılabilir zamanlayıcı + kısayol)<br>• Klavye kısayolları (CTRL+A / CTRL+O)<br>• Otomatik dizi rotasyonu (F2 → 1-9 → 0 → F1)<br>• Tuş dizileriyle 3 özelleştirilebilir makro<br>• Otomatik periyodik makro sistemi (her 15sn'de çağırma + kaydetme)",
    premConfigTitle: "Premium Yapılandırma",
    premConfigSeq:   "<strong>Otomatik diziler:</strong><br>• Panelde «Dizi Rotasyonu»nu etkinleştirin<br>• Döngüler arası aralığı yapılandırın (varsayılan: 5 dk)<br>• Her tuş arası gecikmeyi ayarlayın (varsayılan: 1sn)",
    premConfigMacro: "<strong>Makrolar:</strong><br>• Makro 1, 2 veya 3'ü etkinleştirin<br>• Tuş dizisini tanımlayın (örn. <code>1,2,3,4</code>)<br>• Tekrar aralığını yapılandırın",
    premConfigPer:   "<strong>Periyodik makro:</strong><br>• «Periyodik makro» anahtarını etkinleştirin<br>• Sistem periyodik makronuzu her 15sn'de otomatik çağırır<br>• Çağrı sonrası otomatik kaydetme",
    warnTitle: "⚠️ Önemli not",
    warnText:  "Premium özellikler (Tetikleyici makrolar 1 ve 2, Otomatik diziler, Otomatik periyodik makro, 3 yapılandırılabilir makro) geçerli bir Premium lisansı ve Google girişi gerektirir. Lisans olmadan yalnızca temel makro kullanılabilir.",
    shortcutsH2:   "Klavye kısayolları",
    shortcutsText: "<code>CTRL + A</code>: Otomasyonu başlat<br><code>CTRL + O</code>: Otomasyonu durdur",
    nextH2: "Sonraki adımlar",
    link1:  "Tüm özellikleri keşfedin",
    link2:  "Tam Premium kılavuzu",
    link3:  "Yaygın sorunların çözümleri",
  },

  docInterface: {
    h1:       "🎨 Arayüz & Kişiselleştirme",
    subtitle: "Reborn Assistant'ı tercihlerinize göre özelleştirin",
    themesH2:    "Görsel temalar",
    themesDesc:  "Reborn Assistant, arayüzün görünümünü kişiselleştirmek için 6 tema sunar:",
    changeThemeH3:   "Tema değiştirme",
    changeThemeText: "1. Reborn panelini açın<br>2. \"⚙️ AYARLAR\" sekmesine tıklayın<br>3. Açılır menüden temanızı seçin<br>4. Değişiklik anındadır",
    langsH2:    "Mevcut diller",
    langsDesc:  "15 dilde mevcut arayüz:",
    changeLangH3:   "Dil değiştirme",
    changeLangText: "1. Reborn panelini açın<br>2. \"⚙️ AYARLAR\"a tıklayın<br>3. Açılır menüden dilinizi seçin<br>4. Arayüzün tamamı anında çevrilir",
    shortcutsH2:   "Klavye kısayolları",
    shortcutsDesc: "Reborn Assistant hızlı kontrol için global kısayollar içerir:",
    systemH3: "Sistem kısayolları",
    sysSC1:   "<code>CTRL + A</code>: Otomasyonu başlat",
    sysSC2:   "<code>CTRL + O</code>: Otomasyonu durdur",
    customH3:   "Özelleştirilebilir kısayollar",
    customDesc: "Şunlar için tuşları yapılandırabilirsiniz:",
    customLi1:  "Tip 1 ve 2 eylemleri",
    customLi2:  "Makrolar (tuş dizileri)",
    customLi3:  "Periyodik makro",
    displayH2:    "Görüntüleme seçenekleri",
    panelPosH3:   "Panel konumu",
    panelPosDesc: "Reborn paneli sürüklenebilir:",
    panelLi1: "Panel başlığına tıklayın",
    panelLi2: "Basılı tutun ve sürükleyin",
    panelLi3: "İstediğiniz yere bırakın",
    panelLi4: "Konum otomatik olarak kaydedilir",
    opacityH3:   "Panel saydamlığı",
    opacityDesc: "İstatistiklerinizi kontrol ederken gezinmeye müdahale etmemek için saydamlığı ayarlayın.",
    logH3:   "Etkinlik günlüğü",
    logDesc: "Günlük, gerçek zamanlı olarak tüm gerçekleştirilen eylemleri gösterir:",
    logLi1:  "Sistemlerin etkinleştirilmesi/devre dışı bırakılması",
    logLi2:  "İksir kullanımı",
    logLi3:  "Makro ve dizi yürütme",
    logLi4:  "Periyodik makro çağrıları",
    logLi5:  "Olası hatalar",
    saveH2:    "Ayarların kaydedilmesi",
    saveDesc:  "Tüm ayarlarınız otomatik olarak yerel kaydedilir:",
    saveLi1:   "Seçilen tema",
    saveLi2:   "Arayüz dili",
    saveLi3:   "Aktivasyon eşikleri",
    saveLi4:   "Atanan tuşlar",
    saveLi5:   "Makro yapılandırması",
    saveLi6:   "Panel konumu",
    savePersist: "Tarayıcıyı kapatsanız bile oturumlar arasında korunur.",
  },

  docPremium: {
    h1:       "💎 Premium Kılavuzu",
    subtitle: "Reborn Assistant'ın tüm gelişmiş özelliklerinde ustalaşın",
    rotH2:    "🛡️ Otomatik dizi rotasyonu",
    rotDesc:  "Rotasyon sistemi, düzenli aralıklarla önceden tanımlanmış bir tuş dizisine basarak tüm dizilerinizi otomatik olarak aktif tutar.",
    rotSeqH3:   "Tuş dizisi",
    rotSeqText: "Rotasyon her zaman bu sabit sırayı takip eder:",
    rotConfigH3:   "Yapılandırma",
    rotIntName:    "Döngüler arası aralık",
    rotIntDesc:    "Tüm diziyi yeniden başlatmadan önceki bekleme süresi. Varsayılan: 5 dakika. En kısa dizilerinizin süresine göre ayarlayın.",
    rotDelName:    "Tuşlar arası gecikme",
    rotDelDesc:    "Dizinin her tuşu arasındaki bekleme süresi. Varsayılan: 1 saniye. Hizmet hızına göre ayarlayın (animasyonlar, bekleme süreleri...).",
    rotExTitle:    "💡 Kullanım örneği",
    rotExScenario: "<strong>Senaryo:</strong> Dizileriniz 5 dakika sürüyor ve 1-8 tuşlarında 8 diziniz var.",
    rotExConfig:   "<strong>Yapılandırma:</strong>",
    rotExLi1:      "Aralık: 5 dakika",
    rotExLi2:      "Gecikme: 1 saniye",
    rotExLi3:      "Uzantı her 5 dakikada bir F2, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, F1 tuşlarına basacak",
    rotExLi4:      "Toplam 13 tuş, her biri arasında 1 saniye = döngü başına ~13 saniye",
    macH2:    "⚙️ Özelleştirilebilir Makrolar",
    macDesc:  "Kendi tuş dizilerinizle en fazla 3 bağımsız makro oluşturun. Tekrarlayan görevleri, tekrarlayan kombinasyonları veya yetenek rotasyonlarını otomatikleştirmek için mükemmel.",
    macHowH3:   "Nasıl çalışır",
    macHowText: "Her makro, diğer sistemlerden bağımsız olarak düzenli aralıklarla bir tuş dizisi yürütür.",
    macConfigH3:  "Yapılandırma",
    macSeqName:   "Tuş dizisi",
    macSeqDesc:   "Virgülle ayrılmış sırayla basılacak tuşları tanımlayın. Örnek: 1,2,3,4 veya q,w,e,r,f",
    macRepName:   "Tekrar aralığı",
    macRepDesc:   "Diziyi tekrarlamadan önceki bekleme süresi. İhtiyaçlarınıza göre yapılandırın (saniye veya dakika).",
    macDelName:   "Tuşlar arası gecikme",
    macDelDesc:   "Dizinin her tuşu arasındaki bekleme süresi (genellikle 0,5 ile 2 saniye).",
    macExTitle:   "💡 Kullanım örnekleri",
    mac1Title:    "<strong>Makro 1 – Tekrarlayan otomasyon:</strong>",
    mac1Li1:      "Dizi: 1,2,3,space",
    mac1Li2:      "Aralık: 10 saniye",
    mac1Li3:      "Kullanım: Döngüde temel saldırı rotasyonu",
    mac2Title:    "<strong>Makro 2 – Yetenek kombinasyonu:</strong>",
    mac2Li1:      "Dizi: q,w,e,r",
    mac2Li2:      "Aralık: 30 saniye",
    mac2Li3:      "Kullanım: Optimum DPS rotasyonu",
    mac3Title:    "<strong>Makro 3 – Otomatik destek:</strong>",
    mac3Li1:      "Dizi: f,g,h",
    mac3Li2:      "Aralık: 15 saniye",
    mac3Li3:      "Kullanım: Grup dizileri veya periyodik eylemler",
    perH2:    "🐉 Periyodik makro",
    perDesc:  "Bu sistem her 15 saniyede bir otomatik olarak periyodik bir eylem gerçekleştirir. Düzenli olarak etkinleştirilmesi gereken tekrarlayan görevler için idealdir.",
    perHowH3:   "Nasıl çalışır",
    perHowText: "Sistem bu diziyi her 15 saniyede bir otomatik olarak yürütür:",
    perLi1:     "Periyodik makroyu çağırır (yapılandırılabilir tuş, varsayılan §)",
    perLi2:     "500ms bekler",
    perLi3:     "Periyodik makroyu otomatik olarak kaydeder",
    perConfigH3:  "Yapılandırma",
    perCallName:  "Çağrı tuşu",
    perCallDesc:  "Periyodik makronuzu etkinleştiren tuş. Varsayılan: §. Yapılandırmanıza göre değiştirin.",
    perIntName:   "Aralık (sabit)",
    perIntDesc:   "Sistem her zaman 15 saniyelik sabit bir aralık kullanır. Yapılandırılamaz.",
    perExTitle:   "💡 Kullanım durumu",
    perExText:    "Bazı hizmetlerde eşya toplamak, geçici diziler sağlamak veya deneyim kazanmak için periyodik makronun düzenli olarak çağrılması gerekir. Bu sistem bu süreci tamamen otomatikleştirir.",
    perImpH3:     "⚠️ Önemli",
    perImpLi1:    "Yapılandırılan tuşun çağrı tuşunuza karşılık geldiğini doğrulayın",
    perImpLi2:    "Periyodik makro her çağrıdan sonra otomatik olarak kaydedilir",
    perImpLi3:    "Diğer sistemlerle paralel olarak çalışır (diziler, makrolar, eylemler)",
    optH2:   "Optimizasyon ipuçları",
    combH3:  "🎯 Sistemlerin kombinasyonu",
    combDesc:"Tüm Premium özellikleri aynı anda çalışır. Şunları yapabilirsiniz:",
    combLi1: "Otomatik dizileri + 3 makroyu + periyodik makroyu aynı anda etkinleştirin",
    combLi2: "Tetikleyici eylemler 1 ve 2 her zaman paralel çalışır",
    combLi3: "Her sistemin kendi bağımsız zamanlayıcısı vardır",
    perfH3:  "⚡ Performans",
    perfLi1: "Ne kadar fazla sistem etkinleştirirseniz, uzantı o kadar fazla kaynak tüketir",
    perfLi2: "Çok sık eylemleri önlemek için aralıkları ayarlayın",
    perfLi3: "Doğru çalışmayı doğrulamak için etkinlik günlüğünü izleyin",
    secH3:   "🔑 Güvenlik",
    secLi1:  "Premium lisansınız gerçek zamanlı olarak doğrulanır",
    secLi2:  "Bağlantı kesilirse Premium özellikler devre dışı bırakılır",
    secLi3:  "Tüm özellikleri yeniden etkinleştirmek için tekrar giriş yapın",
  },

  docTroubleshooting: {
    h1:       "🔧 Sorun giderme",
    subtitle: "Yaygın sorunların çözümleri ve sıkça sorulan sorular",
    installH2: "Kurulum sorunları",
    faq1Q: "❌ Uzantı araç çubuğunda görünmüyor",
    faq1A: "<strong>Çözümler:</strong><br>1. Uzantının <strong>Chrome Web Store</strong>'dan yüklendiğini doğrulayın<br>2. Uzantıyı sabitleyin: araç çubuğundaki bulmaca simgesine 🧩 tıklayın ve Reborn Assistant'ı sabitleyin<br>3. Tarayıcınızı yeniden başlatın<br>4. Sorun devam ederse, uzantıyı Chrome Web Store'dan kaldırıp yeniden yükleyin",
    connH2: "Bağlantı sorunları",
    faq2Q: "❌ \"Bağlantı başarısız\" veya \"Geçersiz lisans\"",
    faq2A: "<strong>Olası nedenler:</strong><br>• Kötü internet bağlantısı<br>• Google Cloud sunucuları geçici olarak kullanılamıyor<br>• Süresi dolmuş veya iptal edilmiş lisans<br><br><strong>Çözümler:</strong><br>1. İnternet bağlantınızı kontrol edin<br>2. Google'dan çıkıp tekrar giriş yapın<br>3. Stripe portalınızdaki lisans durumunuzu kontrol edin<br>4. Sorun devam ederse destekle iletişime geçin",
    faq3Q: "❌ Panel Premium'um olmasına rağmen \"FREE\" gösteriyor",
    faq3A: "1. Google hesabınızdan çıkış yapın<br>2. Tarayıcıyı tamamen kapatın<br>3. Yeniden açın ve giriş yapın<br>4. Sorun devam ederse, doğru Google hesabıyla giriş yaptığınızı kontrol edin (satın alma için kullanılan)",
    funcH2: "Çalışma sorunları",
    faq4Q:     "❌ Tip 1/2 eylemler etkinleştirilmiyor",
    faq4Alert: "<strong>⚠️ ÖNEMLİ</strong><br>Tip 1 ve 2 eylemleri <strong>YALNIZCA PREMIUM</strong> özelliklerdir. Yalnızca otomatik tip 1 eylemi (HP) ücretsiz sürümde mevcuttur.",
    faq4Prem:  "<strong>Premium'ünüz varsa:</strong><br>1. Otomasyon aktif mi? <code>CTRL+A</code><br>2. Tetik düğmeleri açık mı? (yeşil gösterge «ON»)<br>3. Yapılandırılan tuşlar doğru mu?",
    faq5Q:     "❌ Diziler / makrolar / periyodik makro / kısayollar çalışmıyor",
    faq5Alert: "<strong>⚠️ ÖNEMLİ</strong><br>Klavye kısayolları, diziler, makrolar ve periyodik makro <strong>YALNIZCA PREMIUM</strong> özelliklerdir. Ücretsiz sürümde yalnızca otomatik tip 1 eylemi (HP) mevcuttur.",
    faq5Prem:  "<strong>Premium'unuz varsa:</strong><br>1. Premium lisansınızın aktif olduğunu doğrulayın (paneldeki 💎 simgesi)<br>2. İlgili anahtarlar etkin mi?<br>3. Yapılandırılan aralıkları ve gecikmeleri kontrol edin",
    faq6Q: "❌ Otomasyon kendiliğinden duruyor",
    faq6A: "<strong>Olası nedenler:</strong><br>• Google Cloud bağlantısı kaybı<br>• DevTools tespiti<br>• Sayfa URL'si değişti<br><br><strong>Çözümler:</strong><br>1. Otomasyonu <code>CTRL+A</code> ile yeniden başlatın (Premium) veya panel üzerinden<br>2. İlgili sayfayı yeniden yükleyin<br>3. İnternet bağlantınızı kontrol edin<br>4. Premium'daysanız DevTools açmayın",
    optH2: "Optimizasyon & Performans",
    faq7Q: "💡 Uzantı çok fazla kaynak tüketiyor",
    faq7A: "<strong>Öneriler:</strong><br>• Makro ve dizi aralıklarını artırın (daha az eylem = daha az CPU)<br>• İhtiyacınız olmayan sistemleri devre dışı bırakın<br>• Gereksiz sekmeleri kapatın<br>• Optimize edilmiş bir tarayıcı kullanın (Brave, Edge Chrome'dan daha hafiftir)",
    faq8Q: "💡 Yapılandırmayı nasıl optimize ederim?",
    faq8A: "<strong>Önerilen yapılandırma:</strong><br>• <strong>Dizi aralığı:</strong> 5-25 dakika (dizilerinizin süresine göre)<br>• <strong>Tuşlar arası gecikme:</strong> 1-2 saniye (hataları önler)<br>• <strong>Makrolar:</strong> Kullanıma göre 10-30sn aralıkları",
    genH2:  "Sıkça Sorulan Sorular",
    faq9Q:  "❓ Reborn'u birden fazla tarayıcıda kullanabilir miyim?",
    faq9A:  "Evet, ancak uzantıyı her tarayıcıya yüklemeniz gerekir. Premium lisansınız, aynı Google hesabıyla giriş yaptığınız sürece tüm cihazlarınızda çalışır (maks. 1 eş zamanlı bağlantı).",
    faq10Q: "❓ Verilerim kaydediliyor mu?",
    faq10A: "Tüm ayarlarınız (tuşlar, makrolar, tema, dil) tarayıcıda <strong>yerel olarak</strong> kaydedilir. Oturumlar arasında korunur. Ancak uzantıyı kaldırırsanız bu verileri kaybedersiniz.",
    faq11Q: "❓ Reborn bana yasak getirebilir mi?",
    faq11A: "Otomasyon araçlarının kullanımı bazı hizmetlerin Hizmet Şartlarını ihlal edebilir. Reborn'u nasıl kullandığınızdan <strong>yalnızca siz sorumlusunuz</strong>. Bu aracı kullanmadan önce hizmetin kullanım koşullarını kontrol edin.",
    faq12Q: "❓ Premium aboneliğimi nasıl iptal ederim?",
    faq12A: "Stripe yönetim portalınızdan (ödeme sonrası e-postayla gönderilen bağlantı) istediğiniz zaman iptal edebilirsiniz. İptal mevcut dönemin sonunda geçerli olur. İptal ücreti yok.",
    faq13Q: "❓ Hizmet kapanırsa Ömür Boyu planıma ne olur?",
    faq13A: "Ömür Boyu planı, hizmet aktif olduğu sürece erişimi garanti eder. Yüklendikten sonra uzantı yerel olarak çalışır; yalnızca lisans doğrulaması internet bağlantısı gerektirir.",
    supportH2:    "Daha fazla yardıma mı ihtiyacınız var?",
    supportTitle: "📧 Destek",
    supportText:  "Sorununuz devam ediyorsa, doğrudan e-posta yoluyla destekle iletişime geçin. Mesajınıza şunları ekleyin:<br><br>• Sorunun ayrıntılı açıklaması<br>• Denediğiniz adımlar<br>• Varsa ekran görüntüleri<br>• Tarayıcınız ve işletim sisteminiz",
  },

  docPrivacy: {
    h1:       "⚖️ Hukuki & Gizlilik",
    subtitle: "Yasal uyarı, yasal bildirimler, lisans koşulları ve gizlilik politikası",
    navLegal:  "⚖️ Hukuki Bilgiler",
    navLicence:"© Lisans",
    navPrivacy:"🔒 Gizlilik",
    disclaimerH2:  "⚠️ Yasal Uyarı",
    disclaimerBox: "<strong>⚠️ Önemli uyarı:</strong> Reborn Assistant bir otomasyon aracıdır. Kullanımı bazı çevrimiçi hizmetlerin Hizmet Şartlarını ihlal edebilir. Bu aracın kullanımı tamamen kendi sorumluluğunuzdadır.",
    respH3:    "Kullanıcı sorumluluğu",
    respIntro: "Reborn Assistant'ı kullanarak şunları kabul ve teyit edersiniz:",
    respLi1:   "Bu yazılımı kullanmaktan yalnızca siz sorumlusunuz",
    respLi2:   "Bu aracı kullanmadan önce her hizmetin kullanım koşullarını kontrol edeceksiniz",
    respLi3:   "Reborn'un kullanımından kaynaklanan herhangi bir yasak, hesap kısıtlaması veya hukuki işlem için yazar sorumlu tutulamaz",
    respLi4:   "Bu yazılımı bilinçli olarak ve kendi riskinizle kullanıyorsunuz",
    respLi5:   "Bu araç diğer kullanıcıların deneyimine zarar verecek şekilde kullanılmamalıdır",
    warrantH3:   "Garanti yok",
    warrantText: "Yazılım herhangi bir garanti olmaksızın «OLDUĞU GİBİ» sunulmaktadır. Yazar, yazılımın kesintisiz veya hatasız çalışacağını ya da tüm hizmetler veya tarayıcılarla uyumlu olacağını garanti etmez.",
    legalH2:    "📄 Yasal Bildirimler",
    copyrightH3:   "Telif hakkı & Fikri mülkiyet",
    copyrightText: "<strong>© 2026 Reborn Assistant – Tüm hakları saklıdır</strong><br><strong>Seymoon</strong> tarafından geliştirildi",
    copyrightText2:"Bu yazılım ve ilgili tüm materyaller yazarın münhasır fikri mülkiyetidir. Yazılı izin olmaksızın herhangi bir çoğaltma, değiştirme, dağıtım veya tersine mühendislik kesinlikle yasaktır.",
    liabilityH3:   "Sorumluluk sınırlaması",
    liabilityIntro:"Hiçbir durumda yazar, aşağıdakiler dahil ancak bunlarla sınırlı olmamak üzere, bu yazılımın kullanımından veya kullanılamamasından kaynaklanan herhangi bir talep veya zarardan sorumlu tutulamaz:",
    liabilityLi1:  "Veri veya kullanıcı hesabı kaybı",
    liabilityLi2:  "Hizmet yayıncıları tarafından uygulanan yasaklar veya kısıtlamalar",
    liabilityLi3:  "Bilgi sistemlerine verilen zararlar",
    liabilityLi4:  "Hizmet koşullarına uygun olmayan kullanımdan kaynaklanan hukuki sonuçlar",
    dataH3:    "Kişisel veriler",
    dataText:  "Reborn Assistant, hesap ve lisans yönetimi için Firebase (Google Cloud) kullanır. Toplanan veriler, yalnızca kimlik doğrulama ve lisans doğrulama amacıyla e-posta adresiniz ve hesap tanımlayıcınızla sınırlıdır.",
    dataText2: "<strong>Hiçbir etkinlik verisi toplanmaz veya iletilmez.</strong> Ayarlarınız cihazınızda yerel olarak saklanır.",
    jurisH3:   "Yetki alanı",
    jurisText: "Bu anlaşma, telif hakkı sahibinin ikamet ettiği yargı bölgesinde geçerli hukuka tabidir. Bu yazılımı yükleyerek ve kullanarak, bu koşulların tamamını okuduğunuzu, anladığınızı ve kabul ettiğinizi onaylarsınız.",
    licenceH2:     "© Lisans koşulları",
    licenceH3:     "Kullanım lisansı",
    licenceIntro:  "Reborn Assistant planı satın almak, yazılımı kullanmak için kişisel, münhasır olmayan ve devredilemez bir lisans verir.",
    licenceAllows: "<strong>Bu lisans size şunları yapma yetkisi verir:</strong>",
    licenceLi1:    "Yazılımı kendi cihazlarınızda kişisel amaçlarla kullanmak",
    licenceLi2:    "Planınıza dahil güncellemelerden yararlanmak",
    licenceForbids:"<strong>Bu lisans size şunları yapma yetkisi vermez:</strong>",
    licenceLi3:    "Erişiminizi yeniden dağıtmak, yeniden satmak veya paylaşmak",
    licenceLi4:    "Yazılımı değiştirmek, decompile etmek veya tersine mühendislik yapmak",
    licenceLi5:    "Önceden yazılı anlaşma olmaksızın yazılımı ticari amaçlarla kullanmak",
    licenceLi6:    "Lisansınızı üçüncü bir tarafa devretmek",
    terminationH3:   "Fesih",
    terminationText: "Bu koşulların ihlali halinde lisans derhal feshedilebilir. Abonelik planları için Stripe portalınızdan istediğiniz zaman iptal edebilirsiniz.",
    refundBox: "<strong>✅ İade politikası:</strong> Satın alma tarihinden itibaren 7 gün içinde memnun kalmazsanız, tam iade için destekle iletişime geçin. Bu süre geçtikten sonra istisnai durumlar dışında iade yapılmaz.",
    privacyH1:      "🔒 Gizlilik Politikası",
    privacySubtitle:"Kişisel verilerinizi nasıl koruyoruz",
    privacyBox:     "<strong>✅ Gizliliğiniz önceliğimizdir</strong><br>Ücretsiz sürüm: kişisel veri toplanmaz. Premium sürüm: yalnızca lisansınızı doğrulamak için kesinlikle gerekli veriler işlenir.",
    collectH2:        "Veri toplama",
    collectFreeH3:    "Ücretsiz Sürüm",
    collectFreeText:  "Hiçbir kişisel veri toplanmaz veya iletilmez. Tüm tercihleriniz yalnızca cihazınızda saklanır.",
    collectPremH3:    "Premium Sürüm",
    collectPremIntro: "Lisansınızı doğrulamak ve hesabınızı korumak için aşağıdaki veriler işlenir:",
    collectPremLi1:   "Google e-posta adresiniz (Google kimlik doğrulaması yoluyla)",
    collectPremLi2:   "Benzersiz cihaz tanımlayıcısı (yerel olarak oluşturulan)",
    collectPremLi3:   "Abonelik durumunuz ve oturum zaman damgaları",
    collectPremLi4:   "Hesap başına en fazla 2 kayıtlı cihaz",
    collectPremBasis: "<strong>Hukuki dayanak:</strong> sözleşmenin ifası (GDPR md. 6.1.b).",
    collectNotH3:     "Hiçbir zaman toplanmayan veriler",
    collectNotLi1:    "❌ Hiçbir oyun veya etkinlik verisi",
    collectNotLi2:    "❌ Hiçbir tarama geçmişi",
    collectNotLi3:    "❌ Hiçbir reklam veya izleme çerezi",
    localH2:    "Yerel olarak saklanan veriler",
    localIntro: "Aşağıdaki bilgiler <strong>yalnızca cihazınızda</strong> kaydedilir:",
    localLi1:   "<strong>Dil tercihleri</strong>: Arayüz dili seçiminiz",
    localLi2:   "<strong>Görsel tema seçimi</strong>: 6 mevcut temadan seçilen",
    localLi3:   "<strong>Yapılandırılan klavye kısayolları</strong>: Eylemleriniz için atanan tuşlar",
    localLi4:   "<strong>Özel zamanlayıcı aralıkları</strong>: Makrolarınız için yapılandırılan zamanlayıcılar",
    localLi5:   "<strong>Arayüz konumu</strong>: Ekranda Reborn panelinin konumu",
    localLi6:   "<strong>Lisans önbelleği (Premium)</strong>: her başlatmada doğrulamayı önlemek için cihaz tanımlayıcısı ve abonelik durumu",
    thirdH2:       "Üçüncü taraf hizmetleri",
    thirdH3:       "Kullanılan hizmetler (Premium sürüm)",
    thirdDesc:     "Kimlik doğrulama ve ödemeler için Reborn Assistant şunları kullanır:",
    thirdLi1:      "🔐 <strong>Google</strong> — Kimlik doğrulama ve lisans verilerinin güvenli depolanması",
    thirdLi2:      "💳 <strong>Stripe</strong> — Premium ödemelerin işlenmesi (banka bilgileriniz asla sunucularımızdan geçmez)",
    thirdTransfer: "Bu sağlayıcılar GDPR'a uygundur ve uluslararası veri aktarımları için uygun güvencelere sahiptir.",
    thirdNoH3:     "İzleme yok, reklam yok",
    thirdLi3:      "❌ Hiçbir analiz veya istatistik hizmeti",
    thirdLi4:      "❌ Hiçbir reklam veya hedefli pazarlama",
    thirdLi5:      "❌ Hiçbir üçüncü taraf çerezi veya davranış takibi",
    authH2:    "Kimlik doğrulama ve cihaz yönetimi",
    authH3:    "Google ile giriş (Premium sürüm)",
    authText:  "Google hesabınız yalnızca kimliğinizi doğrulamak ve lisansınızı kontrol etmek için kullanılır. Cihazınız güvenli sistemimize kaydedilir (hesap başına en fazla 2 cihaz).",
    authText2: "Hesabınız tanınmayan bir cihazda kullanılırsa bildirim alırsınız. Kayıtlı cihazlarınızı doğrudan uzantıdan yönetebilirsiniz.",
    payH2:    "Güvenli Ödemeler",
    payText:  "Premium ödemeler <strong>Stripe</strong> tarafından işlenir. Banka bilgileriniz <strong>asla</strong> sunucularımızdan geçmez. <strong>Hiçbir</strong> banka kartı verisi saklamayız.",
    retentionH2:   "Saklama süresi",
    retentionText: "Verileriniz yalnızca gerekli süre boyunca saklanır:",
    retentionLi1:  "<strong>Aktif hesap:</strong> veriler abonelik süresi boyunca saklanır",
    retentionLi2:  "<strong>İptal sonrası:</strong> 30 gün içinde silme",
    retentionLi3:  "<strong>Yerel veriler:</strong> uzantı kaldırıldığında anında silinir",
    rightsH2:      "Haklarınız (GDPR)",
    rightsText:    "GDPR'a göre verileriniz üzerinde aşağıdaki haklara sahipsiniz:",
    rightsLi1:     "✅ <strong>Erişim</strong> — Kişisel verilerinizin bir kopyasını alma",
    rightsLi2:     "✅ <strong>Düzeltme</strong> — Hatalı verileri düzeltme",
    rightsLi3:     "✅ <strong>Silme</strong> — Hesabınızın ve verilerinizin silinmesini talep etme",
    rightsLi4:     "✅ <strong>Taşınabilirlik</strong> — Verilerinizi okunabilir bir formatta alma",
    rightsLi5:     "✅ <strong>Şikayet</strong> — Ülkenizdeki veri koruma otoritesine şikayette bulunma",
    rightsExercise:"Bu hakları kullanmak için bizimle iletişime geçin: seymoon@constellation-89.fr veya Discord'da (Seymoon)",
    deleteH2:    "Verilerinizin silinmesi",
    deleteText1: "<strong>1. Uzantıyı kaldırın</strong><br>Reborn Assistant'ı kaldırınca tüm yerel veriler otomatik olarak silinir.",
    deleteText2: "<strong>2. Manuel sıfırlama</strong><br>Ayarları istediğiniz zaman Reborn arayüzünden sıfırlayabilirsiniz.",
    deleteText3: "<strong>3. Hesap silme (Premium)</strong><br>Premium hesabınızı ve ilgili tüm verileri silmek için e-posta yoluyla bizimle iletişime geçin.",
    contactH2:   "İletişim",
    contactText: "Hukuki bilgiler veya gizlilik politikası hakkında herhangi bir soru için:",
    changelogH2: "📋 Değişiklik günlüğü",
    v130H3:          "Sürüm 1.3.0 (Mart 2026) · Güncel",
    v130newLabel:    "✨ Yenilikler",
    v130improvLabel: "🔧 İyileştirmeler",
    v130fixLabel:    "🐛 Hata Düzeltmeleri",
    v130Li1:  "⏱ Sürüklenebilir kayan mini-zamanlayıcı — buff zamanlayıcılarını ve 1 dakikadan uzun süreleri gösteren küçük kayan pencere, sonraki başlatmada otomatik olarak yeniden açılır ve aktif skin'i takip eder.",
    v130Li2:  "⚡ Öncelikli macrolar — macrolar iyileştirmelerden/HP/mana'dan önce çalışır, çakışmaları önlemek için her çalıştırmadan önce ve sonra 0,5s iyileştirme dondurulur.",
    v130Li3:  "🧠 Akıllı buff yönetimi — buff önce çalışır, susturulmuş macrolar sıraya alınır ve bittikten sonra otomatik olarak yeniden başlatılır (gecikme 2s'ye düşürüldü).",
    v130Li4:  "💾 Konum belleği — kayan pencereler pozisyonlarını oturumlar arasında hatırlar.",
    v130Li5:  "🇸🇦 Arapça desteği — uzantıda mevcut 15. dil.",
    v130Li6:  "💳 Stripe ödemesi popup'ta — otomatik kapatmalı özel bir pencerede açılır, uzantıdan çıkmadan.",
    v130Li7:  "🐾 Evcil hayvan: pet'in ilk buff'ta çıkmadığı hata düzeltildi + durdurmada saklama için F1/F2 modu takibi iyileştirildi.",
    v130Li8:  "⏱ Zamanlayıcı: premium tasarımın görsel yeniden tasarımı + dinlenme durumunda %55 opaklık → daha iyi okunabilirlik için hover'da %95.",
    v130Li9:  "💳 Faturalandırma portalı: otomatik kapanmalı bellekte tek aktif pencere.",
    v130Li10:  "İçerik ve popup'ta birden fazla bellek sızıntısı düzeltildi.",
    v130Li16:  "2 cihaz maksimum limitinde UI uyumu (backend ile tutarlılık).",
    v120H3:  "Sürüm 1.2.0 (Mart 2026)",
    v120Li1: "✨ 6 skin, ince bir şeffaflık efektiyle yeniden tasarlandı.",
    v120Li2: "🔐 Kayıtlı cihazınızı doğrudan uzantıdan görüntüleyin ve yönetin.",
    v120Li3: "💳 Uzantıdan tek tıklamayla aboneliğinize erişin.",
    v120Li4: "🔔 Hesabınız başka bir cihazda kullanılırsa anında bildirim.",
    v12H3:   "Sürüm 1.2 (Şubat 2026)",
    v12Li1:  "15 dil desteği (Türkçe 🇹🇷 eklendi)",
    v12Li2:  "Web sitesinin görsel yeniden tasarımı",
    v12Li3:  "Hukuki sayfaların tek birleşik sayfada birleştirilmesi",
    v12Li4:  "Sitenin tam FR/EN çevirisi",
    v11H3:   "Sürüm 1.1.1 (Şubat 2026)",
    v11Li1:  "Otomatik periyodik makro eklendi (15sn + otomatik kaydetme)",
    v11Li2:  "CTRL+A / CTRL+O klavye kısayolları",
    v11Li3:  "15 dil desteği (Filipince + Türkçe eklendi)",
    v11Li4:  "Premium lisans kararlılığının iyileştirilmesi",
    v11Li5:  "Dizi rotasyonundaki hata düzeltmeleri",
    v10H3:   "Sürüm 1.0 (2025) · İlk",
    v10Li1:  "Reborn Assistant'ın lansmanı",
    v10Li2:  "Otomatik tip 1 ve 2 eylemleri",
    v10Li3:  "Otomatik dizi rotasyonu (F2 → 1-9 → 0 → F1)",
    v10Li4:  "3 özelleştirilebilir makro",
    v10Li5:  "6 görsel tema ve 12 dil",
    v10Li6:  "Firebase aracılığıyla Premium lisans sistemi",
    pageFooter:"© 2026 Reborn Assistant — Seymoon tarafından geliştirildi · Tüm hakları saklıdır",
  },
  nav: {
    docsFull:    "📚 Belgeler",
    docsShort:   "📚 Docs",
    manageFull:  "Aboneliği yönet",
    manageShort: "Yönet",
  },
};