export default {
  hero: {
    description: "带有高级宏的浏览器自动化扩展。自动化重复任务、键盘快捷键和序列，优化您的工作效率。",
    ctaPrimary: "立即开始",
    ctaSecondary: "了解更多",
    trust1: "提供免费版本",
    trust2: "无需合同",
    trust3: "100% 安全支付",
    trust4: "自动更新",
  },
  features: {
    tag: "技术与功能",
    titleBefore: "您所需的 ",
    titleEm: "一切",
    subtitle: "探索 Reborn Assistant 的卓越功能。",
    card1: { badge: "自动",   title: "完全自动化",          description: "用于完全自动化的键位宏、自动序列和可配置动作。" },
    card2: { badge: "手动",   title: "最高安全性",          description: "您的数据保留在本地。无跟踪，无遥测。" },
    card3: { badge: "自动",   title: "自定义宏",            description: "带自动触发器和键盘快捷键的 3 个可配置宏。" },
    card4: { badge: "手动",   title: "自定义界面",          description: "从 6 个主题中选择，根据您的需求调整界面。" },
    card5: { badge: "手动",   title: "多语言",              description: "提供 15 种语言。具有本地化界面的全球支持。" },
    card6: { badge: "免费",   title: "免费版本",            description: "包含基本功能的免费试用。" },
  },
  security: {
    tag: "安全",
    titleBefore: "专业级别的 ",
    titleEm: "安全",
    titleAfter: "",
    description: "Reborn Assistant 使用与世界顶级流媒体平台相同的安全标准。您的凭据受到 <strong style='color:var(--gold);'>JWT 加密</strong>保护，支付由 <strong style='color:var(--gold);'>Stripe</strong>保障，数据保持 <strong style='color:var(--gold);'>100% 本地</strong>存储。无跟踪，无数据出售。",
    card1Title: "JWT 加密",
    card1Text:  "银行级别的安全认证",
    card2Title: "Stripe 支付",
    card2Text:  "亚马逊和谷歌使用的处理器",
    card3Title: "零跟踪",
    card3Text:  "数据不会离开您的设备",
    card4Text:  "安全的 Google Cloud 基础设施",
  },
  pricing: {
    tag:         "选择等级",
    titleBefore: "选择您的 ",
    titleEm:     "等级",
    subtitle:    "选择最适合您的方案。无需承诺。",
    voyageur: {
      rank: "等级 I · 旅行者", plan: "免费", period: "永久",
      feat1: "治疗宏", feat2: "6 种视觉主题", feat3: "提供 15 种语言", feat4: "浮动界面",
      btn: "开始使用", download: "添加到 Chrome", guarantee: "🔒 永久免费",
    },
    aventurier: {
      rank: "等级 II · 冒险者", plan: "月度", period: "月",
      feat1: "所有高级功能", feat2: "优先支持", feat3: "免费更新",
      btn: "免费试用", guarantee: "🎁 7 天免费 · 无需信用卡",
      download: "添加到 Chrome",
    },
    champion: {
      badge: "⭐ 热门 -17%",
      rank: "等级 III · 冠军", plan: "年度", period: "年 · 2.50€/月",
      feat1: "所有高级功能", feat2: "优先支持", feat3: "免费更新",
      btn: "免费试用", guarantee: "🎁 7 天免费 · 无需信用卡",
      download: "添加到 Chrome",
    },
    legende: {
      badge: "⚡ 限时优惠",
      rank: "等级 IV · 传奇", plan: "终身", period: "一次性付款 · 永不再次",
      feat1: "终身访问", feat2: "所有未来更新", feat3: "专属高级支持", feat4: "最佳性价比",
      btn: "购买", guarantee: "🔒 一次性付款 · 保证终身访问",
      download: "添加到 Chrome",
    },
  },
  stats: {
    label1: "支持的语言", label2: "视觉主题", label3: "本地数据", label4: "活跃扩展",
  },
  trust: {
    badge1: "SSL 安全支付", badge2: "即时访问", badge3: "100% 私密数据", badge4: "快速支持",
  },
  store: {
    status: "官方扩展",
    title:  "在 Chrome 网上应用店中提供",
    install: "安装",
    available: "免费提供 · Google 认证的官方扩展",
  },
  faq: {
    titleBefore: "常见 ",
    titleEm:     "问题",
    subtitle:    "开始之前需要了解的一切。",
    q1: "免费试用需要信用卡吗？",
    a1: "不需要，无需信用卡。前 7 天完全免费，无任何承诺。只需创建账户即可立即开始。",
    q2: "我可以随时更改方案吗？",
    a2: "是的，您可以随时从账户升级或降级。无需更改费用。",
    q3: "终身方案真的包含所有未来更新吗？",
    a3: "当然。终身方案保证无需额外费用即可访问所有未来更新和新功能。",
    q4: "我的数据安全吗？",
    a4: "所有数据都在您的设备上本地存储。我们不收集个人数据，也不使用任何跟踪或遥测。",
    q5: "如何联系支持？",
    a5: "通过电子邮件 seymoon@constellation-89.fr 或 Discord（Seymoon）联系我们。高级订阅用户享有优先响应。",
    q6: "Reborn Assistant 是机器人吗？",
    a6: "不，Reborn Assistant 不是机器人。它是一个具有可配置宏的扩展程序，自动化您自己定义的键序列。没有人工智能，没有与游戏服务器的交互，没有内存读取。扩展程序既不读取也不修改游戏数据 — 它只是模拟您手动按下的键。您必须留在电脑前才能玩：Reborn Assistant 不解决验证码，不复活您的角色，也不会在死亡后将您带回到原地。它是一个使您的游戏体验更简单的工具，而不是取代您。",
  },
  footer: {
    privacy:   "隐私",
    terms:     "条款",
    copyright: "© 2026 Reborn Assistant. 保留所有权利。<br>由 Seymoon 开发",
  },

  docsNav: {
    backToDocs:      "← 返回文档",
    mainSite:        "⌂ 主站",
    backToMainSite:  "← 返回主站",
    footer:          "© 2026 Reborn Assistant — 由 Seymoon 开发 · 保留所有权利",
  },

  docsHome: {
    version:              "版本 1.3 · 完整文档",
    userGuide:            "用户指南",
    support:              "支持",
    legal:                "法律信息",
    quickstartTitle:      "快速入门",
    quickstartDesc:       "Reborn Assistant 的安装、初始设置和第一步。",
    featuresTitle:        "功能",
    featuresDesc:         "包含比较表的免费和高级功能的完整描述。",
    premiumTitle:         "高级指南",
    premiumDesc:          "自动序列、自定义宏、周期性宏。",
    interfaceTitle:       "界面与个性化",
    interfaceDesc:        "视觉主题、语言、个性化选项。",
    troubleshootingTitle: "故障排除",
    troubleshootingDesc:  "常见问题解决方案、常见问题解答、性能优化。",
    legalTitle:           "法律与隐私",
    legalDesc:            "法律免责声明、法律声明、许可条款、隐私政策、更新日志。",
    footer:               "© 2026 Reborn Assistant — 由 Seymoon 开发 · 保留所有权利",
  },

  docFeatures: {
    h1:        "⚡ 功能",
    subtitle:  "探索 Reborn Assistant 的所有功能",
    h2Free:    "免费功能",
    freeBadge: "免费",
    c1Title: "类型 1 自动动作",
    c1Desc:  "基于可配置计时器自动激活类型 1 动作（HP）。",
    c1li1:   "可配置动作计时器",
    c1li2:   "在后台运行",
    c2Title: "视觉主题",
    c2Desc:  "使用 6 种不同的主题自定义界面外观。",
    c2li1:   "MMO Gold（默认）",
    c2li2:   "暗黑模式和白色模式",
    c3Title: "多语言",
    c3Desc:  "提供 15 种语言的界面，实现国际化体验。",
    c3li3:   "即时切换",
    h2Premium: "高级功能 💎",
    p1Title: "自动触发器 1 宏",
    p1Desc:  "基于可配置计时器自动激活类型 1 动作（HP）。",
    p1li1:   "可配置触发器 1 计时器",
    p1li2:   "可配置快捷键",
    p1li3:   "在后台运行",
    p2Title: "自动触发器 2 宏",
    p2Desc:  "基于可配置计时器自动使用类型 2 动作。",
    p2li1:   "可配置触发器 2 计时器",
    p2li2:   "可配置快捷键",
    p2li3:   "在后台运行",
    p3Title: "键盘快捷键",
    p3Desc:  "使用可自定义的全局快捷键立即控制 Reborn Assistant。",
    p3li1:   "CTRL+A：启动自动化",
    p3li2:   "CTRL+O：停止自动化",
    p4Title: "序列轮换",
    p4Desc:  "具有预定义序列的自动序列维护系统。",
    p4li1:   "序列：F2 → 1-9 → 0 → F1",
    p4li2:   "可配置间隔（分钟）",
    p4li3:   "可调节键间延迟",
    p5Title: "自定义宏",
    p5Desc:  "用自己的按键序列创建最多 3 个宏。",
    p5li1:   "3 个独立宏",
    p5li2:   "自定义序列",
    p5li3:   "可调节重复间隔",
    p6Title: "周期性宏",
    p6Desc:  "每 15 秒自动调用并保存周期性宏。",
    p6li1:   "自动调用周期性宏",
    p6li2:   "调用后自动保存",
    p6li3:   "固定 15 秒间隔",
    tableH2:      "比较表",
    tableFeature: "功能",
    tableFree:    "免费",
    row1:  "类型 1 自动动作（HP）",
    row2:  "视觉主题（6）",
    row3:  "多语言（15）",
    row4:  "自动触发器 1 宏",
    row5:  "自动触发器 2 宏",
    row6:  "键盘快捷键（CTRL+A / CTRL+O）",
    row7:  "自动序列轮换",
    row8:  "自定义宏（3x）",
    row9:  "自动周期性宏",
    learnMore: "→ 了解更多高级功能",
  },

  docQuickstart: {
    h1:       "🚀 快速入门",
    subtitle: "在几分钟内安装和配置 Reborn Assistant",
    reqH2:    "要求",
    req1:     "<strong>兼容浏览器：</strong>Google Chrome、Microsoft Edge、Brave 或任何基于 Chromium 的浏览器",
    req2:     "<strong>Google 账户：</strong>仅高级版认证需要（免费版可选）",
    req3:     "<strong>兼容网站：</strong>与标准网站兼容",
    installH2:  "安装",
    step1Title: "访问 Chrome 网上应用店",
    step1p:     "前往 <a href='https://chromewebstore.google.com/detail/reborn-assistant-premium/ammakeedbimichmpipeaacgajcblnnme' target='_blank' style='color:var(--gold);text-decoration:none;' onmouseover='this.style.textDecoration=\"underline\"' onmouseout='this.style.textDecoration=\"none\"'>Chrome 网上应用店</a>中的 Reborn Assistant 页面，点击<strong>《添加到 Chrome》</strong>。",
    step1tip:   "💡 与 Google Chrome、Microsoft Edge、Brave 和基于 Chromium 的浏览器兼容。",
    step2Title: "确认安装",
    step2p:     "在确认对话框中点击<strong>《添加扩展程序》</strong>。扩展程序将自动安装。",
    step3Title: "固定扩展程序",
    step3p:     "点击浏览器工具栏中的拼图图标 🧩，固定 Reborn Assistant 以便快速访问。",
    step4Title: "登录（高级版可选）",
    step4p:     "• 点击工具栏中的 Reborn 图标<br>• 高级版：使用 Google 账户登录<br>• 免费版：无需登录直接使用",
    alertTitle: "✅ 安装成功！",
    alertText:  "扩展程序激活后，Reborn 图标将变为绿色。您现在可以配置功能。",
    configH2:   "初始配置",
    freeH3:     "免费版本",
    freeTitle:  "<strong>无需登录即可使用的功能：</strong>",
    freeText:   "• 类型 1 自动动作（仅 HP）<br>• 6 种视觉主题<br>• 支持 15 种语言",
    freeStepTitle: "配置类型 1 自动动作",
    freeStepText:  "1. 打开 Reborn 面板（点击图标）<br>2. 调整 HP 动作计时器（默认：2 秒）<br>3. 动作将自动激活<br>4. 无需登录",
    premiumH3:       "高级版本 💎",
    premiumFeatTitle:"<strong>额外功能（需要 Google 登录）：</strong>",
    premiumFeatText: "• 自动触发器 1 宏（可配置计时器 + 快捷键）<br>• 自动触发器 2 宏（可配置计时器 + 快捷键）<br>• 键盘快捷键（CTRL+A / CTRL+O）<br>• 自动序列轮换（F2 → 1-9 → 0 → F1）<br>• 带按键序列的 3 个自定义宏<br>• 自动周期性宏系统（每 15 秒调用 + 自动保存）",
    premConfigTitle: "高级版配置",
    premConfigSeq:   "<strong>自动序列：</strong><br>• 在面板中激活《序列轮换》<br>• 设置周期间隔（默认：5 分钟）<br>• 调整键间延迟（默认：1 秒）",
    premConfigMacro: "<strong>宏：</strong><br>• 激活宏 1、2 或 3<br>• 定义按键序列（例：<code>1,2,3,4</code>）<br>• 设置重复间隔",
    premConfigPer:   "<strong>周期性宏：</strong><br>• 激活《周期性宏》开关<br>• 系统将每 15 秒自动调用周期性宏<br>• 调用后自动保存",
    warnTitle: "⚠️ 重要说明",
    warnText:  "高级功能（触发器宏 1 和 2、自动序列、自动周期性宏、3 个可配置宏）需要有效的高级许可证和 Google 登录。没有许可证时，仅基本宏可用。",
    shortcutsH2:   "键盘快捷键",
    shortcutsText: "<code>CTRL + A</code>：启动自动化<br><code>CTRL + O</code>：停止自动化",
    nextH2: "后续步骤",
    link1:  "探索所有功能",
    link2:  "完整高级指南",
    link3:  "常见问题解决方案",
  },

  docInterface: {
    h1:       "🎨 界面与个性化",
    subtitle: "根据您的偏好自定义 Reborn Assistant",
    themesH2:    "视觉主题",
    themesDesc:  "Reborn Assistant 提供 6 个主题来个性化界面外观：",
    changeThemeH3:   "更换主题",
    changeThemeText: "1. 打开 Reborn 面板<br>2. 点击《⚙️ 设置》选项卡<br>3. 从下拉菜单中选择主题<br>4. 更改立即生效",
    langsH2:    "支持的语言",
    langsDesc:  "提供 15 种语言的界面：",
    changeLangH3:   "更换语言",
    changeLangText: "1. 打开 Reborn 面板<br>2. 点击《⚙️ 设置》<br>3. 从下拉菜单中选择语言<br>4. 整个界面立即翻译",
    shortcutsH2:   "键盘快捷键",
    shortcutsDesc: "Reborn Assistant 包含用于快速控制的全局快捷键：",
    systemH3: "系统快捷键",
    sysSC1:   "<code>CTRL + A</code>：启动自动化",
    sysSC2:   "<code>CTRL + O</code>：停止自动化",
    customH3:   "自定义快捷键",
    customDesc: "您可以为以下功能分配键：",
    customLi1:  "类型 1 和 2 动作",
    customLi2:  "宏（按键序列）",
    customLi3:  "周期性宏",
    displayH2:    "显示选项",
    panelPosH3:   "面板位置",
    panelPosDesc: "Reborn 面板可以拖动：",
    panelLi1: "点击面板标题",
    panelLi2: "按住并拖动",
    panelLi3: "放置到所需位置",
    panelLi4: "位置自动保存",
    opacityH3:   "面板透明度",
    opacityDesc: "调整透明度，在管理统计数据的同时不干扰导航。",
    logH3:   "活动日志",
    logDesc: "日志实时显示所有执行的动作：",
    logLi1:  "系统激活/停用",
    logLi2:  "药水使用",
    logLi3:  "宏和序列执行",
    logLi4:  "周期性宏调用",
    logLi5:  "可能的错误",
    saveH2:    "保存设置",
    saveDesc:  "所有设置自动在本地保存：",
    saveLi1:   "选定的主题",
    saveLi2:   "界面语言",
    saveLi3:   "激活阈值",
    saveLi4:   "分配的键",
    saveLi5:   "宏配置",
    saveLi6:   "面板位置",
    savePersist: "即使关闭浏览器后，也会在会话之间保留。",
  },

  docPremium: {
    h1:       "💎 高级指南",
    subtitle: "掌握 Reborn Assistant 的所有高级功能",
    rotH2:    "🛡️ 自动序列轮换",
    rotDesc:  "轮换系统通过定期按预定义的按键序列来自动保持所有序列活跃。",
    rotSeqH3:   "按键序列",
    rotSeqText: "轮换始终遵循此固定顺序：",
    rotConfigH3:   "配置",
    rotIntName:    "周期间隔",
    rotIntDesc:    "重新开始完整序列前的等待时间。默认：5 分钟。根据最短序列的持续时间进行调整。",
    rotDelName:    "键间延迟",
    rotDelDesc:    "序列中每个键之间的等待时间。默认：1 秒。根据服务速度调整（动画、冷却时间...）。",
    rotExTitle:    "💡 使用示例",
    rotExScenario: "<strong>场景：</strong>序列持续 5 分钟，键 1-8 上有 8 个序列。",
    rotExConfig:   "<strong>配置：</strong>",
    rotExLi1:      "间隔：5 分钟",
    rotExLi2:      "延迟：1 秒",
    rotExLi3:      "扩展程序每 5 分钟按下 F2、1、2、3、4、5、6、7、8、9、0、F1",
    rotExLi4:      "共 13 个键，每键间隔 1 秒 = 每周期约 13 秒",
    macH2:    "⚙️ 自定义宏",
    macDesc:  "用自己的按键序列创建最多 3 个独立宏。非常适合自动化重复任务、定期连击或技能轮换。",
    macHowH3:   "工作原理",
    macHowText: "每个宏独立于其他系统，按固定间隔执行按键序列。",
    macConfigH3:  "配置",
    macSeqName:   "按键序列",
    macSeqDesc:   "定义要按顺序按下的键，用逗号分隔。例：1,2,3,4 或 q,w,e,r,f",
    macRepName:   "重复间隔",
    macRepDesc:   "重复序列前的等待时间。根据您的需求设置（秒或分钟）。",
    macDelName:   "键间延迟",
    macDelDesc:   "序列中每个键之间的等待时间（通常 0.5 到 2 秒）。",
    macExTitle:   "💡 使用示例",
    mac1Title:    "<strong>宏 1 – 重复自动化：</strong>",
    mac1Li1:      "序列：1,2,3,space",
    mac1Li2:      "间隔：10 秒",
    mac1Li3:      "用途：循环中的基本攻击轮换",
    mac2Title:    "<strong>宏 2 – 技能连击：</strong>",
    mac2Li1:      "序列：q,w,e,r",
    mac2Li2:      "间隔：30 秒",
    mac2Li3:      "用途：最优 DPS 轮换",
    mac3Title:    "<strong>宏 3 – 自动辅助：</strong>",
    mac3Li1:      "序列：f,g,h",
    mac3Li2:      "间隔：15 秒",
    mac3Li3:      "用途：团队序列或周期性动作",
    perH2:    "🐉 周期性宏",
    perDesc:  "该系统每 15 秒自动执行周期性动作。非常适合需要定期激活的重复任务。",
    perHowH3:   "工作原理",
    perHowText: "系统每 15 秒自动执行此序列：",
    perLi1:     "调用周期性宏（可配置键，默认 §）",
    perLi2:     "等待 500 毫秒",
    perLi3:     "自动保存周期性宏",
    perConfigH3:  "配置",
    perCallName:  "调用键",
    perCallDesc:  "激活周期性宏的键。默认：§。根据您的配置更改。",
    perIntName:   "间隔（固定）",
    perIntDesc:   "系统始终使用固定的 15 秒间隔。不可配置。",
    perExTitle:   "💡 使用场景",
    perExText:    "在某些服务中，您需要定期调用周期性宏来收集物品、触发临时序列或获取经验。该系统完全自动化此过程。",
    perImpH3:     "⚠️ 重要",
    perImpLi1:    "确保配置的键对应调用键",
    perImpLi2:    "每次调用后周期性宏自动保存",
    perImpLi3:    "与其他系统（序列、宏、动作）并行运行",
    optH2:   "优化技巧",
    combH3:  "🎯 系统组合",
    combDesc:"所有高级功能同时运行。您可以：",
    combLi1: "同时激活自动序列 + 3 个宏 + 周期性宏",
    combLi2: "触发动作 1 和 2 始终并行运行",
    combLi3: "每个系统都有自己的独立计时器",
    perfH3:  "⚡ 性能",
    perfLi1: "激活的系统越多，扩展程序消耗的资源越多",
    perfLi2: "调整间隔以避免过于频繁的动作",
    perfLi3: "监控活动日志以确保正常运行",
    secH3:   "🔑 安全",
    secLi1:  "高级许可证实时验证",
    secLi2:  "连接断开时，高级功能停用",
    secLi3:  "重新登录以重新激活所有功能",
  },

  docTroubleshooting: {
    h1:       "🔧 故障排除",
    subtitle: "常见问题解决方案和常见问题解答",
    installH2: "安装问题",
    faq1Q: "❌ 扩展程序未出现在工具栏中",
    faq1A: "<strong>解决方案：</strong><br>1. 确认扩展程序从 <strong>Chrome 网上应用店</strong>安装<br>2. 固定扩展程序：点击工具栏中的拼图图标 🧩，固定 Reborn Assistant<br>3. 重启浏览器<br>4. 如问题持续，从 Chrome 网上应用店卸载并重新安装扩展程序",
    connH2: "连接问题",
    faq2Q: "❌「连接失败」或「无效许可证」",
    faq2A: "<strong>可能原因：</strong><br>• 不稳定的网络连接<br>• Google Cloud 服务器临时不可用<br>• 许可证已过期或已取消<br><br><strong>解决方案：</strong><br>1. 检查网络连接<br>2. 从 Google 退出并重新登录<br>3. 在 Stripe 门户检查许可证状态<br>4. 如问题持续，联系支持",
    faq3Q: "❌ 面板显示「FREE」，但我有高级版",
    faq3A: "1. 退出 Google 账户<br>2. 完全关闭浏览器<br>3. 重新打开并登录<br>4. 如问题持续，确认您使用正确的 Google 账户登录（购买时使用的）",
    funcH2: "功能问题",
    faq4Q:     "❌ 类型 1/2 动作未激活",
    faq4Alert: "<strong>⚠️ 重要</strong><br>类型 1 和 2 动作是<strong>高级专属</strong>功能。只有类型 1 自动动作（HP）在免费版中可用。",
    faq4Prem:  "<strong>如果您有 Premium：</strong><br>1. 自动化正在运行吗？<code>CTRL+A</code><br>2. 触发开关是否已启用？（绿色指示灯「ON」）<br>3. 配置的按键是否正确？",
    faq5Q:     "❌ 序列/宏/周期性宏/快捷键不起作用",
    faq5Alert: "<strong>⚠️ 重要</strong><br>键盘快捷键、序列、宏和周期性宏是<strong>高级专属</strong>功能。在免费版中，只有类型 1 自动动作（HP）可用。",
    faq5Prem:  "<strong>如果您有高级版：</strong><br>1. 确认高级许可证处于活跃状态（面板中的 💎 图标）<br>2. 相应开关已激活吗？<br>3. 检查配置的间隔和延迟",
    faq6Q: "❌ 自动化自己停止了",
    faq6A: "<strong>可能的原因：</strong><br>• 与 Google Cloud 的连接中断<br>• 检测到 DevTools<br>• 页面 URL 已更改<br><br><strong>解决方案：</strong><br>1. 使用 <code>CTRL+A</code> 重新启动自动化（Premium）或通过面板<br>2. 重新加载相关页面<br>3. 检查您的互联网连接<br>4. 如果您是 Premium 用户，请不要打开 DevTools",
    optH2: "优化与性能",
    faq7Q: "💡 扩展程序消耗太多资源",
    faq7A: "<strong>建议：</strong><br>• 增加宏和序列的间隔（动作越少 = CPU 使用越少）<br>• 停用不需要的系统<br>• 关闭不必要的标签页<br>• 使用优化的浏览器（Brave、Edge 比 Chrome 更轻量）",
    faq8Q: "💡 如何优化我的设置？",
    faq8A: "<strong>推荐设置：</strong><br>• <strong>序列间隔：</strong>5 到 25 分钟（取决于序列持续时间）<br>• <strong>键间延迟：</strong>1 到 2 秒（防止错误）<br>• <strong>宏：</strong>根据使用情况设置 10 到 30 秒间隔",
    genH2:  "常见问题解答",
    faq9Q:  "❓ 我可以在多个浏览器上使用 Reborn 吗？",
    faq9A:  "是的，但需要在每个浏览器上安装扩展程序。只要使用同一个 Google 账户登录，高级许可证可在所有设备上使用（最多 1 个同时连接）。",
    faq10Q: "❓ 我的数据会被保存吗？",
    faq10A: "所有设置（键、宏、主题、语言）都<strong>本地</strong>存储在您的浏览器中。它们在会话之间保留。但是，卸载扩展程序时，这些数据将丢失。",
    faq11Q: "❓ Reborn 会导致封号吗？",
    faq11A: "使用自动化工具可能违反某些服务的服务条款。<strong>您独自负责</strong>如何使用 Reborn。使用此工具前请查看服务的使用条款。",
    faq12Q: "❓ 如何取消高级订阅？",
    faq12A: "您可以随时从 Stripe 管理门户（购买后收到的邮件中的链接）取消。取消将在当前期间结束时生效。无取消费用。",
    faq13Q: "❓ 如果服务关闭，终身方案会怎样？",
    faq13A: "终身方案保证在服务活跃期间的访问。安装后，扩展程序在本地运行。只有许可证验证需要网络连接。",
    supportH2:    "需要更多帮助？",
    supportTitle: "📧 支持",
    supportText:  "如问题持续，请通过电子邮件直接联系我们的支持团队。在您的消息中包含：<br><br>• 问题的详细描述<br>• 您已尝试的步骤<br>• 相关截图（如有）<br>• 您的浏览器和操作系统",
  },

  docPrivacy: {
    h1:       "⚖️ 法律信息与隐私",
    subtitle: "法律免责声明、法律声明、许可条款、隐私政策",
    navLegal:  "⚖️ 法律信息",
    navLicence:"© 许可证",
    navPrivacy:"🔒 隐私",
    disclaimerH2:  "⚠️ 法律免责声明",
    disclaimerBox: "<strong>⚠️ 重要声明：</strong>Reborn Assistant 是一个自动化工具。其使用可能违反某些在线服务的服务条款。使用本工具完全由您自行承担风险。",
    respH3:    "用户责任",
    respIntro: "使用 Reborn Assistant，即表示您承认并同意以下内容：",
    respLi1:   "您独自负责使用此软件",
    respLi2:   "使用此工具前，您将查看每个服务的使用条款",
    respLi3:   "作者不对因使用 Reborn 而导致的封号、账户限制或法律行动承担责任",
    respLi4:   "您有意识地自行承担风险使用此软件",
    respLi5:   "本工具不得以损害其他用户体验的方式使用",
    warrantH3:   "无保证",
    warrantText: "软件按「现状」提供，不附任何保证。作者不保证软件将不间断或无错误地运行，或与所有服务或浏览器兼容。",
    legalH2:    "📄 法律声明",
    copyrightH3:   "版权与知识产权",
    copyrightText: "<strong>© 2026 Reborn Assistant – 保留所有权利</strong><br>由 <strong>Seymoon</strong> 开发",
    copyrightText2:"与此软件相关的所有材料均为作者的专有知识产权。未经书面许可，严禁复制、修改、分发或逆向工程。",
    liabilityH3:   "责任限制",
    liabilityIntro:"在任何情况下，作者均不对因使用或无法使用本软件而产生的索赔或损害承担责任，包括但不限于：",
    liabilityLi1:  "数据或用户账户丢失",
    liabilityLi2:  "服务发布者施加的封号或限制",
    liabilityLi3:  "计算机系统损坏",
    liabilityLi4:  "因不符合服务条款的使用而产生的法律后果",
    dataH3:    "个人数据",
    dataText:  "Reborn Assistant 使用 Firebase（Google Cloud）进行账户和许可证管理。收集的数据仅限于用于认证和许可证验证目的的电子邮件地址和账户标识符。",
    dataText2: "<strong>不收集或传输任何活动数据。</strong>设置在您的设备上本地存储。",
    jurisH3:   "管辖权",
    jurisText: "本协议受版权所有者居住地适用法律管辖。安装和使用本软件即表示您承认已阅读、理解并接受所有这些条款。",
    licenceH2:     "© 许可条款",
    licenceH3:     "使用许可",
    licenceIntro:  "购买 Reborn Assistant 方案即授予个人、非独占且不可转让的软件使用许可。",
    licenceAllows: "<strong>此许可允许：</strong>",
    licenceLi1:    "在您自己的设备上为个人目的使用软件",
    licenceLi2:    "利用方案中包含的更新",
    licenceForbids:"<strong>此许可禁止：</strong>",
    licenceLi3:    "重新分发、转售或共享访问权限",
    licenceLi4:    "修改、反编译或逆向工程软件",
    licenceLi5:    "未经事先书面协议将软件用于商业目的",
    licenceLi6:    "将许可证转让给第三方",
    terminationH3:   "终止",
    terminationText: "违反这些条款时，许可证可立即终止。对于订阅方案，您可以随时从 Stripe 门户取消。",
    refundBox: "<strong>✅ 退款政策：</strong>如果购买后 7 天内不满意，请联系支持获取全额退款。此期限后，除特殊情况外，不予退款。",
    privacyH1:      "🔒 隐私政策",
    privacySubtitle:"我们如何保护您的个人数据",
    privacyBox:     "<strong>✅ 您的隐私是我们的首要任务</strong><br>免费版：不收集个人数据。高级版：仅处理许可证验证严格必要的数据。",
    collectH2:        "数据收集",
    collectFreeH3:    "免费版",
    collectFreeText:  "不收集或传输任何个人数据。所有偏好设置仅在您的设备上本地存储。",
    collectPremH3:    "高级版",
    collectPremIntro: "为验证许可证和保护账户，处理以下数据：",
    collectPremLi1:   "Google 电子邮件地址（通过 Google 认证）",
    collectPremLi2:   "唯一设备标识符（本地生成）",
    collectPremLi3:   "订阅状态和会话时间戳",
    collectPremLi4:   "每账户最多 2 个注册设备",
    collectPremBasis: "<strong>法律依据：</strong>履行合同（GDPR 第 6.1.b 条）。",
    collectNotH3:     "从不收集的数据",
    collectNotLi1:    "❌ 无游戏或活动数据",
    collectNotLi2:    "❌ 无浏览器历史记录",
    collectNotLi3:    "❌ 无广告或跟踪 Cookie",
    localH2:    "本地存储的数据",
    localIntro: "以下信息<strong>仅在您的设备上</strong>存储：",
    localLi1:   "<strong>语言偏好</strong>：选择的界面语言",
    localLi2:   "<strong>视觉主题选择</strong>：从 6 个中选择的主题",
    localLi3:   "<strong>配置的键盘快捷键</strong>：分配给动作的键",
    localLi4:   "<strong>自定义计时器间隔</strong>：为宏设置的计时器",
    localLi5:   "<strong>界面位置</strong>：屏幕上 Reborn 面板的位置",
    localLi6:   "<strong>许可证缓存（高级版）</strong>：设备标识符和订阅状态，以避免每次启动时验证",
    thirdH2:       "第三方服务",
    thirdH3:       "使用的服务（高级版）",
    thirdDesc:     "为进行认证和支付，Reborn Assistant 使用：",
    thirdLi1:      "🔐 <strong>Google</strong> — 认证和安全存储许可证数据",
    thirdLi2:      "💳 <strong>Stripe</strong> — 处理高级版支付（银行信息永不通过我们的服务器）",
    thirdTransfer: "这些提供商符合 GDPR，并为国际数据传输提供适当的保护措施。",
    thirdNoH3:     "无跟踪，无广告",
    thirdLi3:      "❌ 无分析或统计服务",
    thirdLi4:      "❌ 无广告或定向营销",
    thirdLi5:      "❌ 无第三方 Cookie 或行为跟踪",
    authH2:    "认证与设备管理",
    authH3:    "使用 Google 登录（高级版）",
    authText:  "Google 账户仅用于身份验证和许可证检查。设备在安全系统中注册（每账户最多 2 台设备）。",
    authText2: "如果您的账户从未识别的设备使用，您将收到通知。注册的设备可以直接从扩展程序管理。",
    payH2:    "安全支付",
    payText:  "高级版支付由 <strong>Stripe</strong> 处理。银行信息<strong>永远不会</strong>通过我们的服务器。<strong>我们不存储任何信用卡数据。</strong>",
    retentionH2:   "保留期限",
    retentionText: "数据仅在必要期间保留：",
    retentionLi1:  "<strong>活跃账户：</strong>在整个订阅期间保留数据",
    retentionLi2:  "<strong>取消后：</strong>30 天内删除",
    retentionLi3:  "<strong>本地数据：</strong>卸载扩展程序时立即删除",
    rightsH2:      "您的权利（GDPR）",
    rightsText:    "根据 GDPR，您对数据享有以下权利：",
    rightsLi1:     "✅ <strong>访问</strong> — 获取您个人数据的副本",
    rightsLi2:     "✅ <strong>更正</strong> — 纠正不准确的数据",
    rightsLi3:     "✅ <strong>删除</strong> — 请求删除您的账户和数据",
    rightsLi4:     "✅ <strong>可携性</strong> — 以可读格式接收您的数据",
    rightsLi5:     "✅ <strong>投诉</strong> — 向国家数据保护机构提出投诉",
    rightsExercise:"要行使这些权利，请联系：seymoon@constellation-89.fr 或 Discord（Seymoon）",
    deleteH2:    "数据删除",
    deleteText1: "<strong>1. 卸载扩展程序</strong><br>卸载 Reborn Assistant 将自动删除所有本地数据。",
    deleteText2: "<strong>2. 手动重置</strong><br>您可以随时从 Reborn 界面重置您的设置。",
    deleteText3: "<strong>3. 账户删除（高级版）</strong><br>要删除与您的高级版账户相关的所有数据，请通过电子邮件联系我们。",
    contactH2:   "联系方式",
    contactText: "关于法律信息或隐私政策的问题：",
    changelogH2: "📋 更新日志",
    v130H3:          "版本 1.3.0（2026 年 3 月）· 当前",
    v130newLabel:    "✨ 新功能",
    v130improvLabel: "🔧 改进",
    v130fixLabel:    "🐛 错误修复",
    v130Li1:  "⏱ 可拖动的浮动迷你计时器 — 显示增益计时器及超过1分钟计时器的小型浮动窗口，下次启动时自动重新打开，并跟随当前皮肤。",
    v130Li2:  "⚡ 优先宏 — 宏在治疗/HP/法力之前执行，每次执行前后有0.5秒的治疗冻结以避免冲突。",
    v130Li3:  "🧠 智能buff管理 — buff优先执行，静默宏被排队并在结束后自动重启（延迟减少至2秒）。",
    v130Li4:  "💾 位置记忆 — 浮动窗口在会话之间保留其位置。",
    v130Li5:  "🇸🇦 阿拉伯语支持 — 扩展中可用的第14种语言。",
    v130Li6:  "💳 弹窗Stripe支付 — 在专用窗口中打开，支付完成后自动关闭，无需离开扩展。",
    v130Li7:  "🐾 宠物：修复宠物在第一次buff时不出现的bug + 改进F1/F2模式追踪以便在停止时收起。",
    v130Li8:  "⏱ 计时器：高级设计视觉重做 + 静止时不透明度55% → 悬停时95%以提高可读性。",
    v130Li9:  "💳 计费门户：内存中单一活动窗口，自动关闭。",
    v130Li10:  "修复了内容和弹窗中的多处内存泄漏。",
    v130Li16:  "UI与最多2台设备限制对齐（与后端的一致性）。",
    v120H3:  "版本 1.2.0（2026 年 3 月）· 当前",
    v120Li1: "✨ 6 个皮肤以微妙的透明效果重新设计。",
    v120Li2: "🔐 直接从扩展程序查看和管理注册设备。",
    v120Li3: "💳 从扩展程序一键访问订阅。",
    v120Li4: "🔔 如果您的账户从其他设备使用，立即通知。",
    v12H3:   "版本 1.2（2026 年 2 月）",
    v12Li1:  "支持 15 种语言（新增土耳其语 🇹🇷）",
    v12Li2:  "网站视觉重新设计",
    v12Li3:  "将法律页面整合为单一统一页面",
    v12Li4:  "网站完整 FR/EN 翻译",
    v11H3:   "版本 1.1.1（2026 年 2 月）",
    v11Li1:  "新增自动周期性宏（15 秒 + 自动保存）",
    v11Li2:  "键盘快捷键 CTRL+A / CTRL+O",
    v11Li3:  "支持 15 种语言（新增菲律宾语 + 土耳其语）",
    v11Li4:  "改进高级许可证稳定性",
    v11Li5:  "修复序列轮换错误",
    v10H3:   "版本 1.0（2025 年）· 初始",
    v10Li1:  "Reborn Assistant 发布",
    v10Li2:  "类型 1 和 2 自动动作",
    v10Li3:  "自动序列轮换（F2 → 1-9 → 0 → F1）",
    v10Li4:  "3 个自定义宏",
    v10Li5:  "6 种视觉主题和 12 种语言",
    v10Li6:  "通过 Firebase 的高级许可证系统",
    pageFooter:"© 2026 Reborn Assistant — 由 Seymoon 开发 · 保留所有权利",
  },
  nav: {
    docsFull:    "📚 文档",
    docsShort:   "📚 Docs",
    manageFull:  "管理订阅",
    manageShort: "管理",
  },
};